import type { Theme } from '../engine/calendar/types';
import type { Locale } from './index';

interface TransitUiText {
  selectProfile: string;
  dateTitle: string;
  today: string;
  nextDay: string;
  nextMonth: string;
  activeAspects: string;
  loadingProfile: string;
  selectProfileAbove: string;
  transitsOf: string;
  for: string;
  natal: string;
  dayEnergy: {
    favorable: [string, string];
    tense: [string, string];
    neutral: [string, string];
  };
  activeAreas: string;
  interpretationTitle: string;
  natalSuffix: string;
  orb: string;
  house: string;
  in: string;
  natalChartHouse: string;
  howToUse: string;
  howToUseText: string;
  themes: Record<Theme, string>;
}

const themes = (love: string, career: string, finances: string, health: string, spirituality: string, family: string, creativity: string, communication: string, transformation: string, freedom: string, travel: string, sexuality: string): Record<Theme, string> => ({ love, career, finances, health, spirituality, family, creativity, communication, transformation, freedom, travel, sexuality });

const texts: Record<Locale, TransitUiText> = {
  pt: { selectProfile: 'Selecione um perfil no menu superior (👤) para ver os trânsitos.', dateTitle: 'Data dos Trânsitos', today: 'Hoje', nextDay: '+1 dia', nextMonth: '+1 mês', activeAspects: 'Aspectos Ativos', loadingProfile: 'Carregando perfil...', selectProfileAbove: 'Selecione um perfil no ícone 👤 acima para ver os trânsitos', transitsOf: 'Trânsitos de', for: 'para', natal: 'Natal', dayEnergy: { favorable: ['Dia Favorável', 'Trânsitos harmoniosos predominam. Energia fluida para ações e decisões.'], tense: ['Dia Tenso', 'Tensões ativas. Cautela em decisões e relações. Canalize a energia.'], neutral: ['Dia Neutro', 'Energia mista. Observe e escolha bem onde investir atenção.'] }, activeAreas: 'Áreas ativadas:', interpretationTitle: 'Interpretação dos Trânsitos', natalSuffix: 'natal', orb: 'orbe', house: 'Casa', in: 'em', natalChartHouse: 'do mapa natal', howToUse: 'Como usar:', howToUseText: 'Os trânsitos mostram a "meteorologia cósmica" do dia em relação ao seu mapa natal. Aspectos harmoniosos (trígono △, sextil ✶) indicam facilidade; tensos (quadratura □, oposição ☍) pedem ajuste. Planetas lentos (Saturno, Urano, Netuno, Plutão) marcam ciclos de meses; rápidos (Sol, Lua, Mercúrio) duram horas a dias.', themes: themes('Amor','Carreira','Finanças','Saúde','Espiritualidade','Família','Criatividade','Comunicação','Transformação','Liberdade','Viagens','Sexualidade') },
  en: { selectProfile: 'Select a profile from the top menu (👤) to view transits.', dateTitle: 'Transit Date', today: 'Today', nextDay: '+1 day', nextMonth: '+1 month', activeAspects: 'Active Aspects', loadingProfile: 'Loading profile...', selectProfileAbove: 'Select a profile using the 👤 icon above to view transits', transitsOf: 'Transits of', for: 'for', natal: 'Natal', dayEnergy: { favorable: ['Favorable Day', 'Harmonious transits predominate. Energy flows well for actions and decisions.'], tense: ['Tense Day', 'Active tensions call for care in decisions and relationships. Channel the energy.'], neutral: ['Neutral Day', 'Mixed energy. Observe and choose carefully where to focus your attention.'] }, activeAreas: 'Active areas:', interpretationTitle: 'Transit Interpretation', natalSuffix: 'natal', orb: 'orb', house: 'House', in: 'in', natalChartHouse: 'of the natal chart', howToUse: 'How to use:', howToUseText: 'Transits show the day’s cosmic weather in relation to your natal chart. Harmonious aspects (trine △, sextile ✶) indicate ease; tense ones (square □, opposition ☍) call for adjustment. Slow planets (Saturn, Uranus, Neptune, Pluto) mark cycles lasting months; fast planets (Sun, Moon, Mercury) last hours to days.', themes: themes('Love','Career','Finances','Health','Spirituality','Family','Creativity','Communication','Transformation','Freedom','Travel','Sexuality') },
  es: { selectProfile: 'Selecciona un perfil en el menú superior (👤) para ver los tránsitos.', dateTitle: 'Fecha de los Tránsitos', today: 'Hoy', nextDay: '+1 día', nextMonth: '+1 mes', activeAspects: 'Aspectos Activos', loadingProfile: 'Cargando perfil...', selectProfileAbove: 'Selecciona un perfil con el icono 👤 para ver los tránsitos', transitsOf: 'Tránsitos del', for: 'para', natal: 'Natal', dayEnergy: { favorable: ['Día Favorable', 'Predominan los tránsitos armónicos. Energía fluida para acciones y decisiones.'], tense: ['Día Tenso', 'Hay tensiones activas. Ten cautela en decisiones y relaciones. Canaliza la energía.'], neutral: ['Día Neutro', 'Energía mixta. Observa y elige bien dónde poner tu atención.'] }, activeAreas: 'Áreas activadas:', interpretationTitle: 'Interpretación de los Tránsitos', natalSuffix: 'natal', orb: 'orbe', house: 'Casa', in: 'en', natalChartHouse: 'de la carta natal', howToUse: 'Cómo usar:', howToUseText: 'Los tránsitos muestran la meteorología cósmica del día respecto a tu carta natal. Los aspectos armónicos (trígono △, sextil ✶) indican facilidad; los tensos (cuadratura □, oposición ☍) piden ajustes. Los planetas lentos marcan ciclos de meses; los rápidos duran de horas a días.', themes: themes('Amor','Carrera','Finanzas','Salud','Espiritualidad','Familia','Creatividad','Comunicación','Transformación','Libertad','Viajes','Sexualidad') },
  fr: { selectProfile: 'Sélectionnez un profil dans le menu supérieur (👤) pour voir les transits.', dateTitle: 'Date des Transits', today: "Aujourd’hui", nextDay: '+1 jour', nextMonth: '+1 mois', activeAspects: 'Aspects Actifs', loadingProfile: 'Chargement du profil...', selectProfileAbove: 'Sélectionnez un profil avec l’icône 👤 pour voir les transits', transitsOf: 'Transits du', for: 'pour', natal: 'Natal', dayEnergy: { favorable: ['Journée Favorable', 'Les transits harmonieux dominent. Énergie fluide pour agir et décider.'], tense: ['Journée Tendue', 'Des tensions sont actives. Prudence dans les décisions et les relations. Canalisez l’énergie.'], neutral: ['Journée Neutre', 'Énergie mixte. Observez et choisissez où placer votre attention.'] }, activeAreas: 'Domaines activés :', interpretationTitle: 'Interprétation des Transits', natalSuffix: 'natal', orb: 'orbe', house: 'Maison', in: 'en', natalChartHouse: 'du thème natal', howToUse: 'Mode d’emploi :', howToUseText: 'Les transits montrent la météo cosmique du jour par rapport à votre thème natal. Les aspects harmonieux indiquent de la facilité ; les aspects tendus demandent un ajustement. Les planètes lentes marquent des cycles de plusieurs mois, les rapides durent de quelques heures à quelques jours.', themes: themes('Amour','Carrière','Finances','Santé','Spiritualité','Famille','Créativité','Communication','Transformation','Liberté','Voyages','Sexualité') },
  de: { selectProfile: 'Wählen Sie oben im Menü ein Profil (👤), um die Transite zu sehen.', dateTitle: 'Transitdatum', today: 'Heute', nextDay: '+1 Tag', nextMonth: '+1 Monat', activeAspects: 'Aktive Aspekte', loadingProfile: 'Profil wird geladen...', selectProfileAbove: 'Wählen Sie über das Symbol 👤 ein Profil, um Transite zu sehen', transitsOf: 'Transite vom', for: 'für', natal: 'Radix', dayEnergy: { favorable: ['Günstiger Tag', 'Harmonische Transite überwiegen. Fließende Energie für Handlungen und Entscheidungen.'], tense: ['Angespannter Tag', 'Aktive Spannungen verlangen Vorsicht bei Entscheidungen und Beziehungen. Lenken Sie die Energie bewusst.'], neutral: ['Neutraler Tag', 'Gemischte Energie. Beobachten Sie und setzen Sie Ihre Aufmerksamkeit gezielt ein.'] }, activeAreas: 'Aktivierte Bereiche:', interpretationTitle: 'Transitdeutung', natalSuffix: 'Radix', orb: 'Orbis', house: 'Haus', in: 'in', natalChartHouse: 'des Geburtshoroskops', howToUse: 'Anwendung:', howToUseText: 'Transite zeigen das kosmische Wetter des Tages in Bezug auf Ihr Geburtshoroskop. Harmonische Aspekte weisen auf Leichtigkeit hin, Spannungsaspekte verlangen Anpassung. Langsame Planeten markieren monatelange Zyklen, schnelle wirken Stunden bis Tage.', themes: themes('Liebe','Karriere','Finanzen','Gesundheit','Spiritualität','Familie','Kreativität','Kommunikation','Transformation','Freiheit','Reisen','Sexualität') },
  it: { selectProfile: 'Seleziona un profilo dal menu superiore (👤) per vedere i transiti.', dateTitle: 'Data dei Transiti', today: 'Oggi', nextDay: '+1 giorno', nextMonth: '+1 mese', activeAspects: 'Aspetti Attivi', loadingProfile: 'Caricamento profilo...', selectProfileAbove: 'Seleziona un profilo con l’icona 👤 per vedere i transiti', transitsOf: 'Transiti del', for: 'per', natal: 'Natale', dayEnergy: { favorable: ['Giornata Favorevole', 'Predominano transiti armoniosi. Energia fluida per azioni e decisioni.'], tense: ['Giornata Tesa', 'Tensioni attive. Prudenza nelle decisioni e nelle relazioni. Canalizza l’energia.'], neutral: ['Giornata Neutra', 'Energia mista. Osserva e scegli bene dove investire l’attenzione.'] }, activeAreas: 'Aree attivate:', interpretationTitle: 'Interpretazione dei Transiti', natalSuffix: 'natale', orb: 'orbe', house: 'Casa', in: 'in', natalChartHouse: 'del tema natale', howToUse: 'Come usare:', howToUseText: 'I transiti mostrano il meteo cosmico del giorno rispetto al tema natale. Gli aspetti armoniosi indicano facilità, quelli tesi richiedono adattamento. I pianeti lenti segnano cicli di mesi; quelli veloci durano da ore a giorni.', themes: themes('Amore','Carriera','Finanze','Salute','Spiritualità','Famiglia','Creatività','Comunicazione','Trasformazione','Libertà','Viaggi','Sessualità') },
  ja: { selectProfile: 'トランジットを見るには上部メニュー（👤）からプロフィールを選択してください。', dateTitle: 'トランジットの日付', today: '今日', nextDay: '+1日', nextMonth: '+1か月', activeAspects: '有効なアスペクト', loadingProfile: 'プロフィールを読み込み中...', selectProfileAbove: '上の👤アイコンからプロフィールを選択してください', transitsOf: 'トランジット', for: '対象', natal: '出生図', dayEnergy: { favorable: ['好調な日', '調和的なトランジットが優勢です。行動や決断に流れがあります。'], tense: ['緊張のある日', '緊張が有効です。決断や人間関係では慎重に。エネルギーを意識的に使いましょう。'], neutral: ['中立的な日', '複合的なエネルギーです。観察し、注意を向ける先を選びましょう。'] }, activeAreas: '活性化する領域：', interpretationTitle: 'トランジット解釈', natalSuffix: '出生', orb: 'オーブ', house: 'ハウス', in: '位置', natalChartHouse: '出生図', howToUse: '使い方：', howToUseText: 'トランジットは出生図に対するその日の宇宙の天気を示します。調和的なアスペクトは容易さを、緊張のあるアスペクトは調整を示します。遅い惑星は数か月の周期を、速い惑星は数時間から数日の影響を表します。', themes: themes('恋愛','キャリア','財政','健康','精神性','家族','創造性','コミュニケーション','変容','自由','旅行','セクシュアリティ') },
  zh: { selectProfile: '请从顶部菜单（👤）选择档案以查看行运。', dateTitle: '行运日期', today: '今天', nextDay: '+1天', nextMonth: '+1个月', activeAspects: '有效相位', loadingProfile: '正在加载档案...', selectProfileAbove: '请通过上方👤图标选择档案以查看行运', transitsOf: '行运日期', for: '对象', natal: '本命盘', dayEnergy: { favorable: ['有利的一天', '和谐行运占主导，行动与决定较为顺畅。'], tense: ['紧张的一天', '紧张能量活跃。做决定和处理关系时要谨慎，并有意识地引导能量。'], neutral: ['中性的一天', '能量混合。先观察，再选择注意力的投入方向。'] }, activeAreas: '激活领域：', interpretationTitle: '行运解读', natalSuffix: '本命', orb: '容许度', house: '宫位', in: '位于', natalChartHouse: '本命盘中', howToUse: '使用方法：', howToUseText: '行运显示相对于本命盘的每日宇宙天气。和谐相位表示顺利，紧张相位要求调整。慢速行星标志持续数月的周期，快速行星影响数小时到数天。', themes: themes('爱情','事业','财务','健康','灵性','家庭','创造力','沟通','转化','自由','旅行','性') },
  ru: { selectProfile: 'Выберите профиль в верхнем меню (👤), чтобы увидеть транзиты.', dateTitle: 'Дата Транзитов', today: 'Сегодня', nextDay: '+1 день', nextMonth: '+1 месяц', activeAspects: 'Активные Аспекты', loadingProfile: 'Загрузка профиля...', selectProfileAbove: 'Выберите профиль значком 👤 выше, чтобы увидеть транзиты', transitsOf: 'Транзиты на', for: 'для', natal: 'Натал', dayEnergy: { favorable: ['Благоприятный День', 'Преобладают гармоничные транзиты. Энергия свободно течёт для действий и решений.'], tense: ['Напряжённый День', 'Активны напряжения. Осторожнее в решениях и отношениях. Направляйте энергию осознанно.'], neutral: ['Нейтральный День', 'Смешанная энергия. Наблюдайте и выбирайте, куда направить внимание.'] }, activeAreas: 'Активные сферы:', interpretationTitle: 'Интерпретация Транзитов', natalSuffix: 'натальный', orb: 'орбис', house: 'Дом', in: 'в', natalChartHouse: 'натальной карты', howToUse: 'Как использовать:', howToUseText: 'Транзиты показывают космическую погоду дня относительно натальной карты. Гармоничные аспекты дают лёгкость, напряжённые требуют корректировки. Медленные планеты отмечают многомесячные циклы, быстрые действуют от часов до дней.', themes: themes('Любовь','Карьера','Финансы','Здоровье','Духовность','Семья','Творчество','Общение','Трансформация','Свобода','Путешествия','Сексуальность') },
  tr: { selectProfile: 'Transitleri görmek için üst menüden (👤) bir profil seçin.', dateTitle: 'Transit Tarihi', today: 'Bugün', nextDay: '+1 gün', nextMonth: '+1 ay', activeAspects: 'Aktif Açılar', loadingProfile: 'Profil yükleniyor...', selectProfileAbove: 'Transitleri görmek için yukarıdaki 👤 simgesinden profil seçin', transitsOf: 'Transitler', for: 'hedef', natal: 'Doğum haritası', dayEnergy: { favorable: ['Olumlu Gün', 'Uyumlu transitler baskın. Eylem ve kararlar için akıcı enerji.'], tense: ['Gergin Gün', 'Aktif gerilimler var. Kararlarda ve ilişkilerde dikkatli olun. Enerjiyi yönlendirin.'], neutral: ['Nötr Gün', 'Karma enerji. Gözlemleyin ve dikkatinizi nereye vereceğinizi iyi seçin.'] }, activeAreas: 'Etkin alanlar:', interpretationTitle: 'Transit Yorumu', natalSuffix: 'doğum', orb: 'orb', house: 'Ev', in: 'burcunda', natalChartHouse: 'doğum haritasında', howToUse: 'Nasıl kullanılır:', howToUseText: 'Transitler, doğum haritanıza göre günün kozmik havasını gösterir. Uyumlu açılar kolaylığı, gergin açılar ayarlama ihtiyacını belirtir. Yavaş gezegenler aylar süren döngüleri, hızlı gezegenler saatler veya günler süren etkileri gösterir.', themes: themes('Aşk','Kariyer','Finans','Sağlık','Maneviyat','Aile','Yaratıcılık','İletişim','Dönüşüm','Özgürlük','Seyahat','Cinsellik') },
  nl: { selectProfile: 'Selecteer een profiel in het bovenste menu (👤) om transits te bekijken.', dateTitle: 'Transitdatum', today: 'Vandaag', nextDay: '+1 dag', nextMonth: '+1 maand', activeAspects: 'Actieve Aspecten', loadingProfile: 'Profiel laden...', selectProfileAbove: 'Selecteer een profiel via het pictogram 👤 om transits te bekijken', transitsOf: 'Transits van', for: 'voor', natal: 'Geboortehoroscoop', dayEnergy: { favorable: ['Gunstige Dag', 'Harmonische transits overheersen. De energie stroomt voor acties en beslissingen.'], tense: ['Gespannen Dag', 'Er zijn actieve spanningen. Wees voorzichtig met beslissingen en relaties. Kanaliseer de energie.'], neutral: ['Neutrale Dag', 'Gemengde energie. Observeer en kies zorgvuldig waar je aandacht naartoe gaat.'] }, activeAreas: 'Geactiveerde gebieden:', interpretationTitle: 'Transitinterpretatie', natalSuffix: 'radix', orb: 'orb', house: 'Huis', in: 'in', natalChartHouse: 'van de geboortehoroscoop', howToUse: 'Gebruik:', howToUseText: 'Transits tonen het kosmische weer van de dag ten opzichte van je geboortehoroscoop. Harmonische aspecten wijzen op gemak; gespannen aspecten vragen aanpassing. Langzame planeten markeren cycli van maanden, snelle planeten duren uren tot dagen.', themes: themes('Liefde','Carrière','Financiën','Gezondheid','Spiritualiteit','Familie','Creativiteit','Communicatie','Transformatie','Vrijheid','Reizen','Seksualiteit') },
};

export function getTransitUi(locale: Locale | undefined): TransitUiText {
  return texts[locale || 'pt'] || texts.pt;
}
