export const chiron = {
  title: 'Chiron — Le Guérisseur Blessé',
  intro: 'Chiron est un corps céleste découvert en 1977, classifié comme planétoïde ou centaure, en orbite entre Saturne et Uranus. En astrologie humaniste, il représente la blessure primordiale que nous portons — une douleur que nous ne pouvons pas guérir en nous-mêmes, mais qui nous rend paradoxalement capables d\'aider les autres. C\'est l\'archétype du thérapeute, du mentor et du sage qui a appris à travers la souffrance.',
  mythology: {
    title: 'La Mythologie de Chiron',
    text: 'Chiron était un centaure différent des autres : sage, civilisé, maître de la médecine, de la musique, de la prophétie et des arts martiaux. Il fut tuteur de héros comme Achille, Asclépios et Jason. Fils de Cronos et Philyra, il fut abandonné par sa mère à la naissance pour être mi-homme, mi-cheval — sa première blessure : le rejet de sa propre origine.',
    wound: 'Son ironie tragique : étant le plus grand guérisseur de la Grèce antique, il reçut une flèche empoisonnée d\'Héraclès — un accident, non une malveillance — et, étant immortel, ne pouvait mourir, mais ne pouvait pas non plus se guérir lui-même. Il vécut dans une douleur éternelle, jusqu\'à ce qu\'il abandonne son immortalité et soit transformé en constellation.',
    meaning: 'La blessure de Chiron ne se résout pas. Elle s\'intègre. C\'est la différence fondamentale entre Saturne (qui surmonte par la discipline) et Chiron (qui apprend à vivre avec la blessure jusqu\'à ce qu\'elle devienne sagesse).',
  },
  signsTitle: 'Chiron à Travers les Signes',
  signsIntro: 'Le signe de Chiron révèle la nature de la blessure — le "où ça fait mal" au niveau de l\'identité. Chiron passant entre 4 et 9 ans dans chaque signe, c\'est une blessure générationnelle partagée par des millions de personnes.',
  signs: [
    { sign: 'Bélier ♈', years: '(1968–77 / 2018–27)', wound: 'Blessure dans l\'existence et l\'initiative', healing: 'Guérison par le droit d\'agir, de mener et d\'exister pleinement' },
    { sign: 'Taureau ♉', years: '(1977–83)', wound: 'Blessure dans la valeur personnelle et le corps', healing: 'Guérison par une relation saine avec la valeur personnelle et les ressources' },
    { sign: 'Gémeaux ♊', years: '(1983–88)', wound: 'Blessure dans la communication et l\'intellect', healing: 'Guérison par la capacité à être entendu et compris' },
    { sign: 'Cancer ♋', years: '(1988–91)', wound: 'Blessure dans l\'appartenance et la famille', healing: 'Guérison en créant un foyer intérieur indépendant de l\'extérieur' },
    { sign: 'Lion ♌', years: '(1991–93)', wound: 'Blessure dans l\'expression de soi et la reconnaissance', healing: 'Guérison par le droit de briller sans avoir besoin d\'approbation' },
    { sign: 'Vierge ♍', years: '(1993–96)', wound: 'Blessure dans la perfection et l\'adéquation', healing: 'Guérison en acceptant l\'imperfection comme partie de l\'être humain' },
    { sign: 'Balance ♎', years: '(1996–99)', wound: 'Blessure dans les relations et l\'équilibre', healing: 'Guérison en apprenant à se relier sans se perdre' },
    { sign: 'Scorpion ♏', years: '(1999–01)', wound: 'Blessure dans le pouvoir et l\'intimité', healing: 'Guérison en affrontant les ombres sans destruction' },
    { sign: 'Sagittaire ♐', years: '(2001–05)', wound: 'Blessure dans la foi, le sens et l\'appartenance philosophique', healing: 'Guérison en trouvant sa propre vérité, non héritée' },
    { sign: 'Capricorne ♑', years: '(2005–10)', wound: 'Blessure dans l\'autorité et le succès', healing: 'Guérison en redéfinissant la réussite selon ses propres termes' },
    { sign: 'Verseau ♒', years: '(2010–11)', wound: 'Blessure dans l\'originalité et l\'appartenance au groupe', healing: 'Guérison par le droit d\'être différent et encore aimé' },
    { sign: 'Poissons ♓', years: '(2011–18)', wound: 'Blessure dans la spiritualité et les limites de l\'ego', healing: 'Guérison en intégrant le transcendant sans s\'y dissoudre' },
  ],
  housesTitle: 'Chiron à Travers les Maisons',
  housesIntro: 'La maison de Chiron indique le domaine de vie où la blessure se manifeste — où vous vous sentez comme l\'"éternel blessé qui guérit les autres". C\'est aussi là où votre plus grande sagesse émerge après intégration.',
  houses: [
    { num: '1ère', name: 'Maison de l\'Identité', wound: 'Blessure dans sa propre existence et présence', gift: 'Pouvoir d\'enseigner aux autres comment exister pleinement' },
    { num: '2ème', name: 'Maison des Ressources', wound: 'Blessure dans la valeur personnelle et le soutien matériel', gift: 'Don pour aider les autres à découvrir leurs talents' },
    { num: '3ème', name: 'Maison de la Communication', wound: 'Blessure dans l\'expression verbale et l\'apprentissage', gift: 'Don comme enseignant, écrivain ou communicateur' },
    { num: '4ème', name: 'Maison du Foyer', wound: 'Blessure dans les racines, la famille et la sécurité émotionnelle', gift: 'Capacité de créer foyer et accueil pour les autres' },
    { num: '5ème', name: 'Maison de la Création', wound: 'Blessure dans l\'expression créatrice et la joie', gift: 'Don pour inspirer la créativité chez les autres' },
    { num: '6ème', name: 'Maison de la Santé', wound: 'Blessure dans le corps, la santé et les routines', gift: 'Don pour la guérison physique et holistique' },
    { num: '7ème', name: 'Maison des Relations', wound: 'Blessure dans le partenariat intime et l\'engagement', gift: 'Don pour médier et conseiller les relations' },
    { num: '8ème', name: 'Maison de la Transformation', wound: 'Blessure dans les pertes, la sexualité et le pouvoir partagé', gift: 'Don pour guider les autres à travers les processus de mort/renaissance' },
    { num: '9ème', name: 'Maison de la Philosophie', wound: 'Blessure dans la croyance, la foi et la recherche de sens', gift: 'Don comme enseignant spirituel et philosophe' },
    { num: '10ème', name: 'Maison de la Carrière', wound: 'Blessure dans la reconnaissance publique et l\'autorité', gift: 'Don pour diriger avec une humilité sincère' },
    { num: '11ème', name: 'Maison des Groupes', wound: 'Blessure dans l\'appartenance et les amitiés', gift: 'Don pour guérir les communautés et les groupes' },
    { num: '12ème', name: 'Maison de l\'Inconscient', wound: 'Blessure profondément inconsciente, difficile à articuler', gift: 'Don spirituel et capacité de guérison transcendante' },
  ],
  healingTitle: 'Comment Guérir la Blessure de Chiron',
  healingIntro: 'La blessure de Chiron ne disparaît pas — elle s\'intègre. Le processus n\'est pas de la surmonter, mais de l\'alchimie : transformer la douleur en sagesse.',
  healingSteps: [
    { step: '1. Reconnaître la blessure', text: 'La première étape est de la nommer : "voici où ça fait mal d\'une façon sans remède simple". Ne minimisez pas, ne dramatisez pas. Reconnaissez simplement avec compassion.' },
    { step: '2. Abandonner le rôle du "guérisseur qui nie"', text: 'Le Chiron blessé passe fréquemment sa vie à guérir tout le monde sauf lui-même. Aider les autres est réel et précieux — mais ne peut pas être une fuite du regard intérieur.' },
    { step: '3. Accepter la vulnérabilité comme force', text: 'La tendance est de cacher la blessure de Chiron. Mais c\'est précisément quand nous la révélons — avec discernement — qu\'elle gagne un pouvoir guérisseur. La vulnérabilité authentique génère la connexion.' },
    { step: '4. Chercher thérapie, mentorat ou soutien', text: 'Ironique mais vrai : ceux qui ont un Chiron prominent cherchent rarement de l\'aide. La guérison commence quand vous acceptez que vous pouvez aussi être le "blessé" et pas seulement le "guérisseur".' },
    { step: '5. La transformer en vocation', text: 'La question n\'est pas "comment me débarrasser de cette blessure ?" mais "comment cette blessure peut-elle me rendre utile au monde ?" Un Chiron bien intégré est l\'un des points les plus puissants du thème.' },
  ],
  cta: 'Découvrez la position de Chiron dans votre thème natal',
  ctaButton: 'Calculer Mon Thème →',
};
