export const horoscope = {
  daily: {
    title: 'Horoscope Quotidien Personnel',
    subtitle: 'Vos transits personnels du jour avec interprétation détaillée',
    selectProfile: 'Sélectionnez un profil pour voir votre horoscope personnalisé',
    noProfile: 'Calculez d\'abord votre thème natal.',
    moonToday: 'Lune aujourd\'hui',
    activeTransits: 'Transits Actifs',
    intensity: { high: 'fort', medium: 'moyen', low: 'léger' },
    categories: { love: 'Amour', career: 'Carrière', health: 'Santé' },
    today: 'Aujourd\'hui',
    tomorrow: 'Demain',
  },
  love: {
    title: 'Horoscope Amoureux',
    subtitle: 'Vénus, Mars et les aspects d\'aujourd\'hui influençant votre vie amoureuse',
  },
  weekly: {
    title: 'Horoscope Hebdomadaire',
    subtitle: 'Aperçu des transits et énergies pour les 7 prochains jours',
    thisWeek: 'Cette semaine',
    prevWeek: '← Semaine',
    nextWeek: 'Semaine →',
    selectProfile: 'Sélectionnez un profil pour voir l\'horoscope hebdomadaire',
  },
  events: {
    title: 'Événements Célestes',
    subtitle: 'Ingresses planétaires, aspects exacts, phases lunaires et stations rétrogrades',
    noEvents: 'Aucun événement céleste significatif ce jour.',
    types: { ingress: 'Ingresse', aspect: 'Aspect exact', 'moon-phase': 'Phase lunaire', retrograde: 'Station' },
  },
  interpretation: {
    title: 'Interprétation de Base',
    premiumCta: 'Vous voulez une analyse personnalisée complète ?',
    premiumDesc: 'Notre Rapport Natal Complet inclut toutes les planètes, aspects, dignités et prévisions en PDF professionnel.',
    premiumButton: 'Voir les Rapports Premium',
    freeNotice: 'Interprétation résumée gratuite. Pour une analyse complète (plus de 20 pages), consultez nos rapports premium.',
  },
  transitTexts: {
    noTransits: 'Journée calme sans transits significatifs. Prenez du temps pour vous reposer et réfléchir.',
    intenseDay: 'Journée intense avec de multiples transits puissants. Restez conscient et flexible.',
    normalWork: 'Journée normale au travail. Gardez votre focus sur les tâches quotidiennes.',
    energyHigh: 'Énergie élevée mais tendance à l\'excès. Faites de l\'exercice mais évitez la surcharge.',
    vitalityGood: 'Vitalité élevée. Excellent pour les activités physiques et le sport.',
    energyStable: 'Énergie stable. Maintenez des habitudes saines et respectez votre rythme.',
  },
  moonLove: [
    'Impulsion romantique et passion rapide.',
    'Sensualité et désir de confort ensemble.',
    'Flirt intellectuel et conversations séduisantes.',
    'Besoin d\'affection et de sécurité en amour.',
    'Romance dramatique et expression généreuse.',
    'Amour montré à travers des actes pratiques.',
    'Recherche d\'harmonie et de compagnie.',
    'Désir intense et possessif.',
    'Attraction pour la nouveauté et l\'aventure.',
    'Amour mûr et engagement.',
    'Liberté en amour et connexions inhabituelles.',
    'Romantisme et idéalisation.',
  ],
};
