export const planetaryCycles = {
  title: 'Cycles Planétaires',
  intro: 'L\'astrologie a une dimension temporelle qui va au-delà du thème natal. Les planètes continuent de se déplacer après la naissance et reviennent périodiquement au même point du ciel où elles se trouvaient à votre naissance — ou forment des angles significatifs avec ce point. Ces cycles fonctionnent comme une horloge biologique-symbolique de la psyché, marquant des phases naturelles de croissance, de crise, d\'intégration et de renouveau.',
  whatAreCycles: {
    title: 'Que Sont les Cycles Planétaires ?',
    text: 'Chaque planète a une période orbitale — le temps qu\'il faut pour compléter une orbite complète autour du Soleil. Quand une planète en transit revient au point exact qu\'elle occupait au moment de votre naissance, on appelle cela un "retour". Quand elle forme un angle de 180° avec la position natale, on appelle cela une "opposition".',
    note: 'Les retours et oppositions ne sont pas des événements externes qui "vous arrivent" — ce sont des invitations internes à réviser, intégrer ou transformer une dimension spécifique de votre vie.',
  },
  cycles: [
    {
      planet: 'Jupiter ♃',
      icon: '✦',
      cycle: 'Retour tous les ~12 ans',
      ages: '12, 24, 36, 48, 60, 72...',
      title: 'Le Cycle d\'Expansion',
      description: 'Jupiter complète une orbite en environ 12 ans. Ses retours coïncident avec des années d\'opportunité, d\'expansion et de portes ouvertes. Le retour de Jupiter ne livre pas d\'opportunités — il affûte votre perception de celles déjà présentes.',
      phases: [
        { age: '~12 ans', title: 'Premier retour', text: 'Transition de l\'enfance à la pré-adolescence. Expansion de la vision du monde, premiers questionnements philosophiques.' },
        { age: '~24 ans', title: 'Deuxième retour', text: 'Expansion vers la vie adulte indépendante. Année d\'opportunités professionnelles ou éducatives.' },
        { age: '~36 ans', title: 'Troisième retour', text: 'Consolidation et expansion de l\'identité adulte. Ouverture à de nouveaux projets de vie.' },
        { age: '~48 ans', title: 'Quatrième retour', text: 'Renouveau de but et de sens. Coïncide souvent avec des changements de carrière ou de philosophie de vie.' },
      ],
    },
    {
      planet: 'Saturne ♄',
      icon: '⧖',
      cycle: 'Retour à ~29-30 ans et ~58-60 ans',
      ages: '~14-15 (carré), ~29-30 (retour), ~36-37 (opposition), ~58-60 (retour)',
      title: 'Le Grand Maître — Retour de Saturne',
      description: 'Saturne est la planète la plus redoutée et la plus importante des cycles de vie. Son premier retour, vers 29-30 ans, est un rite de passage universel — le moment où la jeunesse se termine et la vraie vie adulte commence. Vous êtes convoqué à assumer pleinement la responsabilité de qui vous êtes.',
      phases: [
        { age: '~14-15 ans', title: 'Premier carré', text: 'Première confrontation avec l\'autorité et les limites. Identité adolescente en formation.' },
        { age: '~21-22 ans', title: 'Premier carré croissant', text: 'Tension entre la liberté désirée et les responsabilités croissantes.' },
        { age: '~29-30 ans', title: 'Retour de Saturne', text: 'Le grand tournant. Saturne "réclame sa dette" — les relations, carrières et identités bâties sans authenticité ont tendance à se dissoudre. Ce qui est genuinement vrai se renforce. Crise existentielle fréquente, mais nécessaire.' },
        { age: '~36-37 ans', title: 'Opposition de Saturne', text: 'Révision à mi-cycle. Évaluation de ce qui a été construit depuis 29 ans. Moment de correction de cap.' },
        { age: '~44 ans', title: 'Deuxième carré décroissant', text: 'Préparation au deuxième retour. Confrontation avec ce qui a été remis à plus tard ou nié.' },
        { age: '~58-60 ans', title: 'Deuxième Retour de Saturne', text: 'Transition vers la pleine maturité. Profonde révision de l\'héritage et du but de vie.' },
      ],
    },
    {
      planet: 'Uranus ♅',
      icon: '⚡',
      cycle: 'Opposition à ~38-44 ans',
      ages: '~38-44 (opposition), ~84 (retour)',
      title: 'La Crise du Milieu de Vie — Opposition d\'Uranus',
      description: 'Uranus met 84 ans pour compléter son cycle. L\'opposition — quand Uranus en transit forme 180° avec Uranus natal — se produit entre 38 et 44 ans. C\'est la fameuse "crise du milieu de vie". Uranus, la planète de la liberté et de la rupture, remet radicalement en question les schémas établis.',
      phases: [
        { age: '~38-44 ans', title: 'Opposition d\'Uranus', text: 'Urgence soudaine de liberté. Remise en question de tout ce qui a été construit. "Pour qui est-ce que je vis cette vie ?" Peut se manifester par des changements abrupts de carrière, de relation ou de style de vie. Ce n\'est pas une crise à éviter — c\'est un appel à l\'authenticité.' },
        { age: '~21 ans', title: 'Carré d\'Uranus', text: 'Premier élan pour se libérer des schémas parentaux et sociaux. "Je ne veux pas de la vie qu\'on m\'a appris à vouloir."' },
        { age: '~63 ans', title: 'Deuxième carré', text: 'Consolidation de l\'identité authentique après la crise du milieu de vie. Qui suis-je vraiment, libre des attentes ?' },
      ],
    },
    {
      planet: 'Chiron ⚷',
      icon: '⚷',
      cycle: 'Retour à ~49-51 ans',
      ages: '~49-51 (retour)',
      title: 'Le Retour de Chiron',
      description: 'Chiron, le Guérisseur Blessé, revient au point natal vers 49 à 51 ans — coïncidant souvent avec la ménopause/andropause et ce que Jung appelait "l\'individuation". C\'est une invitation à l\'intégration finale de la blessure primordiale.',
      phases: [
        { age: '~49-51 ans', title: 'Retour de Chiron', text: 'La question centrale : "Quelle part de cette douleur que je porte est encore nécessaire ?" C\'est le moment d\'accepter que la blessure n\'a plus besoin d\'être cachée. La vulnérabilité devient sagesse. Beaucoup de gens commencent ou approfondissent un travail thérapeutique ou spirituel pendant cette période.' },
        { age: '~22-25 ans', title: 'Carré de Chiron', text: 'Première crise avec la blessure. Peut être une période d\'isolement, de honte ou de difficulté d\'appartenance.' },
        { age: '~37-40 ans', title: 'Opposition de Chiron', text: 'Confrontation directe avec la blessure. Coïncide souvent avec la crise du milieu de vie et demande de faire face à ce qui a été évité.' },
      ],
    },
    {
      planet: 'Neptune ♆',
      icon: '🌊',
      cycle: 'Carré à ~40-42 ans et ~82-84 ans',
      ages: '~40-42 (premier carré), ~82-84 (retour)',
      title: 'Dissolution et Transcendance',
      description: 'Neptune met 165 ans pour compléter son cycle. Le carré de Neptune (à ~40-42 ans) coïncide souvent avec la crise du milieu de vie et ajoute une dimension de dissolution des illusions — notamment sur qui nous sommes et ce que nous voulons.',
      phases: [
        { age: '~40-42 ans', title: 'Carré de Neptune', text: 'Dissolution des illusions construites dans la jeunesse. "La vie que j\'imaginais n\'est pas exactement celle-ci." Période de désorientation créatrice — l\'ancien soi se dissout avant que le nouveau se forme.' },
      ],
    },
    {
      planet: 'Pluton ♇',
      icon: '🔥',
      cycle: 'Carré à ~36-44 ans',
      ages: '~36-44 (premier carré)',
      title: 'Mort et Renaissance',
      description: 'Pluton met 248 ans, donc il ne revient jamais. Mais le carré plutonien (à ~36-44 ans) est l\'une des transitions les plus intenses — coïncidant avec la crise du milieu de vie et exigeant la mort symbolique des parties de l\'ego devenues des obstacles.',
      phases: [
        { age: '~36-44 ans', title: 'Carré de Pluton', text: 'Processus de mort-renaissance psychologique. Pouvoir, contrôle, ombre et vulnérabilité remontent à la surface. Ce à quoi vous vous accrochiez avec force commence à se dissoudre. Profondément transformateur et potentiellement effrayant — et nécessaire.' },
      ],
    },
  ],
  integration: {
    title: 'Comment Travailler avec les Cycles Consciemment',
    text: 'Connaître vos cycles ne vise pas à prédire l\'avenir — c\'est à préparer le terrain intérieur. Quand vous savez que vous entrez dans une période saturnienne, par exemple, vous pouvez créer de l\'espace pour la révision plutôt que d\'être emporté par elle. Les cycles ne sont pas déterministes : ils révèlent la qualité du temps, pas son contenu.',
    tips: [
      'Identifiez dans quel cycle vous vous trouvez actuellement',
      'Demandez-vous : quel type de croissance ce cycle invite-t-il ?',
      'Résistez à l\'impulsion de "fuir" les crises des grands cycles',
      'Utilisez la thérapie, la méditation ou le journal comme outils d\'intégration',
      'Les cycles difficiles produisent les plus grands bonds de conscience quand on les traverse consciemment',
    ],
  },
  cta: 'Découvrez dans quels cycles vous vous trouvez maintenant',
  ctaButton: 'Voir Mes Transits →',
};
