export const signs = {
  title: 'Les 12 Signes du Zodiaque',
  intro: 'Les signes sont 12 archétypes énergétiques. Chaque planète dans votre thème est dans un signe, colorant son expression de qualités spécifiques.',
  list: [
    { symbol: '♈', name: 'Bélier', dates: '21 Mar – 19 Avr', element: 'Feu', mode: 'Cardinal', ruler: '♂ Mars', color: '#cc0000', description: 'Premier signe — l\'étincelle du commencement. Courage, impulsion, compétitivité et individualité. Le Bélier brise l\'inertie et ouvre de nouvelles voies. Ombre : impulsivité, égoïsme, agressivité.' },
    { symbol: '♉', name: 'Taureau', dates: '20 Avr – 20 Mai', element: 'Terre', mode: 'Fixe', ruler: '♀ Vénus', color: '#006600', description: 'Consolidation de ce que le Bélier a commencé. Stabilité, plaisir sensoriel, loyauté et persévérance. Le Taureau bâtit des fondations solides avec patience. Ombre : possessivité, entêtement, matérialisme.' },
    { symbol: '♊', name: 'Gémeaux', dates: '21 Mai – 20 Jun', element: 'Air', mode: 'Mutable', ruler: '☿ Mercure', color: '#0000cc', description: 'Le pont entre les mondes. Curiosité insatiable, communication, versatilité et légèreté. Les Gémeaux relient information et personnes. Ombre : superficialité, inconsistance, dualité.' },
    { symbol: '♋', name: 'Cancer', dates: '21 Jun – 22 Jul', element: 'Eau', mode: 'Cardinal', ruler: '☽ Lune', color: '#cc6600', description: 'Le nid émotionnel. Protection, mémoire, appartenance et soin. Le Cancer crée des racines et prend soin profondément. Ombre : dépendance, manipulation émotionnelle, attachement au passé.' },
    { symbol: '♌', name: 'Lion', dates: '23 Jul – 22 Aoû', element: 'Feu', mode: 'Fixe', ruler: '☉ Soleil', color: '#cc0000', description: 'La scène de la vie. Expression créatrice, éclat personnel, générosité et leadership. Le Lion irradie et inspire. Ombre : arrogance, besoin d\'applaudissements, drame.' },
    { symbol: '♍', name: 'Vierge', dates: '23 Aoû – 22 Sep', element: 'Terre', mode: 'Mutable', ruler: '☿ Mercure', color: '#006600', description: 'Raffinement de l\'expérience. Analyse, compétence, service et amélioration. La Vierge sépare l\'essentiel du superflu. Ombre : critique excessive, perfectionnisme, anxiété.' },
    { symbol: '♎', name: 'Balance', dates: '23 Sep – 22 Oct', element: 'Air', mode: 'Cardinal', ruler: '♀ Vénus', color: '#0000cc', description: 'La rencontre avec l\'autre. Équilibre, justice, diplomatie et partenariat. La Balance cherche harmonie dans les relations et l\'esthétique. Ombre : indécision, dépendance aux autres.' },
    { symbol: '♏', name: 'Scorpion', dates: '23 Oct – 21 Nov', element: 'Eau', mode: 'Fixe', ruler: '♇ Pluton', color: '#cc6600', description: 'La descente dans les profondeurs. Intensité, transformation, vérité et pouvoir. Le Scorpion ne craint pas ce qui est caché. Ombre : obsession, jalousie, manipulation, vengeance.' },
    { symbol: '♐', name: 'Sagittaire', dates: '22 Nov – 21 Déc', element: 'Feu', mode: 'Mutable', ruler: '♃ Jupiter', color: '#cc0000', description: 'La flèche du sens. Expansion, philosophie, aventure et foi. Le Sagittaire cherche la signification au-delà de l\'horizon. Ombre : excès, fanatisme, irresponsabilité.' },
    { symbol: '♑', name: 'Capricorne', dates: '22 Déc – 19 Jan', element: 'Terre', mode: 'Cardinal', ruler: '♄ Saturne', color: '#006600', description: 'La montagne à gravir. Ambition, discipline, maturité et héritage. Le Capricorne bâtit avec le temps et la persistance. Ombre : froideur, rigidité, pessimisme.' },
    { symbol: '♒', name: 'Verseau', dates: '20 Jan – 18 Fév', element: 'Air', mode: 'Fixe', ruler: '♅ Uranus', color: '#0000cc', description: 'La révolution silencieuse. Originalité, indépendance, vision d\'avenir et humanitarisme. Le Verseau remet en question le statu quo. Ombre : distanciation émotionnelle, rébellion vide.' },
    { symbol: '♓', name: 'Poissons', dates: '19 Fév – 20 Mar', element: 'Eau', mode: 'Mutable', ruler: '♆ Neptune', color: '#cc6600', description: 'L\'océan final. Compassion universelle, spiritualité, art et dissolution de l\'ego. Les Poissons ressentent tout et se connectent au tout. Ombre : évasion, victimisation, confusion.' },
  ],
};
