export const chiron = {
  title: 'Chirone — Il Guaritore Ferito',
  intro: 'Chirone è un corpo celeste scoperto nel 1977, classificato come planetoide o centauro, in orbita tra Saturno e Urano. Nell\'astrologia umanistica, rappresenta la ferita primordiale che portiamo — un dolore che non possiamo guarire in noi stessi, ma che paradossalmente ci rende capaci di aiutare gli altri. È l\'archetipo del terapeuta, del mentore e del saggio che ha imparato attraverso la sofferenza.',
  mythology: {
    title: 'La Mitologia di Chirone',
    text: 'Chirone era un centauro diverso dagli altri: saggio, civilizzato, maestro di medicina, musica, profezia e arti marziali. Fu tutore di eroi come Achille, Asclepio e Giasone. Figlio di Crono e Fillira, fu abbandonato da sua madre alla nascita per essere metà uomo, metà cavallo — la sua prima ferita: il rifiuto della propria origine.',
    wound: 'La sua tragica ironia: essendo il più grande guaritore dell\'Antica Grecia, ricevette una freccia avvelenata da Ercole — un incidente, non malizia — e, essendo immortale, non poteva morire, ma nemmeno guarire se stesso. Visse in eterno dolore, finché rinunciò alla sua immortalità e fu trasformato in costellazione.',
    meaning: 'La ferita di Chirone non si risolve. Si integra. Questa è la differenza fondamentale tra Saturno (che supera attraverso la disciplina) e Chirone (che impara a convivere con la ferita finché diventa saggezza).',
  },
  signsTitle: 'Chirone Attraverso i Segni',
  signsIntro: 'Il segno di Chirone rivela la natura della ferita — il "dove fa male" al livello dell\'identità. Poiché Chirone trascorre tra 4 e 9 anni in ogni segno, è una ferita generazionale condivisa da milioni di persone.',
  signs: [
    { sign: 'Ariete ♈', years: '(1968–77 / 2018–27)', wound: 'Ferita nell\'esistenza e nell\'iniziativa', healing: 'Guarigione attraverso il diritto di agire, guidare ed esistere pienamente' },
    { sign: 'Toro ♉', years: '(1977–83)', wound: 'Ferita nell\'autostima e nel corpo', healing: 'Guarigione attraverso un sano rapporto con il valore personale e le risorse' },
    { sign: 'Gemelli ♊', years: '(1983–88)', wound: 'Ferita nella comunicazione e nell\'intelletto', healing: 'Guarigione attraverso la capacità di essere ascoltato e compreso' },
    { sign: 'Cancro ♋', years: '(1988–91)', wound: 'Ferita nell\'appartenenza e nella famiglia', healing: 'Guarigione creando una casa interiore indipendente dall\'esterno' },
    { sign: 'Leone ♌', years: '(1991–93)', wound: 'Ferita nell\'espressione di sé e nel riconoscimento', healing: 'Guarigione attraverso il diritto di brillare senza bisogno di approvazione' },
    { sign: 'Vergine ♍', years: '(1993–96)', wound: 'Ferita nella perfezione e nell\'adeguatezza', healing: 'Guarigione accettando l\'imperfezione come parte dell\'essere umano' },
    { sign: 'Bilancia ♎', years: '(1996–99)', wound: 'Ferita nelle relazioni e nell\'equilibrio', healing: 'Guarigione imparando a relazionarsi senza perdersi' },
    { sign: 'Scorpione ♏', years: '(1999–01)', wound: 'Ferita nel potere e nell\'intimità', healing: 'Guarigione affrontando le ombre senza distruzione' },
    { sign: 'Sagittario ♐', years: '(2001–05)', wound: 'Ferita nella fede, nel senso e nell\'appartenenza filosofica', healing: 'Guarigione trovando la propria verità, non una ereditata' },
    { sign: 'Capricorno ♑', years: '(2005–10)', wound: 'Ferita nell\'autorità e nel successo', healing: 'Guarigione ridefinendo il successo secondo i propri termini' },
    { sign: 'Acquario ♒', years: '(2010–11)', wound: 'Ferita nell\'originalità e nell\'appartenenza al gruppo', healing: 'Guarigione attraverso il diritto di essere diversi e ancora amati' },
    { sign: 'Pesci ♓', years: '(2011–18)', wound: 'Ferita nella spiritualità e nei confini dell\'ego', healing: 'Guarigione integrando il trascendente senza dissolversi in esso' },
  ],
  housesTitle: 'Chirone Attraverso le Case',
  housesIntro: 'La casa di Chirone indica l\'area della vita dove la ferita si manifesta — dove ti senti come il "ferito eterno che guarisce gli altri". È anche dove emerge la tua più grande saggezza dopo l\'integrazione.',
  houses: [
    { num: '1ª', name: 'Casa dell\'Identità', wound: 'Ferita nella propria esistenza e presenza', gift: 'Potere di insegnare agli altri come esistere pienamente' },
    { num: '2ª', name: 'Casa delle Risorse', wound: 'Ferita nell\'autostima e nel sostentamento materiale', gift: 'Dono per aiutare gli altri a scoprire i propri talenti' },
    { num: '3ª', name: 'Casa della Comunicazione', wound: 'Ferita nell\'espressione verbale e nell\'apprendimento', gift: 'Dono come insegnante, scrittore o comunicatore' },
    { num: '4ª', name: 'Casa della Casa', wound: 'Ferita nelle radici, nella famiglia e nella sicurezza emotiva', gift: 'Capacità di creare casa e accoglienza per gli altri' },
    { num: '5ª', name: 'Casa della Creazione', wound: 'Ferita nell\'espressione creativa e nella gioia', gift: 'Dono per ispirare la creatività negli altri' },
    { num: '6ª', name: 'Casa della Salute', wound: 'Ferita nel corpo, nella salute e nelle routine', gift: 'Dono per la guarigione fisica e olistica' },
    { num: '7ª', name: 'Casa delle Relazioni', wound: 'Ferita nella partnership intima e nell\'impegno', gift: 'Dono per mediare e consigliare nelle relazioni' },
    { num: '8ª', name: 'Casa della Trasformazione', wound: 'Ferita nelle perdite, nella sessualità e nel potere condiviso', gift: 'Dono per guidare gli altri attraverso i processi di morte/rinascita' },
    { num: '9ª', name: 'Casa della Filosofia', wound: 'Ferita nella credenza, nella fede e nella ricerca di senso', gift: 'Dono come insegnante spirituale e filosofo' },
    { num: '10ª', name: 'Casa della Carriera', wound: 'Ferita nel riconoscimento pubblico e nell\'autorità', gift: 'Dono per guidare con genuina umiltà' },
    { num: '11ª', name: 'Casa dei Gruppi', wound: 'Ferita nell\'appartenenza e nelle amicizie', gift: 'Dono per guarire comunità e gruppi' },
    { num: '12ª', name: 'Casa dell\'Inconscio', wound: 'Ferita profondamente inconscia, difficile da articolare', gift: 'Dono spirituale e capacità di guarigione trascendente' },
  ],
  healingTitle: 'Come Guarire la Ferita di Chirone',
  healingIntro: 'La ferita di Chirone non scompare — si integra. Il processo non è di superamento, ma di alchimia: trasformare il dolore in saggezza.',
  healingSteps: [
    { step: '1. Riconoscere la ferita', text: 'Il primo passo è nominarla: "qui è dove fa male in un modo che non ha cura semplice". Non minimizzare, non drammatizzare. Semplicemente riconoscere con compassione.' },
    { step: '2. Abbandonare il ruolo del "guaritore che nega"', text: 'Il Chirone ferito trascorre spesso la vita a guarire tutti tranne se stesso. Aiutare gli altri è reale e prezioso — ma non può essere una fuga dal guardare dentro di sé.' },
    { step: '3. Accettare la vulnerabilità come forza', text: 'La tendenza è nascondere la ferita di Chirone. Ma è precisamente quando la riveliamo — con discernimento — che guadagna potere guaritore. La vulnerabilità autentica genera connessione.' },
    { step: '4. Cercare terapia, mentorship o supporto', text: 'Ironico ma vero: coloro che hanno un Chirone prominente raramente cercano aiuto. La guarigione inizia quando accetti di poter essere anche il "ferito" e non solo il "guaritore".' },
    { step: '5. Trasformarla in vocazione', text: 'La domanda non è "come mi libero di questa ferita?" ma "come può questa ferita rendermi utile al mondo?" Un Chirone ben integrato è uno dei punti più potenti nel tema.' },
  ],
  cta: 'Scopri la posizione di Chirone nel tuo tema natale',
  ctaButton: 'Calcola il Mio Tema →',
};
