export const horoscope = {
  daily: {
    title: 'Oroscopo Giornaliero Personale',
    subtitle: 'I tuoi transiti personali del giorno con interpretazione dettagliata',
    selectProfile: 'Seleziona un profilo per vedere il tuo oroscopo personalizzato',
    noProfile: 'Calcola prima il tuo tema natale.',
    moonToday: 'Luna oggi',
    activeTransits: 'Transiti Attivi',
    intensity: { high: 'forte', medium: 'medio', low: 'lieve' },
    categories: { love: 'Amore', career: 'Carriera', health: 'Salute' },
    today: 'Oggi',
    tomorrow: 'Domani',
  },
  love: {
    title: 'Oroscopo dell\'Amore',
    subtitle: 'Venere, Marte e gli aspetti di oggi che influenzano la tua vita amorosa',
  },
  weekly: {
    title: 'Oroscopo Settimanale',
    subtitle: 'Panoramica dei transiti e delle energie per i prossimi 7 giorni',
    thisWeek: 'Questa settimana',
    prevWeek: '← Settimana',
    nextWeek: 'Settimana →',
    selectProfile: 'Seleziona un profilo per vedere l\'oroscopo settimanale',
  },
  events: {
    title: 'Eventi Celesti',
    subtitle: 'Ingressi planetari, aspetti esatti, fasi lunari e stazioni retrogrado',
    noEvents: 'Nessun evento celeste significativo in questo giorno.',
    types: { ingress: 'Ingresso', aspect: 'Aspetto esatto', 'moon-phase': 'Fase lunare', retrograde: 'Stazione' },
  },
  interpretation: {
    title: 'Interpretazione di Base',
    premiumCta: 'Vuoi un\'analisi personalizzata completa?',
    premiumDesc: 'Il Nostro Rapporto Natale Completo include tutti i pianeti, aspetti, dignità e previsioni in PDF professionale.',
    premiumButton: 'Visualizza Rapporti Premium',
    freeNotice: 'Interpretazione riassuntiva gratuita. Per analisi completa (più di 20 pagine), consulta i nostri rapporti premium.',
  },
  transitTexts: {
    noTransits: 'Giornata tranquilla senza transiti significativi. Prenditi tempo per riposare e riflettere.',
    intenseDay: 'Giornata intensa con molteplici transiti potenti. Rimani consapevole e flessibile.',
    normalWork: 'Giornata normale al lavoro. Mantieni il focus sui compiti quotidiani.',
    energyHigh: 'Energia alta ma tendenza all\'eccesso. Fai attività fisica ma evita lo sforzo eccessivo.',
    vitalityGood: 'Vitalità alta. Eccellente per attività fisiche e sport.',
    energyStable: 'Energia stabile. Mantieni abitudini sane e rispetta il tuo ritmo.',
  },
  moonLove: [
    'Impulso romantico e passione rapida.',
    'Sensualità e desiderio di conforto insieme.',
    'Flirt intellettuale e conversazioni seducenti.',
    'Bisogno di affetto e sicurezza in amore.',
    'Romance drammatico ed espressione generosa.',
    'Amore mostrato attraverso atti pratici.',
    'Ricerca di armonia e compagnia.',
    'Desiderio intenso e possessivo.',
    'Attrazione per la novità e l\'avventura.',
    'Amore maturo e impegno.',
    'Libertà in amore e connessioni insolite.',
    'Romanticismo e idealizzazione.',
  ],
};
