export const planetaryCycles = {
  title: 'Cicli Planetari',
  intro: 'L\'astrologia ha una dimensione temporale che va oltre il tema natale. I pianeti continuano a muoversi dopo la nascita e periodicamente ritornano allo stesso punto del cielo dove si trovavano al momento della tua nascita — o formano angoli significativi con quel punto. Questi cicli funzionano come un orologio biologico-simbolico della psiche, segnando fasi naturali di crescita, crisi, integrazione e rinnovamento.',
  whatAreCycles: {
    title: 'Cosa Sono i Cicli Planetari?',
    text: 'Ogni pianeta ha un periodo orbitale — il tempo che impiega per completare un\'orbita completa attorno al Sole. Quando un pianeta in transito ritorna al punto esatto che occupava al momento della tua nascita, lo chiamiamo "ritorno". Quando forma un angolo di 180° con la posizione natale, lo chiamiamo "opposizione".',
    note: 'I ritorni e le opposizioni non sono eventi esterni che "ti accadono" — sono inviti interni a rivedere, integrare o trasformare una dimensione specifica della tua vita.',
  },
  cycles: [
    {
      planet: 'Giove ♃',
      icon: '✦',
      cycle: 'Ritorno ogni ~12 anni',
      ages: '12, 24, 36, 48, 60, 72...',
      title: 'Il Ciclo di Espansione',
      description: 'Giove completa un\'orbita in circa 12 anni. I suoi ritorni coincidono con anni di opportunità, espansione e porte aperte. Il ritorno di Giove non consegna opportunità — affina la tua percezione di quelle già presenti.',
      phases: [
        { age: '~12 anni', title: 'Primo ritorno', text: 'Transizione dall\'infanzia alla pre-adolescenza. Espansione della visione del mondo, primi interrogativi filosofici.' },
        { age: '~24 anni', title: 'Secondo ritorno', text: 'Espansione nella vita adulta indipendente. Anno di opportunità professionali o educative.' },
        { age: '~36 anni', title: 'Terzo ritorno', text: 'Consolidamento ed espansione dell\'identità adulta. Apertura a nuovi progetti di vita.' },
        { age: '~48 anni', title: 'Quarto ritorno', text: 'Rinnovo di scopo e significato. Spesso coincide con cambiamenti di carriera o filosofia di vita.' },
      ],
    },
    {
      planet: 'Saturno ♄',
      icon: '⧖',
      cycle: 'Ritorno a ~29-30 anni e ~58-60 anni',
      ages: '~14-15 (quadrato), ~29-30 (ritorno), ~36-37 (opposizione), ~58-60 (ritorno)',
      title: 'Il Grande Maestro — Ritorno di Saturno',
      description: 'Saturno è il pianeta più temuto e più importante dei cicli di vita. Il suo primo ritorno, intorno ai 29-30 anni, è un rito di passaggio universale — il momento in cui la giovinezza finisce e la vera vita adulta inizia. Sei chiamato ad assumerti la piena responsabilità di chi sei.',
      phases: [
        { age: '~14-15 anni', title: 'Primo quadrato', text: 'Prima confrontazione con l\'autorità e i limiti. Identità adolescenziale in formazione.' },
        { age: '~21-22 anni', title: 'Primo quadrato crescente', text: 'Tensione tra la libertà desiderata e le responsabilità crescenti.' },
        { age: '~29-30 anni', title: 'Ritorno di Saturno', text: 'Il grande punto di svolta. Saturno "chiede il debito" — le relazioni, le carriere e le identità costruite senza autenticità tendono a dissolversi. Ciò che è genuino si rafforza. Frequente crisi esistenziale, ma necessaria.' },
        { age: '~36-37 anni', title: 'Opposizione di Saturno', text: 'Revisione a metà ciclo. Valutazione di ciò che è stato costruito dai 29 anni. Momento di correzione di rotta.' },
        { age: '~44 anni', title: 'Secondo quadrato calante', text: 'Preparazione al secondo ritorno. Confrontazione con ciò che è stato rimandato o negato.' },
        { age: '~58-60 anni', title: 'Secondo Ritorno di Saturno', text: 'Transizione alla piena maturità. Profonda revisione del lascito e dello scopo di vita.' },
      ],
    },
    {
      planet: 'Urano ♅',
      icon: '⚡',
      cycle: 'Opposizione a ~38-44 anni',
      ages: '~38-44 (opposizione), ~84 (ritorno)',
      title: 'La Crisi di Mezza Età — Opposizione di Urano',
      description: 'Urano impiega 84 anni per completare il suo ciclo. L\'opposizione — quando Urano in transito forma 180° con Urano natale — si verifica tra 38 e 44 anni. Questa è la famosa "crisi di mezza età". Urano, il pianeta della libertà e della rottura, mette radicalmente in discussione i modelli stabiliti.',
      phases: [
        { age: '~38-44 anni', title: 'Opposizione di Urano', text: 'Urgenza improvvisa di libertà. Messa in discussione di tutto ciò che è stato costruito. "Per chi sto vivendo questa vita?" Può manifestarsi come cambiamenti bruschi di carriera, relazione o stile di vita. Questa non è una crisi da evitare — è un appello all\'autenticità.' },
        { age: '~21 anni', title: 'Quadrato di Urano', text: 'Primo impulso a liberarsi dai modelli genitoriali e sociali. "Non voglio la vita che mi hanno insegnato a volere."' },
        { age: '~63 anni', title: 'Secondo quadrato', text: 'Consolidamento dell\'identità autentica dopo la crisi di mezza età. Chi sono davvero, libero dalle aspettative?' },
      ],
    },
    {
      planet: 'Chirone ⚷',
      icon: '⚷',
      cycle: 'Ritorno a ~49-51 anni',
      ages: '~49-51 (ritorno)',
      title: 'Il Ritorno di Chirone',
      description: 'Chirone, il Guaritore Ferito, ritorna al punto natale intorno ai 49-51 anni — spesso coincidendo con la menopausa/andropausa e quello che Jung chiamava "individuazione". È un invito all\'integrazione finale della ferita primordiale.',
      phases: [
        { age: '~49-51 anni', title: 'Ritorno di Chirone', text: 'La domanda centrale: "Quanta di questa sofferenza che porto è ancora necessaria?" È il momento di accettare che la ferita non ha più bisogno di essere nascosta. La vulnerabilità diventa saggezza. Molte persone iniziano o approfondiscono lavoro terapeutico o spirituale in questo periodo.' },
        { age: '~22-25 anni', title: 'Quadrato di Chirone', text: 'Prima crisi con la ferita. Può essere un periodo di isolamento, vergogna o difficoltà di appartenenza.' },
        { age: '~37-40 anni', title: 'Opposizione di Chirone', text: 'Confrontazione diretta con la ferita. Spesso coincide con la crisi di mezza età e richiede di affrontare ciò che è stato evitato.' },
      ],
    },
    {
      planet: 'Nettuno ♆',
      icon: '🌊',
      cycle: 'Quadrato a ~40-42 anni e ~82-84 anni',
      ages: '~40-42 (primo quadrato), ~82-84 (ritorno)',
      title: 'Dissoluzione e Trascendenza',
      description: 'Nettuno impiega 165 anni per completare il suo ciclo. Il quadrato di Nettuno (a ~40-42 anni) spesso coincide con la crisi di mezza età e aggiunge una dimensione di dissoluzione delle illusioni — specialmente illusioni su chi siamo e cosa vogliamo.',
      phases: [
        { age: '~40-42 anni', title: 'Quadrato di Nettuno', text: 'Dissoluzione delle illusioni costruite nella giovinezza. "La vita che immaginavo non è esattamente questa." Periodo di disorientamento creativo — il vecchio sé si dissolve prima che si formi quello nuovo.' },
      ],
    },
    {
      planet: 'Plutone ♇',
      icon: '🔥',
      cycle: 'Quadrato a ~36-44 anni',
      ages: '~36-44 (primo quadrato)',
      title: 'Morte e Rinascita',
      description: 'Plutone impiega 248 anni, quindi non ritorna mai. Ma il quadrato plutoniano (a ~36-44 anni) è una delle transizioni più intense — coincidendo con la crisi di mezza età e richiedendo la morte simbolica delle parti dell\'ego diventate ostacoli.',
      phases: [
        { age: '~36-44 anni', title: 'Quadrato di Plutone', text: 'Processo di morte-rinascita psicologica. Potere, controllo, ombra e vulnerabilità vengono in superficie. Ciò a cui ti aggrappi con forza inizia a dissolversi. Profondamente trasformativo e potenzialmente spaventoso — e necessario.' },
      ],
    },
  ],
  integration: {
    title: 'Come Lavorare con i Cicli Consapevolmente',
    text: 'Conoscere i propri cicli non si tratta di prevedere il futuro — si tratta di preparare il terreno interiore. Quando sai che stai entrando in un periodo saturnino, ad esempio, puoi creare spazio per la revisione invece di essere travolto da esso. I cicli non sono deterministici: rivelano la qualità del tempo, non il suo contenuto.',
    tips: [
      'Identifica in quale ciclo ti trovi attualmente',
      'Chiedi: che tipo di crescita invita questo ciclo?',
      'Resistere all\'impulso di "fuggire" le crisi dei cicli più grandi',
      'Usa la terapia, la meditazione o il diario come strumenti di integrazione',
      'I cicli difficili producono i maggiori salti di coscienza quando vengono attraversati consapevolmente',
    ],
  },
  cta: 'Scopri in quali cicli ti trovi in questo momento',
  ctaButton: 'Vedi i Miei Transiti →',
};
