export const signs = {
  title: 'I 12 Segni dello Zodiaco',
  intro: 'I segni sono 12 archetipi energetici. Ogni pianeta nel tuo tema è in un segno, colorando la sua espressione con qualità specifiche.',
  list: [
    { symbol: '♈', name: 'Ariete', dates: '21 Mar – 19 Apr', element: 'Fuoco', mode: 'Cardinale', ruler: '♂ Marte', color: '#cc0000', description: 'Primo segno — la scintilla dell\'inizio. Coraggio, impulso, competitività e individualità. L\'Ariete rompe l\'inerzia e apre nuove strade. Ombra: impulsività, egoismo, aggressività.' },
    { symbol: '♉', name: 'Toro', dates: '20 Apr – 20 Mag', element: 'Terra', mode: 'Fisso', ruler: '♀ Venere', color: '#006600', description: 'Consolidamento di ciò che l\'Ariete ha iniziato. Stabilità, piacere sensoriale, lealtà e perseveranza. Il Toro costruisce basi solide con pazienza. Ombra: possessività, testardaggine, materialismo.' },
    { symbol: '♊', name: 'Gemelli', dates: '21 Mag – 20 Giu', element: 'Aria', mode: 'Mutabile', ruler: '☿ Mercurio', color: '#0000cc', description: 'Il ponte tra i mondi. Curiosità insaziabile, comunicazione, versatilità e leggerezza. I Gemelli collegano informazioni e persone. Ombra: superficialità, inconsistenza, dualità.' },
    { symbol: '♋', name: 'Cancro', dates: '21 Giu – 22 Lug', element: 'Acqua', mode: 'Cardinale', ruler: '☽ Luna', color: '#cc6600', description: 'Il nido emotivo. Protezione, memoria, appartenenza e cura. Il Cancro crea radici e si prende cura profondamente. Ombra: dipendenza, manipolazione emotiva, attaccamento al passato.' },
    { symbol: '♌', name: 'Leone', dates: '23 Lug – 22 Ago', element: 'Fuoco', mode: 'Fisso', ruler: '☉ Sole', color: '#cc0000', description: 'Il palcoscenico della vita. Espressione creativa, splendore personale, generosità e leadership. Il Leone irradia e ispira. Ombra: arroganza, bisogno di applausi, dramma.' },
    { symbol: '♍', name: 'Vergine', dates: '23 Ago – 22 Set', element: 'Terra', mode: 'Mutabile', ruler: '☿ Mercurio', color: '#006600', description: 'Raffinamento dell\'esperienza. Analisi, competenza, servizio e miglioramento. La Vergine separa l\'essenziale dal superfluo. Ombra: critica eccessiva, perfezionismo, ansia.' },
    { symbol: '♎', name: 'Bilancia', dates: '23 Set – 22 Ott', element: 'Aria', mode: 'Cardinale', ruler: '♀ Venere', color: '#0000cc', description: 'L\'incontro con l\'altro. Equilibrio, giustizia, diplomazia e partnership. La Bilancia cerca armonia nelle relazioni e nell\'estetica. Ombra: indecisione, dipendenza dagli altri.' },
    { symbol: '♏', name: 'Scorpione', dates: '23 Ott – 21 Nov', element: 'Acqua', mode: 'Fisso', ruler: '♇ Plutone', color: '#cc6600', description: 'La discesa nelle profondità. Intensità, trasformazione, verità e potere. Lo Scorpione non teme ciò che è nascosto. Ombra: ossessione, gelosia, manipolazione, vendetta.' },
    { symbol: '♐', name: 'Sagittario', dates: '22 Nov – 21 Dic', element: 'Fuoco', mode: 'Mutabile', ruler: '♃ Giove', color: '#cc0000', description: 'La freccia del significato. Espansione, filosofia, avventura e fede. Il Sagittario cerca il senso oltre l\'orizzonte. Ombra: eccesso, fanatismo, irresponsabilità.' },
    { symbol: '♑', name: 'Capricorno', dates: '22 Dic – 19 Gen', element: 'Terra', mode: 'Cardinale', ruler: '♄ Saturno', color: '#006600', description: 'La montagna da scalare. Ambizione, disciplina, maturità e eredità. Il Capricorno costruisce con il tempo e la perseveranza. Ombra: freddezza, rigidità, pessimismo.' },
    { symbol: '♒', name: 'Acquario', dates: '20 Gen – 18 Feb', element: 'Aria', mode: 'Fisso', ruler: '♅ Urano', color: '#0000cc', description: 'La rivoluzione silenziosa. Originalità, indipendenza, visione del futuro e umanitarismo. L\'Acquario mette in discussione lo status quo. Ombra: distacco emotivo, ribellione vuota.' },
    { symbol: '♓', name: 'Pesci', dates: '19 Feb – 20 Mar', element: 'Acqua', mode: 'Mutabile', ruler: '♆ Nettuno', color: '#cc6600', description: 'L\'oceano finale. Compassione universale, spiritualità, arte e dissoluzione dell\'ego. I Pesci sentono tutto e si connettono al tutto. Ombra: escapismo, vittimismo, confusione.' },
  ],
};
