// ============================================================
// CHIRON.TS — A Ferida que Cura
// Quíron indica a ferida central e o dom que emerge da cura.
// Linguagem empoderada: não fatalista, focada em potencial.
// ============================================================

// CHIRON IN HOUSE — Onde está a ferida central (e o dom)
export const CHIRON_IN_HOUSE: string[] = [
  /* Casa 1 */ 'Quíron na Casa 1 indica uma ferida ligada à identidade e ao direito de existir como você é. Pode ter crescido sentindo que havia algo "errado" em você — no corpo, no comportamento, na forma de ser. Mas é exatamente essa sensibilidade ao autoconhecimento que te torna capaz de ajudar outros a encontrarem a si mesmos. Ao aceitar sua própria singularidade sem precisar justificá-la, você se torna um espelho de cura para o mundo.',
  /* Casa 2 */ 'Quíron na Casa 2 toca a ferida do valor próprio e da segurança material. Pode ter aprendido cedo que amor era condicional ao que você produzia, tinha ou fornecia. O caminho de cura passa por construir uma relação saudável com seus talentos e recursos — percebendo que seu valor existe independentemente do que possui. Ao fazer isso, você se torna um guia poderoso para quem ainda busca aprovação externa.',
  /* Casa 3 */ 'Quíron na Casa 3 revela uma ferida na comunicação e na expressão intelectual. Pode ter sentido que suas palavras não eram ouvidas, que era "burro" ou que não tinha o direito de se expressar. O dom que emerge é uma sensibilidade única à linguagem — você aprende a se comunicar com profundidade e cuidado, tornando-se um mentor capaz de dar voz a quem sente o mesmo.',
  /* Casa 4 */ 'Quíron na Casa 4 indica uma ferida nas raízes — família de origem, sentimento de pertencimento, segurança emocional. Pode ter crescido sem um lar emocionalmente estável ou ter sentido que não se encaixava na família. O processo de cura envolve criar suas próprias raízes, definir o que é "lar" para você. Quando faz isso, você se torna um ancorante para outros que também buscam pertencimento.',
  /* Casa 5 */ 'Quíron na Casa 5 toca a ferida da criatividade, da autenticidade e do prazer. Pode ter recebido mensagens de que sua expressão criativa não era boa o suficiente, ou que se divertir era perigoso ou proibido. O dom que surge é uma criatividade profunda e corajosa — ao se permitir criar e se alegrar sem julgamento, você inspira outros a recuperar seu próprio brilho.',
  /* Casa 6 */ 'Quíron na Casa 6 revela uma ferida na relação com o trabalho, saúde e cotidiano. Pode ter aprendido que precisa ser perfeito para merecer seu lugar, ou que cuidar dos outros é obrigação enquanto cuidar de si é egoísmo. O processo de cura passa por entender que servir tem que partir de um lugar de plenitude, não de culpa. Você se torna um modelo de autocuidado consciente.',
  /* Casa 7 */ 'Quíron na Casa 7 toca a ferida nos relacionamentos e na parceria. Pode ter vivenciado perdas, rejeições ou padrões relacionais dolorosos que geraram medo de se comprometer ou de se revelar. O dom que emerge é uma profunda compreensão das dinâmicas relacionais — ao curar essa ferida, você se torna alguém capaz de criar conexões genuínas e de guiar outros em seus relacionamentos.',
  /* Casa 8 */ 'Quíron na Casa 8 indica uma ferida ligada a perdas, transformações forçadas, poder e intimidade profunda. Pode ter vivenciado situações de vulnerabilidade extrema — financeiras, emocionais ou relacionadas a morte e ciclos de vida. O dom que emerge é uma força incomum de renascimento e uma capacidade única de acompanhar outros nas passagens mais difíceis da vida.',
  /* Casa 9 */ 'Quíron na Casa 9 toca a ferida nas crenças, na espiritualidade e na busca por sentido. Pode ter sofrido com dogmas rígidos, com a sensação de que sua visão de mundo não era válida, ou com experiências que abalaram profundamente sua fé. O caminho de cura é construir uma filosofia de vida verdadeiramente sua. Ao fazer isso, você se torna um guia espiritual de raro discernimento.',
  /* Casa 10 */ 'Quíron na Casa 10 revela uma ferida na carreira, no legado e na figura de autoridade. Pode ter tido dificuldades com figuras paternas, com reconhecimento profissional ou com o direito de ocupar posições de destaque. O processo de cura passa por assumir sua autoridade sem precisar de validação externa. Quando o faz, você se torna uma referência inspiradora para outros que buscam seu próprio lugar no mundo.',
  /* Casa 11 */ 'Quíron na Casa 11 toca a ferida no pertencimento coletivo e nas amizades. Pode ter se sentido excluído de grupos, diferente demais para pertencer a algum lugar, ou decepcionado por amizades que não sustentaram o que prometeram. O dom que emerge é a capacidade de criar comunidades verdadeiramente inclusivas e de enxergar o valor em quem se sente à margem.',
  /* Casa 12 */ 'Quíron na Casa 12 indica uma ferida espiritual profunda, ligada ao isolamento, à invisibilidade e às dores não expressas. Pode ter carregado feridas de forma solitária, sentido que precisava esconder o que sentia ou vivenciado experiências de confinamento ou exclusão. O dom que emerge dessa profundidade é uma capacidade ímpar de compaixão, de escuta e de cura silenciosa — você toca a alma das pessoas sem precisar de palavras.',
];

// CHIRON IN SIGN — O Tom da Ferida (dimensão geracional)
export const CHIRON_IN_SIGN: string[] = [
  /* Áries */ 'Com Quíron em Áries, a ferida tem uma qualidade ativa e identitária — envolve o direito de agir, de existir com força e de ser o primeiro. A cura passa por recuperar a coragem de existir sem pedir permissão.',
  /* Touro */ 'Com Quíron em Touro, a ferida toca o valor intrínseco e a segurança corporal. Envolve a crença de que você precisa merecer o prazer e o conforto. A cura passa por habitar o corpo com paz e confiar que você é suficiente.',
  /* Gêmeos */ 'Com Quíron em Gêmeos, a ferida tem uma qualidade comunicativa e intelectual — envolve dúvidas sobre a própria inteligência ou o direito de ser ouvido. A cura passa por confiar na própria voz e na singularidade do seu pensamento.',
  /* Câncer */ 'Com Quíron em Câncer, a ferida toca o mundo emocional e familiar. Envolve questões de pertencimento, nutrição e segurança emocional. A cura passa por aprender a nutrir a si mesmo com a mesma generosidade que você oferece aos outros.',
  /* Leão */ 'Com Quíron em Leão, a ferida tem uma qualidade expressiva e criativa — envolve o direito de brilhar, de ser visto e de se expressar sem julgamento. A cura passa por recuperar a alegria da autoexpressão autêntica.',
  /* Virgem */ 'Com Quíron em Virgem, a ferida toca a perfeição, a utilidade e a saúde. Pode envolver sentir que nunca é bom o suficiente ou que seu valor depende de quanto você serve. A cura passa por abraçar a imperfeição como parte da plenitude.',
  /* Libra */ 'Com Quíron em Libra, a ferida tem uma qualidade relacional — envolve equilíbrio, justiça e o direito de ter necessidades em relacionamentos. A cura passa por aprender que harmonia verdadeira inclui sua própria voz.',
  /* Escorpião */ 'Com Quíron em Escorpião, a ferida toca a transformação, o poder e a intimidade. Envolve medos profundos de perda, traição ou vulnerabilidade. A cura passa por abraçar a profundidade emocional como um dom, não como um fardo.',
  /* Sagitário */ 'Com Quíron em Sagitário, a ferida tem uma qualidade filosófica e espiritual. Pode envolver a perda de fé, conflitos de crenças ou a sensação de que a verdade é inacessível. A cura passa por construir uma sabedoria própria, baseada na experiência vivida.',
  /* Capricórnio */ 'Com Quíron em Capricórnio, a ferida toca a ambição, a responsabilidade e a relação com autoridade. Pode envolver pressão excessiva por resultados ou a crença de que precisa sofrer para alcançar. A cura passa por redefinir o sucesso em seus próprios termos.',
  /* Aquário */ 'Com Quíron em Aquário, a ferida tem uma qualidade coletiva — envolve o sentimento de ser diferente demais, de não pertencer a lugar algum. A cura passa por transformar essa singularidade em dádiva e usar a visão de futuro para inspirar mudanças.',
  /* Peixes */ 'Com Quíron em Peixes, a ferida toca a dissolução, a espiritualidade e os limites do ego. Pode envolver sensação de perda de si mesmo em outros ou no sofrimento coletivo. A cura passa por aprender a compaixão com fronteiras — servir ao mundo sem se perder nele.',
];
