export const chiron = {
  title: 'Chiron — De Gewonde Genezer',
  intro: 'Chiron is een hemellichaam ontdekt in 1977, geclassificeerd als planetoïde of centaur, in een baan tussen Saturnus en Uranus. In humanistische astrologie vertegenwoordigt het de oerwond die we dragen — een pijn die we in onszelf niet kunnen genezen, maar die ons paradoxaal genoeg in staat stelt anderen te helpen. Het is het archetype van de therapeut, de mentor en de wijze die door lijden leerde.',
  mythology: {
    title: 'De Mythologie van Chiron',
    text: 'Chiron was een centaur anders dan de anderen: wijs, beschaafd, meester van geneeskunde, muziek, profetie en krijgskunsten. Hij was tutor voor helden als Achilles, Asclepius en Jason. Zoon van Cronus en Philyra, werd hij bij de geboorte verlaten door zijn moeder omdat hij half mens, half paard was — zijn eerste wond: verwerping door zijn eigen oorsprong.',
    wound: 'Zijn tragische ironie: als de grootste genezer van het oude Griekenland ontving hij een vergiftigde pijl van Hercules — een ongeluk, geen kwaadwilligheid — en kon als onsterfelijke noch sterven, noch zichzelf genezen. Hij leefde in eeuwige pijn, totdat hij zijn onsterfelijkheid opgaf en werd omgevormd tot een sterrenbeeld.',
    meaning: 'Chirons wond wordt niet opgelost. Ze wordt geïntegreerd. Dat is het fundamentele verschil tussen Saturnus (die door discipline overwint) en Chiron (die leert te leven met de wond totdat ze wijsheid wordt).',
  },
  signsTitle: 'Chiron Door de Tekens',
  signsIntro: 'Het teken van Chiron onthult de aard van de wond — het "waar het pijn doet" op het niveau van identiteit. Omdat Chiron tussen 4 en 9 jaar in elk teken doorbrengt, is het een generatiewond gedeeld door miljoenen.',
  signs: [
    { sign: 'Ram ♈', years: '(1968–77 / 2018–27)', wound: 'Wond in bestaan en initiatief', healing: 'Genezing door het recht om te handelen, te leiden en volledig te bestaan' },
    { sign: 'Stier ♉', years: '(1977–83)', wound: 'Wond in zelfwaarde en lichaam', healing: 'Genezing door een gezonde relatie met eigenwaarde en hulpbronnen' },
    { sign: 'Tweelingen ♊', years: '(1983–88)', wound: 'Wond in communicatie en intellect', healing: 'Genezing door het vermogen gehoord en begrepen te worden' },
    { sign: 'Kreeft ♋', years: '(1988–91)', wound: 'Wond in verbondenheid en familie', healing: 'Genezing door het creëren van een innerlijk thuis, onafhankelijk van het externe' },
    { sign: 'Leeuw ♌', years: '(1991–93)', wound: 'Wond in zelfexpressie en erkenning', healing: 'Genezing door het recht te schitteren zonder goedkeuring nodig te hebben' },
    { sign: 'Maagd ♍', years: '(1993–96)', wound: 'Wond in perfectie en geschiktheid', healing: 'Genezing door onvolmaaktheid te accepteren als deel van het menszijn' },
    { sign: 'Weegschaal ♎', years: '(1996–99)', wound: 'Wond in relaties en evenwicht', healing: 'Genezing door te leren te verbinden zonder zichzelf te verliezen' },
    { sign: 'Schorpioen ♏', years: '(1999–01)', wound: 'Wond in macht en intimiteit', healing: 'Genezing door schaduwen te confronteren zonder vernietiging' },
    { sign: 'Boogschutter ♐', years: '(2001–05)', wound: 'Wond in geloof, zingeving en filosofische verbondenheid', healing: 'Genezing door een eigen waarheid te vinden, niet een geërfde' },
    { sign: 'Steenbok ♑', years: '(2005–10)', wound: 'Wond in autoriteit en succes', healing: 'Genezing door prestatie op eigen voorwaarden te herdefiniëren' },
    { sign: 'Waterman ♒', years: '(2010–11)', wound: 'Wond in originaliteit en groepsverbondenheid', healing: 'Genezing door het recht anders te zijn en toch geliefd te worden' },
    { sign: 'Vissen ♓', years: '(2011–18)', wound: 'Wond in spiritualiteit en ego-grenzen', healing: 'Genezing door het transcendente te integreren zonder er in op te gaan' },
  ],
  housesTitle: 'Chiron Door de Huizen',
  housesIntro: 'Het huis van Chiron geeft het levensgebied aan waar de wond zich manifesteert — waar u zich voelt als de "eeuwig verwonde die anderen geneest". Het is ook waar uw grootste wijsheid ontstaat na integratie.',
  houses: [
    { num: '1e', name: 'Huis van Identiteit', wound: 'Wond in eigen bestaan en aanwezigheid', gift: 'Kracht om anderen te leren hoe volledig te bestaan' },
    { num: '2e', name: 'Huis van Hulpbronnen', wound: 'Wond in eigenwaarde en materieel onderhoud', gift: 'Gave om anderen te helpen hun talenten te ontdekken' },
    { num: '3e', name: 'Huis van Communicatie', wound: 'Wond in verbale expressie en leren', gift: 'Gave als leraar, schrijver of communicator' },
    { num: '4e', name: 'Huis van Thuis', wound: 'Wond in wortels, familie en emotionele veiligheid', gift: 'Vermogen om thuis en welkom te creëren voor anderen' },
    { num: '5e', name: 'Huis van Creatie', wound: 'Wond in creatieve zelfexpressie en vreugde', gift: 'Gave om creativiteit bij anderen te inspireren' },
    { num: '6e', name: 'Huis van Gezondheid', wound: 'Wond in lichaam, gezondheid en routines', gift: 'Gave voor fysieke en holistische genezing' },
    { num: '7e', name: 'Huis van Relaties', wound: 'Wond in intiem partnerschap en toewijding', gift: 'Gave voor bemiddeling en begeleiding van relaties' },
    { num: '8e', name: 'Huis van Transformatie', wound: 'Wond in verliezen, seksualiteit en gedeelde macht', gift: 'Gave om anderen te begeleiden door dood/wedergeboorteprocessen' },
    { num: '9e', name: 'Huis van Filosofie', wound: 'Wond in geloof, vertrouwen en zoektocht naar zin', gift: 'Gave als spiritueel leraar en filosoof' },
    { num: '10e', name: 'Huis van Carrière', wound: 'Wond in publieke erkenning en autoriteit', gift: 'Gave voor leiderschap met oprechte bescheidenheid' },
    { num: '11e', name: 'Huis van Groepen', wound: 'Wond in verbondenheid en vriendschappen', gift: 'Gave voor het genezen van gemeenschappen en groepen' },
    { num: '12e', name: 'Huis van het Onbewuste', wound: 'Diep onbewuste wond, moeilijk te articuleren', gift: 'Spirituele gave en capaciteit voor transcendente genezing' },
  ],
  healingTitle: 'Hoe Chirons Wond te Genezen',
  healingIntro: 'Chirons wond verdwijnt niet — ze wordt geïntegreerd. Het proces gaat niet over overwinnen, maar over alchemie: pijn omzetten in wijsheid.',
  healingSteps: [
    { step: '1. De wond erkennen', text: 'De eerste stap is haar te benoemen: "hier doet het pijn op een manier zonder eenvoudige genezing". Niet minimaliseren, niet dramatiseren. Gewoon met compassie erkennen.' },
    { step: '2. De rol van de "ontkennende genezer" opgeven', text: 'De gewonde Chiron brengt vaak zijn leven door met iedereen behalve zichzelf te genezen. Anderen helpen is reëel en waardevol — maar kan geen vlucht zijn van naar binnen kijken.' },
    { step: '3. Kwetsbaarheid als kracht accepteren', text: 'De neiging is Chirons wond te verbergen. Maar precies wanneer we haar — met onderscheidingsvermogen — onthullen, krijgt ze genezende kracht. Authentieke kwetsbaarheid genereert verbinding.' },
    { step: '4. Therapie, mentorship of ondersteuning zoeken', text: 'Ironisch maar waar: mensen met een prominente Chiron zoeken zelden hulp. Genezing begint wanneer u accepteert dat u ook de "gewonde" kunt zijn, niet alleen de "genezer".' },
    { step: '5. Haar in een roeping transformeren', text: 'De vraag is niet "hoe raak ik deze wond kwijt?" maar "hoe kan deze wond me nuttig maken voor de wereld?" Een goed geïntegreerde Chiron is een van de krachtigste punten in het horoscoop.' },
  ],
  cta: 'Ontdek de positie van Chiron in uw geboortehoroscoop',
  ctaButton: 'Bereken Mijn Horoscoop →',
};
