export const horoscope = {
  daily: {
    title: 'Persoonlijk Daghoroscoop',
    subtitle: 'Uw persoonlijke transits van de dag met gedetailleerde interpretatie',
    selectProfile: 'Selecteer een profiel om uw gepersonaliseerde horoscoop te zien',
    noProfile: 'Bereken eerst uw geboortehoroscoop.',
    moonToday: 'Maan vandaag',
    activeTransits: 'Actieve Transits',
    intensity: { high: 'sterk', medium: 'middel', low: 'licht' },
    categories: { love: 'Liefde', career: 'Carrière', health: 'Gezondheid' },
    today: 'Vandaag',
    tomorrow: 'Morgen',
  },
  love: {
    title: 'Liefdeshoroscoop',
    subtitle: 'Venus, Mars en de aspecten van vandaag die uw liefdesleven beïnvloeden',
  },
  weekly: {
    title: 'Weekhoroscoop',
    subtitle: 'Overzicht van transits en energieën voor de komende 7 dagen',
    thisWeek: 'Deze week',
    prevWeek: '← Week',
    nextWeek: 'Week →',
    selectProfile: 'Selecteer een profiel om het weekhoroscoop te zien',
  },
  events: {
    title: 'Hemelgebeurtenissen',
    subtitle: 'Planetaire ingresses, exacte aspecten, maanfasen en retrograde stations',
    noEvents: 'Geen significante hemelgebeurtenissen op deze dag.',
    types: { ingress: 'Ingress', aspect: 'Exact aspect', 'moon-phase': 'Maanfase', retrograde: 'Station' },
  },
  interpretation: {
    title: 'Basisinterpretatie',
    premiumCta: 'Wilt u een volledige gepersonaliseerde analyse?',
    premiumDesc: 'Ons Volledig Natalrapport bevat alle planeten, aspecten, waardigheden en voorspellingen in professionele PDF.',
    premiumButton: 'Bekijk Premium Rapporten',
    freeNotice: 'Gratis samenvattingsinterpretatie. Voor volledige analyse (meer dan 20 pagina\'s), zie onze premium rapporten.',
  },
  transitTexts: {
    noTransits: 'Rustige dag zonder significante transits. Neem tijd om te rusten en na te denken.',
    intenseDay: 'Intense dag met meerdere krachtige transits. Blijf bewust en flexibel.',
    normalWork: 'Normale werkdag. Houd de focus op alledaagse taken.',
    energyHigh: 'Hoge energie maar neiging tot overdaad. Beweeg, maar vermijd overbelasting.',
    vitalityGood: 'Vitaliteit is hoog. Uitstekend voor lichamelijke activiteiten en sport.',
    energyStable: 'Stabiele energie. Houd gezonde gewoonten aan en respecteer uw ritme.',
  },
  moonLove: [
    'Romantische impuls en snelle passie.',
    'Sensualiteit en verlangen naar comfort samen.',
    'Intellectueel flirten en verleidelijke gesprekken.',
    'Behoefte aan genegenheid en veiligheid in de liefde.',
    'Dramatisch romantiek en royale expressie.',
    'Liefde getoond door praktische daden.',
    'Zoeken naar harmonie en gezelschap.',
    'Intens en bezitterig verlangen.',
    'Aantrekking door nieuwheid en avontuur.',
    'Rijpe liefde en toewijding.',
    'Vrijheid in de liefde en ongewone verbindingen.',
    'Romantiek en idealisering.',
  ],
};
