export const planetaryCycles = {
  title: 'Planetaire Cycli',
  intro: 'Astrologie heeft een tijdelijke dimensie die verder gaat dan het geboortehoroscoop. Planeten bewegen door na de geboorte en keren periodiek terug naar hetzelfde punt aan de hemel waar ze waren toen u geboren werd — of vormen significante hoeken met dat punt. Deze cycli functioneren als een biologisch-symbolische klok van de psyche, die natuurlijke fasen van groei, crisis, integratie en vernieuwing markeert.',
  whatAreCycles: {
    title: 'Wat Zijn Planetaire Cycli?',
    text: 'Elke planeet heeft een omlooptijd — de tijd die nodig is om een volledige baan rond de Zon te voltooien. Wanneer een transitplaneet terugkeert naar het exacte punt dat hij innam op het moment van uw geboorte, noemen we dit een "terugkeer". Wanneer hij een 180°-hoek vormt met de natale positie, noemen we dit een "oppositie".',
    note: 'Terugkeren en opposities zijn geen externe gebeurtenissen die "u overkomen" — het zijn interne uitnodigingen om een specifieke dimensie van uw leven te herzien, te integreren of te transformeren.',
  },
  cycles: [
    {
      planet: 'Jupiter ♃',
      icon: '✦',
      cycle: 'Terugkeer elke ~12 jaar',
      ages: '12, 24, 36, 48, 60, 72...',
      title: 'De Expansiecyclus',
      description: 'Jupiter voltooit één baan in ongeveer 12 jaar. Zijn terugkeren vallen samen met jaren van kansen, expansie en open deuren. De Jupiter-terugkeer levert geen kansen — het verscherpt uw perceptie van de kansen die al aanwezig zijn.',
      phases: [
        { age: '~12 jaar', title: 'Eerste terugkeer', text: 'Overgang van kindertijd naar pre-adolescentie. Uitbreiding van wereldvisie, eerste filosofische vragen.' },
        { age: '~24 jaar', title: 'Tweede terugkeer', text: 'Expansie naar onafhankelijk volwassen leven. Jaar van professionele of educatieve kansen.' },
        { age: '~36 jaar', title: 'Derde terugkeer', text: 'Consolidatie en expansie van volwassen identiteit. Openstelling voor nieuwe levensprojecten.' },
        { age: '~48 jaar', title: 'Vierde terugkeer', text: 'Vernieuwing van doel en betekenis. Valt vaak samen met carrière- of levensfilosofiewijzigingen.' },
      ],
    },
    {
      planet: 'Saturnus ♄',
      icon: '⧖',
      cycle: 'Terugkeer bij ~29-30 jaar en ~58-60 jaar',
      ages: '~14-15 (vierkant), ~29-30 (terugkeer), ~36-37 (oppositie), ~58-60 (terugkeer)',
      title: 'De Grote Leraar — Saturnusretour',
      description: 'Saturnus is de meest gevreesde en meest belangrijke planeet van de levenscycli. Zijn eerste terugkeer, rond 29-30 jaar, is een universele overgangsrite — het moment waarop de jeugd eindigt en het echte volwassen leven begint. U wordt opgeroepen om volledige verantwoordelijkheid te nemen voor wie u bent.',
      phases: [
        { age: '~14-15 jaar', title: 'Eerste vierkant', text: 'Eerste confrontatie met autoriteit en grenzen. Adolescente identiteit in vorming.' },
        { age: '~21-22 jaar', title: 'Wassend eerste vierkant', text: 'Spanning tussen gewenste vrijheid en groeiende verantwoordelijkheden.' },
        { age: '~29-30 jaar', title: 'Saturnusretour', text: 'Het grote keerpunt. Saturnus "eist de schuld op" — relaties, carrières en identiteiten die zonder authenticiteit zijn opgebouwd, neigen te ontbinden. Wat echt is, wordt sterker. Frequente existentiële crisis, maar noodzakelijk.' },
        { age: '~36-37 jaar', title: 'Saturnus Oppositie', text: 'Halverwege-cyclus herziening. Evaluatie van wat is gebouwd sinds 29 jaar. Moment van koerscorrectie.' },
        { age: '~44 jaar', title: 'Tweede afnemend vierkant', text: 'Voorbereiding op de tweede terugkeer. Confrontatie met wat is uitgesteld of ontkend.' },
        { age: '~58-60 jaar', title: 'Tweede Saturnusretour', text: 'Overgang naar volledige rijpheid. Diepgaande herziening van nalatenschap en levensdoel.' },
      ],
    },
    {
      planet: 'Uranus ♅',
      icon: '⚡',
      cycle: 'Oppositie bij ~38-44 jaar',
      ages: '~38-44 (oppositie), ~84 (terugkeer)',
      title: 'De Midlifecrisis — Uranus Oppositie',
      description: 'Uranus heeft 84 jaar nodig om zijn cyclus te voltooien. De oppositie — wanneer de transiting Uranus 180° vormt met de natale Uranus — treedt op tussen 38 en 44 jaar. Dit is de beroemde "midlifecrisis". Uranus, de planeet van vrijheid en doorbraak, stelt radicaal de gevestigde patronen in vraag.',
      phases: [
        { age: '~38-44 jaar', title: 'Uranus Oppositie', text: 'Plotselinge urgentie voor vrijheid. Bevraging van alles dat is opgebouwd. "Voor wie leef ik dit leven?" Kan zich manifesteren als abrupte carrière-, relatie- of levensstijlwijzigingen. Dit is geen crisis te vermijden — het is een oproep tot authenticiteit.' },
        { age: '~21 jaar', title: 'Uranus Vierkant', text: 'Eerste impuls om zich te bevrijden van ouderlijke en maatschappelijke patronen. "Ik wil het leven niet dat men mij leerde te willen."' },
        { age: '~63 jaar', title: 'Tweede vierkant', text: 'Consolidatie van authentieke identiteit na de midlifecrisis. Wie ben ik echt, vrij van verwachtingen?' },
      ],
    },
    {
      planet: 'Chiron ⚷',
      icon: '⚷',
      cycle: 'Terugkeer bij ~49-51 jaar',
      ages: '~49-51 (terugkeer)',
      title: 'De Chiron-Terugkeer',
      description: 'Chiron, de Gewonde Genezer, keert rond 49-51 jaar terug naar het natale punt — valt vaak samen met menopauze/andropauze en wat Jung "individuatie" noemde. Het is een uitnodiging tot de finale integratie van de oerwond.',
      phases: [
        { age: '~49-51 jaar', title: 'Chiron-Terugkeer', text: 'De centrale vraag: "Hoeveel van deze pijn die ik draag is nog noodzakelijk?" Het is het moment te accepteren dat de wond niet meer verborgen hoeft te worden. Kwetsbaarheid wordt wijsheid. Veel mensen beginnen of verdiepen therapeutisch of spiritueel werk tijdens deze periode.' },
        { age: '~22-25 jaar', title: 'Chiron Vierkant', text: 'Eerste crisis met de wond. Kan een periode van isolatie, schaamte of moeite met verbondenheid zijn.' },
        { age: '~37-40 jaar', title: 'Chiron Oppositie', text: 'Directe confrontatie met de wond. Valt vaak samen met de midlifecrisis en vereist het confronteren van wat vermeden werd.' },
      ],
    },
    {
      planet: 'Neptunus ♆',
      icon: '🌊',
      cycle: 'Vierkant bij ~40-42 jaar en ~82-84 jaar',
      ages: '~40-42 (eerste vierkant), ~82-84 (terugkeer)',
      title: 'Ontbinding en Transcendentie',
      description: 'Neptunus heeft 165 jaar nodig voor zijn cyclus. Het Neptunus-vierkant (bij ~40-42 jaar) valt vaak samen met de midlifecrisis en voegt een dimensie toe van illusie-ontbinding — met name illusies over wie we zijn en wat we willen.',
      phases: [
        { age: '~40-42 jaar', title: 'Neptunus Vierkant', text: 'Ontbinding van in de jeugd opgebouwde illusies. "Het leven dat ik me voorstelde is niet precies dit." Periode van creatieve desoriëntatie — het oude zelf lost op voordat het nieuwe zich vormt.' },
      ],
    },
    {
      planet: 'Pluto ♇',
      icon: '🔥',
      cycle: 'Vierkant bij ~36-44 jaar',
      ages: '~36-44 (eerste vierkant)',
      title: 'Dood en Wedergeboorte',
      description: 'Pluto heeft 248 jaar nodig, keert dus nooit terug. Maar het Plutonische vierkant (bij ~36-44 jaar) is een van de meest intense overgangen — valt samen met de midlifecrisis en eist de symbolische dood van ego-delen die hindernissen zijn geworden.',
      phases: [
        { age: '~36-44 jaar', title: 'Pluto Vierkant', text: 'Psychologisch dood-wedergeboorteproces. Macht, controle, schaduw en kwetsbaarheid komen naar de oppervlakte. Waaraan u met kracht vasthield, begint te ontbinden. Diepgaand transformerend en mogelijk angstaanjagend — en noodzakelijk.' },
      ],
    },
  ],
  integration: {
    title: 'Hoe Bewust met Cycli te Werken',
    text: 'Uw cycli kennen gaat niet over de toekomst voorspellen — het gaat over de innerlijke grond voorbereiden. Wanneer u weet dat u een Saturnaanse periode ingaat, kunt u ruimte creëren voor herziening in plaats van meegesleurd te worden. Cycli zijn niet deterministisch: ze onthullen de kwaliteit van de tijd, niet haar inhoud.',
    tips: [
      'Identificeer in welke cyclus u zich momenteel bevindt',
      'Vraag: welk soort groei nodigt deze cyclus uit?',
      'Weersta de impuls om de crises van de grotere cycli te "ontvluchten"',
      'Gebruik therapie, meditatie of dagboekschrijven als integratiemiddelen',
      'Moeilijke cycli produceren de grootste bewustzijnssprongen wanneer ze bewust worden doorleefd',
    ],
  },
  cta: 'Ontdek in welke cycli u zich nu bevindt',
  ctaButton: 'Zie Mijn Transits →',
};
