export const signs = {
  title: 'De 12 Dierenriemtekens',
  intro: 'Tekens zijn 12 energetische archetypen. Elke planeet in uw horoscoop staat in een teken en kleurt zijn expressie met specifieke kwaliteiten.',
  list: [
    { symbol: '♈', name: 'Ram', dates: '21 Mrt – 19 Apr', element: 'Vuur', mode: 'Kardinaal', ruler: '♂ Mars', color: '#cc0000', description: 'Eerste teken — de vonk van het begin. Moed, impuls, competitiviteit en individualiteit. Ram doorbreekt traagheid en opent nieuwe paden. Schaduw: impulsiviteit, egoïsme, agressie.' },
    { symbol: '♉', name: 'Stier', dates: '20 Apr – 20 Mei', element: 'Aarde', mode: 'Vast', ruler: '♀ Venus', color: '#006600', description: 'Consolidering van wat Ram begon. Stabiliteit, zintuiglijk genot, loyaliteit en doorzettingsvermogen. Stier bouwt solide fundamenten met geduld. Schaduw: bezitterigheid, koppigheid, materialisme.' },
    { symbol: '♊', name: 'Tweelingen', dates: '21 Mei – 20 Jun', element: 'Lucht', mode: 'Beweeglijk', ruler: '☿ Mercurius', color: '#0000cc', description: 'De brug tussen werelden. Onverzadigbare nieuwsgierigheid, communicatie, veelzijdigheid en lichtheid. Tweelingen verbinden informatie en mensen. Schaduw: oppervlakkigheid, inconsistentie, dualiteit.' },
    { symbol: '♋', name: 'Kreeft', dates: '21 Jun – 22 Jul', element: 'Water', mode: 'Kardinaal', ruler: '☽ Maan', color: '#cc6600', description: 'Het emotionele nest. Bescherming, geheugen, verbondenheid en zorg. Kreeft schept wortels en zorgt diep. Schaduw: afhankelijkheid, emotionele manipulatie, vasthouden aan het verleden.' },
    { symbol: '♌', name: 'Leeuw', dates: '23 Jul – 22 Aug', element: 'Vuur', mode: 'Vast', ruler: '☉ Zon', color: '#cc0000', description: 'Het podium van het leven. Creatieve expressie, persoonlijke uitstraling, vrijgevigheid en leiderschap. Leeuw straalt en inspireert. Schaduw: arrogantie, behoefte aan applaus, drama.' },
    { symbol: '♍', name: 'Maagd', dates: '23 Aug – 22 Sep', element: 'Aarde', mode: 'Beweeglijk', ruler: '☿ Mercurius', color: '#006600', description: 'Verfijning van ervaring. Analyse, bekwaamheid, dienstverlening en verbetering. Maagd scheidt het essentiële van het overbodige. Schaduw: overmatige kritiek, perfectionisme, angst.' },
    { symbol: '♎', name: 'Weegschaal', dates: '23 Sep – 22 Okt', element: 'Lucht', mode: 'Kardinaal', ruler: '♀ Venus', color: '#0000cc', description: 'De ontmoeting met de ander. Evenwicht, rechtvaardigheid, diplomatie en partnerschap. Weegschaal zoekt harmonie in relaties en esthetiek. Schaduw: besluiteloosheid, afhankelijkheid van anderen.' },
    { symbol: '♏', name: 'Schorpioen', dates: '23 Okt – 21 Nov', element: 'Water', mode: 'Vast', ruler: '♇ Pluto', color: '#cc6600', description: 'De afdaling naar de diepten. Intensiteit, transformatie, waarheid en macht. Schorpioen vreest het verborgen niet. Schaduw: obsessie, jaloezie, manipulatie, wraak.' },
    { symbol: '♐', name: 'Boogschutter', dates: '22 Nov – 21 Dec', element: 'Vuur', mode: 'Beweeglijk', ruler: '♃ Jupiter', color: '#cc0000', description: 'De pijl van betekenis. Expansie, filosofie, avontuur en geloof. Boogschutter zoekt zin voorbij de horizon. Schaduw: overdaad, fanatisme, onverantwoordelijkheid.' },
    { symbol: '♑', name: 'Steenbok', dates: '22 Dec – 19 Jan', element: 'Aarde', mode: 'Kardinaal', ruler: '♄ Saturnus', color: '#006600', description: 'De berg om te beklimmen. Ambitie, discipline, volwassenheid en erfenis. Steenbok bouwt met tijd en doorzettingsvermogen. Schaduw: koelheid, starheid, pessimisme.' },
    { symbol: '♒', name: 'Waterman', dates: '20 Jan – 18 Feb', element: 'Lucht', mode: 'Vast', ruler: '♅ Uranus', color: '#0000cc', description: 'De stille revolutie. Originaliteit, onafhankelijkheid, toekomstvisie en humanitarisme. Waterman stelt de status quo in vraag. Schaduw: emotionele distantie, lege rebellie.' },
    { symbol: '♓', name: 'Vissen', dates: '19 Feb – 20 Mrt', element: 'Water', mode: 'Beweeglijk', ruler: '♆ Neptunus', color: '#cc6600', description: 'De laatste oceaan. Universeel mededogen, spiritualiteit, kunst en ego-ontbinding. Vissen voelen alles en verbinden zich met het geheel. Schaduw: escapisme, slachtofferrol, verwarring.' },
  ],
};
