export const chiron = {
  title: 'Quirón — El Sanador Herido',
  intro: 'Quirón es un cuerpo celeste descubierto en 1977, clasificado como planetoide o centauro, en órbita entre Saturno y Urano. En la astrología humanística, representa la herida primordial que llevamos — un dolor que no podemos sanar en nosotros mismos, pero que paradójicamente nos hace capaces de ayudar a los demás. Es el arquetipo del terapeuta, el mentor y el sabio que aprendió a través del sufrimiento.',
  mythology: {
    title: 'La Mitología de Quirón',
    text: 'Quirón era un centauro diferente a los demás: sabio, civilizado, maestro de la medicina, la música, la profecía y las artes marciales. Fue tutor de héroes como Aquiles, Asclepio y Jasón. Hijo de Cronos y Filira, fue abandonado por su madre al nacer por ser mitad hombre, mitad caballo — su primera herida: el rechazo de su propio origen.',
    wound: 'Su trágica ironía: siendo el mayor sanador de la Antigua Grecia, recibió una flecha envenenada de Hércules — un accidente, no maldad — y, siendo inmortal, no podía morir, pero tampoco podía sanarse a sí mismo. Vivió en dolor eterno, hasta que renunció a su inmortalidad y fue transformado en constelación.',
    meaning: 'La herida de Quirón no se resuelve. Se integra. Esa es la diferencia fundamental entre Saturno (que supera a través de la disciplina) y Quirón (que aprende a vivir con la herida hasta que se convierte en sabiduría).',
  },
  signsTitle: 'Quirón a Través de los Signos',
  signsIntro: 'El signo de Quirón revela la naturaleza de la herida — el "dónde duele" a nivel de identidad. Como Quirón pasa entre 4 y 9 años en cada signo, es una herida generacional compartida por millones.',
  signs: [
    { sign: 'Aries ♈', years: '(1968–77 / 2018–27)', wound: 'Herida en la existencia y la iniciativa', healing: 'Sanación a través del derecho a actuar, liderar y existir plenamente' },
    { sign: 'Tauro ♉', years: '(1977–83)', wound: 'Herida en el autovalor y el cuerpo', healing: 'Sanación a través de una relación sana con el autovalor y los recursos' },
    { sign: 'Géminis ♊', years: '(1983–88)', wound: 'Herida en la comunicación y el intelecto', healing: 'Sanación a través de la capacidad de ser escuchado y comprendido' },
    { sign: 'Cáncer ♋', years: '(1988–91)', wound: 'Herida en la pertenencia y la familia', healing: 'Sanación creando un hogar interior independiente del exterior' },
    { sign: 'Leo ♌', years: '(1991–93)', wound: 'Herida en la autoexpresión y el reconocimiento', healing: 'Sanación a través del derecho a brillar sin necesitar aprobación' },
    { sign: 'Virgo ♍', years: '(1993–96)', wound: 'Herida en la perfección y la adecuación', healing: 'Sanación aceptando la imperfección como parte del ser humano' },
    { sign: 'Libra ♎', years: '(1996–99)', wound: 'Herida en las relaciones y el equilibrio', healing: 'Sanación aprendiendo a relacionarse sin perderse a uno mismo' },
    { sign: 'Escorpio ♏', years: '(1999–01)', wound: 'Herida en el poder y la intimidad', healing: 'Sanación enfrentando las sombras sin destrucción' },
    { sign: 'Sagitario ♐', years: '(2001–05)', wound: 'Herida en la fe, el significado y la pertenencia filosófica', healing: 'Sanación encontrando la propia verdad, no una heredada' },
    { sign: 'Capricornio ♑', years: '(2005–10)', wound: 'Herida en la autoridad y el éxito', healing: 'Sanación redefiniendo el logro en términos propios' },
    { sign: 'Acuario ♒', years: '(2010–11)', wound: 'Herida en la originalidad y la pertenencia grupal', healing: 'Sanación a través del derecho a ser diferente y aun así amado' },
    { sign: 'Piscis ♓', years: '(2011–18)', wound: 'Herida en la espiritualidad y los límites del ego', healing: 'Sanación integrando lo trascendente sin disolverse en ello' },
  ],
  housesTitle: 'Quirón a Través de las Casas',
  housesIntro: 'La casa de Quirón indica el área de la vida donde la herida se manifiesta — donde te sientes como el "eterno herido que sana a los demás". También es donde emerge tu mayor sabiduría después de la integración.',
  houses: [
    { num: '1ª', name: 'Casa de la Identidad', wound: 'Herida en la propia existencia y presencia', gift: 'Poder para enseñar a otros cómo existir plenamente' },
    { num: '2ª', name: 'Casa de los Recursos', wound: 'Herida en el autovalor y el sustento material', gift: 'Don para ayudar a los demás a descubrir sus talentos' },
    { num: '3ª', name: 'Casa de la Comunicación', wound: 'Herida en la expresión verbal y el aprendizaje', gift: 'Don como maestro, escritor o comunicador' },
    { num: '4ª', name: 'Casa del Hogar', wound: 'Herida en las raíces, la familia y la seguridad emocional', gift: 'Capacidad de crear hogar y acogida para los demás' },
    { num: '5ª', name: 'Casa de la Creación', wound: 'Herida en la autoexpresión creativa y la alegría', gift: 'Don para inspirar la creatividad en los demás' },
    { num: '6ª', name: 'Casa de la Salud', wound: 'Herida en el cuerpo, la salud y las rutinas', gift: 'Don para la sanación física y holística' },
    { num: '7ª', name: 'Casa de las Relaciones', wound: 'Herida en la pareja íntima y el compromiso', gift: 'Don para mediar y aconsejar en relaciones' },
    { num: '8ª', name: 'Casa de la Transformación', wound: 'Herida en las pérdidas, la sexualidad y el poder compartido', gift: 'Don para guiar a los demás a través de procesos de muerte/renacimiento' },
    { num: '9ª', name: 'Casa de la Filosofía', wound: 'Herida en la creencia, la fe y la búsqueda de significado', gift: 'Don como maestro espiritual y filósofo' },
    { num: '10ª', name: 'Casa de la Carrera', wound: 'Herida en el reconocimiento público y la autoridad', gift: 'Don para liderar con genuina humildad' },
    { num: '11ª', name: 'Casa de los Grupos', wound: 'Herida en la pertenencia y las amistades', gift: 'Don para sanar comunidades y grupos' },
    { num: '12ª', name: 'Casa del Inconsciente', wound: 'Herida profundamente inconsciente, difícil de articular', gift: 'Don espiritual y capacidad de sanación trascendente' },
  ],
  healingTitle: 'Cómo Sanar la Herida de Quirón',
  healingIntro: 'La herida de Quirón no desaparece — se integra. El proceso no es de superación, sino de alquimia: transformar el dolor en sabiduría.',
  healingSteps: [
    { step: '1. Reconoce la herida', text: 'El primer paso es nombrarla: "aquí es donde duele de una manera que no tiene cura simple". No minimices, no dramatices. Simplemente reconoce con compasión.' },
    { step: '2. Abandona el papel del "sanador que niega"', text: 'El Quirón herido frecuentemente pasa la vida sanando a todos menos a sí mismo. Ayudar a los demás es real y valioso — pero no puede ser una evasión de mirar hacia adentro.' },
    { step: '3. Acepta la vulnerabilidad como fortaleza', text: 'La tendencia es ocultar la herida de Quirón. Pero es precisamente cuando la revelamos — con discernimiento — que gana poder sanador. La vulnerabilidad auténtica genera conexión.' },
    { step: '4. Busca terapia, mentoría o apoyo', text: 'Irónico pero verdadero: quienes tienen un Quirón prominente raramente buscan ayuda. La sanación comienza cuando aceptas que también puedes ser el "herido" y no solo el "sanador".' },
    { step: '5. Transfórmala en vocación', text: 'La pregunta no es "¿cómo me deshago de esta herida?" sino "¿cómo puede esta herida hacerme útil al mundo?" Un Quirón bien integrado es uno de los puntos más poderosos en la carta.' },
  ],
  cta: 'Descubre la posición de Quirón en tu carta natal',
  ctaButton: 'Calcular Mi Carta →',
};
