export const horoscope = {
  daily: {
    title: 'Horóscopo Diario Personal',
    subtitle: 'Tus tránsitos personales del día con interpretación detallada',
    selectProfile: 'Selecciona un perfil para ver tu horóscopo personalizado',
    noProfile: 'Calcula tu carta natal primero.',
    moonToday: 'Luna hoy',
    activeTransits: 'Tránsitos Activos',
    intensity: { high: 'fuerte', medium: 'medio', low: 'leve' },
    categories: { love: 'Amor', career: 'Carrera', health: 'Salud' },
    today: 'Hoy',
    tomorrow: 'Mañana',
  },
  love: {
    title: 'Horóscopo del Amor',
    subtitle: 'Venus, Marte y los aspectos de hoy que influyen en tu vida amorosa',
  },
  weekly: {
    title: 'Horóscopo Semanal',
    subtitle: 'Visión general de tránsitos y energías para los próximos 7 días',
    thisWeek: 'Esta semana',
    prevWeek: '← Semana',
    nextWeek: 'Semana →',
    selectProfile: 'Selecciona un perfil para ver el horóscopo semanal',
  },
  events: {
    title: 'Eventos Celestes',
    subtitle: 'Ingresos planetarios, aspectos exactos, fases lunares y estaciones retrógradas',
    noEvents: 'No hay eventos celestes significativos este día.',
    types: { ingress: 'Ingreso', aspect: 'Aspecto exacto', 'moon-phase': 'Fase lunar', retrograde: 'Estación' },
  },
  interpretation: {
    title: 'Interpretación Básica',
    premiumCta: '¿Quieres un análisis personalizado completo?',
    premiumDesc: 'Nuestro Informe Natal Completo incluye todos los planetas, aspectos, dignidades y previsiones en PDF profesional.',
    premiumButton: 'Ver Informes Premium',
    freeNotice: 'Interpretación resumida gratuita. Para análisis completo (más de 20 páginas), consulta nuestros informes premium.',
  },
  transitTexts: {
    noTransits: 'Día tranquilo sin tránsitos significativos. Tómate tiempo para descansar y reflexionar.',
    intenseDay: 'Día intenso con múltiples tránsitos poderosos. Mantente consciente y flexible.',
    normalWork: 'Día normal en el trabajo. Mantén el foco en las tareas cotidianas.',
    energyHigh: 'Energía alta pero tendencia al exceso. Ejercítate pero evita el sobresfuerzo.',
    vitalityGood: 'Vitalidad alta. Excelente para actividades físicas y deporte.',
    energyStable: 'Energía estable. Mantén hábitos saludables y respeta tu ritmo.',
  },
  moonLove: [
    'Impulso romántico y pasión rápida.',
    'Sensualidad y deseo de confort juntos.',
    'Coqueteo intelectual y conversaciones seductoras.',
    'Necesidad de afecto y seguridad en el amor.',
    'Romance dramático y expresión generosa.',
    'Amor mostrado a través de actos prácticos.',
    'Búsqueda de armonía y compañerismo.',
    'Deseo intenso y posesivo.',
    'Atracción por la novedad y la aventura.',
    'Amor maduro y compromiso.',
    'Libertad en el amor y conexiones inusuales.',
    'Romanticismo e idealización.',
  ],
};
