export const planetaryCycles = {
  title: 'Ciclos Planetarios',
  intro: 'La astrología tiene una dimensión temporal que va más allá de la carta natal. Los planetas siguen moviéndose después del nacimiento y periódicamente regresan al mismo punto del cielo donde estaban cuando naciste — o forman ángulos significativos con ese punto. Estos ciclos funcionan como un reloj biológico-simbólico de la psique, marcando fases naturales de crecimiento, crisis, integración y renovación.',
  whatAreCycles: {
    title: '¿Qué Son los Ciclos Planetarios?',
    text: 'Cada planeta tiene un período orbital — el tiempo que tarda en completar una órbita completa alrededor del Sol. Cuando un planeta en tránsito regresa al punto exacto que ocupaba en el momento de tu nacimiento, lo llamamos "retorno". Cuando forma un ángulo de 180° con la posición natal, lo llamamos "oposición".',
    note: 'Los retornos y oposiciones no son eventos externos que "te suceden" — son invitaciones internas a revisar, integrar o transformar una dimensión específica de tu vida.',
  },
  cycles: [
    {
      planet: 'Júpiter ♃',
      icon: '✦',
      cycle: 'Retorno cada ~12 años',
      ages: '12, 24, 36, 48, 60, 72...',
      title: 'El Ciclo de Expansión',
      description: 'Júpiter completa una órbita en aproximadamente 12 años. Sus retornos coinciden con años de oportunidad, expansión y puertas abiertas. El retorno de Júpiter no entrega oportunidades — agudiza tu percepción de las que ya están presentes.',
      phases: [
        { age: '~12 años', title: 'Primer retorno', text: 'Transición de la infancia a la pre-adolescencia. Expansión de la visión del mundo, primeros cuestionamientos filosóficos.' },
        { age: '~24 años', title: 'Segundo retorno', text: 'Expansión hacia la vida adulta independiente. Año de oportunidades profesionales o educativas.' },
        { age: '~36 años', title: 'Tercer retorno', text: 'Consolidación y expansión de la identidad adulta. Apertura a nuevos proyectos de vida.' },
        { age: '~48 años', title: 'Cuarto retorno', text: 'Renovación de propósito y significado. A menudo coincide con cambios de carrera o filosofía de vida.' },
      ],
    },
    {
      planet: 'Saturno ♄',
      icon: '⧖',
      cycle: 'Retorno a los ~29-30 años y ~58-60 años',
      ages: '~14-15 (cuadratura), ~29-30 (retorno), ~36-37 (oposición), ~58-60 (retorno)',
      title: 'El Gran Maestro — El Retorno de Saturno',
      description: 'Saturno es el planeta más temido e importante de los ciclos de vida. Su primer retorno, alrededor de los 29-30 años, es un rito de paso universal — el momento en que la juventud termina y la vida adulta real comienza. Eres convocado a asumir plena responsabilidad de quién eres.',
      phases: [
        { age: '~14-15 años', title: 'Primera cuadratura', text: 'Primera confrontación con la autoridad y los límites. Identidad adolescente en formación.' },
        { age: '~21-22 años', title: 'Primera cuadratura creciente', text: 'Tensión entre la libertad deseada y las responsabilidades crecientes.' },
        { age: '~29-30 años', title: 'Retorno de Saturno', text: 'El gran punto de inflexión. Saturno "cobra la deuda" — las relaciones, carreras e identidades construidas sin autenticidad tienden a disolverse. Lo genuino se fortalece. Crisis existencial frecuente, pero necesaria.' },
        { age: '~36-37 años', title: 'Oposición de Saturno', text: 'Revisión a mitad de ciclo. Evaluación de lo construido desde los 29 años. Momento de corrección de rumbo.' },
        { age: '~44 años', title: 'Segunda cuadratura menguante', text: 'Preparación para el segundo retorno. Confrontación con lo que fue postergado o negado.' },
        { age: '~58-60 años', title: 'Segundo Retorno de Saturno', text: 'Transición a la madurez plena. Revisión profunda del legado y propósito de vida.' },
      ],
    },
    {
      planet: 'Urano ♅',
      icon: '⚡',
      cycle: 'Oposición a los ~38-44 años',
      ages: '~38-44 (oposición), ~84 (retorno)',
      title: 'La Crisis de la Mediana Edad — Oposición de Urano',
      description: 'Urano tarda 84 años en completar su ciclo. La oposición — cuando Urano en tránsito forma 180° con Urano natal — ocurre entre los 38 y 44 años. Esta es la famosa "crisis de la mediana edad". Urano, el planeta de la libertad y la ruptura, cuestiona radicalmente los patrones establecidos.',
      phases: [
        { age: '~38-44 años', title: 'Oposición de Urano', text: 'Urgencia repentina de libertad. Cuestionamiento de todo lo construido. "¿Para quién estoy viviendo esta vida?" Puede manifestarse como cambios abruptos de carrera, relación o estilo de vida. Esta no es una crisis a evitar — es un llamado a la autenticidad.' },
        { age: '~21 años', title: 'Cuadratura de Urano', text: 'Primer impulso para liberarse de los patrones parentales y sociales. "No quiero la vida que me enseñaron a querer."' },
        { age: '~63 años', title: 'Segunda cuadratura', text: 'Consolidación de la identidad auténtica después de la crisis de la mediana edad. ¿Quién soy realmente, libre de expectativas?' },
      ],
    },
    {
      planet: 'Quirón ⚷',
      icon: '⚷',
      cycle: 'Retorno a los ~49-51 años',
      ages: '~49-51 (retorno)',
      title: 'El Retorno de Quirón',
      description: 'Quirón, el Sanador Herido, regresa al punto natal alrededor de los 49 a 51 años — a menudo coincidiendo con la menopausia/andropausia y lo que Jung llamó "individuación". Es una invitación a la integración final de la herida primordial.',
      phases: [
        { age: '~49-51 años', title: 'Retorno de Quirón', text: 'La pregunta central: "¿Cuánto de este dolor que llevo todavía es necesario?" Es el momento de aceptar que la herida ya no necesita ser ocultada. La vulnerabilidad se convierte en sabiduría. Muchas personas comienzan o profundizan el trabajo terapéutico o espiritual en este período.' },
        { age: '~22-25 años', title: 'Cuadratura de Quirón', text: 'Primera crisis con la herida. Puede ser un período de aislamiento, vergüenza o dificultad para pertenecer.' },
        { age: '~37-40 años', title: 'Oposición de Quirón', text: 'Confrontación directa con la herida. A menudo coincide con la crisis de la mediana edad y requiere enfrentar lo que fue evitado.' },
      ],
    },
    {
      planet: 'Neptuno ♆',
      icon: '🌊',
      cycle: 'Cuadratura a los ~40-42 años y ~82-84 años',
      ages: '~40-42 (primera cuadratura), ~82-84 (retorno)',
      title: 'Disolución y Trascendencia',
      description: 'Neptuno tarda 165 años en completar su ciclo. La cuadratura de Neptuno (a los ~40-42 años) a menudo coincide con la crisis de la mediana edad y agrega una dimensión de disolución de ilusiones — especialmente ilusiones sobre quiénes somos y qué queremos.',
      phases: [
        { age: '~40-42 años', title: 'Cuadratura de Neptuno', text: 'Disolución de las ilusiones construidas en la juventud. "La vida que imaginé no es exactamente esta." Período de desorientación creativa — el viejo yo se disuelve antes de que el nuevo se forme.' },
      ],
    },
    {
      planet: 'Plutón ♇',
      icon: '🔥',
      cycle: 'Cuadratura a los ~36-44 años',
      ages: '~36-44 (primera cuadratura)',
      title: 'Muerte y Renacimiento',
      description: 'Plutón tarda 248 años, así que nunca retorna. Pero la cuadratura plutoniana (a los ~36-44 años) es una de las transiciones más intensas — coincidiendo con la crisis de la mediana edad y exigiendo la muerte simbólica de partes del ego que se han convertido en obstáculos.',
      phases: [
        { age: '~36-44 años', title: 'Cuadratura de Plutón', text: 'Proceso de muerte-renacimiento psicológico. Poder, control, sombra y vulnerabilidad salen a la superficie. Lo que sostenías con fuerza comienza a disolverse. Profundamente transformador y potencialmente aterrador — y necesario.' },
      ],
    },
  ],
  integration: {
    title: 'Cómo Trabajar con los Ciclos Conscientemente',
    text: 'Conocer tus ciclos no se trata de predecir el futuro — se trata de preparar el terreno interno. Cuando sabes que estás entrando en un período saturnino, por ejemplo, puedes crear espacio para la revisión en lugar de ser arrastrado por él. Los ciclos no son deterministas: revelan la calidad del tiempo, no su contenido.',
    tips: [
      'Identifica en qué ciclo te encuentras actualmente',
      'Pregunta: ¿qué tipo de crecimiento invita este ciclo?',
      'Resiste el impulso de "escapar" de las crisis de los ciclos más grandes',
      'Usa la terapia, la meditación o el diario como herramientas de integración',
      'Los ciclos difíciles producen los mayores saltos de conciencia cuando se atraviesan conscientemente',
    ],
  },
  cta: 'Descubre en qué ciclos te encuentras ahora mismo',
  ctaButton: 'Ver Mis Tránsitos →',
};
