export const signs = {
  title: 'Los 12 Signos del Zodíaco',
  intro: 'Los signos son 12 arquetipos energéticos. Cada planeta en tu carta está en un signo, tiñendo su expresión con cualidades específicas.',
  list: [
    { symbol: '♈', name: 'Aries', dates: '21 Mar – 19 Abr', element: 'Fuego', mode: 'Cardinal', ruler: '♂ Marte', color: '#cc0000', description: 'Primer signo — la chispa del comienzo. Valentía, impulso, competitividad e individualidad. Aries rompe la inercia y abre nuevos caminos. Sombra: impulsividad, egoísmo, agresión.' },
    { symbol: '♉', name: 'Tauro', dates: '20 Abr – 20 May', element: 'Tierra', mode: 'Fijo', ruler: '♀ Venus', color: '#006600', description: 'Consolidación de lo que Aries comenzó. Estabilidad, placer sensorial, lealtad y perseverancia. Tauro construye bases sólidas con paciencia. Sombra: posesividad, terquedad, materialismo.' },
    { symbol: '♊', name: 'Géminis', dates: '21 May – 20 Jun', element: 'Aire', mode: 'Mutable', ruler: '☿ Mercurio', color: '#0000cc', description: 'El puente entre mundos. Curiosidad insaciable, comunicación, versatilidad y ligereza. Géminis conecta información y personas. Sombra: superficialidad, inconsistencia, dualidad.' },
    { symbol: '♋', name: 'Cáncer', dates: '21 Jun – 22 Jul', element: 'Agua', mode: 'Cardinal', ruler: '☽ Luna', color: '#cc6600', description: 'El nido emocional. Protección, memoria, pertenencia y cuidado. Cáncer crea raíces y cuida profundamente. Sombra: dependencia, manipulación emocional, aferrarse al pasado.' },
    { symbol: '♌', name: 'Leo', dates: '23 Jul – 22 Ago', element: 'Fuego', mode: 'Fijo', ruler: '☉ Sol', color: '#cc0000', description: 'El escenario de la vida. Expresión creativa, brillo personal, generosidad y liderazgo. Leo irradia e inspira. Sombra: arrogancia, necesidad de aplausos, drama.' },
    { symbol: '♍', name: 'Virgo', dates: '23 Ago – 22 Sep', element: 'Tierra', mode: 'Mutable', ruler: '☿ Mercurio', color: '#006600', description: 'Refinamiento de la experiencia. Análisis, competencia, servicio y mejora. Virgo separa lo esencial de lo superfluo. Sombra: crítica excesiva, perfeccionismo, ansiedad.' },
    { symbol: '♎', name: 'Libra', dates: '23 Sep – 22 Oct', element: 'Aire', mode: 'Cardinal', ruler: '♀ Venus', color: '#0000cc', description: 'El encuentro con el otro. Equilibrio, justicia, diplomacia y asociación. Libra busca armonía en las relaciones y la estética. Sombra: indecisión, dependencia de los demás.' },
    { symbol: '♏', name: 'Escorpio', dates: '23 Oct – 21 Nov', element: 'Agua', mode: 'Fijo', ruler: '♇ Plutón', color: '#cc6600', description: 'El descenso a las profundidades. Intensidad, transformación, verdad y poder. Escorpio no teme lo oculto. Sombra: obsesión, celos, manipulación, venganza.' },
    { symbol: '♐', name: 'Sagitario', dates: '22 Nov – 21 Dic', element: 'Fuego', mode: 'Mutable', ruler: '♃ Júpiter', color: '#cc0000', description: 'La flecha del significado. Expansión, filosofía, aventura y fe. Sagitario busca significado más allá del horizonte. Sombra: exceso, fanatismo, irresponsabilidad.' },
    { symbol: '♑', name: 'Capricornio', dates: '22 Dic – 19 Ene', element: 'Tierra', mode: 'Cardinal', ruler: '♄ Saturno', color: '#006600', description: 'La montaña a escalar. Ambición, disciplina, madurez y legado. Capricornio construye con tiempo y persistencia. Sombra: frialdad, rigidez, pesimismo.' },
    { symbol: '♒', name: 'Acuario', dates: '20 Ene – 18 Feb', element: 'Aire', mode: 'Fijo', ruler: '♅ Urano', color: '#0000cc', description: 'La revolución silenciosa. Originalidad, independencia, visión de futuro y humanitarismo. Acuario cuestiona el statu quo. Sombra: distanciamiento emocional, rebeldía vacía.' },
    { symbol: '♓', name: 'Piscis', dates: '19 Feb – 20 Mar', element: 'Agua', mode: 'Mutable', ruler: '♆ Neptuno', color: '#cc6600', description: 'El océano final. Compasión universal, espiritualidad, arte y disolución del ego. Piscis lo siente todo y se conecta con el todo. Sombra: escapismo, victimismo, confusión.' },
  ],
};
