export const chiron = {
  title: 'Kiron — Yaralı Şifacı',
  intro: 'Kiron, 1977\'de keşfedilen, Satürn ile Uranüs arasında yörüngede olan, planetoid veya centaur olarak sınıflandırılmış bir gök cismidir. İnsancı astrolojide, taşıdığımız ilkel yarayı temsil eder — kendimizde iyileştiremediğimiz, ancak paradoks olarak başkalarına yardım etme kapasitesi kazandıran bir acı. Bu, terapeistin, mentörün ve acı yoluyla öğrenen bilgenin arketipidir.',
  mythology: {
    title: 'Kiron\'un Mitolojisi',
    text: 'Kiron, diğerlerinden farklı bir centaurdu: bilge, medeni, tıp, müzik, kehanet ve dövüş sanatlarının ustası. Aşil, Asklepios ve Jason gibi kahramanların eğiticisiydi. Kronos ve Philyra\'nın oğlu, yarı insan yarı at olduğu için doğumunda annesi tarafından terk edildi — ilk yarası: kendi kökeninin reddi.',
    wound: 'Trajik ironisi: Antik Yunanistan\'ın en büyük şifacısı olarak Herakles\'ten zehirli bir ok aldı — kaza eseri, kötü niyetle değil — ve ölümsüz olduğundan ne ölebiliyordu ne de kendini iyileştirebiliyordu. Ölümsüzlüğünden vazgeçip bir takımyıldızına dönüştürülene kadar sonsuz acıyla yaşadı.',
    meaning: 'Kiron\'un yarası çözülmez. Entegre edilir. Bu, Satürn (disiplin yoluyla aşan) ile Kiron (yara bilgeliğe dönüşene kadar onunla yaşamayı öğrenen) arasındaki temel farktır.',
  },
  signsTitle: 'Burçlarda Kiron',
  signsIntro: 'Kiron\'un burcu, yaranın doğasını ortaya koyar — kimlik düzeyinde "nerenin acıdığını". Kiron her burçta 4 ile 9 yıl arasında kaldığından, milyonlar tarafından paylaşılan kuşak yarasıdır.',
  signs: [
    { sign: 'Koç ♈', years: '(1968–77 / 2018–27)', wound: 'Varoluş ve inisiyatifte yara', healing: 'Tam olarak hareket etme, liderlik etme ve var olma hakkıyla iyileşme' },
    { sign: 'Boğa ♉', years: '(1977–83)', wound: 'Öz-değer ve bedende yara', healing: 'Öz-değer ve kaynaklarla sağlıklı ilişkiyle iyileşme' },
    { sign: 'İkizler ♊', years: '(1983–88)', wound: 'İletişim ve zekâda yara', healing: 'Duyulma ve anlaşılma kapasitesiyle iyileşme' },
    { sign: 'Yengeç ♋', years: '(1988–91)', wound: 'Aidiyet ve ailede yara', healing: 'Dışarıdan bağımsız bir iç yuva yaratarak iyileşme' },
    { sign: 'Aslan ♌', years: '(1991–93)', wound: 'Öz-ifade ve takdirde yara', healing: 'Onay aramadan parlama hakkıyla iyileşme' },
    { sign: 'Başak ♍', years: '(1993–96)', wound: 'Mükemmellik ve uygunlukta yara', healing: 'Kusurluluğu insan olmanın parçası olarak kabul ederek iyileşme' },
    { sign: 'Terazi ♎', years: '(1996–99)', wound: 'İlişkiler ve dengede yara', healing: 'Kendini kaybetmeden ilişki kurmayı öğrenerek iyileşme' },
    { sign: 'Akrep ♏', years: '(1999–01)', wound: 'Güç ve yakınlıkta yara', healing: 'Yıkım olmadan gölgelerle yüzleşerek iyileşme' },
    { sign: 'Yay ♐', years: '(2001–05)', wound: 'İnanç, anlam ve felsefi aidiyette yara', healing: 'Miras alınan değil kendi gerçeğini bularak iyileşme' },
    { sign: 'Oğlak ♑', years: '(2005–10)', wound: 'Otorite ve başarıda yara', healing: 'Başarıyı kendi koşullarıyla yeniden tanımlayarak iyileşme' },
    { sign: 'Kova ♒', years: '(2010–11)', wound: 'Özgünlük ve gruba aidiyette yara', healing: 'Farklı olma ve yine de sevilme hakkıyla iyileşme' },
    { sign: 'Balık ♓', years: '(2011–18)', wound: 'Maneviyat ve ego sınırlarında yara', healing: 'İçinde erimeden aşkınlığı entegre ederek iyileşme' },
  ],
  housesTitle: 'Evlerde Kiron',
  housesIntro: 'Kiron\'un evi, yaranın tezahür ettiği yaşam alanını gösterir — kendinizi "başkalarını iyileştiren ebedi yaralı" gibi hissettiğiniz yer. Aynı zamanda entegrasyondan sonra en büyük bilgeliğinizin ortaya çıktığı yerdir.',
  houses: [
    { num: '1.', name: 'Kimlik Evi', wound: 'Kendi varoluşunda ve varlığında yara', gift: 'Başkalarına tam olarak var olmayı öğretme gücü' },
    { num: '2.', name: 'Kaynaklar Evi', wound: 'Öz-değer ve maddi geçimde yara', gift: 'Başkalarının yeteneklerini keşfetmelerine yardım etme armağanı' },
    { num: '3.', name: 'İletişim Evi', wound: 'Sözlü ifade ve öğrenmede yara', gift: 'Öğretmen, yazar veya iletişimci olma armağanı' },
    { num: '4.', name: 'Yuva Evi', wound: 'Köklerde, ailede ve duygusal güvende yara', gift: 'Başkaları için yuva ve sıcaklık yaratma kapasitesi' },
    { num: '5.', name: 'Yaratım Evi', wound: 'Yaratıcı öz-ifadede ve neşede yara', gift: 'Başkalarında yaratıcılığa ilham verme armağanı' },
    { num: '6.', name: 'Sağlık Evi', wound: 'Beden, sağlık ve rutinlerde yara', gift: 'Fiziksel ve bütünsel şifa armağanı' },
    { num: '7.', name: 'İlişkiler Evi', wound: 'Samimi ortaklık ve bağlılıkta yara', gift: 'İlişkilerde arabuluculuk ve rehberlik armağanı' },
    { num: '8.', name: 'Dönüşüm Evi', wound: 'Kayıplarda, cinsellikte ve paylaşılan güçte yara', gift: 'Başkalarına ölüm/yeniden doğuş süreçlerinde rehberlik etme armağanı' },
    { num: '9.', name: 'Felsefe Evi', wound: 'İnanç, iman ve anlam arayışında yara', gift: 'Ruhsal öğretmen ve filozof olma armağanı' },
    { num: '10.', name: 'Kariyer Evi', wound: 'Kamuoyu tanınırlığı ve otoritede yara', gift: 'Gerçek alçakgönüllülükle liderlik etme armağanı' },
    { num: '11.', name: 'Gruplar Evi', wound: 'Aidiyet ve dostluklarda yara', gift: 'Toplulukları ve grupları iyileştirme armağanı' },
    { num: '12.', name: 'Bilinçdışı Evi', wound: 'Derin bilinçdışı yara, ifade etmesi zor', gift: 'Manevi armağan ve aşkın şifa kapasitesi' },
  ],
  healingTitle: 'Kiron\'un Yarası Nasıl İyileştirilir',
  healingIntro: 'Kiron\'un yarası kaybolmaz — entegre edilir. Süreç, yenmeyle değil simyayla ilgilidir: acıyı bilgeliğe dönüştürmek.',
  healingSteps: [
    { step: '1. Yarayı kabul etmek', text: 'İlk adım onu adlandırmaktır: "basit bir çözümü olmayan bir şekilde burada acıyor". Küçümseme, dramatize etme. Sadece şefkatle kabul et.' },
    { step: '2. "İnkâr eden şifacı" rolünü bırakmak', text: 'Yaralı Kiron çoğunlukla hayatını kendisi dışında herkesi iyileştirerek geçirir. Başkalarına yardım etmek gerçek ve değerlidir — ama içe bakıştan kaçış olamaz.' },
    { step: '3. Kırılganlığı güç olarak kabul etmek', text: 'Eğilim Kiron\'un yarasını saklamaktır. Ama tam olarak onu — basiret ile — ortaya koyduğumuzda iyileştirici güç kazanır. Özgün kırılganlık bağlantı üretir.' },
    { step: '4. Terapi, mentorluk veya destek aramak', text: 'İronik ama doğru: belirgin Kiron\'u olanlar nadiren yardım arar. İyileşme, "yaralı" da olabileceğinizi kabul ettiğinizde başlar, sadece "şifacı" değil.' },
    { step: '5. Onu mesleğe dönüştürmek', text: '"Bu yaradan nasıl kurtulabilirim?" sorusu değil, "bu yara beni dünya için nasıl faydalı kılabilir?" sorusudur. İyi entegre edilmiş Kiron, haritadaki en güçlü noktalardan biridir.' },
  ],
  cta: 'Doğum haritanızda Kiron\'un konumunu keşfedin',
  ctaButton: 'Haritamı Hesapla →',
};
