export const horoscope = {
  daily: {
    title: 'Kişisel Günlük Burç Yorumu',
    subtitle: 'Ayrıntılı yorumlu günlük kişisel transit\'leriniz',
    selectProfile: 'Kişiselleştirilmiş burcunuzu görmek için bir profil seçin',
    noProfile: 'Önce doğum haritanızı hesaplayın.',
    moonToday: 'Bugün Ay',
    activeTransits: 'Aktif Transitler',
    intensity: { high: 'güçlü', medium: 'orta', low: 'hafif' },
    categories: { love: 'Aşk', career: 'Kariyer', health: 'Sağlık' },
    today: 'Bugün',
    tomorrow: 'Yarın',
  },
  love: {
    title: 'Aşk Burç Yorumu',
    subtitle: 'Aşk hayatınızı etkileyen Venus, Mars ve bugünün açıları',
  },
  weekly: {
    title: 'Haftalık Burç Yorumu',
    subtitle: 'Önümüzdeki 7 gün için transit ve enerji genel bakışı',
    thisWeek: 'Bu hafta',
    prevWeek: '← Hafta',
    nextWeek: 'Hafta →',
    selectProfile: 'Haftalık burç yorumunu görmek için bir profil seçin',
  },
  events: {
    title: 'Gök Olayları',
    subtitle: 'Gezegen geçişleri, kesin açılar, ay evreleri ve geri hareket istasyonları',
    noEvents: 'Bu günde önemli gök olayı yok.',
    types: { ingress: 'Geçiş', aspect: 'Kesin açı', 'moon-phase': 'Ay evresi', retrograde: 'İstasyon' },
  },
  interpretation: {
    title: 'Temel Yorum',
    premiumCta: 'Tam kişiselleştirilmiş bir analiz ister misiniz?',
    premiumDesc: 'Tam Natal Raporumuz tüm gezegenleri, açıları, esanslıları ve tahminleri profesyonel PDF\'de içermektedir.',
    premiumButton: 'Premium Raporları Gör',
    freeNotice: 'Ücretsiz özet yorum. Tam analiz (20+ sayfa) için premium raporlarımıza bakın.',
  },
  transitTexts: {
    noTransits: 'Önemli transit\'ler olmadan sakin bir gün. Dinlenmek ve düşünmek için zaman ayırın.',
    intenseDay: 'Birden fazla güçlü transit ile yoğun bir gün. Bilinçli ve esnek kalın.',
    normalWork: 'İşte normal bir gün. Günlük görevlere odaklanın.',
    energyHigh: 'Yüksek enerji ama aşırılık eğilimi. Egzersiz yapın ama aşırı zorlanmaktan kaçının.',
    vitalityGood: 'Vitalite yüksek. Fiziksel aktiviteler ve spor için mükemmel.',
    energyStable: 'Stabil enerji. Sağlıklı alışkanlıkları sürdürün ve ritminize saygı gösterin.',
  },
  moonLove: [
    'Romantik dürtü ve hızlı tutku.',
    'Duyusallık ve birlikte konfor arzusu.',
    'Entelektüel flört ve baştan çıkarıcı konuşmalar.',
    'Aşkta şefkat ve güvenlik ihtiyacı.',
    'Dramatik romantizm ve cömert ifade.',
    'Pratik eylemlerle gösterilen aşk.',
    'Uyum ve arkadaşlık arayışı.',
    'Yoğun ve sahiplenici arzu.',
    'Yenilik ve maceraya çekim.',
    'Olgun aşk ve bağlılık.',
    'Aşkta özgürlük ve alışılmadık bağlantılar.',
    'Romantizm ve idealleştirme.',
  ],
};
