export const planetaryCycles = {
  title: 'Gezegen Döngüleri',
  intro: 'Astrolojinin, doğum haritasının ötesine geçen zamansal bir boyutu vardır. Gezegenler doğumdan sonra hareket etmeye devam eder ve periyodik olarak doğduğunuzda gökyüzündeki bulundukları noktaya geri döner — ya da o noktayla anlamlı açılar oluşturur. Bu döngüler psikenin biyolojik-sembolik saati gibi işlev görerek büyüme, kriz, entegrasyon ve yenilenmenin doğal evrelerini işaretler.',
  whatAreCycles: {
    title: 'Gezegen Döngüleri Nedir?',
    text: 'Her gezegenin bir yörünge periyodu vardır — Güneş\'in etrafında tam bir yörüngeyi tamamlaması için geçen süre. Bir transit gezegen, doğum anında işgal ettiği tam noktaya geri döndüğünde, buna "dönüş" diyoruz. Natal konumla 180° açı oluşturduğunda ise buna "karşıtlık" diyoruz.',
    note: 'Dönüşler ve karşıtlıklar, size "olan" dışsal olaylar değildir — bunlar, hayatınızın belirli bir boyutunu gözden geçirmeye, entegre etmeye veya dönüştürmeye yönelik içsel davetlerdir.',
  },
  cycles: [
    {
      planet: 'Jüpiter ♃',
      icon: '✦',
      cycle: 'Her ~12 yılda bir dönüş',
      ages: '12, 24, 36, 48, 60, 72...',
      title: 'Genişleme Döngüsü',
      description: 'Jüpiter bir yörüngeyi yaklaşık 12 yılda tamamlar. Dönüşleri fırsat, genişleme ve açık kapıların yıllarıyla çakışır. Jüpiter dönüşü fırsat vermez — halihazırda mevcut olanları algılama keskinliğinizi artırır.',
      phases: [
        { age: '~12 yaş', title: 'Birinci dönüş', text: 'Çocukluktan ergen öncesine geçiş. Dünya görüşünün genişlemesi, ilk felsefi sorgulamalar.' },
        { age: '~24 yaş', title: 'İkinci dönüş', text: 'Bağımsız yetişkin hayatına genişleme. Mesleki veya eğitimsel fırsatlar yılı.' },
        { age: '~36 yaş', title: 'Üçüncü dönüş', text: 'Yetişkin kimliğinin pekişmesi ve genişlemesi. Yeni yaşam projelerine açılış.' },
        { age: '~48 yaş', title: 'Dördüncü dönüş', text: 'Amaç ve anlam yenilenmesi. Çoğunlukla kariyer veya yaşam felsefesi değişiklikleriyle çakışır.' },
      ],
    },
    {
      planet: 'Satürn ♄',
      icon: '⧖',
      cycle: 'Dönüş ~29-30 ve ~58-60 yaşlarında',
      ages: '~14-15 (kare), ~29-30 (dönüş), ~36-37 (karşıtlık), ~58-60 (dönüş)',
      title: 'Büyük Öğretmen — Satürn Dönüşü',
      description: 'Satürn, yaşam döngülerinin en korkulan ve en önemli gezegenidir. Yaklaşık 29-30 yaşlarındaki ilk dönüşü, evrensel bir geçiş ritüelidir — gençliğin sona erdiği ve gerçek yetişkin yaşamının başladığı an. Kim olduğunuzun tam sorumluluğunu üstlenmeye davet edilirsiniz.',
      phases: [
        { age: '~14-15 yaş', title: 'Birinci kare', text: 'Otorite ve sınırlarla ilk yüzleşme. Oluşum halindeki ergen kimliği.' },
        { age: '~21-22 yaş', title: 'Büyüyen birinci kare', text: 'İstenen özgürlük ile büyüyen sorumluluklar arasındaki gerilim.' },
        { age: '~29-30 yaş', title: 'Satürn Dönüşü', text: 'Büyük dönüm noktası. Satürn "borcu tahsil eder" — özgünlük olmadan kurulmuş ilişkiler, kariyerler ve kimlikler çözülme eğilimi gösterir. Gerçek olan güçlenir. Sık varoluşsal kriz, ama gerekli.' },
        { age: '~36-37 yaş', title: 'Satürn Karşıtlığı', text: 'Orta döngü incelemesi. 29 yaşından bu yana inşa edilenlerin değerlendirmesi. Rota düzeltme anı.' },
        { age: '~44 yaş', title: 'İkinci azalan kare', text: 'İkinci dönüşe hazırlık. Ertelenenle veya reddedilenle yüzleşme.' },
        { age: '~58-60 yaş', title: 'İkinci Satürn Dönüşü', text: 'Tam olgunluğa geçiş. Miras ve yaşam amacının derin incelemesi.' },
      ],
    },
    {
      planet: 'Uranüs ♅',
      icon: '⚡',
      cycle: 'Karşıtlık ~38-44 yaşlarında',
      ages: '~38-44 (karşıtlık), ~84 (dönüş)',
      title: 'Orta Yaş Krizi — Uranüs Karşıtlığı',
      description: 'Uranüs döngüsünü 84 yılda tamamlar. Karşıtlık — transit Uranüs natal Uranüs ile 180° oluşturduğunda — 38 ile 44 yaşları arasında gerçekleşir. Bu ünlü "orta yaş krizidir". Özgürlük ve kopuş gezegeni Uranüs, yerleşik kalıpları radikally sorgular.',
      phases: [
        { age: '~38-44 yaş', title: 'Uranüs Karşıtlığı', text: 'Özgürlük için ani aciliyet. İnşa edilenlerin her şeyini sorgulamak. "Bu hayatı kim için yaşıyorum?" Ani kariyer, ilişki veya yaşam tarzı değişiklikleri olarak tezahür edebilir. Bu, kaçınılacak bir kriz değil — özgünlüğe çağrıdır.' },
        { age: '~21 yaş', title: 'Uranüs Karesi', text: 'Anne-baba ve toplumsal kalıplardan kurtulma için ilk dürtü. "Bana istemeyi öğrettikleri hayatı istemiyorum."' },
        { age: '~63 yaş', title: 'İkinci kare', text: 'Orta yaş krizinden sonra özgün kimliğin pekişmesi. Beklentilerden özgür, gerçekten kimim?' },
      ],
    },
    {
      planet: 'Kiron ⚷',
      icon: '⚷',
      cycle: 'Dönüş ~49-51 yaşlarında',
      ages: '~49-51 (dönüş)',
      title: 'Kiron Dönüşü',
      description: 'Yaralı Şifacı Kiron, yaklaşık 49-51 yaşlarında natal noktaya geri döner — çoğunlukla menopoz/andropoz ve Jung\'un "bireyleşme" dediği şeyle çakışır. İlkel yaranın nihai entegrasyonu için bir davettir.',
      phases: [
        { age: '~49-51 yaş', title: 'Kiron Dönüşü', text: 'Temel soru: "Taşıdığım bu acının ne kadarı hâlâ gerekli?" Yaranın artık gizlenmeye gerek olmadığını kabul etme anıdır. Kırılganlık bilgeliğe dönüşür. Pek çok kişi bu dönemde terapötik veya spiritüel çalışma başlatır ya da derinleştirir.' },
        { age: '~22-25 yaş', title: 'Kiron Karesi', text: 'Yarayla ilk kriz. İzolasyon, utanç veya ait olma zorluğunun yaşandığı dönem olabilir.' },
        { age: '~37-40 yaş', title: 'Kiron Karşıtlığı', text: 'Yarayla doğrudan yüzleşme. Çoğunlukla orta yaş kriziyle çakışır ve kaçınılanla yüzleşmeyi gerektirir.' },
      ],
    },
    {
      planet: 'Neptün ♆',
      icon: '🌊',
      cycle: 'Kare ~40-42 ve ~82-84 yaşlarında',
      ages: '~40-42 (birinci kare), ~82-84 (dönüş)',
      title: 'Çözünüm ve Aşkınlık',
      description: 'Neptün döngüsünü 165 yılda tamamlar. Neptün karesi (~40-42 yaşlarında) çoğunlukla orta yaş kriziyle çakışır ve özellikle kim olduğumuz ve ne istediğimiz konusunda illüzyonların çözünümünün bir boyutunu ekler.',
      phases: [
        { age: '~40-42 yaş', title: 'Neptün Karesi', text: 'Gençlikte kurulan illüzyonların çözünümü. "Hayal ettiğim hayat tam olarak bu değil." Yaratıcı yönelim kaybı dönemi — eski benlik yeni benlik oluşmadan önce çözünür.' },
      ],
    },
    {
      planet: 'Plüton ♇',
      icon: '🔥',
      cycle: 'Kare ~36-44 yaşlarında',
      ages: '~36-44 (birinci kare)',
      title: 'Ölüm ve Yeniden Doğuş',
      description: 'Plüton 248 yıl sürer, dolayısıyla hiç geri dönmez. Ama Plütona karesi (~36-44 yaşlarında) en yoğun geçişlerden biridir — orta yaş kriziyle çakışır ve engel haline gelen ego parçalarının sembolik ölümünü talep eder.',
      phases: [
        { age: '~36-44 yaş', title: 'Plüton Karesi', text: 'Psikolojik ölüm-yeniden doğuş süreci. Güç, kontrol, gölge ve kırılganlık yüzeye çıkar. Güçle tutunulan şey çözünmeye başlar. Derinden dönüştürücü ve potansiyel olarak korkutucu — ve gerekli.' },
      ],
    },
  ],
  integration: {
    title: 'Döngülerle Bilinçli Nasıl Çalışılır',
    text: 'Kendi döngülerinizi bilmek geleceği tahmin etmek için değil — içsel zemini hazırlamak içindir. Satürn dönemine girdiğinizi bildiğinizde, örneğin, onun sürüklenmesi yerine gözden geçirme için alan yaratabilirsiniz. Döngüler kaderci değildir: zamanın kalitesini ortaya koyarlar, içeriğini değil.',
    tips: [
      'Şu anda hangi döngüde olduğunuzu belirleyin',
      'Sorun: Bu döngü nasıl bir büyümeye davet ediyor?',
      'Daha büyük döngülerin krizlerinden "kaçma" dürtüsüne direnin',
      'Terapi, meditasyon veya günlük tutmayı entegrasyon araçları olarak kullanın',
      'Zor döngüler, bilinçli yaşandığında en büyük bilinç sıçramalarını üretir',
    ],
  },
  cta: 'Şu anda hangi döngülerde olduğunuzu keşfedin',
  ctaButton: 'Transitlerime Bak →',
};
