export const chiron = {
  title: 'Chiron — The Wounded Healer',
  intro: 'Chiron is a celestial body discovered in 1977, classified as a planetoid or centaur, orbiting between Saturn and Uranus. In humanistic astrology, it represents the primordial wound we carry — a pain we cannot heal in ourselves, but which paradoxically makes us capable of helping others. It is the archetype of the therapist, the mentor, and the sage who learned through suffering.',
  mythology: {
    title: 'The Mythology of Chiron',
    text: 'Chiron was a centaur unlike the others: wise, civilized, master of medicine, music, prophecy and martial arts. He was tutor to heroes like Achilles, Asclepius and Jason. Son of Cronus and Philyra, he was abandoned by his mother at birth for being half man, half horse — his first wound: rejection by his own origin.',
    wound: 'His tragic irony: being the greatest healer of Ancient Greece, he received a poisoned arrow from Hercules — an accident, not malice — and, being immortal, could not die, but neither could he heal himself. He lived in eternal pain, until he gave up his immortality and was transformed into a constellation.',
    meaning: "Chiron's wound is not resolved. It is integrated. That is the fundamental difference between Saturn (who overcomes through discipline) and Chiron (who learns to live with the wound until it becomes wisdom).",
  },
  signsTitle: 'Chiron Through the Signs',
  signsIntro: "The sign of Chiron reveals the nature of the wound — the 'where it hurts' at the level of identity. Since Chiron spends between 4 and 9 years in each sign, it is a generational wound shared by millions.",
  signs: [
    { sign: 'Aries ♈', years: '(1968–77 / 2018–27)', wound: 'Wound in existence and initiative', healing: 'Healing through the right to act, lead and exist fully' },
    { sign: 'Taurus ♉', years: '(1977–83)', wound: 'Wound in self-worth and the body', healing: 'Healing through a healthy relationship with self-value and resources' },
    { sign: 'Gemini ♊', years: '(1983–88)', wound: 'Wound in communication and intellect', healing: 'Healing through the ability to be heard and understood' },
    { sign: 'Cancer ♋', years: '(1988–91)', wound: 'Wound in belonging and family', healing: 'Healing by creating an inner home that is independent of the external' },
    { sign: 'Leo ♌', years: '(1991–93)', wound: 'Wound in self-expression and recognition', healing: 'Healing through the right to shine without needing approval' },
    { sign: 'Virgo ♍', years: '(1993–96)', wound: 'Wound in perfection and adequacy', healing: 'Healing by accepting imperfection as part of being human' },
    { sign: 'Libra ♎', years: '(1996–99)', wound: 'Wound in relationships and balance', healing: 'Healing by learning to relate without losing oneself' },
    { sign: 'Scorpio ♏', years: '(1999–01)', wound: 'Wound in power and intimacy', healing: 'Healing by facing shadows without destruction' },
    { sign: 'Sagittarius ♐', years: '(2001–05)', wound: 'Wound in faith, meaning and philosophical belonging', healing: 'Healing by finding one\'s own truth, not an inherited one' },
    { sign: 'Capricorn ♑', years: '(2005–10)', wound: 'Wound in authority and success', healing: 'Healing by redefining achievement on one\'s own terms' },
    { sign: 'Aquarius ♒', years: '(2010–11)', wound: 'Wound in originality and group belonging', healing: 'Healing through the right to be different and still loved' },
    { sign: 'Pisces ♓', years: '(2011–18)', wound: 'Wound in spirituality and ego boundaries', healing: 'Healing by integrating the transcendent without dissolving into it' },
  ],
  housesTitle: 'Chiron Through the Houses',
  housesIntro: "The house of Chiron indicates the area of life where the wound manifests — where you feel like the 'eternal wounded one who heals others'. It is also where your greatest wisdom emerges after integration.",
  houses: [
    { num: '1st', name: 'House of Identity', wound: 'Wound in one\'s own existence and presence', gift: 'Power to teach others how to exist fully' },
    { num: '2nd', name: 'House of Resources', wound: 'Wound in self-worth and material sustenance', gift: 'Gift for helping others discover their talents' },
    { num: '3rd', name: 'House of Communication', wound: 'Wound in verbal expression and learning', gift: 'Gift as a teacher, writer or communicator' },
    { num: '4th', name: 'House of Home', wound: 'Wound in roots, family and emotional security', gift: 'Ability to create home and welcome for others' },
    { num: '5th', name: 'House of Creation', wound: 'Wound in creative self-expression and joy', gift: 'Gift for inspiring creativity in others' },
    { num: '6th', name: 'House of Health', wound: 'Wound in body, health and routines', gift: 'Gift for physical and holistic healing' },
    { num: '7th', name: 'House of Relationships', wound: 'Wound in intimate partnership and commitment', gift: 'Gift for mediating and counseling relationships' },
    { num: '8th', name: 'House of Transformation', wound: 'Wound in losses, sexuality and shared power', gift: 'Gift for guiding others through death/rebirth processes' },
    { num: '9th', name: 'House of Philosophy', wound: 'Wound in belief, faith and search for meaning', gift: 'Gift as a spiritual teacher and philosopher' },
    { num: '10th', name: 'House of Career', wound: 'Wound in public recognition and authority', gift: 'Gift for leading with genuine humility' },
    { num: '11th', name: 'House of Groups', wound: 'Wound in belonging and friendships', gift: 'Gift for healing communities and groups' },
    { num: '12th', name: 'House of the Unconscious', wound: 'Deeply unconscious wound, difficult to articulate', gift: 'Spiritual gift and capacity for transcendent healing' },
  ],
  healingTitle: "How to Heal Chiron's Wound",
  healingIntro: "Chiron's wound does not disappear — it is integrated. The process is not about overcoming, but about alchemy: transforming pain into wisdom.",
  healingSteps: [
    { step: '1. Acknowledge the wound', text: "The first step is to name it: 'here is where it hurts in a way that has no simple cure'. Don't minimize, don't dramatize. Simply acknowledge with compassion." },
    { step: '2. Abandon the role of the "denying healer"', text: 'The wounded Chiron frequently spends life healing everyone except themselves. Helping others is real and valuable — but cannot be an escape from looking inward.' },
    { step: '3. Accept vulnerability as strength', text: "The tendency is to hide Chiron's wound. But it is precisely when we reveal it — with discernment — that it gains healing power. Authentic vulnerability generates connection." },
    { step: '4. Seek therapy, mentorship or support', text: "Ironic but true: those with prominent Chiron rarely seek help. Healing begins when you accept that you can also be the 'wounded one' and not just the 'healer'." },
    { step: '5. Transform it into vocation', text: "The question is not 'how do I get rid of this wound?' but 'how can this wound make me useful to the world?' A well-integrated Chiron is one of the most powerful points in the chart." },
  ],
  cta: 'Discover the position of Chiron in your natal chart',
  ctaButton: 'Calculate My Chart →',
};
