export const horoscope = {
  daily: {
    title: 'Personal Daily Horoscope',
    subtitle: 'Your personal transits of the day with detailed interpretation',
    selectProfile: 'Select a profile to see your personalized horoscope',
    noProfile: 'Calculate your natal chart first.',
    moonToday: 'Moon today',
    activeTransits: 'Active Transits',
    intensity: { high: 'strong', medium: 'medium', low: 'mild' },
    categories: { love: 'Love', career: 'Career', health: 'Health' },
    today: 'Today',
    tomorrow: 'Tomorrow',
  },
  love: {
    title: 'Love Horoscope',
    subtitle: 'Venus, Mars and today\'s aspects influencing your love life',
  },
  weekly: {
    title: 'Weekly Horoscope',
    subtitle: 'Overview of transits and energies for the next 7 days',
    thisWeek: 'This week',
    prevWeek: '← Week',
    nextWeek: 'Week →',
    selectProfile: 'Select a profile to see the weekly horoscope',
  },
  events: {
    title: 'Celestial Events',
    subtitle: 'Planetary ingresses, exact aspects, Moon phases and retrograde stations',
    noEvents: 'No significant celestial events on this day.',
    types: { ingress: 'Ingress', aspect: 'Exact aspect', 'moon-phase': 'Moon phase', retrograde: 'Station' },
  },
  interpretation: {
    title: 'Basic Interpretation',
    premiumCta: 'Want a complete personalized analysis?',
    premiumDesc: 'Our Complete Natal Report includes all planets, aspects, dignities and forecasts in professional PDF.',
    premiumButton: 'View Premium Reports',
    freeNotice: 'Free summary interpretation. For complete analysis (20+ pages), see our premium reports.',
  },
  transitTexts: {
    noTransits: 'Quiet day with no significant transits. Take time to rest and reflect.',
    intenseDay: 'Intense day with multiple powerful transits. Stay conscious and flexible.',
    normalWork: 'Normal day at work. Keep focus on everyday tasks.',
    energyHigh: 'High energy but tendency to excess. Exercise but avoid overexertion.',
    vitalityGood: 'Vitality is high. Excellent for physical activities and sport.',
    energyStable: 'Stable energy. Maintain healthy habits and respect your rhythm.',
  },
  moonLove: [
    'Romantic impulse and quick passion.',
    'Sensuality and desire for comfort together.',
    'Intellectual flirting and seductive conversations.',
    'Need for affection and security in love.',
    'Dramatic romance and generous expression.',
    'Love shown through practical acts.',
    'Seeking harmony and companionship.',
    'Intense and possessive desire.',
    'Attraction to novelty and adventure.',
    'Mature love and commitment.',
    'Freedom in love and unusual connections.',
    'Romanticism and idealization.',
  ],
};
