export const planetaryCycles = {
  title: 'Planetary Cycles',
  intro: 'Astrology has a temporal dimension that goes beyond the natal chart. Planets keep moving after birth and periodically return to the same point in the sky where they were when you were born — or form significant angles with that point. These cycles function as a biological-symbolic clock of the psyche, marking natural phases of growth, crisis, integration and renewal.',
  whatAreCycles: {
    title: 'What Are Planetary Cycles?',
    text: "Each planet has an orbital period — the time it takes to complete a full orbit around the Sun. When a transiting planet returns to the exact point it occupied at the moment of your birth, we call it a 'return'. When it forms a 180° angle with the natal position, we call it an 'opposition'.",
    note: "Returns and oppositions are not external events that 'happen to you' — they are internal invitations to review, integrate or transform a specific dimension of your life.",
  },
  cycles: [
    {
      planet: 'Jupiter ♃',
      icon: '✦',
      cycle: 'Return every ~12 years',
      ages: '12, 24, 36, 48, 60, 72...',
      title: 'The Expansion Cycle',
      description: 'Jupiter completes one orbit in approximately 12 years. Its returns coincide with years of opportunity, expansion and open doors. The Jupiter return does not deliver opportunities — it sharpens your perception of those already present.',
      phases: [
        { age: '~12 years', title: 'First return', text: 'Transition from childhood to pre-adolescence. Expansion of worldview, first philosophical questioning.' },
        { age: '~24 years', title: 'Second return', text: 'Expansion into independent adult life. Year of professional or educational opportunities.' },
        { age: '~36 years', title: 'Third return', text: 'Consolidation and expansion of adult identity. Opening to new life projects.' },
        { age: '~48 years', title: 'Fourth return', text: 'Renewal of purpose and meaning. Often coincides with career or life philosophy changes.' },
      ],
    },
    {
      planet: 'Saturn ♄',
      icon: '⧖',
      cycle: 'Return at ~29-30 years and ~58-60 years',
      ages: '~14-15 (square), ~29-30 (return), ~36-37 (opposition), ~58-60 (return)',
      title: 'The Great Teacher — Saturn Return',
      description: 'Saturn is the most feared and most important planet of life cycles. Its first return, around ages 29-30, is a universal rite of passage — the moment when youth ends and real adult life begins. You are summoned to take full responsibility for who you are.',
      phases: [
        { age: '~14-15 years', title: 'First square', text: 'First confrontation with authority and limits. Adolescent identity in formation.' },
        { age: '~21-22 years', title: 'Waxing first square', text: 'Tension between desired freedom and growing responsibilities.' },
        { age: '~29-30 years', title: 'Saturn Return', text: 'The great turning point. Saturn "calls in the debt" — relationships, careers and identities built without authenticity tend to dissolve. What is genuine strengthens. Frequent existential crisis, but necessary.' },
        { age: '~36-37 years', title: 'Saturn Opposition', text: 'Mid-cycle review. Evaluation of what was built since age 29. Course correction moment.' },
        { age: '~44 years', title: 'Second waning square', text: 'Preparation for the second return. Confrontation with what was delayed or denied.' },
        { age: '~58-60 years', title: 'Second Saturn Return', text: 'Transition to full maturity. Deep review of legacy and life purpose.' },
      ],
    },
    {
      planet: 'Uranus ♅',
      icon: '⚡',
      cycle: 'Opposition at ~38-44 years',
      ages: '~38-44 (opposition), ~84 (return)',
      title: 'The Midlife Crisis — Uranus Opposition',
      description: 'Uranus takes 84 years to complete its cycle. The opposition — when transiting Uranus forms 180° with natal Uranus — occurs between ages 38 and 44. This is the famous "midlife crisis". Uranus, the planet of freedom and rupture, radically questions established patterns.',
      phases: [
        { age: '~38-44 years', title: 'Uranus Opposition', text: "Sudden urgency for freedom. Questioning everything that was built. 'For whom am I living this life?' Can manifest as abrupt career, relationship or lifestyle changes. This is not a crisis to be avoided — it is a call for authenticity." },
        { age: '~21 years', title: 'Uranus Square', text: "First impulse to break free from parental and societal patterns. 'I don't want the life I was taught to want.'" },
        { age: '~63 years', title: 'Second square', text: 'Consolidation of authentic identity after the midlife crisis. Who am I really, free from expectations?' },
      ],
    },
    {
      planet: 'Chiron ⚷',
      icon: '⚷',
      cycle: 'Return at ~49-51 years',
      ages: '~49-51 (return)',
      title: 'The Chiron Return',
      description: "Chiron, the Wounded Healer, returns to the natal point around ages 49 to 51 — often coinciding with menopause/andropause and what Jung called 'individuation'. It is an invitation to the final integration of the primordial wound.",
      phases: [
        { age: '~49-51 years', title: 'Chiron Return', text: "The central question: 'How much of this pain I carry is still necessary?' It is the moment to accept that the wound no longer needs to be hidden. Vulnerability becomes wisdom. Many people begin or deepen therapeutic or spiritual work during this period." },
        { age: '~22-25 years', title: 'Chiron Square', text: 'First crisis with the wound. May be a period of isolation, shame or difficulty in belonging.' },
        { age: '~37-40 years', title: 'Chiron Opposition', text: 'Direct confrontation with the wound. Often coincides with the midlife crisis and requires facing what was avoided.' },
      ],
    },
    {
      planet: 'Neptune ♆',
      icon: '🌊',
      cycle: 'Square at ~40-42 years and ~82-84 years',
      ages: '~40-42 (first square), ~82-84 (return)',
      title: 'Dissolution and Transcendence',
      description: "Neptune takes 165 years to complete its cycle. Neptune's square (at ~40-42 years) often coincides with the midlife crisis and adds a dimension of illusion dissolution — especially illusions about who we are and what we want.",
      phases: [
        { age: '~40-42 years', title: 'Neptune Square', text: 'Dissolution of illusions built in youth. "The life I imagined is not exactly this." Period of creative disorientation — the old self dissolves before the new one forms.' },
      ],
    },
    {
      planet: 'Pluto ♇',
      icon: '🔥',
      cycle: 'Square at ~36-44 years',
      ages: '~36-44 (first square)',
      title: 'Death and Rebirth',
      description: 'Pluto takes 248 years, so it never returns. But the Plutonian square (at ~36-44 years) is one of the most intense transitions — coinciding with the midlife crisis and demanding symbolic death of ego parts that have become obstacles.',
      phases: [
        { age: '~36-44 years', title: 'Pluto Square', text: 'Psychological death-rebirth process. Power, control, shadow and vulnerability come to the surface. What you held on to with force begins to dissolve. Deeply transformative and potentially frightening — and necessary.' },
      ],
    },
  ],
  integration: {
    title: 'How to Work with Cycles Consciously',
    text: "Knowing your cycles is not about predicting the future — it's about preparing the internal ground. When you know you're entering a Saturnian period, for example, you can create space for review instead of being swept away by it. Cycles are not deterministic: they reveal the quality of time, not its content.",
    tips: [
      'Identify which cycle you are currently in',
      'Ask: what kind of growth does this cycle invite?',
      'Resist the impulse to "escape" the crises of the larger cycles',
      'Use therapy, meditation or journaling as integration tools',
      'Difficult cycles produce the greatest leaps in consciousness when traversed consciously',
    ],
  },
  cta: 'Discover which cycles you are in right now',
  ctaButton: 'See My Transits →',
};
