export const signs = {
  title: 'The 12 Zodiac Signs',
  intro: 'Signs are 12 energy archetypes. Each planet in your chart is in a sign, coloring its expression with specific qualities.',
  list: [
    { symbol: '♈', name: 'Aries', dates: 'Mar 21 – Apr 19', element: 'Fire', mode: 'Cardinal', ruler: '♂ Mars', color: '#cc0000', description: 'First sign — the spark of beginning. Courage, impulse, competitiveness and individuality. Aries breaks through inertia and opens new paths. Shadow: impulsiveness, selfishness, aggression.' },
    { symbol: '♉', name: 'Taurus', dates: 'Apr 20 – May 20', element: 'Earth', mode: 'Fixed', ruler: '♀ Venus', color: '#006600', description: 'Consolidation of what Aries started. Stability, sensory pleasure, loyalty and persistence. Taurus builds solid foundations with patience. Shadow: possessiveness, stubbornness, materialism.' },
    { symbol: '♊', name: 'Gemini', dates: 'May 21 – Jun 20', element: 'Air', mode: 'Mutable', ruler: '☿ Mercury', color: '#0000cc', description: 'The bridge between worlds. Insatiable curiosity, communication, versatility and lightness. Gemini connects information and people. Shadow: superficiality, inconsistency, duality.' },
    { symbol: '♋', name: 'Cancer', dates: 'Jun 21 – Jul 22', element: 'Water', mode: 'Cardinal', ruler: '☽ Moon', color: '#cc6600', description: 'The emotional nest. Protection, memory, belonging and nurturing. Cancer creates roots and cares deeply. Shadow: dependence, emotional manipulation, clinging to the past.' },
    { symbol: '♌', name: 'Leo', dates: 'Jul 23 – Aug 22', element: 'Fire', mode: 'Fixed', ruler: '☉ Sun', color: '#cc0000', description: 'Life\'s stage. Creative expression, personal shine, generosity and leadership. Leo radiates and inspires. Shadow: arrogance, need for applause, drama.' },
    { symbol: '♍', name: 'Virgo', dates: 'Aug 23 – Sep 22', element: 'Earth', mode: 'Mutable', ruler: '☿ Mercury', color: '#006600', description: 'Refinement of experience. Analysis, competence, service and improvement. Virgo separates the essential from the superfluous. Shadow: excessive criticism, perfectionism, anxiety.' },
    { symbol: '♎', name: 'Libra', dates: 'Sep 23 – Oct 22', element: 'Air', mode: 'Cardinal', ruler: '♀ Venus', color: '#0000cc', description: 'The encounter with the other. Balance, justice, diplomacy and partnership. Libra seeks harmony in relationships and aesthetics. Shadow: indecision, dependency on others.' },
    { symbol: '♏', name: 'Scorpio', dates: 'Oct 23 – Nov 21', element: 'Water', mode: 'Fixed', ruler: '♇ Pluto', color: '#cc6600', description: 'The descent to the depths. Intensity, transformation, truth and power. Scorpio doesn\'t fear what is hidden. Shadow: obsession, jealousy, manipulation, revenge.' },
    { symbol: '♐', name: 'Sagittarius', dates: 'Nov 22 – Dec 21', element: 'Fire', mode: 'Mutable', ruler: '♃ Jupiter', color: '#cc0000', description: 'The arrow of meaning. Expansion, philosophy, adventure and faith. Sagittarius seeks significance beyond the horizon. Shadow: excess, fanaticism, irresponsibility.' },
    { symbol: '♑', name: 'Capricorn', dates: 'Dec 22 – Jan 19', element: 'Earth', mode: 'Cardinal', ruler: '♄ Saturn', color: '#006600', description: 'The mountain to climb. Ambition, discipline, maturity and legacy. Capricorn builds with time and persistence. Shadow: coldness, rigidity, pessimism.' },
    { symbol: '♒', name: 'Aquarius', dates: 'Jan 20 – Feb 18', element: 'Air', mode: 'Fixed', ruler: '♅ Uranus', color: '#0000cc', description: 'The quiet revolution. Originality, independence, future vision and humanitarianism. Aquarius questions the status quo. Shadow: emotional distancing, empty rebellion.' },
    { symbol: '♓', name: 'Pisces', dates: 'Feb 19 – Mar 20', element: 'Water', mode: 'Mutable', ruler: '♆ Neptune', color: '#cc6600', description: 'The final ocean. Universal compassion, spirituality, art and ego dissolution. Pisces feels everything and connects to the whole. Shadow: escapism, victimhood, confusion.' },
  ],
};
