// INTERPRETATIONS — Deutsch (de)
import { SUN_IN_HOUSE, MOON_IN_HOUSE, MERCURY_IN_HOUSE } from './pt';
import { VENUS_IN_HOUSE, MARS_IN_HOUSE, NORTH_NODE_HOUSE, NORTH_NODE_IN_SIGN } from '../interpret';
import { JUPITER_IN_HOUSE, SATURN_IN_HOUSE, URANUS_IN_HOUSE, NEPTUNE_IN_HOUSE, PLUTO_IN_HOUSE } from '../outer-planets';
import { CHIRON_IN_HOUSE, CHIRON_IN_SIGN } from '../chiron';
export { SUN_IN_HOUSE, MOON_IN_HOUSE, MERCURY_IN_HOUSE, VENUS_IN_HOUSE, MARS_IN_HOUSE };
export { JUPITER_IN_HOUSE, SATURN_IN_HOUSE, URANUS_IN_HOUSE, NEPTUNE_IN_HOUSE, PLUTO_IN_HOUSE };
export { CHIRON_IN_HOUSE, CHIRON_IN_SIGN, NORTH_NODE_HOUSE, NORTH_NODE_IN_SIGN };

export const SIGN_NAMES = ['Widder','Stier','Zwillinge','Krebs','Löwe','Jungfrau','Waage','Skorpion','Schütze','Steinbock','Wassermann','Fische'];
export const PLANET_NAMES: Record<string,string> = { sun:'Sonne', moon:'Mond', mercury:'Merkur', venus:'Venus', mars:'Mars', jupiter:'Jupiter', saturn:'Saturn', uranus:'Uranus', neptune:'Neptun', pluto:'Pluto', northNode:'Nordknoten', chiron:'Chiron', lilith:'Lilith' };
export const MONTHS = ['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'];
export const SECTION_TITLES = { sun:(h:number,s:string)=>`☉ Sonne im ${h}. Haus in ${s}`, moon:(h:number,s:string)=>`☽ Mond im ${h}. Haus in ${s}`, mercury:(h:number,s:string)=>`☿ Merkur im ${h}. Haus in ${s}`, venus:(h:number,s:string)=>`♀ Venus im ${h}. Haus in ${s}`, mars:(h:number,s:string)=>`♂ Mars im ${h}. Haus in ${s}`, jupiter:(h:number,s:string)=>`♃ Jupiter im ${h}. Haus in ${s}`, saturn:(h:number,s:string)=>`♄ Saturn im ${h}. Haus in ${s}`, uranus:(h:number,s:string)=>`♅ Uranus im ${h}. Haus in ${s}`, neptune:(h:number,s:string)=>`♆ Neptun im ${h}. Haus in ${s}`, pluto:(h:number,s:string)=>`♇ Pluto im ${h}. Haus in ${s}`, northNode:(h:number,s:string)=>`☊ Nordknoten im ${h}. Haus in ${s}`, chiron:(h:number,s:string)=>`⚷ Chiron im ${h}. Haus in ${s}`, ascendant:(s:string)=>`Aszendent in ${s}` };
export const PLANET_SUBTITLES: Record<string,string> = { sun:'Ihre Sonnenessenz — Identität, Zweck und Lebensenergie', moon:'Ihre emotionale Welt — Bedürfnisse, Instinkte und innere Sicherheit', mercury:'Ihr Geist und Kommunikation — wie Sie denken und lernen', venus:'Ihre Liebessprache — was Sie anziehen und wertschätzen', mars:'Ihr Antrieb und Handeln — wie Sie Ziele verfolgen', jupiter:'Ihr Expansionsweg — wo Fülle und Wachstum fließen', saturn:'Ihre Meisterzone — wo Disziplin dauerhafte Erfolge schmiedet', uranus:'Ihre innere Revolution — wo Sie Muster brechen', neptune:'Ihr spirituelles Portal — wo Sie Grenzen auflösen', pluto:'Ihre transformative Kraft — Tod und Wiedergeburt', northNode:'Ihr evolutionärer Zweck — die Richtung Ihrer Seele', chiron:'Ihre heilige Wunde — Schmerz der zum Heilungsgeschenk wird' };
export const LABELS = { reportTitle:'Vollständiger Geburtsbericht', reportSubtitle:'Tiefe Deutung', positions:'Planetenpositionen', houses:'Hausspitzen', overview:'Überblick', potentials:'Ihre 5 größten Potenziale', challenges:'Ihre 5 wichtigsten Herausforderungen', conclusion:'Schlussfolgerung', advice:'Praktischer Rat', elements:'Elemente und Modalitäten', dignities:'Wesentliche Würden', aspects:'Hauptaspekte', themes:'Thematische Synthese', quote:'"Die Sterne neigen, sie bestimmen nicht."', sampleNote:'Dies war eine kostenlose Vorschau!', sampleFull:'Der vollständige Bericht enthält 20-30 Seiten mit detaillierter Deutung.', buyNow:'Vollversion:', buyInstant:'Jetzt kaufen und sofort herunterladen — 100% im Browser.', natalChart:'Ihr Geburtshoroskop', retrograde:'(rückläufig)', annualTitle:'Jahresvorschau', annualSubtitle:'Transite und Tendenzen', profection:'Jahresprofektion — Thema des Jahres', houseInFocus:'im Fokus', rulerOfYear:'Herrscher des Jahres', eclipses:'Finsternisse des Jahres', jupiterExpansion:'Die Expansion des Jahres', saturnLesson:'Die Lektion des Jahres', conclusionAnnual:'Schlussfolgerung — Ihr Jahr in Perspektive', relationshipTitle:'Beziehungsbericht', compatibility:'Kompatibilität', emotionalConnection:'Emotionale Verbindung', attractionChemistry:'Anziehung und Chemie', communication:'Kommunikation', commitmentLimits:'Engagement und Grenzen — Saturn', growthPotential:'Wachstumspotenzial', challengesTension:'Spannungspunkte', psychTitle:'Tiefenpsychologische Analyse', egoStructure:'Ego-Struktur — Sonne und Aszendent', emotionalWorld:'Emotionale Welt — Mond', mentalProcesses:'Mentale Prozesse — Merkur', lovePatterns:'Liebesmuster — Venus', vitalForce:'Lebenskraft — Mars', shadow:'Schatten — Pluto', wound:'Kernwunde — Chiron', unconscious:'Unbewusstes — 12. Haus und Neptun', familyPatterns:'Familienmuster — Mond, 4. Haus und Saturn', defenseMechanisms:'Abwehrmechanismen — Saturn', integrationPath:'Integrationsweg — Nordknoten', careerTitle:'Karriere und Berufung', midheaven:'Medium Coeli', house10:'10. Haus — Berufung', house6:'6. Haus — Alltag und Arbeit', house2:'2. Haus — Ressourcen und Talente', sinsTitle:'Die Sieben Sünden', pride:'Stolz — Sonne', lust:'Wollust — Venus und Mars', greed:'Habgier — Saturn', gluttony:'Völlerei — Jupiter', wrath:'Zorn — Mars', envy:'Neid — Pluto', sloth:'Trägheit — Neptun', repetitivePatterns:'Wiederholungsmuster — Quadrate und Oppositionen', unexploredPotentials:'Unerforschte Potenziale — Trigone und Talente', integrationPaths:'Integrationswege', recommendedPractices:'Empfohlene Praktiken', childhoodTemplate:'Kindheit und emotionale Prägung', fromWoundToGift:'Von der Wunde zum Geschenk', differentiation:'Differenzierung — Sie selbst sein', mainTensions:'Hauptspannungen der Karte', plutoAspects:'Spannungsaspekte des Pluto' };
export const TRANSITIONS = { afterOverview:'Diese Identitätsbasis manifestiert sich konkret in den Planeten in ihren Häusern.', afterPersonalPlanets:'Die Aspekte zwischen Planeten zeigen, wie diese Energien miteinander kommunizieren.', afterAspects:'Aus diesen Wechselwirkungen entstehen Muster — zentrale Themen Ihrer Erfahrung.', beforeConclusion:'Alles zusammengenommen erzählt Ihre Karte eine kohärente Geschichte.' };
