// ============================================================
// INTERPRETATIONS — Deutsch (de)
// Vollständige interpretative Texte auf Deutsch
// ============================================================

// ============================================================
// SONNE IM HAUS
// ============================================================
export const SUN_IN_HOUSE: string[] = [
  /* House 1  */ 'Ihre persönliche Ausstrahlung lebt in der Art, wie Sie sich der Welt präsentieren. Sie sind hier, um gesehen zu werden, um Ihre Präsenz spürbar zu machen. Das 1. Haus bittet Sie, Ihre Individualität zu ehren — wenn Sie sich erlauben, wirklich Sie selbst zu sein, ohne Masken, fließt alles. Ihre Herausforderung besteht darin, zu lernen, nicht von der Zustimmung anderer abhängig zu sein, um zu strahlen.',
  /* House 2  */ 'Ihre Identität ist tief mit dem verbunden, was Sie aufbauen und was Sie wertschätzen. Sie strahlen, wenn Sie Ihre Talente entwickeln und sie in etwas Greifbares verwandeln. Materielle Sicherheit ist für Sie keine Eitelkeit — sie ist Ausdruck Ihres Wertes. Die Herausforderung besteht darin, sich nicht ausschließlich über Besitz zu definieren.',
  /* House 3  */ 'Sie wurden geboren, um zu kommunizieren, zu lehren, Ideen zu verbinden. Ihre Ausstrahlung lebt in Leichtigkeit, Neugier und der Fähigkeit, Komplexes zugänglich zu machen. Wenn Sie irgendwo arbeiten, wo Sie Ihre Meinung nicht äußern oder kreativ sein können, wird immer etwas fehlen. Wenn Sie diese kommunikative Qualität ehren, folgt Fülle.',
  /* House 4  */ 'Ihre Identität wurzelt in Familie, Zuhause und Ihren emotionalen Grundlagen. Sie strahlen, wenn Sie einen sicheren Raum schaffen — für sich selbst und für andere. Sie sind vielleicht die Person, die eine Familie oder Gemeinschaft emotional trägt. Die Herausforderung besteht darin, sich nicht in den Bedürfnissen anderer zu verlieren.',
  /* House 5  */ 'Sie wurden geboren, um zu erschaffen, sich auszudrücken, zu strahlen! Das 5. Haus ist die natürliche Bühne der Sonne. Kreativität, Romantik, Kinder, Spiel — all das energetisiert Sie. Wenn Sie sich erlauben, spielerisch und authentisch zu sein, strahlen Sie. Die Herausforderung ist, nicht ständig nach Bestätigung zu suchen oder Ego mit Essenz zu verwechseln.',
  /* House 6  */ 'Ihre Identität drückt sich durch Dienst, Routine und ständige Verfeinerung aus. Sie strahlen, wenn Sie nützlich sind, wenn Sie Probleme lösen, wenn Sie auf Details achten, die niemand sonst sieht. Gesundheit und Arbeit sind heilige Bereiche für Sie. Die Herausforderung ist, sich nicht im Namen der Produktivität auszulöschen.',
  /* House 7  */ 'Ihre Ausstrahlung zeigt sich in Beziehungen. Sie entdecken sich selbst durch andere — Partner, Geschäftspartner, Vereinbarungen. Das bedeutet nicht Abhängigkeit: Es bedeutet, dass der Spiegel der Beziehung Ihnen hilft zu sehen, wer Sie sind. Die Herausforderung ist, sich nicht im anderen zu verlieren oder Ihre Identität auf Partner zu projizieren.',
  /* House 8  */ 'Ihre Identität bewegt sich durch tiefe Transformationen im Laufe Ihres Lebens. Sie strahlen in Momenten der Krise, wenn alles zusammenzubrechen scheint und Sie wieder aufstehen. Themen der Sexualität, Macht und geteilter Ressourcen sind zentral. Die Herausforderung ist, nicht an Kontrolle zu klammern oder Verletzlichkeit zu fürchten.',
  /* House 9  */ 'Sie wurden geboren, um Horizonte zu erweitern — tiefes Studium, Reisen die Ihre Perspektive verändern, Lebensphilosophien. Ihre Ausstrahlung lebt darin, ein ewiger Schüler zu sein und schließlich ein Lehrer, der Weisheit teilt. Die Herausforderung ist, sich nicht in Theorien ohne praktische Anwendung zu verlieren.',
  /* House 10 */ 'Ihre Identität ist stark mit Ihrer Karriere und Ihrem öffentlichen Image verbunden. Sie sind hier, um etwas in der Welt aufzubauen, um für das anerkannt zu werden, was Sie mit Meisterschaft vollbringen. Das ist keine Eitelkeit — es ist Bestimmung. Die Herausforderung ist, das Privatleben mit dem Druck äußerer Leistung auszubalancieren.',
  /* House 11 */ 'Ihre Ausstrahlung lebt in kollektiven Anliegen, Freundschaften und zukunftsorientierten Projekten. Sie werden von Gruppen energetisiert, von der Arbeit an etwas Größerem als Sie selbst. Innovation und Originalität definieren Sie. Die Herausforderung ist, nicht emotional distanziert von den nächsten Menschen zu werden.',
  /* House 12 */ 'Ihre Identität trägt eine tiefe spirituelle Dimension. Sie strahlen hinter den Kulissen, in kreativer Einsamkeit, in Verbindung mit etwas Größerem. Es kann schwierig sein, sich der Welt zu zeigen, weil Ihre Ausstrahlung subtil und innerlich ist. Die Herausforderung ist, sich nicht selbst zu sabotieren oder vor dem praktischen Leben zu fliehen.',
];

// ============================================================
// MOND IM HAUS
// ============================================================
export const MOON_IN_HOUSE: string[] = [
  /* House 1  */ 'Ihre Emotionen stehen Ihnen ins Gesicht geschrieben — Sie sind transparent, Menschen fühlen, was Sie fühlen. Sie brauchen die Freiheit, emotional zu sein, ohne verurteilt zu werden. Ihr Körper reagiert direkt auf Ihren emotionalen Zustand.',
  /* House 2  */ 'Sie fühlen sich sicher, wenn Sie finanzielle Stabilität haben. Das ist keine Gier — Geld repräsentiert für Sie emotionale Sicherheit. Sie erleben möglicherweise finanzielle Höhen und Tiefen, die Ihre emotionalen Zyklen widerspiegeln.',
  /* House 3  */ 'Sie verarbeiten Emotionen durch Sprechen, Schreiben und geistige Aktivität. Sie brauchen intellektuelle Stimulation, um sich wohlzufühlen. Die Umgebung von Geschwistern und Nachbarschaft hat Ihre Emotionen in der Kindheit geprägt.',
  /* House 4  */ 'Dies ist die natürlichste Platzierung des Mondes. Familie und Zuhause sind Ihnen heilig. Sie brauchen einen physischen Raum, der sich wirklich nach Ihrem anfühlt, um sich aufzuladen. Die Emotionen Ihrer Mutter (oder mütterlichen Figur) haben Sie tief geprägt.',
  /* House 5  */ 'Sie nähren sich emotional, wenn Sie spielen, etwas erschaffen oder sich verlieben. Sie brauchen kreativen Ausdruck als emotionales Ventil. Mit Kindern ist die Verbindung intensiv und tief emotional.',
  /* House 6  */ 'Ihre körperliche Gesundheit wird direkt von Ihrem emotionalen Zustand beeinflusst. Wenn emotional etwas nicht stimmt, signalisiert Ihr Körper es. Sie brauchen eine Routine, die Selbstfürsorge einschließt, um sich zentriert zu fühlen.',
  /* House 7  */ 'Sie fühlen sich emotional vollständig in Beziehungen. Sie brauchen Partnerschaft, um sich sicher zu fühlen — und Sie ziehen Partner an, die Ihre emotionale Landschaft spiegeln (einschließlich ihrer Schatten). Die Herausforderung ist, Ihr emotionales Wohlbefinden nicht auszulagern.',
  /* House 8  */ 'Ihre Emotionen sind intensiv, tief und manchmal überwältigend. Sie fühlen alles mit großer Kraft und können leicht spüren, was andere verbergen. Sich zu öffnen kann schwierig sein, aber wenn Sie jemandem vertrauen, geben Sie ihm Ihre ganze Seele.',
  /* House 9  */ 'Sie nähren sich emotional, wenn Sie lernen, reisen oder neue Perspektiven erkunden. Sie brauchen Raum und Freiheit zum Wachsen. Sie haben möglicherweise Schwierigkeiten mit Routine und konventioneller emotionaler Nähe — Sie bevorzugen philosophische Tiefe.',
  /* House 10 */ 'Ihre Emotionen sind mit Karriere und öffentlicher Anerkennung verbunden. Sie fühlen möglicherweise, dass Sie „jemand sein" müssen, um Liebe zu verdienen. Ihre Beziehung zu Ihrer Mutter wurde möglicherweise durch Leistungserwartungen geprägt.',
  /* House 11 */ 'Sie nähren sich in Freundschaften und kollektiven Anliegen. Sie müssen zu einer Gruppe gehören, die Ihre Ideale teilt. Intimität zu zweit kann herausfordernd sein; Sie bevorzugen breitere, gemeinschaftliche Verbindungen.',
  /* House 12 */ 'Ihre Emotionen haben eine ozeanische Qualität — tief, manchmal diffus, mit fließenden Grenzen. Sie brauchen Einsamkeit, um zu verarbeiten, was Sie fühlen. Sie tragen starke Intuition und Empathie, aber Sie müssen lernen, sich emotional zu schützen.',
];

// ============================================================
// MERKUR IM HAUS
// ============================================================
export const MERCURY_IN_HOUSE: string[] = [
  /* House 1  */ 'Ihr Geist ist schnell und formt die Art, wie die Welt Sie wahrnimmt. Sie denken laut, verarbeiten in Echtzeit, und Menschen erkennen Sie sofort als intelligent und kommunikativ. Ihr nervöses, intuitives Temperament verleiht Ihnen ein natürliches Talent für den Ideenaustausch. Die Herausforderung ist, langsam genug zu werden, um zuzuhören — Ihr Geist bewegt sich so schnell, dass er die Antworten überholen kann, die in sanfterem Tempo ankommen.',
  /* House 2  */ 'Ihre Intelligenz ist Ihr größtes Werkzeug zur Vermögensbildung. Sie verdienen durch den Geist — Schreiben, Journalismus, Handel, Verwaltung, Lehre oder jede Form intellektueller Arbeit. Es gibt einen natürlichen Geschäftsinstinkt. Die Herausforderung ist, nicht alle Intelligenz auf finanziellen Nutzen zu reduzieren — Ihr Geist braucht Freiheit zum Erforschen, nicht nur zum Profitieren.',
  /* House 3  */ 'Die natürliche Platzierung Merkurs — Ihr Geist ist hier zuhause. Sie haben eine außergewöhnliche Leichtigkeit beim Lernen, Kommunizieren und Sich-Ausdrücken. Sie assimilieren Informationen schnell, bewegen sich mit Leichtigkeit zwischen Themen und tragen einen jugendlichen Geist. Die Herausforderung ist die Tiefe: Wenn alles leicht kommt, gibt es wenig Anreiz, wirklich tief zu gehen.',
  /* House 4  */ 'Ihr Geist ist in Familie, Erinnerung und dem intellektuellen Erbe Ihrer Erziehung verwurzelt. Sie sind vielleicht die Person, die Familiengeschichten lebendig hält oder von zu Hause aus arbeitet. Eine intellektuelle Vitalität begleitet Sie durchs Leben. Sie haben eine bemerkenswerte Anpassungsfähigkeit an Veränderungen.',
  /* House 5  */ 'Ihr Geist ist kreativ und spielerisch — Sie drücken Ideen auf unterhaltsame und fesselnde Weise aus. Es gibt ein natürliches Talent für den Unterricht, besonders mit Kindern und Jugendlichen. Sie lieben Wortspiele, Rätsel und mentale Herausforderungen. In Beziehungen intellektualisieren Sie die Liebe. Wenn Geist und Herz sich verbinden, wird Ihre Kommunikation unwiderstehlich.',
  /* House 6  */ 'Ihr Geist ist eine Problemlösungsmaschine — analytisch, präzise und unermüdlich. Sie haben eine starke Kapazität für intellektuelle Arbeit, besonders in administrativen oder organisatorischen Rollen. Die Herausforderung ist nervöse Anspannung: Derselbe Geist, der alles löst, kann sich überlasten, wenn er keine Erholungsmöglichkeiten findet.',
  /* House 7  */ 'Ihr Geist funktioniert am besten im Dialog — Sie brauchen die andere Person zum Denken, Debattieren und Verarbeiten von Ideen. Sie glänzen in Mediation, Verhandlung und jeder Form intellektueller Partnerschaft. Professioneller oder literarischer Erfolg kann durch Zusammenarbeit kommen. Die Herausforderung ist, nicht auf die Reflexion anderer angewiesen zu sein, um Ihre eigenen Ideen zu bestätigen.',
  /* House 8  */ 'Ihr Geist ist forschend — Sie gehen natürlich über die Oberfläche hinaus, angezogen von Mysterien, Tiefenpsychologie, dem Okkulten und allem Verborgenen. Sie lesen zwischen den Zeilen mit beunruhigender Leichtigkeit. Es kann eine Faszination für Tod, Transformation, Erbschaft oder Sexualität geben. Die Herausforderung ist, diese Durchdringungskraft zum Heilen zu nutzen, nicht zum Manipulieren.',
  /* House 9  */ 'Ihr Geist ist philosophisch und expansiv — auf Sinn ausgerichtet, nicht nur auf Fakten. Sie haben eine natürliche Begabung für Fremdsprachen, höhere Bildung und Reisen, die den Horizont erweitern. Die Herausforderung ist, sich nicht in abstrakten Theorien ohne Anwendung zu verlieren — Weisheit muss gelebt werden, nicht nur studiert.',
  /* House 10 */ 'Kommunikation ist Ihr Karrierewerkzeug — Sie stechen professionell durch Intelligenz und Artikulation hervor. Dies ist die Platzierung für den Vermittler, den öffentlichen Kommunikator, den Intellektuellen, der Anerkennung gewinnt. Die Herausforderung ist, den Fokus zu halten: Die Vielseitigkeit kann Energie zerstreuen ohne klare Richtung.',
  /* House 11 */ 'Ihr Geist ist auf die Zukunft ausgerichtet — intellektuelle Projekte, kollektive Anliegen, die Verbreitung von Ideen. Sie kommunizieren außergewöhnlich gut in Gruppen und knüpfen leicht Freundschaften um intellektuellen Austausch. Die Herausforderung ist, sich nicht so in kollektiven Idealen zu verlieren, dass Sie die intimen Verbindungen vernachlässigen.',
  /* House 12 */ 'Ihr Geist ist kontemplativ und intuitiv — Einsichten kommen durch Träume, Meditation und Einsamkeit. Sie haben eine natürliche Begabung für die Arbeit mit dem Unbewussten: Psychologie, introspektives Schreiben, Forschung in verborgenen Dimensionen. Die Herausforderung ist, Ihrer subtilen Wahrnehmung zu vertrauen, ohne sich in Unbestimmtheit zu verlieren.',
];

// ============================================================
// VENUS IM HAUS
// ============================================================
export const VENUS_IN_HOUSE: string[] = [
  /* House 1  */ 'Sie strahlen natürlich Charme aus — es gibt eine angenehme, harmonische Präsenz, die Menschen anzieht, bevor Sie überhaupt sprechen. Zärtlichkeit, emotionale Tiefe und Sensibilität sind Ihre Markenzeichen. Gewinne und Wohlbefinden können durch Aktivitäten fließen, die mit Kunst, Mode, Schönheit und Ästhetik verbunden sind. Die Herausforderung ist, sich nicht ausschließlich auf Schönheit oder das Gefallen anderer als primäre Existenzweise zu verlassen.',
  /* House 2  */ 'Sie lieben materiellen Komfort und schöne Dinge — und das ist keine Eitelkeit, es ist sensorische Intelligenz. Sie haben ein natürliches Auge für Qualität und bleibenden Wert. Es gibt eine Leichtigkeit, durch Nahestehende oder durch Aktivitäten mit Ästhetik und Genuss zu gewinnen. Die Herausforderung ist, Liebe nicht mit finanzieller Sicherheit zu verwechseln.',
  /* House 3  */ 'Ihre Kommunikation ist verführerisch und angenehm — Ihre Worte tragen einen entwaffnenden Charme. Sie pflegen natürlich Harmonie mit Geschwistern und Nachbarn. Freundschaft ist etwas, ohne das Sie nicht leben können. Die Herausforderung ist, Charme nicht mit Tiefe zu verwechseln.',
  /* House 4  */ 'Ihre Liebe drückt sich darin aus, schöne, einladende Zuhause zu schaffen — Räume, die jeden nähren, der sie betritt. Es gibt eine tiefe Harmonie zwischen Ihnen und Ihren Eltern, oder zumindest eine tiefe Sehnsucht danach. In reifen Jahren erblüht die Liebe mit erneuter Intensität. Die Herausforderung ist, nicht so am häuslichen Komfort zu hängen, dass Sie Ihren Sinn für Abenteuer verlieren.',
  /* House 5  */ 'Eine kraftvolle Platzierung für Venus — romantische Liebe, die intensiv, genussvoll und lebendig ist. Große kreative Kapazität in Kunst, Musik und Theater. Glück in sozialen Beziehungen. Kinder bringen tiefe Zufriedenheit. Die Herausforderung ist, Liebe nicht zur Aufführung zu machen — manchmal ist die echteste Zuneigung still.',
  /* House 6  */ 'Sie drücken Liebe durch praktische Fürsorge aus — Sie lernen die Gewohnheiten des anderen, bereiten vor, was benötigt wird, bevor es verlangt wird. Liebe kann am Arbeitsplatz entstehen. Sie schätzen angenehme Routinen und ästhetisch harmonische Umgebungen. Die Herausforderung ist, Liebe nicht auf Dienst zu reduzieren — Sie verdienen es, umsorgt zu werden.',
  /* House 7  */ 'Die natürliche Platzierung der Venus — Partnerschaft ist Ihre Kunst. Sie ziehen Beziehungen mit Leichtigkeit an und haben ein natürliches Talent, Harmonie zu zweit zu schaffen. Eine Ehe ohne ernste Krisen ist möglich, wenn gegenseitiger Respekt und Schönheit in der Interaktion herrschen. Die Herausforderung ist, sich nicht auszulöschen, um den Frieden zu wahren.',
  /* House 8  */ 'Ihre Liebe ist intensiv und transformativ — Ihre Beziehungen gehen tief, bewegen die Seele und beinhalten Themen von Macht, Verletzlichkeit und Sexualität. Die Herausforderung ist, Liebe nicht als Kontrollmittel zu nutzen oder Intensität mit Tiefe der Bindung zu verwechseln.',
  /* House 9  */ 'Liebe und Abenteuer verflechten sich — Sie können sich in Ausländer, andere Kulturen oder Menschen mit expansiven Lebensphilosophien verlieben. Genussreisen. Ein hohes künstlerisches Ideal. Die Herausforderung ist, das „Ferne" nicht so sehr zu idealisieren, dass alltägliche, nahe Liebe unzureichend erscheint.',
  /* House 10 */ 'Beziehungen verbunden mit Karriere — großes Glück und Anerkennung für jene in künstlerischen Berufen oder in Bereichen, die Schönheit und persönlichen Charme schätzen. Die Herausforderung ist, wahre Liebe von der Liebe zum Status zu trennen — und sich erlauben, für das geliebt zu werden, was man ist.',
  /* House 11 */ 'Liebe entsteht aus Freundschaft — Ihre dauerhaftesten Romanzen beginnen als intellektuelle und soziale Verbindung. Charme und magnetische Anziehung in Gruppensettings. Sie schätzen Freiheit in Beziehungen und Verbindung mit aufgeschlossenen Menschen. Die Herausforderung ist, wahre Intimität nicht zu vermeiden, indem man sich hinter Geselligkeit versteckt.',
  /* House 12 */ 'Geheime, spirituelle oder platonische Liebe — es gibt eine transzendente Qualität in Ihrer Art zu lieben, die nicht immer im konkreten Ausdruck findet. Geheime Beziehungen sind möglich, ebenso wie Lieben, die sich über die Zeit tief transformieren. Venus hier lindert Herzschmerz durch Kunst und Kontemplation. Die Herausforderung ist, diese Liebe an die Oberfläche zu bringen.',
];

// ============================================================
// MARS IM HAUS
// ============================================================
export const MARS_IN_HOUSE: string[] = [
  /* House 1  */ 'Kampfgeist und Enthusiasmus definieren Ihre Präsenz — Sie strahlen Energie, Durchsetzungskraft und Handlungsbereitschaft aus, die Menschen sofort spüren. Sie haben eine natürliche Eignung für Aktivitäten, die Führung, Initiative oder Wettbewerb erfordern. Sie gehen ohne Zögern auf das zu, was Sie wollen. Die Herausforderung ist, Ihre Intensität zu modulieren — das ist Ihre Reifungsarbeit.',
  /* House 2  */ 'Ihre Energie und Entschlossenheit werden in den Aufbau von Ressourcen kanalisiert — Sie kämpfen aktiv für das, was Ihnen gehört, mit der Bereitschaft, hart für materielle Sicherheit zu arbeiten. Die Herausforderung ist eine Tendenz zum Übermäßigen — dieselbe Energie, die erobert, kann sich ohne Finanzstrategie verflüchtigen.',
  /* House 3  */ 'Ihre Kommunikation ist direkt, durchsetzungsfähig und manchmal schneidend — Ihr Geist ist kämpferisch, kritisch und kompromisslos bei der Verteidigung einer Idee. Es kann Reibungen mit Geschwistern geben. Die Herausforderung ist, das Schwert der Worte in ein Werkzeug zu verwandeln — dieselbe Sprache, die verwundet, kann auch mobilisieren und inspirieren.',
  /* House 4  */ 'Ihre Energie ist tief mit Zuhause und Wurzeln verbunden — Sie sind möglicherweise in einem intensiven häuslichen Umfeld aufgewachsen. Sie arbeiten hart für den Komfort Ihrer Familie und verteidigen Ihren Raum mit Wildheit. Die Herausforderung ist, die empfangene Intensität nicht zu reproduzieren — ein Zuhause zu bauen, das Zuflucht ist, nicht Schlachtfeld.',
  /* House 5  */ 'Kreative, wettbewerbsfähige und leidenschaftliche Energie — Sie zeichnen sich in Sport, Kunst oder jeder Ausdrucksform aus, die Mut und Präsenz verlangt. Liebe durch Überwindung von Hindernissen oder mit Kühnheit ergriffen. Die Herausforderung ist, Leidenschaft nicht mit Besitz zu verwechseln — kreatives Feuer ist am schönsten, wenn es leuchtet, ohne zu verbrennen.',
  /* House 6  */ 'Ein unermüdlicher Arbeiter — Ihre Energie fließt in Produktivität und praktische Problemlösung. Sie sind für anspruchsvolle Arbeit geeignet, die Mut und Ausdauer erfordert. Robuste Gesundheit, aber mit Veranlagung zu Fieber, Entzündungen und Stress bei unterdrückter Energie. Die Herausforderung ist, produktive Intensität mit Ruhe auszubalancieren.',
  /* House 7  */ 'Ihre Beziehungen sind Arenen für Wachstum — Sie ziehen durchsetzungsfähige, starke und manchmal kämpferische Partner an. Emotionale Zusammenstöße und Machtkämpfe in Beziehungen sind möglich. Die Herausforderung ist, Wettbewerb zu zweit in Zusammenarbeit zu verwandeln — der andere ist kein Gegner, sondern ein Spiegel.',
  /* House 8  */ 'Eine Platzierung intensiver Macht — starker Überlebensinstinkt, die Fähigkeit, aus der Asche aufzuerstehen, Sexualität als transformierende Lebenskraft. Die Herausforderung ist, diese immense Kraft zur bewussten Transformation zu nutzen — nicht zur Zerstörung oder Selbstzerstörung.',
  /* House 9  */ 'Vollständige Hingabe an eine Sache — Sie verteidigen Ihre Überzeugungen mit absoluter Leidenschaft und machen keine Zugeständnisse bei Wahrheit und Gerechtigkeit. Die Herausforderung ist der Fanatismus: Dieselbe Leidenschaft, die Sie antreibt, kann Sie blenden, wenn sie nicht durch intellektuelle Demut gemäßigt wird.',
  /* House 10 */ 'Mächtiger beruflicher Ehrgeiz — Sie nutzen wilde Entschlossenheit, um sich in Karriere und öffentlichem Leben zu etablieren. Sie gedeihen angesichts von Herausforderungen. Eine Eignung für Führung in jedem Bereich, der Mut und Entschlusskraft erfordert. Die Herausforderung ist, auf dem Weg nach oben keine unnötigen Feinde zu schaffen.',
  /* House 11 */ 'Enthusiasmus und Führung in Gruppen und kollektiven Anliegen — Sie sind der Freund, der mobilisiert, der zum Handeln antreibt, der Passivität ablehnt. Die Herausforderung ist, auch anderen zu erlauben zu führen — eine kollektive Sache braucht keinen General, sie braucht einen Katalysator.',
  /* House 12 */ 'Subtile und introspektive Energie — Sie handeln hinter den Kulissen, im Verborgenen oder auf Weisen, die nicht immer sichtbar sind. Es kann unterdrückte Wut geben, die in bewusste Praktiken kanalisiert werden muss. Die Herausforderung ist, diese Energie nicht gegen sich selbst zu richten — Mars im 12. Haus braucht Ausdruckskanäle, sonst wird es Selbstzerstörung.',
];

// ============================================================
// JUPITER IM HAUS
// ============================================================
export const JUPITER_IN_HOUSE: string[] = [
  /* House 1  */ 'Jupiter im 1. Haus bringt natürlichen Optimismus, magnetische Präsenz und die Tendenz, Gelegenheiten anzuziehen. Sie projizieren Vertrauen und Großzügigkeit. Achten Sie auf Übermaß — Sie können mehr versprechen als liefern.',
  /* House 2  */ 'Jupiter im 2. Haus zeigt eine Leichtigkeit beim Anziehen von Ressourcen und beim Aufbau von Wohlstand. Sie haben eine großzügige Beziehung zum Geld — es kommt leicht, kann aber ebenso leicht wieder gehen. Ihre Werte sind expansiv und offen.',
  /* House 3  */ 'Jupiter im 3. Haus erweitert den Geist und die Kommunikation. Leichtigkeit mit Sprachen, Schreiben und Lehren. Sie sind der ewige Schüler, der Wissen gerne teilt. Eine positive Beziehung zu Geschwistern oder Nachbarn ist möglich.',
  /* House 4  */ 'Jupiter im 4. Haus zeigt ein großzügiges Zuhause, eine unterstützende Familie oder Expansion im häuslichen Leben. Sie sind möglicherweise in emotionaler Fülle aufgewachsen. Solide Wurzeln und Vertrauen in die familiäre Grundlage.',
  /* House 5  */ 'Jupiter im 5. Haus ist eine Platzierung der Freude: reiche Kreativität, Glück in der Liebe und Großzügigkeit mit Kindern. Sie brauchen Raum zum Spielen, Erschaffen und Sich-Ausdrücken.',
  /* House 6  */ 'Jupiter im 6. Haus bringt Enthusiasmus in die tägliche Arbeit und allgemein gute Gesundheit. Sie finden Sinn in der Routine, wenn sie einen Zweck hat. Sie können in Bildung, Gesundheit oder Anliegen arbeiten, die das kollektive Wohlbefinden erweitern.',
  /* House 7  */ 'Jupiter im 7. Haus zieht großzügige, optimistische Partner oder solche aus verschiedenen kulturellen Hintergründen an. Beziehungen sind eine Wachstumsquelle. Achten Sie auf unrealistische Erwartungen an Partner.',
  /* House 8  */ 'Jupiter im 8. Haus zeigt Schutz in Krisen und Leichtigkeit mit geteilten Ressourcen. Sie wachsen durch tiefe Transformationen. Erbschaft oder Glück bei Investitionen sind möglich.',
  /* House 9  */ 'Jupiter im 9. Haus ist in seiner natürlichen Heimat — maximale philosophische Expansion, transformative Reisen, tiefe höhere Bildung. Sie sind von Natur aus weise, optimistisch und immer auf der Suche nach Sinn.',
  /* House 10 */ 'Jupiter im 10. Haus bringt berufliche Anerkennung, Karriereexpansion und ein positives öffentliches Image. Eine Karriere, die von einem Sinn für Mission geprägt ist.',
  /* House 11 */ 'Jupiter im 11. Haus erweitert Ihr soziales Netzwerk und Ihre Zukunftsträume. Sie ziehen großzügige Freunde an und profitieren von Gruppen. Soziale Anliegen und kollaborative Projekte sind Quellen der Fülle.',
  /* House 12 */ 'Jupiter im 12. Haus ist ein verborgener Schutzengel. Spiritueller Schutz, tiefer Glaube, erweiterte Intuition. Sie profitieren von Retreats, Spiritualität und Arbeit hinter den Kulissen. Ihre Großzügigkeit kann still oder anonym sein.',
];

// ============================================================
// SATURN IM HAUS
// ============================================================
export const SATURN_IN_HOUSE: string[] = [
  /* House 1  */ 'Saturn im 1. Haus bringt von früh an Ernst. Sie wirkten möglicherweise älter als Ihr Alter oder trugen früh Verantwortung. Mit Reife verwandelt sich dies in natürliche Autorität und eine gebietende, respektierte Präsenz.',
  /* House 2  */ 'Saturn im 2. Haus zeigt anfängliche Herausforderungen mit Geld oder Selbstwert, aber auch die Fähigkeit, durch Disziplin echte Sicherheit aufzubauen. Sie schätzen, was Sie durch Anstrengung verdienen — nichts kommt leicht, aber was kommt, bleibt.',
  /* House 3  */ 'Saturn im 3. Haus kann frühe Schwierigkeiten mit Kommunikation, Lernen oder Beziehungen zu Geschwistern bringen. Mit der Zeit entwickeln Sie einen strukturierten Geist, präzises Schreiben und Kommunikation, die Autorität trägt.',
  /* House 4  */ 'Saturn im 4. Haus zeigt oft eine durch Einschränkung geprägte Kindheit, frühe familiäre Verantwortung oder eine abwesende oder strenge Elternfigur. Die Mission ist, im Erwachsenenleben eigene solide emotionale Grundlagen aufzubauen.',
  /* House 5  */ 'Saturn im 5. Haus kann kreativen Ausdruck oder Freude im frühen Leben blockieren. Kinder können später kommen oder bedeutende Verantwortung bringen. Mit Reife entwickeln Sie disziplinierte, dauerhafte Kreativität.',
  /* House 6  */ 'Saturn im 6. Haus verlangt Hingabe an die Arbeit und ständige Aufmerksamkeit für die Gesundheit. Die Lektion ist, nachhaltige Routinen aufzubauen und sich nicht allein über Produktivität zu definieren.',
  /* House 7  */ 'Saturn im 7. Haus bringt Ernst in Beziehungen. Es kann eine Verzögerung beim Finden eines Partners geben oder Ehen mit älteren oder reiferen Personen. Die Lektion ist echtes Engagement — frei gewählt, nicht aus Pflicht eingegangen.',
  /* House 8  */ 'Saturn im 8. Haus zeigt eine Angst vor Kontrollverlust, Schwierigkeiten mit tiefer Intimität oder Herausforderungen rund um Erbschaft und geteilte Ressourcen. Die Lektion ist, Vertrauen zu lernen und sich ohne Widerstand zu transformieren.',
  /* House 9  */ 'Saturn im 9. Haus kann Reisen oder formale Bildung früh im Leben einschränken. Mit Reife werden Sie zur Autorität in Ihrem Studiengebiet. Ihre Überzeugungen werden durch Strenge aufgebaut, nicht durch blinden Glauben.',
  /* House 10 */ 'Saturn im 10. Haus ist eine der ehrgeizigsten Platzierungen — Sie sind hier, um ein Vermächtnis aufzubauen. Karriere ist eine ernste, zentrale Angelegenheit. Der Fortschritt mag anfangs langsam sein, aber der Erfolg, der kommt, ist solide und dauerhaft.',
  /* House 11 */ 'Saturn im 11. Haus kann wenige aber treue Freunde bringen oder eine anfängliche Schwierigkeit, sich in Gruppen einzufügen. Die Mission ist, ein echtes Unterstützungsnetzwerk aufzubauen und für Anliegen zu arbeiten, die langfristiges Engagement erfordern.',
  /* House 12 */ 'Saturn im 12. Haus kann verborgene Ängste, Isolation oder unsichtbare Verantwortungen anzeigen. Die Lektion ist, innere Geister zu konfrontieren und zu entdecken, dass Struktur auch innerhalb von Spiritualität und dem Unbewussten existieren kann.',
];

// ============================================================
// URANUS IM HAUS
// ============================================================
export const URANUS_IN_HOUSE: string[] = [
  /* House 1  */ 'Uranus im 1. Haus macht Sie zu jemandem Einzigartigem, Rebellischem und Unvorhersehbarem. Sie weigern sich, in Formen zu passen. Menschen finden Sie vielleicht exzentrisch — und das sind Sie wahrscheinlich, mit Stolz.',
  /* House 2  */ 'Uranus im 2. Haus bringt finanzielle Instabilität, aber auch brillante Einsichten in unkonventionelle Wege des Geldverdienens. Ihre Werte sind progressiv und sich ständig verändernd.',
  /* House 3  */ 'Uranus im 3. Haus gibt Ihnen einen elektrischen Geist — schnelle Gedanken, plötzliche Einsichten, unkonventionelle Kommunikation. Sie haben möglicherweise Schwierigkeiten mit traditionellem Lernen, glänzen aber mit alternativen Methoden.',
  /* House 4  */ 'Uranus im 4. Haus zeigt ein instabiles Zuhause in der Kindheit oder häufige Wohnungswechsel. Sie brauchen Freiheit selbst innerhalb des Zuhauses. Ihre Familie kann unkonventionell sein.',
  /* House 5  */ 'Uranus im 5. Haus bringt radikale Kreativität und unerwartete Romanzen. Sie drücken sich auf originelle Weise aus und haben möglicherweise eine nicht-traditionelle Beziehung zur Elternschaft.',
  /* House 6  */ 'Uranus im 6. Haus kann repetitive Routine nicht tolerieren. Sie brauchen Arbeit mit Autonomie und Raum für Innovation. Gesundheit kann unregelmäßigen Mustern folgen. Alternative Selbstfürsorge-Ansätze funktionieren gut.',
  /* House 7  */ 'Uranus im 7. Haus zieht unkonventionelle Partner und Beziehungen an, die Normen herausfordern. Plötzliche Brüche in Partnerschaften sind möglich. Sie brauchen Freiheit innerhalb der Verbindlichkeit.',
  /* House 8  */ 'Uranus im 8. Haus bringt plötzliche Transformationen und tiefe Einsichten in Macht und Sexualität. Unerwartete finanzielle Veränderungen. Unkonventionelle transzendente Erfahrungen sind möglich.',
  /* House 9  */ 'Uranus im 9. Haus baut sein eigenes Glaubenssystem — akzeptiert keine Dogmen. Unerwartete Reisen, plötzliche philosophische Einsichten. Sie können Ihr Studiengebiet revolutionieren.',
  /* House 10 */ 'Uranus im 10. Haus zeigt eine unkonventionelle Karriere, plötzliche berufliche Veränderungen oder Arbeit in Technologie und Innovation. Starre Hierarchien sind nichts für Sie.',
  /* House 11 */ 'Uranus im 11. Haus ist in seiner natürlichen Heimat — exzentrische Freundschaften, revolutionäre Zukunftsvision, Teilnahme an Gruppen, die Paradigmen verschieben. Sie sind der Visionär des Kollektivs.',
  /* House 12 */ 'Uranus im 12. Haus zeigt plötzliche spirituelle Einsichten, elektrische Intuition und ein mögliches unerwartetes spirituelles Erwachen. Sie spüren möglicherweise Unruhe ohne erkennbare Ursache — es ist das Unbewusste, das nach Freiheit ruft.',
];

// ============================================================
// NEPTUN IM HAUS
// ============================================================
export const NEPTUNE_IN_HOUSE: string[] = [
  /* House 1  */ 'Neptun im 1. Haus macht Sie chamäleonartig, tief empathisch und schwer zu definieren. Menschen projizieren auf Sie, was sie sehen möchten. Sie absorbieren Ihre Umgebung — Grenzen zu halten ist wesentlich.',
  /* House 2  */ 'Neptun im 2. Haus löst die Beziehung zum Geld auf — es kann finanzielle Verwirrung, übermäßige Großzügigkeit oder Schwierigkeiten geben, für Ihre Arbeit Geld zu verlangen. Die Lektion ist, Ihre Gaben ohne Schuldgefühl zu würdigen.',
  /* House 3  */ 'Neptun im 3. Haus gibt poetische Kommunikation, intuitives Denken und eine Leichtigkeit mit symbolischer Sprache. Es kann Verwirrung um konkrete Informationen geben oder Idealisierung von Geschwistern.',
  /* House 4  */ 'Neptun im 4. Haus zeigt ein Zuhause mit nebulöser Atmosphäre — idealisierte oder auf irgendeine Weise abwesende Familie. Es kann Familiengeheimnisse geben. Ihre wahre Zuflucht ist innerlich, spirituell.',
  /* House 5  */ 'Neptun im 5. Haus bringt tiefe künstlerische Kreativität — Musik, Film, Poesie, Tanz. Idealisierte Romanzen, die enttäuschen können. Kreativer Ausdruck ist Ihre Verbindung zum Göttlichen.',
  /* House 6  */ 'Neptun im 6. Haus zeigt Empfindlichkeit gegenüber Arbeitsumgebungen und mögliche schwer zu diagnostizierende Gesundheitszustände. Sie arbeiten am besten in Aktivitäten mit Heilung, Kunst oder Mitgefühl.',
  /* House 7  */ 'Neptun im 7. Haus kann dazu führen, Partner zu idealisieren oder sich in Beziehungen zu verlieren. Die Lektion ist, ohne Illusion zu lieben — den anderen zu sehen, wie er ist, nicht wie Sie ihn sich wünschen. Künstlerische oder spirituelle Partner sind häufig.',
  /* House 8  */ 'Neptun im 8. Haus löst die Grenzen der Intimität auf — transzendente Erfahrungen in der Sexualität, Verwirrung um geteilte Ressourcen. Tiefe Intuition über Leben und Tod.',
  /* House 9  */ 'Neptun im 9. Haus zeigt tiefen Glauben, seelentransformierende Reisen und eine Anziehung zum Mystizismus. Achten Sie auf Gurus oder Glaubenssysteme, die leichte Erlösung versprechen.',
  /* House 10 */ 'Neptun im 10. Haus zeigt eine Karriere in Kunst, Heilung, Spiritualität oder Bereichen, in denen Mitgefühl zentral ist. Ihr öffentliches Image kann schwer zu fassen sein — Menschen wissen nicht immer genau, was Sie tun.',
  /* House 11 */ 'Neptun im 11. Haus idealisiert Freundschaften und soziale Anliegen. Sie können von Gruppen enttäuscht werden oder Freunde anziehen, die Rettung brauchen. Die Mission ist, dem Kollektiv zu dienen, ohne sich selbst zu opfern.',
  /* House 12 */ 'Neptun im 12. Haus ist in seiner natürlichen Heimat — tiefe Spiritualität, ozeanische Intuition, Verbindung mit dem kollektiven Unbewussten. Sie können Heiler, Künstler oder Medium sein. Regelmäßige Einsamkeit ist wesentlich.',
];

// ============================================================
// PLUTO IM HAUS
// ============================================================
export const PLUTO_IN_HOUSE: string[] = [
  /* House 1  */ 'Pluto im 1. Haus gibt Ihnen eine intensive, magnetische Präsenz. Sie erfinden sich im Laufe Ihres Lebens immer wieder neu. Menschen spüren Ihre Energie, bevor Sie sprechen. Sie können einschüchtern, ohne es zu beabsichtigen.',
  /* House 2  */ 'Pluto im 2. Haus zeigt tiefe Transformationen in Bezug auf Geld, Werte und Selbstwert. Sie können alles verlieren und wieder aufbauen. Ihre Beziehung zu Ressourcen ist intensiv — alles oder nichts.',
  /* House 3  */ 'Pluto im 3. Haus gibt einen forschenden Geist und mächtige Worte. Intensive Kommunikation, Überzeugungskraft. Sie haben möglicherweise transformative Erfahrungen mit Geschwistern oder im schulischen Umfeld gemacht.',
  /* House 4  */ 'Pluto im 4. Haus zeigt intensive Familiendynamiken — Geheimnisse, Macht, Transformation an den Wurzeln. Die Kindheit war möglicherweise durch Kontrolle oder Verlust geprägt. Heilung kommt durch die Transformation Ihres Verständnisses von Zuhause.',
  /* House 5  */ 'Pluto im 5. Haus bringt obsessive Kreativität und intensive, fast zwanghafte Romanzen. Die Beziehung zu Kindern kann transformativ sein. Sie erschaffen mit viszeraler Leidenschaft.',
  /* House 6  */ 'Pluto im 6. Haus kann Gesundheitskrisen anzeigen, die zu vollständiger Regeneration führen, oder Arbeit, die Systeme transformiert. Sie haben die Kraft zu heilen — aber Sie müssen zuerst für sich selbst sorgen.',
  /* House 7  */ 'Pluto im 7. Haus zieht intensive, transformative Beziehungen an. Machtdynamiken in Partnerschaften. Die Lektion ist weder den anderen zu kontrollieren noch sich zu unterwerfen — sondern sich gemeinsam zu transformieren.',
  /* House 8  */ 'Pluto im 8. Haus ist in seiner natürlichen Heimat — maximale Intensität in Transformation, Sexualität, Macht und geteilten Ressourcen. Sie wurden in diesem Leben viele Male wiedergeboren. Nichts ist oberflächlich.',
  /* House 9  */ 'Pluto im 9. Haus transformiert Ihre Überzeugungen radikal im Laufe Ihres Lebens. Reisen können Erfahrungen von Tod und Wiedergeburt sein. Sie verfolgen Wahrheit mit Besessenheit — oberflächliche Antworten genügen nie.',
  /* House 10 */ 'Pluto im 10. Haus zeigt Macht in der Karriere — Sie transformieren Ihr berufliches Feld. Sie können Machtkämpfe mit Autorität erleben, bevor Sie selbst zu einer werden. Karriere als Transformation.',
  /* House 11 */ 'Pluto im 11. Haus transformiert die Gruppen, denen Sie angehören. Sie können intensive Freundschaften oder Brüche mit Kollektiven haben. Sie sind ein Agent sozialen Wandels — aber Sie müssen aufpassen, nicht zu manipulieren.',
  /* House 12 */ 'Pluto im 12. Haus zeigt verborgene Macht im Unbewussten. Tiefe Transformationen, die hinter den Kulissen geschehen. Sie erleben möglicherweise intensive Ängste ohne erkennbare Ursache — Rückstände früherer Leben, die um Integration bitten.',
];

// ============================================================
// CHIRON IM HAUS
// ============================================================
export const CHIRON_IN_HOUSE: string[] = [
  /* House 1  */ 'Chiron im 1. Haus zeigt auf eine Wunde rund um Identität und das Recht, so zu existieren, wie Sie sind. Sie sind möglicherweise aufgewachsen mit dem Gefühl, dass etwas an Ihnen „falsch" war. Aber genau diese Sensibilität für Selbsterkenntnis befähigt Sie, anderen zu helfen, sich selbst zu finden. Indem Sie Ihre Einzigartigkeit akzeptieren, werden Sie ein Spiegel der Heilung für die Welt.',
  /* House 2  */ 'Chiron im 2. Haus berührt die Wunde des Selbstwerts und der materiellen Sicherheit. Sie haben möglicherweise früh gelernt, dass Liebe an das geknüpft war, was Sie produzieren oder besitzen. Der Heilungsweg führt durch den Aufbau einer gesunden Beziehung zu Ihren Talenten und Ressourcen — zu erkennen, dass Ihr Wert unabhängig von Besitz existiert.',
  /* House 3  */ 'Chiron im 3. Haus offenbart eine Wunde in der Kommunikation und im intellektuellen Ausdruck. Sie haben möglicherweise gespürt, dass Ihre Worte nicht gehört wurden oder dass Sie „nicht klug genug" waren. Das Geschenk, das entsteht, ist eine einzigartige Sensibilität für Sprache — Sie lernen, mit Tiefe und Sorgfalt zu kommunizieren.',
  /* House 4  */ 'Chiron im 4. Haus zeigt eine Wunde in den Wurzeln — Herkunftsfamilie, Zugehörigkeitsgefühl, emotionale Sicherheit. Sie sind möglicherweise ohne ein emotional stabiles Zuhause aufgewachsen. Der Heilungsprozess beinhaltet, eigene Wurzeln zu schaffen und zu definieren, was „Zuhause" für Sie bedeutet.',
  /* House 5  */ 'Chiron im 5. Haus berührt die Wunde der Kreativität, Authentizität und Freude. Sie haben möglicherweise Botschaften erhalten, dass Ihr kreativer Ausdruck nicht gut genug war oder dass Spaß gefährlich oder verboten war. Das Geschenk ist eine tiefe und mutige Kreativität — indem Sie sich erlauben zu erschaffen und zu genießen, inspirieren Sie andere.',
  /* House 6  */ 'Chiron im 6. Haus offenbart eine Wunde in der Beziehung zu Arbeit, Gesundheit und täglicher Routine. Sie haben möglicherweise gelernt, dass Sie perfekt sein müssen, um Ihren Platz zu verdienen. Der Heilungsweg führt durch das Verständnis, dass Dienst aus Fülle kommen muss, nicht aus Schuldgefühlen.',
  /* House 7  */ 'Chiron im 7. Haus berührt die Wunde in Beziehungen und Partnerschaft. Sie haben möglicherweise Verluste, Zurückweisungen oder schmerzhafte Beziehungsmuster erlebt, die Angst vor Bindung geschaffen haben. Das Geschenk ist ein tiefes Verständnis von Beziehungsdynamiken — indem Sie diese Wunde heilen, werden Sie fähig, authentische Verbindungen zu schaffen.',
  /* House 8  */ 'Chiron im 8. Haus zeigt eine Wunde verbunden mit Verlust, erzwungenen Transformationen, Macht und tiefer Intimität. Sie haben möglicherweise Situationen extremer Verletzlichkeit erlebt. Das Geschenk ist eine ungewöhnliche Kraft der Erneuerung und die einzigartige Fähigkeit, andere durch die schwierigsten Lebenspassagen zu begleiten.',
  /* House 9  */ 'Chiron im 9. Haus berührt die Wunde in Überzeugungen, Spiritualität und der Suche nach Sinn. Sie haben möglicherweise unter starren Dogmen gelitten oder Erfahrungen gemacht, die Ihren Glauben tief erschüttert haben. Der Heilungsweg ist, eine Lebensphilosophie aufzubauen, die wirklich Ihre eigene ist.',
  /* House 10 */ 'Chiron im 10. Haus offenbart eine Wunde in Karriere, Vermächtnis und der Beziehung zu Autorität. Sie hatten möglicherweise Schwierigkeiten mit Elternfiguren, beruflicher Anerkennung oder dem Recht, prominente Positionen einzunehmen. Der Heilungsprozess führt durch die Beanspruchung Ihrer eigenen Autorität ohne externe Bestätigung.',
  /* House 11 */ 'Chiron im 11. Haus berührt die Wunde der kollektiven Zugehörigkeit und Freundschaft. Sie haben möglicherweise Ausgrenzung aus Gruppen gespürt, zu anders um irgendwohin zu gehören. Das Geschenk ist die Fähigkeit, wahrhaft inklusive Gemeinschaften aufzubauen und den Wert in jenen zu erkennen, die sich am Rand fühlen.',
  /* House 12 */ 'Chiron im 12. Haus zeigt eine tiefe spirituelle Wunde verbunden mit Isolation, Unsichtbarkeit und unausgedrücktem Schmerz. Sie haben möglicherweise Wunden in Einsamkeit getragen. Das Geschenk, das aus dieser Tiefe entsteht, ist eine außergewöhnliche Fähigkeit zu Mitgefühl, tiefem Zuhören und stiller Heilung — Sie berühren die Seelen der Menschen ohne Worte.',
];

// ============================================================
// CHIRON IM ZEICHEN
// ============================================================
export const CHIRON_IN_SIGN: string[] = [
  /* Aries       */ 'Mit Chiron im Widder hat die Wunde eine aktive, identitätszentrierte Qualität — sie betrifft das Recht zu handeln, mit Stärke zu existieren und voranzugehen. Der Heilungsweg führt durch die Wiedererlangung des Mutes, ohne Erlaubnis zu fragen.',
  /* Taurus      */ 'Mit Chiron im Stier berührt die Wunde den inneren Wert und die körperliche Sicherheit. Sie beinhaltet den Glauben, Vergnügen und Komfort verdienen zu müssen. Heilung kommt durch das friedliche Bewohnen des eigenen Körpers und das Vertrauen, dass Sie genug sind.',
  /* Gemini      */ 'Mit Chiron in den Zwillingen hat die Wunde eine kommunikative und intellektuelle Qualität — sie betrifft Zweifel an der eigenen Intelligenz oder dem Recht, gehört zu werden. Heilung kommt durch Vertrauen in die eigene Stimme und die Einzigartigkeit des eigenen Denkens.',
  /* Cancer      */ 'Mit Chiron im Krebs berührt die Wunde die emotionale und familiäre Welt. Sie betrifft Fragen der Zugehörigkeit, Nahrung und emotionalen Sicherheit. Heilung kommt durch das Lernen, sich selbst mit derselben Großzügigkeit zu nähren, die Sie anderen bieten.',
  /* Leo         */ 'Mit Chiron im Löwen hat die Wunde eine expressive und kreative Qualität — sie betrifft das Recht zu strahlen, gesehen zu werden und sich ohne Urteil auszudrücken. Heilung kommt durch die Wiedererlangung der Freude am authentischen Selbstausdruck.',
  /* Virgo       */ 'Mit Chiron in der Jungfrau berührt die Wunde Perfektion, Nützlichkeit und Gesundheit. Sie kann das Gefühl beinhalten, nie gut genug zu sein. Heilung kommt durch das Umarmen von Unvollkommenheit als Teil der Ganzheit.',
  /* Libra       */ 'Mit Chiron in der Waage hat die Wunde eine relationale Qualität — sie betrifft Gleichgewicht, Fairness und das Recht, in Beziehungen Bedürfnisse zu haben. Heilung kommt durch das Lernen, dass wahre Harmonie die eigene Stimme einschließt.',
  /* Scorpio     */ 'Mit Chiron im Skorpion berührt die Wunde Transformation, Macht und Intimität. Sie beinhaltet tiefe Ängste vor Verlust, Verrat oder Verletzlichkeit. Heilung kommt durch das Umarmen emotionaler Tiefe als Geschenk, nicht als Last.',
  /* Sagittarius */ 'Mit Chiron im Schützen hat die Wunde eine philosophische und spirituelle Qualität. Sie kann Glaubensverlust, Konflikte oder das Gefühl beinhalten, dass Wahrheit unerreichbar ist. Heilung kommt durch den Aufbau eigener Weisheit, gegründet auf gelebter Erfahrung.',
  /* Capricorn   */ 'Mit Chiron im Steinbock berührt die Wunde Ehrgeiz, Verantwortung und die Beziehung zu Autorität. Sie kann übermäßigen Leistungsdruck oder den Glauben beinhalten, leiden zu müssen, um zu erreichen. Heilung kommt durch die Neudefinition von Erfolg nach eigenen Maßstäben.',
  /* Aquarius    */ 'Mit Chiron im Wassermann hat die Wunde eine kollektive Qualität — sie beinhaltet das Gefühl, zu anders zu sein, nirgendwohin zu gehören. Heilung kommt durch die Transformation dieser Einzigartigkeit in ein Geschenk und die Nutzung Ihrer Zukunftsvision, um Wandel zu inspirieren.',
  /* Pisces      */ 'Mit Chiron in den Fischen berührt die Wunde Auflösung, Spiritualität und die Grenzen des Egos. Sie kann ein Gefühl beinhalten, sich in anderen oder im kollektiven Leid zu verlieren. Heilung kommt durch das Lernen von Mitgefühl mit Grenzen — der Welt zu dienen, ohne sich darin zu verlieren.',
];

// ============================================================
// NORDKNOTEN IM HAUS
// ============================================================
export const NORTH_NODE_HOUSE: string[] = [
  /* House 1  */ 'Nordknoten im 1. Haus: Sie haben das „Wir" bereits gemeistert (Partnerschaft, Diplomatie) und sind gekommen, Unabhängigkeit zu lernen — sich selbst ohne Schuldgefühle an erste Stelle zu setzen. Ihre Mission ist die Entwicklung Ihrer eigenen Identität.',
  /* House 2  */ 'Nordknoten im 2. Haus: Sie haben Transformation und fremde Ressourcen bereits gemeistert. Jetzt sind Sie gekommen zu lernen, eigene Sicherheit und eigene Werte aufzubauen. Selbstgenügsamkeit ist der Weg.',
  /* House 3  */ 'Nordknoten im 3. Haus: Sie tragen bereits die Weisheit tiefen Studiums und sind gekommen zu lernen, mit Leichtigkeit zu kommunizieren, zugänglich zu lehren und mehr zuzuhören als zu predigen.',
  /* House 4  */ 'Nordknoten im 4. Haus: Sie haben das öffentliche Leben und die Karriere bereits gemeistert. Jetzt sind Sie gekommen zu lernen, Ihre emotionalen Grundlagen zu nähren, für Familie zu sorgen und echte Wurzeln zu schaffen.',
  /* House 5  */ 'Nordknoten im 5. Haus: Sie gehören bereits zu Gruppen und kollektiven Anliegen. Jetzt sind Sie gekommen zu lernen, individuell zu strahlen, zu erschaffen, ohne Schuldgefühle zu spielen. Persönlicher Ausdruck ist der Weg.',
  /* House 6  */ 'Nordknoten im 6. Haus: Sie haben die spirituelle Welt und Einsamkeit bereits gemeistert. Jetzt sind Sie gekommen zu lernen, im Alltag zu dienen, die praktische Realität zu organisieren und für den Körper zu sorgen.',
  /* House 7  */ 'Nordknoten im 7. Haus: Sie sind bereits unabhängig und selbstgenügsam. Jetzt sind Sie gekommen zu lernen, Raum für den anderen zu öffnen — zu verhandeln, echte Partnerschaften aufzubauen.',
  /* House 8  */ 'Nordknoten im 8. Haus: Sie haben materiellen Komfort und Stabilität bereits gemeistert. Jetzt sind Sie gekommen zu lernen, sich zu transformieren, sich hinzugeben, Macht und Verletzlichkeit zu navigieren.',
  /* House 9  */ 'Nordknoten im 9. Haus: Sie haben Kommunikation und oberflächliches Wissen bereits gemeistert. Jetzt sind Sie gekommen zu lernen, tiefer zu gehen, Horizonte zu erweitern und Ihre eigene Lebensphilosophie zu entwickeln.',
  /* House 10 */ 'Nordknoten im 10. Haus: Sie haben Zuhause und Emotionen bereits gemeistert. Jetzt sind Sie gekommen zu lernen, etwas in der Welt aufzubauen, öffentliche Verantwortung zu übernehmen und ein Vermächtnis zu hinterlassen.',
  /* House 11 */ 'Nordknoten im 11. Haus: Sie strahlen bereits individuell. Jetzt sind Sie gekommen zu lernen, für größere Anliegen zu arbeiten, sich in Gruppen zu integrieren und kollektiv zu denken.',
  /* House 12 */ 'Nordknoten im 12. Haus: Sie haben Organisation und praktischen Dienst bereits gemeistert. Jetzt sind Sie gekommen zu lernen, Kontrolle loszulassen, Ihrer Intuition zu vertrauen und sich mit etwas Transzendentem zu verbinden.',
];

// ============================================================
// NORDKNOTEN IM ZEICHEN
// ============================================================
export const NORTH_NODE_IN_SIGN: string[] = [
  /* Aries       */ 'Nordknoten im Widder: Ihre evolutionäre Reise ist es, Selbstführung, Mut und das Recht auf eigenständiges Handeln zu entwickeln. Sie kommen aus Lebensmustern der Abhängigkeit, übermäßiger Diplomatie und Suche nach Zustimmung. Befreiung kommt, wenn Sie handeln, ohne auf Konsens zu warten — wenn Sie das Risiko eingehen, im Namen der Authentizität unpopulär zu sein.',
  /* Taurus      */ 'Nordknoten im Stier: Ihre Reise ist es, eigene Sicherheit aufzubauen, Ihrem Körper und der materiellen Welt zu vertrauen. Sie kommen aus Mustern des Chaos, emotionaler Intensität und Krise als Lebensweise. Befreiung kommt, wenn Sie sich einfache Freuden erlauben, Stabilität ohne Drama und das Vertrauen, dass der Boden unter Ihnen nicht nachgeben wird.',
  /* Gemini      */ 'Nordknoten in den Zwillingen: Ihre Reise ist es, Neugier, einen offenen Geist und Verbindung mit Ihrer unmittelbaren Umgebung zu kultivieren. Sie kommen aus dogmatischen Mustern, absoluten Gewissheiten und einer Tendenz zu predigen statt zuzuhören. Befreiung kommt, wenn Sie sich erlauben, nicht zu wissen — wenn die Frage wertvoller wird als die Antwort.',
  /* Cancer      */ 'Nordknoten im Krebs: Ihre Reise ist emotionale Verwurzelung — Zuhause, Fürsorge, Verletzlichkeit. Sie kommen aus Mustern der Kontrolle, starrem Ehrgeiz und Verleugnung emotionaler Bedürfnisse. Befreiung kommt, wenn Sie sich erlauben, andere zu brauchen, wenn Sie sorgen ohne zu kalkulieren und wenn Zuhause Zuflucht wird statt Pflicht.',
  /* Leo         */ 'Nordknoten im Löwen: Ihre Reise ist es, sich aus dem Herzen auszudrücken, individuell zu strahlen und mit Großzügigkeit zu erschaffen. Sie kommen aus Mustern kollektiver Anonymität und Angst, aufzufallen. Befreiung kommt, wenn Sie aufhören, sich hinter der Gruppe zu verstecken und das Risiko eingehen, wirklich gesehen zu werden.',
  /* Virgo       */ 'Nordknoten in der Jungfrau: Ihre Reise ist es, mit Unterscheidungsvermögen zu dienen, für die Gesundheit zu sorgen und Spiritualität im praktischen Alltag anzuwenden. Sie kommen aus Mustern der Auflösung und Flucht vor der materiellen Realität. Befreiung kommt, wenn Sie entdecken, dass das Heilige in den Details des Alltags lebt.',
  /* Libra       */ 'Nordknoten in der Waage: Ihre Reise ist Heilung durch Partnerschaft, Engagement und Vergebung. Sie kommen aus Mustern der Isolation und übermäßigem Individualismus. Befreiung kommt, wenn Sie lernen, dass wahre Stärke nicht darin besteht, alles allein zu tun — sondern sich ergänzen zu lassen.',
  /* Scorpio     */ 'Nordknoten im Skorpion: Ihre Reise ist es, sich zu transformieren, indem Sie sich dem Verborgenen stellen — Macht, Intimität, Verletzlichkeit. Sie kommen aus Mustern des Komforts und der Vermeidung von Krisen. Befreiung kommt, wenn Sie sich erlauben, symbolisch zu sterben, um ganzheitlicher wiedergeboren zu werden.',
  /* Sagittarius */ 'Nordknoten im Schützen: Ihre Reise ist es, Horizonte zu erweitern, Glauben aufzubauen und Ihre Wahrheit zu leben. Sie kommen aus Mustern der Informationsangst und Angst, sich auf eine Vision einzulassen. Befreiung kommt, wenn Sie aufhören, Daten zu sammeln und beginnen, Weisheit zu leben.',
  /* Capricorn   */ 'Nordknoten im Steinbock: Ihre Reise ist es, Ihre Berufung zu beanspruchen, Struktur aufzubauen und ein Vermächtnis zu hinterlassen. Sie kommen aus Mustern emotionaler Abhängigkeit und Schwierigkeiten, Verantwortung für den eigenen Weg zu übernehmen. Befreiung kommt, wenn Sie das Steuer übernehmen und mit eigenen Händen aufbauen.',
  /* Aquarius    */ 'Nordknoten im Wassermann: Ihre Reise ist es, dem Kollektiv zu dienen, Innovation zu umarmen und über das Selbst hinauszudenken. Sie kommen aus Mustern aufgeblähten Egos und dem Bedürfnis nach persönlicher Anerkennung. Befreiung kommt, wenn Sie entdecken, dass Ihre Brillanz am mächtigsten ist, wenn sie Anliegen größer als Sie selbst beleuchtet.',
  /* Pisces      */ 'Nordknoten in den Fischen: Ihre Reise ist spirituelle Hingabe — Kontrolle loslassen, der Intuition vertrauen und die starren Grenzen des Egos auflösen. Sie kommen aus Mustern der Hyperkontrolle, des Perfektionismus und der Angst, „es richtig zu machen". Befreiung kommt, wenn Sie sich erlauben zu fließen — wenn Sie akzeptieren, dass nicht alles analysiert werden muss, um wahr zu sein.',
];

// ============================================================
// NAMES AND LABELS — English
// ============================================================

export const SIGN_NAMES = ['Widder','Stier','Zwillinge','Krebs','Löwe','Jungfrau','Waage','Skorpion','Schütze','Steinbock','Wassermann','Fische'];
export const PLANET_NAMES: Record<string,string> = { sun:'Sonne', moon:'Mond', mercury:'Merkur', venus:'Venus', mars:'Mars', jupiter:'Jupiter', saturn:'Saturn', uranus:'Uranus', neptune:'Neptun', pluto:'Pluto', northNode:'Nordknoten', chiron:'Chiron', lilith:'Lilith' };
export const MONTHS = ['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'];
export const SECTION_TITLES = { sun:(h:number,s:string)=>`☉ Sonne im ${h}. Haus in ${s}`, moon:(h:number,s:string)=>`☽ Mond im ${h}. Haus in ${s}`, mercury:(h:number,s:string)=>`☿ Merkur im ${h}. Haus in ${s}`, venus:(h:number,s:string)=>`♀ Venus im ${h}. Haus in ${s}`, mars:(h:number,s:string)=>`♂ Mars im ${h}. Haus in ${s}`, jupiter:(h:number,s:string)=>`♃ Jupiter im ${h}. Haus in ${s}`, saturn:(h:number,s:string)=>`♄ Saturn im ${h}. Haus in ${s}`, uranus:(h:number,s:string)=>`♅ Uranus im ${h}. Haus in ${s}`, neptune:(h:number,s:string)=>`♆ Neptun im ${h}. Haus in ${s}`, pluto:(h:number,s:string)=>`♇ Pluto im ${h}. Haus in ${s}`, northNode:(h:number,s:string)=>`☊ Nordknoten im ${h}. Haus in ${s}`, chiron:(h:number,s:string)=>`⚷ Chiron im ${h}. Haus in ${s}`, ascendant:(s:string)=>`Aszendent in ${s}` };
export const PLANET_SUBTITLES: Record<string,string> = { sun:'Ihre Sonnenessenz — Identität, Zweck und Lebensenergie', moon:'Ihre emotionale Welt — Bedürfnisse, Instinkte und innere Sicherheit', mercury:'Ihr Geist und Kommunikation — wie Sie denken und lernen', venus:'Ihre Liebessprache — was Sie anziehen und wertschätzen', mars:'Ihr Antrieb und Handeln — wie Sie Ziele verfolgen', jupiter:'Ihr Expansionsweg — wo Fülle und Wachstum fließen', saturn:'Ihre Meisterzone — wo Disziplin dauerhafte Erfolge schmiedet', uranus:'Ihre innere Revolution — wo Sie Muster brechen', neptune:'Ihr spirituelles Portal — wo Sie Grenzen auflösen', pluto:'Ihre transformative Kraft — Tod und Wiedergeburt', northNode:'Ihr evolutionärer Zweck — die Richtung Ihrer Seele', chiron:'Ihre heilige Wunde — Schmerz der zum Heilungsgeschenk wird' };
export const LABELS = { reportTitle:'Vollständiger Geburtsbericht', reportSubtitle:'Tiefe Deutung', positions:'Planetenpositionen', houses:'Hausspitzen', overview:'Überblick', potentials:'Ihre 5 größten Potenziale', challenges:'Ihre 5 wichtigsten Herausforderungen', conclusion:'Schlussfolgerung', advice:'Praktischer Rat', elements:'Elemente und Modalitäten', dignities:'Wesentliche Würden', aspects:'Hauptaspekte', themes:'Thematische Synthese', quote:'"Die Sterne neigen, sie bestimmen nicht."', sampleNote:'Dies war eine kostenlose Vorschau!', sampleFull:'Der vollständige Bericht enthält 20-30 Seiten mit detaillierter Deutung.', buyNow:'Vollversion:', buyInstant:'Jetzt kaufen und sofort herunterladen — 100% im Browser.', natalChart:'Ihr Geburtshoroskop', retrograde:'(rückläufig)', annualTitle:'Jahresvorschau', annualSubtitle:'Transite und Tendenzen', profection:'Jahresprofektion — Thema des Jahres', houseInFocus:'im Fokus', rulerOfYear:'Herrscher des Jahres', eclipses:'Finsternisse des Jahres', jupiterExpansion:'Die Expansion des Jahres', saturnLesson:'Die Lektion des Jahres', conclusionAnnual:'Schlussfolgerung — Ihr Jahr in Perspektive', relationshipTitle:'Beziehungsbericht', compatibility:'Kompatibilität', emotionalConnection:'Emotionale Verbindung', attractionChemistry:'Anziehung und Chemie', communication:'Kommunikation', commitmentLimits:'Engagement und Grenzen — Saturn', growthPotential:'Wachstumspotenzial', challengesTension:'Spannungspunkte', psychTitle:'Tiefenpsychologische Analyse', egoStructure:'Ego-Struktur — Sonne und Aszendent', emotionalWorld:'Emotionale Welt — Mond', mentalProcesses:'Mentale Prozesse — Merkur', lovePatterns:'Liebesmuster — Venus', vitalForce:'Lebenskraft — Mars', shadow:'Schatten — Pluto', wound:'Kernwunde — Chiron', unconscious:'Unbewusstes — 12. Haus und Neptun', familyPatterns:'Familienmuster — Mond, 4. Haus und Saturn', defenseMechanisms:'Abwehrmechanismen — Saturn', integrationPath:'Integrationsweg — Nordknoten', careerTitle:'Karriere und Berufung', midheaven:'Medium Coeli', house10:'10. Haus — Berufung', house6:'6. Haus — Alltag und Arbeit', house2:'2. Haus — Ressourcen und Talente', sinsTitle:'Die Sieben Sünden', pride:'Stolz — Sonne', lust:'Wollust — Venus und Mars', greed:'Habgier — Saturn', gluttony:'Völlerei — Jupiter', wrath:'Zorn — Mars', envy:'Neid — Pluto', sloth:'Trägheit — Neptun', repetitivePatterns:'Wiederholungsmuster — Quadrate und Oppositionen', unexploredPotentials:'Unerforschte Potenziale — Trigone und Talente', integrationPaths:'Integrationswege', recommendedPractices:'Empfohlene Praktiken', childhoodTemplate:'Kindheit und emotionale Prägung', fromWoundToGift:'Von der Wunde zum Geschenk', differentiation:'Differenzierung — Sie selbst sein', mainTensions:'Hauptspannungen der Karte', plutoAspects:'Spannungsaspekte des Pluto' };
export const TRANSITIONS = { afterOverview:'Diese Identitätsbasis manifestiert sich konkret in den Planeten in ihren Häusern.', afterPersonalPlanets:'Die Aspekte zwischen Planeten zeigen, wie diese Energien miteinander kommunizieren.', afterAspects:'Aus diesen Wechselwirkungen entstehen Muster — zentrale Themen Ihrer Erfahrung.', beforeConclusion:'Alles zusammengenommen erzählt Ihre Karte eine kohärente Geschichte.' };
