// ============================================================
// INTERPRETATIONS — Français (fr)
// Textes interprétatifs complets en français — sans imports PT
// ============================================================

// ============================================================
// SOLEIL EN MAISON
// ============================================================
export const SUN_IN_HOUSE: string[] = [
  /* House 1  */ 'Votre rayonnement personnel réside dans la manière dont vous vous présentez au monde. Vous êtes venu·e ici pour être vu·e, pour faire sentir votre présence. La maison 1 vous invite à honorer votre individualité — lorsque vous vous autorisez à être qui vous êtes vraiment, sans masques, tout coule naturellement. Votre défi consiste à apprendre à ne pas dépendre de l\'approbation des autres pour briller.',
  /* House 2  */ 'Votre identité est profondément liée à ce que vous construisez et à ce que vous valorisez. Vous brillez lorsque vous développez vos talents et les transformez en quelque chose de tangible. La sécurité matérielle n\'est pas de la vanité pour vous — c\'est une expression de votre valeur. Le défi est de ne pas vous définir uniquement par ce que vous possédez.',
  /* House 3  */ 'Vous êtes né·e pour communiquer, enseigner, relier les idées. Votre rayonnement réside dans la légèreté, la curiosité et la capacité à traduire des choses complexes en quelque chose d\'accessible. Si vous travaillez dans un endroit qui ne vous permet pas d\'exprimer votre opinion ou de créer, quelque chose manquera toujours. Lorsque vous honorez cette qualité communicative, l\'abondance suit.',
  /* House 4  */ 'Votre identité s\'enracine dans la famille, le foyer et vos fondations émotionnelles. Vous brillez lorsque vous créez un espace sûr — pour vous-même et pour les autres. Vous êtes peut-être la personne qui soutient émotionnellement une famille ou une communauté. Le défi est de ne pas vous perdre dans les besoins des autres au point d\'oublier les vôtres.',
  /* House 5  */ 'Vous êtes né·e pour créer, vous exprimer, briller ! La maison 5 est la scène naturelle du Soleil. Créativité, romance, enfants, jeu — tout cela vous dynamise. Lorsque vous vous autorisez à être ludique et authentique, vous rayonnez. Le défi est de ne pas chercher une validation constante ni confondre ego et essence.',
  /* House 6  */ 'Votre identité s\'exprime à travers le service, la routine et le perfectionnement constant. Vous brillez quand vous êtes utile, quand vous résolvez des problèmes, quand vous prêtez attention aux détails que personne d\'autre ne voit. La santé et le travail sont des domaines sacrés pour vous. Le défi est de ne pas vous effacer au nom de la productivité.',
  /* House 7  */ 'Votre rayonnement se révèle dans les relations. Vous vous découvrez à travers les autres — partenaires, associés, accords. Cela ne signifie pas la dépendance : cela signifie que le miroir de la relation vous aide à voir qui vous êtes. Le défi est de ne pas vous perdre dans l\'autre ou projeter votre identité sur vos partenaires.',
  /* House 8  */ 'Votre identité se forge à travers de profondes transformations au cours de votre vie. Vous brillez dans les moments de crise, quand tout semble s\'effondrer et que vous vous relevez. Les thèmes de la sexualité, du pouvoir et des ressources partagées sont centraux. Le défi est de ne pas vous accrocher au contrôle ni craindre la vulnérabilité.',
  /* House 9  */ 'Vous êtes né·e pour élargir les horizons — études approfondies, voyages qui changent votre perspective, philosophies de vie. Votre rayonnement réside dans le fait d\'être un·e éternel·le étudiant·e et, éventuellement, un·e enseignant·e qui partage sa sagesse. Le défi est de ne pas vous perdre dans les théories sans application pratique.',
  /* House 10 */ 'Votre identité est fortement liée à votre carrière et à votre image publique. Vous êtes venu·e ici pour construire quelque chose dans le monde, pour être reconnu·e pour ce que vous accomplissez avec maîtrise. Ce n\'est pas de la vanité — c\'est un objectif de vie. Le défi est d\'équilibrer la vie personnelle avec la pression de la réussite extérieure.',
  /* House 11 */ 'Votre rayonnement vit dans les causes collectives, les amitiés et les projets tournés vers l\'avenir. Vous êtes dynamisé·e par les groupes, par le travail vers quelque chose de plus grand que vous. L\'innovation et l\'originalité vous définissent. Le défi est de ne pas devenir émotionnellement distant·e des personnes qui vous sont les plus proches.',
  /* House 12 */ 'Votre identité porte une profonde dimension spirituelle. Vous brillez en coulisses, dans la solitude créative, en connexion avec quelque chose de plus grand. Il peut être difficile de vous montrer au monde car votre rayonnement est subtil, intérieur. Le défi est de ne pas vous saboter ni fuir la vie pratique.',
];

// ============================================================
// LUNE EN MAISON
// ============================================================
export const MOON_IN_HOUSE: string[] = [
  /* House 1  */ 'Vos émotions se lisent sur votre visage — vous êtes transparent·e, les gens ressentent ce que vous ressentez. Vous avez besoin de liberté pour être émotionnel·le sans jugement. Votre corps répond directement à votre état émotionnel.',
  /* House 2  */ 'Vous vous sentez en sécurité quand vous avez une stabilité financière. Ce n\'est pas de l\'avidité — l\'argent représente une sécurité émotionnelle pour vous. Vous pouvez vivre des hauts et des bas financiers qui reflètent vos cycles émotionnels.',
  /* House 3  */ 'Vous traitez vos émotions en parlant, en écrivant et en stimulant votre mental. Vous avez besoin de stimulation intellectuelle pour vous sentir bien. L\'environnement des frères et sœurs et du voisinage a laissé une empreinte sur vos émotions dans l\'enfance.',
  /* House 4  */ 'C\'est le placement le plus naturel de la Lune. La famille et le foyer sont sacrés pour vous. Vous avez besoin d\'un espace physique qui vous appartient vraiment pour vous ressourcer. Les émotions de votre mère (ou figure maternelle) ont profondément façonné qui vous êtes.',
  /* House 5  */ 'Vous vous nourrissez émotionnellement quand vous jouez, créez quelque chose ou tombez amoureux·se. Vous avez besoin d\'expression créative comme exutoire émotionnel. Avec les enfants, la connexion est intense et profondément émotionnelle.',
  /* House 6  */ 'Votre santé physique est directement affectée par votre état émotionnel. Quand quelque chose ne va pas émotionnellement, votre corps le signale. Vous avez besoin d\'une routine qui inclut le soin de soi pour vous sentir centré·e.',
  /* House 7  */ 'Vous vous sentez émotionnellement complet·e dans les relations. Vous avez besoin de partenariat pour vous sentir en sécurité — et vous attirez des partenaires qui reflètent votre paysage émotionnel (y compris ses ombres). Le défi est de ne pas externaliser votre bien-être émotionnel.',
  /* House 8  */ 'Vos émotions sont intenses, profondes et parfois envahissantes. Vous ressentez tout avec une grande force et pouvez facilement percevoir ce que les autres cachent. S\'ouvrir peut être difficile, mais quand vous faites confiance à quelqu\'un, vous lui donnez toute votre âme.',
  /* House 9  */ 'Vous vous nourrissez émotionnellement quand vous apprenez, voyagez ou explorez de nouvelles perspectives. Vous avez besoin d\'espace et de liberté pour grandir. Vous pouvez avoir du mal avec la routine et la proximité émotionnelle conventionnelle — vous préférez la profondeur philosophique.',
  /* House 10 */ 'Vos émotions sont liées à la carrière et à la reconnaissance publique. Vous pouvez sentir que vous devez « être quelqu\'un » pour mériter l\'amour. Votre relation avec votre mère a peut-être été façonnée par des attentes de performance.',
  /* House 11 */ 'Vous vous nourrissez dans les amitiés et les causes collectives. Vous avez besoin d\'appartenir à un groupe qui partage vos idéaux. L\'intimité en tête-à-tête peut être un défi ; vous tendez à préférer les connexions plus larges, communautaires.',
  /* House 12 */ 'Vos émotions ont une qualité océanique — profondes, parfois diffuses, aux frontières fluides. Vous avez besoin de solitude pour traiter ce que vous ressentez. Vous portez une forte intuition et empathie, mais vous devez apprendre à vous protéger émotionnellement.',
];

// ============================================================
// MERCURE EN MAISON
// ============================================================
export const MERCURY_IN_HOUSE: string[] = [
  /* House 1  */ 'Votre esprit est vif et façonne la manière dont le monde vous perçoit. Vous pensez à voix haute, traitez en temps réel, et les gens vous reconnaissent immédiatement comme intelligent·e et communicatif·ve. Votre tempérament nerveux et intuitif vous donne un don naturel pour l\'échange d\'idées. Le défi est de ralentir suffisamment pour écouter — votre esprit va si vite qu\'il peut dépasser les réponses qui arrivent à un rythme plus doux.',
  /* House 2  */ 'Votre intelligence est votre plus grand outil pour générer de la richesse. Vous gagnez par l\'esprit — écriture, journalisme, commerce, administration, enseignement ou toute forme de travail intellectuel. Il y a un instinct naturel pour les affaires et pour identifier où se trouve la valeur. Le défi est de ne pas réduire toute intelligence à une utilité financière — votre esprit a besoin de liberté pour explorer, pas seulement pour profiter.',
  /* House 3  */ 'Le placement naturel de Mercure — votre esprit est chez lui ici. Vous avez une facilité extraordinaire pour apprendre, communiquer et vous exprimer. Vous assimilez l\'information rapidement, passez d\'un sujet à l\'autre avec légèreté et portez un esprit jeune qui maintient l\'environnement autour de vous vivant. L\'écriture, l\'enseignement et toute forme de transmission du savoir sont des voies naturelles vers le succès. Le défi est la profondeur : quand tout vient facilement, il peut y avoir peu d\'incitation à vraiment creuser.',
  /* House 4  */ 'Votre esprit est enraciné dans la famille, la mémoire et l\'héritage intellectuel de votre éducation. Vous êtes peut-être celui ou celle qui garde vivantes les histoires familiales, qui travaille depuis la maison ou dont la profession a été inspirée par l\'environnement domestique. Une vitalité intellectuelle vous accompagne tout au long de la vie. Vous avez une remarquable capacité d\'adaptation au changement — chaque nouveau début est une opportunité de réécrire votre récit.',
  /* House 5  */ 'Votre esprit est créatif et ludique — vous exprimez vos idées de manière amusante et engageante. Il y a un don naturel pour l\'enseignement, surtout avec les enfants et les jeunes. Vous adorez les jeux de mots, les puzzles et les défis mentaux. En relations, vous intellectualisez l\'amour — vous avez besoin de comprendre avant de pouvoir vous abandonner pleinement. Quand l\'esprit et le cœur s\'alignent, votre communication devient irrésistible.',
  /* House 6  */ 'Votre esprit est une machine à résoudre les problèmes — analytique, précis et infatigable. Vous avez une forte capacité pour le travail intellectuel, particulièrement dans les rôles administratifs, de santé ou organisationnels qui nécessitent une structure méthodique. Vous vous distinguez par l\'efficacité et l\'ingéniosité. Le défi est la tension nerveuse : le même esprit qui résout tout peut se surcharger s\'il ne trouve pas d\'exutoires pour le repos.',
  /* House 7  */ 'Votre esprit fonctionne le mieux en dialogue — vous avez besoin de l\'autre pour penser, débattre et traiter les idées. Vous excellez dans la médiation, la négociation et toute forme de partenariat intellectuel. Vous pouvez attirer des partenaires mercuriens (communicatifs, agités, polyvalents). Le succès professionnel ou littéraire peut venir de la collaboration. Le défi est de ne pas compter sur le reflet des autres pour valider vos propres idées.',
  /* House 8  */ 'Votre esprit est investigateur — vous allez naturellement au-delà de la surface, attiré·e par le mystère, la psychologie des profondeurs, l\'occulte et tout ce qui est caché. Vous lisez entre les lignes avec une facilité troublante, percevant ce qui n\'est pas dit. Il peut y avoir une fascination pour la mort, la transformation, l\'héritage ou la sexualité. Le défi est d\'utiliser ce pouvoir de pénétration pour guérir, non pour manipuler.',
  /* House 9  */ 'Votre esprit est philosophique et expansif — orienté vers le sens, pas seulement les faits. Vous avez une aptitude naturelle pour les langues étrangères, l\'enseignement supérieur et les voyages qui élargissent la perspective. Vous avez l\'objectivité d\'accepter la critique et les idées opposées, à condition qu\'elles soient intellectuellement sérieuses. Le défi est de ne pas se perdre dans des théories abstraites sans application — la sagesse doit être vécue, pas seulement étudiée.',
  /* House 10 */ 'La communication est votre outil de carrière — vous vous distinguez professionnellement par l\'intelligence et l\'articulation. C\'est le placement par excellence de l\'intermédiaire, du communicateur public, de l\'intellectuel qui gagne en reconnaissance. De multiples voies professionnelles sont possibles au cours d\'une vie. Le défi est de maintenir la concentration : la polyvalence qui vous permet de naviguer entre les domaines peut disperser l\'énergie sans direction claire.',
  /* House 11 */ 'Votre esprit est orienté vers l\'avenir — projets intellectuels, causes collectives, diffusion des idées. Vous communiquez exceptionnellement bien en groupe et nouez facilement des amitiés autour de l\'échange intellectuel. Vos amis sont divers et stimulants. Le défi est de ne pas vous absorber tellement dans les idéaux collectifs que vous négligez les connexions intimes qui ont aussi besoin de votre présence.',
  /* House 12 */ 'Votre esprit est contemplatif et intuitif — les idées arrivent par les rêves, la méditation et la solitude. Vous avez une aptitude naturelle pour travailler avec l\'inconscient : psychologie, écriture introspective, recherche dans les dimensions cachées. Verbaliser ce que vous percevez peut être difficile, car ce que vous sentez est plus vaste que ce que les mots peuvent atteindre. Le défi est de faire confiance à votre perception subtile sans vous perdre dans l\'indéfinition.',
];
// ============================================================
// VÉNUS EN MAISON
// ============================================================
export const VENUS_IN_HOUSE: string[] = [
  /* House 1  */ 'Vous rayonnez de charme naturellement — il y a une présence agréable et harmonieuse qui attire les gens avant même que vous ne parliez. La tendresse, la profondeur émotionnelle et la sensibilité sont vos marques distinctives. Les gains et le bien-être peuvent venir d\'activités liées à l\'art, la mode, la beauté et l\'esthétique. Quand vous entrez dans un espace, quelque chose s\'adoucit. Le défi est de ne pas compter exclusivement sur la beauté ou le fait de plaire aux autres comme principale façon d\'exister.',
  /* House 2  */ 'Vous aimez le confort matériel et les belles choses — et ce n\'est pas de la vanité, c\'est de l\'intelligence sensorielle. Vous avez un œil naturel pour la qualité et la valeur durable. Il y a une facilité à gagner par les proches ou par des activités impliquant l\'esthétique et le plaisir. Vous pouvez construire une vie partagée pleine de grâce et d\'abondance. Le défi est de ne pas confondre l\'amour avec la sécurité financière, ou utiliser les possessions comme substitut à l\'affection.',
  /* House 3  */ 'Votre communication est séduisante et agréable — vos mots portent un charme désarmant. Vous cultivez naturellement l\'harmonie avec vos frères et sœurs et vos voisins. L\'amitié est quelque chose dont vous ne pouvez pas vous passer — vous avez besoin de connexions intellectuelles qui soient aussi nourrissantes émotionnellement. Vous aimez les arts, le beau langage et les conversations qui nourrissent l\'âme. Le défi est de ne pas confondre charme et profondeur.',
  /* House 4  */ 'Votre amour s\'exprime en créant des foyers beaux et accueillants — des espaces qui nourrissent tous ceux qui y entrent. Il y a une harmonie profonde entre vous et vos parents, ou du moins un profond désir de celle-ci. Dans les années de maturité, l\'amour s\'épanouit avec une intensité renouvelée. Le travail vénusien mené depuis la maison (art, antiquités, décoration, esthétique) vient naturellement. Le défi est de ne pas devenir si attaché·e au confort domestique que vous perdez votre sens de l\'aventure.',
  /* House 5  */ 'Un placement puissant pour Vénus — l\'amour romantique intense, agréable et vivant. Grande capacité créative dans les arts, la musique et le théâtre. Chance dans les relations sociales et mondaines. Les enfants apportent une profonde satisfaction. Vous aimez généreusement et espérez être adoré·e en retour. Le défi est de ne pas transformer l\'amour en spectacle — parfois l\'affection la plus authentique est silencieuse.',
  /* House 6  */ 'Vous exprimez l\'amour à travers le soin pratique — vous apprenez les habitudes de l\'autre, préparez ce dont il ou elle a besoin avant de le demander, et êtes présent·e dans les détails invisibles. L\'amour peut naître sur le lieu de travail, parmi les collègues. Vous appréciez les routines agréables et les environnements esthétiquement harmonieux. Le défi est de ne pas réduire l\'amour au service — vous méritez d\'être soigné·e, pas seulement de soigner.',
  /* House 7  */ 'Le placement naturel de Vénus — le partenariat est votre art. Vous attirez les relations avec facilité et avez un don naturel pour créer l\'harmonie à deux. Un mariage sans crises graves est possible quand il y a respect mutuel et beauté dans l\'interaction. Vous avez une popularité naturelle, surtout quand elle s\'exprime à travers l\'art ou la diplomatie. Le défi est de ne pas vous effacer pour maintenir la paix — la vraie harmonie ne nécessite pas votre disparition.',
  /* House 8  */ 'Votre amour est intense et transformateur — vos relations vont en profondeur, remuent l\'âme et impliquent des thèmes de pouvoir, de vulnérabilité et de sexualité. Votre vie émotionnelle est influencée par les finances partagées et les ressources. Une tendance à la générosité est possible. Le défi est de ne pas utiliser l\'amour comme moyen de contrôle, ou confondre intensité et profondeur du lien.',
  /* House 9  */ 'L\'amour et l\'aventure s\'entremêlent — vous pouvez tomber amoureux·se d\'étrangers, de cultures différentes ou de personnes aux philosophies de vie expansives. Voyages de plaisir. Un idéal artistique élevé. Des relations qui élargissent votre vision du monde. Le défi est de ne pas tant idéaliser le « lointain » que l\'amour quotidien et proche semble insuffisant.',
  /* House 10 */ 'Des relations connectées à la carrière — grande fortune et reconnaissance pour ceux dans les professions artistiques, la mode ou tout domaine qui valorise la beauté et le charme personnel. Les gens vous voient publiquement comme quelqu\'un d\'attirant et d\'agréable. Le défi est de séparer le véritable amour de l\'amour du statut — et de vous permettre d\'être aimé·e pour qui vous êtes, pas pour ce que vous avez accompli.',
  /* House 11 */ 'L\'amour naît de l\'amitié — vos romances les plus durables commencent comme une connexion intellectuelle et sociale. Charme et attrait magnétique en contexte de groupe. Une facilité à former des amitiés influentes qui soutiennent la croissance professionnelle. Vous valorisez la liberté dans les relations et la connexion avec des personnes ouvertes d\'esprit. Le défi est de ne pas éviter la véritable intimité en se cachant derrière la sociabilité.',
  /* House 12 */ 'Amour secret, spirituel ou platonique — il y a une qualité transcendante dans votre façon d\'aimer qui ne trouve pas toujours d\'expression dans le monde concret. Des relations secrètes sont possibles, ainsi que des amours qui se transforment profondément au fil du temps. Vénus ici apaise les peines de cœur par l\'art et la contemplation. Le défi est d\'amener cet amour à la surface — ce qui reste uniquement intérieur demeure incomplet.',
];

// ============================================================
// ============================================================
// MARS EN MAISON
// ============================================================
export const MARS_IN_HOUSE: string[] = [
  /* House 1  */ 'La combativité et l\'enthousiasme définissent votre présence — vous rayonnez d\'énergie, d\'assurance et d\'une disponibilité à l\'action que les gens ressentent immédiatement. Vous avez une aptitude naturelle pour les activités demandant du leadership, de l\'initiative ou de la compétition. Vous allez chercher ce que vous voulez sans hésiter, ce qui est une force immense quand c\'est canalisé avec conscience. Le défi est que votre assertivité peut émerger sous de nombreuses formes sans que vous le remarquiez — apprendre à moduler votre intensité est votre travail de maturation.',
  /* House 2  */ 'Votre énergie et votre détermination sont canalisées dans la construction de ressources — vous luttez activement pour ce qui est à vous, avec une volonté de travailler dur pour la sécurité matérielle. Les revenus peuvent venir de domaines qui demandent force, courage ou compétition (industrie, sport, entrepreneuriat). Le défi est une tendance à dépenser excessivement — la même énergie qui conquiert peut se dissiper sans stratégie financière.',
  /* House 3  */ 'Votre communication est directe, assertive et parfois tranchante — votre esprit est combatif, critique et intransigeant quand il s\'agit de défendre une idée. Il peut y avoir des frictions avec les frères et sœurs ou dans votre environnement immédiat. Votre esprit est rapide et intolérant à la médiocrité intellectuelle. Le défi est de transformer l\'épée des mots en outil — le même langage qui blesse peut aussi mobiliser et inspirer.',
  /* House 4  */ 'Votre énergie est profondément connectée au foyer et aux racines — vous avez peut-être grandi dans un environnement domestique intense, avec un parent autoritaire ou une éducation excessivement stricte. Vous travaillez dur pour le confort de votre famille et défendez votre espace avec férocité. Une énergie vitale vous accompagne tout au long de la vie. Le défi est de ne pas reproduire l\'intensité que vous avez reçue — construire un foyer qui soit un refuge, pas un champ de bataille.',
  /* House 5  */ 'Énergie créative, compétitive et passionnée — vous vous distinguez dans le sport, les arts ou toute forme d\'expression qui demande du courage et de la présence. L\'amour conquis en surmontant des obstacles ou saisi avec audace. Des aventures marquées par l\'impulsivité et l\'intensité. Le défi est de ne pas confondre passion et possession — le feu créatif est plus beau quand il illumine sans brûler.',
  /* House 6  */ 'Un travailleur infatigable — votre énergie coule dans la productivité et la résolution pratique de problèmes. Vous êtes adapté·e à un travail exigeant ou à enjeux élevés qui requiert courage et endurance. Un rôle naturel de leader opérationnel. Santé robuste, mais avec une prédisposition aux fièvres, inflammations et stress quand l\'énergie est supprimée. Le défi est d\'équilibrer l\'intensité productive avec le repos — vous n\'êtes pas une machine, même si vous fonctionnez comme telle.',
  /* House 7  */ 'Vos relations sont des arènes de croissance — vous attirez des partenaires assertifs, forts et parfois combatifs. Des affrontements émotionnels et des luttes de pouvoir dans les relations sont possibles. Des partenariats conclus hâtivement, à un jeune âge, avec risque de séparation si l\'énergie n\'est pas canalisée dans la croissance mutuelle. Le défi est de transformer la compétitivité à deux en collaboration — l\'autre n\'est pas un adversaire, mais un miroir.',
  /* House 8  */ 'Un placement de pouvoir intense — fort instinct de survie, capacité de renaître de ses cendres, sexualité comme force vitale transformatrice. Il peut y avoir des disputes d\'héritage ou une implication dans des situations à haut risque. Le défi est d\'utiliser cet immense pouvoir pour transformer consciemment — pas pour détruire ni s\'autodétruire.',
  /* House 9  */ 'Dévouement complet à une cause — vous défendez vos croyances avec une passion absolue et ne faites aucune concession quand il s\'agit de vérité et de justice. Un caractère qui s\'engage dans l\'aventure même face au danger. Il peut y avoir des voyages audacieux ou des conflits avec les systèmes de croyances établis. Le défi est le fanatisme : la même passion qui vous anime peut vous aveugler si elle n\'est pas tempérée par l\'humilité intellectuelle.',
  /* House 10 */ 'Ambition professionnelle puissante — vous utilisez une détermination féroce pour vous établir dans la carrière et la vie publique. Vous attirez l\'hostilité mais savez la gérer — en fait, vous prospérez face au défi. Une aptitude au leadership dans tout domaine requérant courage et sens de la décision. Le défi est de ne pas créer d\'ennemis inutiles en chemin — le pouvoir le plus durable est celui qui construit des ponts, pas celui qui les brûle.',
  /* House 11 */ 'Enthousiasme et leadership dans les groupes et les causes collectives — vous êtes l\'ami·e qui mobilise, qui pousse à l\'action, qui refuse la passivité. Des amitiés intenses et parfois dominantes : le grand ami qui, s\'il ne trouve pas de réciprocité, peut devenir un adversaire féroce. Le défi est de permettre aux autres de diriger aussi — une cause collective n\'a pas besoin d\'un général, elle a besoin d\'un catalyseur.',
  /* House 12 */ 'Énergie subtile et introspective — vous agissez en coulisses, en secret, ou de manières pas toujours visibles aux autres. Il peut y avoir de la colère supprimée qui a besoin d\'être canalisée dans des pratiques conscientes (art, spiritualité, activisme silencieux). Des hostilités cachées sont possibles. Le défi est de ne pas retourner cette énergie contre vous-même — Mars en maison 12 a besoin de canaux d\'expression, sinon cela devient de l\'autodestruction.',
];

// ============================================================
// JUPITER EN MAISON
// ============================================================
export const JUPITER_IN_HOUSE: string[] = [
  /* House 1  */ 'Jupiter en maison 1 apporte un optimisme naturel, une présence magnétique et une tendance à attirer les opportunités. Vous projetez confiance et générosité. Attention à l\'excès — vous pouvez promettre plus que vous ne livrez ou ignorer vos propres limites.',
  /* House 2  */ 'Jupiter en maison 2 indique une facilité à attirer les ressources et construire la richesse. Vous avez une relation généreuse avec l\'argent — il entre facilement, mais peut sortir tout aussi facilement. Vos valeurs sont expansives et ouvertes.',
  /* House 3  */ 'Jupiter en maison 3 élargit l\'esprit et la communication. Facilité avec les langues, l\'écriture et l\'enseignement. Vous êtes l\'éternel·le étudiant·e qui adore partager le savoir. Vous pouvez avoir une relation positive avec vos frères et sœurs ou vos voisins.',
  /* House 4  */ 'Jupiter en maison 4 indique un foyer généreux, une famille soutenante ou une expansion dans la vie domestique. Vous avez peut-être grandi dans l\'abondance émotionnelle ou vous vous retrouvez à déménager dans des maisons progressivement plus grandes. Des racines solides et la foi dans les fondations familiales.',
  /* House 5  */ 'Jupiter en maison 5 est un placement de joie : créativité abondante, chance en amour et générosité avec les enfants. Vous avez besoin d\'espace pour jouer, créer et vous exprimer. Vous pouvez avoir de nombreux hobbies ou talents artistiques.',
  /* House 6  */ 'Jupiter en maison 6 apporte de l\'enthousiasme au travail quotidien et une bonne santé générale. Vous trouvez du sens dans la routine quand elle a un but. Vous pouvez travailler dans l\'éducation, la santé ou des causes qui élargissent le bien-être collectif.',
  /* House 7  */ 'Jupiter en maison 7 attire des partenaires généreux, optimistes ou de divers horizons culturels. Les relations sont une source de croissance. Attention aux attentes irréalistes envers les partenaires ou à une tendance à attirer « trop ».',
  /* House 8  */ 'Jupiter en maison 8 indique une protection pendant les crises et une facilité avec les ressources partagées. Vous grandissez à travers de profondes transformations. Vous pouvez hériter de richesses ou trouver la bonne fortune dans les investissements et fonds communs.',
  /* House 9  */ 'Jupiter en maison 9 est dans sa maison naturelle — expansion philosophique maximale, voyages transformateurs, études supérieures profondes. Vous êtes naturellement sage, optimiste et toujours en quête de sens.',
  /* House 10 */ 'Jupiter en maison 10 apporte reconnaissance professionnelle, expansion de carrière et une image publique positive. Vous pouvez vous distinguer dans des domaines comme l\'éducation, le droit, la philosophie ou les voyages. Une carrière façonnée par un sens de la mission.',
  /* House 11 */ 'Jupiter en maison 11 élargit votre réseau social et vos rêves pour l\'avenir. Vous attirez des amis généreux et bénéficiez des groupes. Les causes sociales et les projets collaboratifs sont des sources d\'abondance.',
  /* House 12 */ 'Jupiter en maison 12 est un ange gardien caché. Protection spirituelle, foi profonde, intuition élargie. Vous bénéficiez des retraites, de la spiritualité et du travail en coulisses. Votre générosité peut être discrète ou anonyme.',
];

// ============================================================
// SATURNE EN MAISON
// ============================================================
export const SATURN_IN_HOUSE: string[] = [
  /* House 1  */ 'Saturne en maison 1 apporte du sérieux dès le plus jeune âge. Vous avez peut-être paru plus âgé·e que votre âge ou porté des responsabilités précoces. Avec la maturité, cela se transforme en autorité naturelle et en une présence imposante et respectée.',
  /* House 2  */ 'Saturne en maison 2 indique des défis initiaux avec l\'argent ou l\'estime de soi, mais aussi la capacité de construire une véritable sécurité par la discipline. Vous valorisez ce que vous gagnez par l\'effort — rien ne vient facilement, mais ce qui arrive, reste.',
  /* House 3  */ 'Saturne en maison 3 peut apporter des difficultés précoces avec la communication, l\'apprentissage ou les relations avec les frères et sœurs. Avec le temps, vous développez un esprit structuré, une écriture précise et une communication qui porte de l\'autorité.',
  /* House 4  */ 'Saturne en maison 4 indique souvent une enfance marquée par la restriction, des responsabilités familiales précoces ou une figure parentale absente ou rigide. La mission est de construire vos propres fondations émotionnelles solides à l\'âge adulte.',
  /* House 5  */ 'Saturne en maison 5 peut bloquer l\'expression créative ou la joie au début de la vie. Les enfants peuvent venir plus tard ou apporter des responsabilités significatives. Avec la maturité, vous développez une créativité disciplinée et durable.',
  /* House 6  */ 'Saturne en maison 6 exige du dévouement au travail et une attention constante à la santé. Il peut y avoir une tendance à se surcharger de tâches. La leçon est de construire des routines durables et de ne pas se définir uniquement par la productivité.',
  /* House 7  */ 'Saturne en maison 7 apporte du sérieux aux relations. Il peut y avoir un retard dans la rencontre d\'un partenaire, ou des mariages avec des personnes plus âgées ou plus matures. La leçon est l\'engagement authentique — choisi librement, pas contracté par obligation.',
  /* House 8  */ 'Saturne en maison 8 indique une peur de perdre le contrôle, une difficulté avec l\'intimité profonde ou des défis autour de l\'héritage et des ressources partagées. La leçon est d\'apprendre à faire confiance et à se transformer sans résistance.',
  /* House 9  */ 'Saturne en maison 9 peut limiter les voyages ou l\'éducation formelle au début de la vie. Avec la maturité, vous devenez une autorité dans votre domaine d\'étude. Vos croyances sont construites par la rigueur, pas par la foi aveugle.',
  /* House 10 */ 'Saturne en maison 10 est l\'un des placements les plus ambitieux — vous êtes venu·e ici pour construire un héritage. La carrière est une affaire sérieuse et centrale. Le progrès peut être lent au début, mais le succès qui vient est solide et durable.',
  /* House 11 */ 'Saturne en maison 11 peut apporter peu mais de loyaux amis, ou une difficulté initiale à s\'intégrer dans les groupes. La mission est de construire un véritable réseau de soutien et de travailler pour des causes qui demandent un engagement à long terme.',
  /* House 12 */ 'Saturne en maison 12 peut indiquer des peurs cachées, de l\'isolement ou des responsabilités invisibles. La leçon est de confronter les fantômes intérieurs et de découvrir que la structure peut exister même au sein de la spiritualité et de l\'inconscient.',
];

// ============================================================
// URANUS EN MAISON
// ============================================================
export const URANUS_IN_HOUSE: string[] = [
  /* House 1  */ 'Uranus en maison 1 fait de vous quelqu\'un d\'unique, de rebelle et d\'imprévisible. Vous refusez de rentrer dans les moules. Les gens peuvent vous trouver excentrique — et vous l\'êtes probablement, avec fierté.',
  /* House 2  */ 'Uranus en maison 2 apporte une instabilité financière mais aussi des intuitions brillantes sur des moyens non conventionnels de gagner de l\'argent. Vos valeurs sont progressistes et en constante évolution.',
  /* House 3  */ 'Uranus en maison 3 vous donne un esprit électrique — pensées rapides, insights soudains, communication non conventionnelle. Vous pouvez avoir du mal avec l\'apprentissage traditionnel mais briller avec des méthodes alternatives.',
  /* House 4  */ 'Uranus en maison 4 indique un foyer instable dans l\'enfance ou des changements fréquents de résidence. Vous avez besoin de liberté même au sein du foyer. Votre famille peut être non conventionnelle.',
  /* House 5  */ 'Uranus en maison 5 apporte une créativité radicale et des romances inattendues. Vous vous exprimez de manières originales et pouvez avoir des enfants non conventionnels ou une relation non traditionnelle avec la parentalité.',
  /* House 6  */ 'Uranus en maison 6 ne peut pas tolérer la routine répétitive. Vous avez besoin d\'un travail avec de l\'autonomie et de la place pour l\'innovation. La santé peut suivre des patterns irréguliers. Les approches alternatives de soin de soi fonctionnent bien.',
  /* House 7  */ 'Uranus en maison 7 attire des partenaires non conventionnels et des relations qui défient les normes. Des ruptures soudaines dans les partenariats sont possibles. Vous avez besoin de liberté au sein de l\'engagement.',
  /* House 8  */ 'Uranus en maison 8 apporte des transformations soudaines et des insights profonds sur le pouvoir et la sexualité. Des changements financiers inattendus. Vous pouvez avoir des expériences transcendantes non conventionnelles.',
  /* House 9  */ 'Uranus en maison 9 construit son propre système de croyances — il n\'accepte aucun dogme. Voyages inattendus, insights philosophiques soudains. Vous pouvez révolutionner votre domaine d\'étude.',
  /* House 10 */ 'Uranus en maison 10 indique une carrière non conventionnelle, des changements professionnels soudains ou un travail dans la technologie et l\'innovation. Les hiérarchies rigides ne sont pas pour vous.',
  /* House 11 */ 'Uranus en maison 11 est dans sa maison naturelle — amitiés excentriques, vision révolutionnaire de l\'avenir, participation à des groupes qui changent les paradigmes. Vous êtes le visionnaire du collectif.',
  /* House 12 */ 'Uranus en maison 12 indique des insights spirituels soudains, une intuition électrique et un possible éveil spirituel inattendu. Vous pouvez ressentir de l\'agitation sans cause apparente — c\'est l\'inconscient qui appelle la liberté.',
];

// ============================================================
// NEPTUNE EN MAISON
// ============================================================
export const NEPTUNE_IN_HOUSE: string[] = [
  /* House 1  */ 'Neptune en maison 1 fait de vous un caméléon, profondément empathique et difficile à définir. Les gens projettent sur vous ce qu\'ils souhaitent voir. Vous absorbez votre environnement — apprendre à maintenir des limites est essentiel.',
  /* House 2  */ 'Neptune en maison 2 dissout la relation avec l\'argent — il peut y avoir de la confusion financière, une générosité excessive ou une difficulté à facturer votre travail. La leçon est de valoriser vos dons sans culpabilité.',
  /* House 3  */ 'Neptune en maison 3 donne une communication poétique, une pensée intuitive et une facilité avec le langage symbolique. Il peut y avoir de la confusion autour de l\'information concrète ou une idéalisation des frères et sœurs.',
  /* House 4  */ 'Neptune en maison 4 indique un foyer à l\'atmosphère nébuleuse — famille idéalisée ou absente d\'une certaine manière. Il peut y avoir des secrets familiaux. Votre véritable refuge est intérieur, spirituel.',
  /* House 5  */ 'Neptune en maison 5 apporte une profonde créativité artistique — musique, cinéma, poésie, danse. Des romances idéalisées qui peuvent décevoir. L\'expression créative est votre connexion au divin.',
  /* House 6  */ 'Neptune en maison 6 indique une sensibilité aux environnements de travail et de possibles conditions de santé difficiles à diagnostiquer. Vous travaillez mieux dans des activités impliquant la guérison, l\'art ou la compassion.',
  /* House 7  */ 'Neptune en maison 7 peut mener à idéaliser les partenaires ou à se perdre dans les relations. La leçon est d\'aimer sans illusion — voir l\'autre tel qu\'il est, pas tel que vous souhaitez qu\'il soit. Des partenaires artistiques ou spirituels sont courants.',
  /* House 8  */ 'Neptune en maison 8 dissout les frontières de l\'intimité — expériences transcendantes dans la sexualité, confusion autour des ressources partagées. Intuition profonde sur la vie et la mort.',
  /* House 9  */ 'Neptune en maison 9 indique une foi profonde, des voyages qui transforment l\'âme et une attraction pour le mysticisme. Attention aux gourous ou systèmes de croyances qui promettent un salut facile.',
  /* House 10 */ 'Neptune en maison 10 indique une carrière dans les arts, la guérison, la spiritualité ou des domaines où la compassion est centrale. Votre image publique peut être difficile à cerner — les gens ne savent pas toujours exactement ce que vous faites.',
  /* House 11 */ 'Neptune en maison 11 idéalise les amitiés et les causes sociales. Vous pouvez être déçu·e par les groupes ou attirer des amis qui ont besoin d\'être sauvés. La mission est de servir le collectif sans vous sacrifier.',
  /* House 12 */ 'Neptune en maison 12 est dans sa maison naturelle — spiritualité profonde, intuition océanique, connexion avec l\'inconscient collectif. Vous pouvez être guérisseur·se, artiste ou médium. La solitude régulière est essentielle.',
];

// ============================================================
// PLUTON EN MAISON
// ============================================================
export const PLUTO_IN_HOUSE: string[] = [
  /* House 1  */ 'Pluton en maison 1 vous donne une présence intense et magnétique. Vous vous réinventez de manière répétée au cours de votre vie. Les gens sentent votre énergie avant que vous ne parliez. Vous pouvez intimider sans le vouloir.',
  /* House 2  */ 'Pluton en maison 2 indique de profondes transformations liées à l\'argent, aux valeurs et à l\'estime de soi. Vous pouvez tout perdre et reconstruire. Votre relation avec les ressources est intense — tout ou rien.',
  /* House 3  */ 'Pluton en maison 3 donne un esprit investigateur et des mots puissants. Communication intense, capacité de persuasion. Vous avez peut-être eu des expériences transformatrices avec vos frères et sœurs ou dans l\'environnement scolaire.',
  /* House 4  */ 'Pluton en maison 4 indique des dynamiques familiales intenses — secrets, pouvoir, transformation aux racines. L\'enfance a peut-être été marquée par le contrôle ou la perte. La guérison vient en transformant votre compréhension du foyer.',
  /* House 5  */ 'Pluton en maison 5 apporte une créativité obsessionnelle et des romances intenses, presque compulsives. La relation avec les enfants peut être transformatrice. Vous créez avec une passion viscérale.',
  /* House 6  */ 'Pluton en maison 6 peut indiquer des crises de santé qui mènent à une régénération complète, ou un travail qui implique de transformer les systèmes. Vous avez le pouvoir de guérir — mais vous devez d\'abord prendre soin de vous.',
  /* House 7  */ 'Pluton en maison 7 attire des relations intenses et transformatrices. Des dynamiques de pouvoir dans les partenariats. La leçon n\'est ni de contrôler l\'autre ni de se soumettre — mais de se transformer ensemble.',
  /* House 8  */ 'Pluton en maison 8 est dans sa maison naturelle — intensité maximale dans la transformation, la sexualité, le pouvoir et les ressources partagées. Vous êtes rené·e de nombreuses fois dans cette vie. Rien n\'est superficiel.',
  /* House 9  */ 'Pluton en maison 9 transforme vos croyances radicalement au cours de votre vie. Les voyages peuvent être des expériences de mort et de renaissance. Vous poursuivez la vérité avec obsession — les réponses superficielles ne suffisent jamais.',
  /* House 10 */ 'Pluton en maison 10 indique du pouvoir dans la carrière — vous transformez votre domaine professionnel. Vous pouvez faire face à des luttes de pouvoir avec l\'autorité avant d\'en devenir une vous-même. La carrière comme transformation.',
  /* House 11 */ 'Pluton en maison 11 transforme les groupes auxquels vous appartenez. Vous pouvez avoir des amitiés intenses ou des ruptures avec des collectifs. Vous êtes un agent de changement social — mais vous devez faire attention à ne pas manipuler.',
  /* House 12 */ 'Pluton en maison 12 indique un pouvoir caché dans l\'inconscient. Des transformations profondes qui se produisent en coulisses. Vous pouvez éprouver des peurs intenses sans cause apparente — des résidus de vies passées qui demandent à être intégrés.',
];

// ============================================================
// CHIRON EN MAISON
// ============================================================
export const CHIRON_IN_HOUSE: string[] = [
  /* House 1  */ 'Chiron en maison 1 pointe vers une blessure autour de l\'identité et du droit d\'exister tel·le que vous êtes. Vous avez peut-être grandi en sentant que quelque chose n\'allait pas chez vous — dans votre corps, votre comportement, votre manière d\'être. Mais c\'est précisément cette sensibilité à la connaissance de soi qui vous rend capable d\'aider les autres à se trouver. En acceptant votre propre singularité sans avoir besoin de la justifier, vous devenez un miroir de guérison pour le monde.',
  /* House 2  */ 'Chiron en maison 2 touche la blessure de l\'estime de soi et de la sécurité matérielle. Vous avez peut-être appris tôt que l\'amour était conditionnel à ce que vous produisiez, possédiez ou fournissiez. Le chemin de guérison passe par la construction d\'une relation saine avec vos talents et ressources — reconnaître que votre valeur existe indépendamment de ce que vous possédez. Ce faisant, vous devenez un guide puissant pour ceux qui cherchent encore l\'approbation extérieure.',
  /* House 3  */ 'Chiron en maison 3 révèle une blessure dans la communication et l\'expression intellectuelle. Vous avez peut-être senti que vos mots n\'étaient pas entendus, que vous n\'étiez « pas assez intelligent·e » ou que vous n\'aviez pas le droit de parler. Le don qui émerge est une sensibilité unique au langage — vous apprenez à communiquer avec profondeur et soin, devenant un mentor qui donne une voix à ceux qui ressentent la même chose.',
  /* House 4  */ 'Chiron en maison 4 indique une blessure dans les racines — famille d\'origine, sentiment d\'appartenance, sécurité émotionnelle. Vous avez peut-être grandi sans un foyer émotionnellement stable ou senti que vous ne correspondiez pas à votre famille. Le processus de guérison implique de créer vos propres racines et de définir ce que « chez soi » signifie pour vous. Quand vous le faites, vous devenez un ancrage pour les autres qui cherchent aussi l\'appartenance.',
  /* House 5  */ 'Chiron en maison 5 touche la blessure de la créativité, de l\'authenticité et de la joie. Vous avez peut-être reçu des messages que votre expression créative n\'était pas assez bonne, ou que le plaisir était dangereux ou interdit. Le don qui émerge est une créativité profonde et courageuse — en vous autorisant à créer et à vous réjouir sans jugement, vous inspirez les autres à retrouver leur propre rayonnement.',
  /* House 6  */ 'Chiron en maison 6 révèle une blessure dans la relation au travail, à la santé et à la routine quotidienne. Vous avez peut-être appris que vous deviez être parfait·e pour mériter votre place, ou que prendre soin des autres était une obligation tandis que prendre soin de soi était égoïste. Le chemin de guérison passe par la compréhension que le service doit venir d\'un lieu de plénitude, pas de culpabilité. Vous devenez un modèle de soin de soi conscient.',
  /* House 7  */ 'Chiron en maison 7 touche la blessure dans les relations et le partenariat. Vous avez peut-être vécu des pertes, des rejets ou des schémas relationnels douloureux qui ont créé une peur de l\'engagement ou de se révéler. Le don qui émerge est une compréhension profonde des dynamiques relationnelles — en guérissant cette blessure, vous devenez quelqu\'un capable de créer des connexions authentiques et de guider les autres dans leurs relations.',
  /* House 8  */ 'Chiron en maison 8 indique une blessure connectée à la perte, aux transformations forcées, au pouvoir et à l\'intimité profonde. Vous avez peut-être vécu des situations d\'extrême vulnérabilité — financière, émotionnelle ou liée à la mort et aux cycles de vie. Le don qui émerge est une force de renouveau peu commune et une capacité unique à accompagner les autres dans les passages les plus difficiles de la vie.',
  /* House 9  */ 'Chiron en maison 9 touche la blessure dans les croyances, la spiritualité et la quête de sens. Vous avez peut-être souffert sous des dogmes rigides, senti que votre vision du monde était invalide, ou eu des expériences qui ont profondément ébranlé votre foi. Le chemin de guérison est de construire une philosophie de vie qui est vraiment la vôtre. Ce faisant, vous devenez un guide spirituel d\'un rare discernement.',
  /* House 10 */ 'Chiron en maison 10 révèle une blessure dans la carrière, l\'héritage et la relation à l\'autorité. Vous avez peut-être eu des difficultés avec les figures parentales, la reconnaissance professionnelle ou le droit d\'occuper des positions de premier plan. Le processus de guérison passe par la revendication de votre autorité sans avoir besoin de validation extérieure. Quand vous le faites, vous devenez une référence inspirante pour les autres qui cherchent leur propre place dans le monde.',
  /* House 11 */ 'Chiron en maison 11 touche la blessure de l\'appartenance collective et de l\'amitié. Vous avez peut-être senti l\'exclusion des groupes, trop différent·e pour appartenir où que ce soit, ou déçu·e par des amitiés qui n\'ont pas tenu leurs promesses. Le don qui émerge est la capacité de construire des communautés véritablement inclusives et de reconnaître la valeur chez ceux qui se sentent en marge.',
  /* House 12 */ 'Chiron en maison 12 indique une blessure spirituelle profonde liée à l\'isolement, l\'invisibilité et la douleur inexprimée. Vous avez peut-être porté des blessures dans la solitude, senti que vous deviez cacher ce que vous ressentiez, ou vécu l\'enfermement ou l\'exclusion. Le don qui émerge de cette profondeur est une capacité extraordinaire de compassion, d\'écoute profonde et de guérison silencieuse — vous touchez l\'âme des gens sans avoir besoin de mots.',
];

// ============================================================
// CHIRON EN SIGNE
// ============================================================
export const CHIRON_IN_SIGN: string[] = [
  /* Aries       */ 'Avec Chiron en Bélier, la blessure a une qualité active, centrée sur l\'identité — elle implique le droit d\'agir, d\'exister avec force et de passer en premier. Le chemin de guérison passe par la reconquête du courage d\'exister sans demander la permission.',
  /* Taurus      */ 'Avec Chiron en Taureau, la blessure touche la valeur intrinsèque et la sécurité corporelle. Elle implique la croyance qu\'on doit mériter le plaisir et le confort. La guérison vient en habitant son corps avec paix et en ayant confiance que vous êtes suffisant·e.',
  /* Gemini      */ 'Avec Chiron en Gémeaux, la blessure a une qualité communicative et intellectuelle — elle implique des doutes sur votre propre intelligence ou le droit d\'être entendu·e. La guérison vient en faisant confiance à votre propre voix et à l\'unicité de votre pensée.',
  /* Cancer      */ 'Avec Chiron en Cancer, la blessure touche le monde émotionnel et familial. Elle implique des questions d\'appartenance, de nourriture et de sécurité émotionnelle. La guérison vient en apprenant à vous nourrir avec la même générosité que vous offrez aux autres.',
  /* Leo         */ 'Avec Chiron en Lion, la blessure a une qualité expressive et créative — elle implique le droit de briller, d\'être vu·e et de s\'exprimer sans jugement. La guérison vient en reconquérant la joie de l\'expression authentique de soi.',
  /* Virgo       */ 'Avec Chiron en Vierge, la blessure touche la perfection, l\'utilité et la santé. Elle peut impliquer le sentiment de n\'être jamais assez bien, ou que votre valeur dépend de combien vous servez. La guérison vient en embrassant l\'imperfection comme partie de la complétude.',
  /* Libra       */ 'Avec Chiron en Balance, la blessure a une qualité relationnelle — elle implique l\'équilibre, la justice et le droit d\'avoir des besoins dans les relations. La guérison vient en apprenant que la vraie harmonie inclut votre propre voix.',
  /* Scorpio     */ 'Avec Chiron en Scorpion, la blessure touche la transformation, le pouvoir et l\'intimité. Elle implique des peurs profondes de perte, de trahison ou de vulnérabilité. La guérison vient en embrassant la profondeur émotionnelle comme un don, pas un fardeau.',
  /* Sagittarius */ 'Avec Chiron en Sagittaire, la blessure a une qualité philosophique et spirituelle. Elle peut impliquer la perte de foi, des conflits de croyances ou le sentiment que la vérité est hors d\'atteinte. La guérison vient en construisant une sagesse qui est la vôtre, fondée sur l\'expérience vécue.',
  /* Capricorn   */ 'Avec Chiron en Capricorne, la blessure touche l\'ambition, la responsabilité et la relation à l\'autorité. Elle peut impliquer une pression excessive pour les résultats ou la croyance qu\'on doit souffrir pour réussir. La guérison vient en redéfinissant le succès selon vos propres termes.',
  /* Aquarius    */ 'Avec Chiron en Verseau, la blessure a une qualité collective — elle implique le sentiment d\'être trop différent·e, de n\'appartenir nulle part. La guérison vient en transformant cette singularité en don et en utilisant votre vision du futur pour inspirer le changement.',
  /* Pisces      */ 'Avec Chiron en Poissons, la blessure touche la dissolution, la spiritualité et les frontières de l\'ego. Elle peut impliquer un sentiment de se perdre dans les autres ou dans la souffrance collective. La guérison vient en apprenant la compassion avec des limites — servir le monde sans s\'y perdre.',
];

// ============================================================
// NŒUD NORD EN MAISON
// ============================================================
export const NORTH_NODE_HOUSE: string[] = [
  /* House 1  */ 'Nœud Nord en maison 1 : Vous avez déjà maîtrisé le « nous » (partenariat, diplomatie) et êtes venu·e apprendre l\'indépendance — vous mettre en premier sans culpabilité. Votre mission est de développer votre propre identité.',
  /* House 2  */ 'Nœud Nord en maison 2 : Vous avez déjà maîtrisé la transformation et les ressources des autres. Maintenant vous êtes venu·e apprendre à construire votre propre sécurité et vos propres valeurs. L\'autosuffisance est le chemin.',
  /* House 3  */ 'Nœud Nord en maison 3 : Vous portez déjà la sagesse de l\'étude profonde (maison 9) et êtes venu·e apprendre à communiquer avec légèreté, à enseigner de manière accessible et à écouter plus que vous ne prêchez.',
  /* House 4  */ 'Nœud Nord en maison 4 : Vous avez déjà maîtrisé la vie publique et la carrière. Maintenant vous êtes venu·e apprendre à nourrir vos fondations émotionnelles, prendre soin de la famille et créer de véritables racines.',
  /* House 5  */ 'Nœud Nord en maison 5 : Vous appartenez déjà aux groupes et causes collectives. Maintenant vous êtes venu·e apprendre à briller individuellement, à créer, à jouer sans culpabilité. L\'expression personnelle est le chemin.',
  /* House 6  */ 'Nœud Nord en maison 6 : Vous avez déjà maîtrisé le monde spirituel et la solitude. Maintenant vous êtes venu·e apprendre à servir dans la vie quotidienne, à organiser la réalité pratique et à prendre soin du corps.',
  /* House 7  */ 'Nœud Nord en maison 7 : Vous êtes déjà indépendant·e et autosuffisant·e. Maintenant vous êtes venu·e apprendre à ouvrir un espace pour l\'autre — négocier, construire de véritables partenariats.',
  /* House 8  */ 'Nœud Nord en maison 8 : Vous avez déjà maîtrisé le confort matériel et la stabilité. Maintenant vous êtes venu·e apprendre à vous transformer, à vous abandonner, à naviguer le pouvoir et la vulnérabilité.',
  /* House 9  */ 'Nœud Nord en maison 9 : Vous avez déjà maîtrisé la communication et les connaissances superficielles. Maintenant vous êtes venu·e apprendre à approfondir, élargir les horizons et développer votre propre philosophie de vie.',
  /* House 10 */ 'Nœud Nord en maison 10 : Vous avez déjà maîtrisé le foyer et les émotions. Maintenant vous êtes venu·e apprendre à construire quelque chose dans le monde, à assumer des responsabilités publiques et à laisser un héritage.',
  /* House 11 */ 'Nœud Nord en maison 11 : Vous brillez déjà individuellement. Maintenant vous êtes venu·e apprendre à travailler pour des causes plus grandes, à vous intégrer dans des groupes et à penser collectivement.',
  /* House 12 */ 'Nœud Nord en maison 12 : Vous avez déjà maîtrisé l\'organisation et le service pratique. Maintenant vous êtes venu·e apprendre à lâcher le contrôle, faire confiance à votre intuition et vous connecter à quelque chose de transcendant.',
];

// ============================================================
// NŒUD NORD EN SIGNE
// ============================================================
export const NORTH_NODE_IN_SIGN: string[] = [
  /* Aries       */ 'Nœud Nord en Bélier : votre voyage évolutif est de développer l\'auto-leadership, le courage et le droit d\'agir par vous-même. Vous venez de vies (ou schémas) de dépendance, de diplomatie excessive et de recherche d\'approbation. La libération vient quand vous agissez sans attendre le consensus — quand vous prenez le risque d\'être impopulaire au nom de l\'authenticité.',
  /* Taurus      */ 'Nœud Nord en Taureau : votre voyage est de construire votre propre sécurité, de faire confiance à votre corps et au monde matériel. Vous venez de schémas de chaos, d\'intensité émotionnelle et de crise comme mode de vie. La libération vient quand vous vous autorisez les plaisirs simples, la stabilité sans drame et la confiance que le sol sous vos pieds ne se dérobera pas.',
  /* Gemini      */ 'Nœud Nord en Gémeaux : votre voyage est de cultiver la curiosité, l\'ouverture d\'esprit et la connexion avec votre environnement immédiat. Vous venez de schémas dogmatiques, de certitudes absolues et d\'une tendance à prêcher plutôt qu\'écouter. La libération vient quand vous vous autorisez à ne pas savoir — quand la question devient plus précieuse que la réponse.',
  /* Cancer      */ 'Nœud Nord en Cancer : votre voyage est l\'enracinement émotionnel — le foyer, le soin, la vulnérabilité. Vous venez de schémas de contrôle, d\'ambition rigide et de déni des besoins émotionnels. La libération vient quand vous vous autorisez à avoir besoin des autres, quand vous prenez soin sans calculer et quand le foyer devient un refuge plutôt qu\'une obligation.',
  /* Leo         */ 'Nœud Nord en Lion : votre voyage est de vous exprimer depuis le cœur, de briller individuellement et de créer avec générosité. Vous venez de schémas d\'anonymat collectif, de détachement intellectuel et de peur de se démarquer. La libération vient quand vous cessez de vous cacher derrière le groupe et prenez le risque d\'être véritablement vu·e.',
  /* Virgo       */ 'Nœud Nord en Vierge : votre voyage est de servir avec discernement, de prendre soin de la santé et d\'appliquer la spiritualité à la vie pratique quotidienne. Vous venez de schémas de dissolution, d\'idéalisme sans action et de fuite de la réalité matérielle. La libération vient quand vous découvrez que le sacré vit dans les détails du quotidien.',
  /* Libra       */ 'Nœud Nord en Balance : votre voyage est la guérison par le partenariat, l\'engagement et le pardon. Vous venez de schémas d\'isolement, d\'individualisme excessif et de difficulté à céder. La libération vient quand vous apprenez que la vraie force n\'est pas de tout faire seul·e — c\'est de se permettre d\'être complété·e.',
  /* Scorpio     */ 'Nœud Nord en Scorpion : votre voyage est de vous transformer en confrontant ce qui est caché — le pouvoir, l\'intimité, la vulnérabilité. Vous venez de schémas de confort, d\'attachement matériel et d\'évitement de la crise. La libération vient quand vous vous autorisez à mourir symboliquement pour renaître plus entier·e — quand vous acceptez que la vraie sécurité ne vient pas de la stabilité, mais de la capacité à se régénérer.',
  /* Sagittarius */ 'Nœud Nord en Sagittaire : votre voyage est d\'élargir les horizons, de construire la foi et de vivre votre vérité. Vous venez de schémas d\'anxiété informationnelle, de superficialité et de peur de s\'engager dans une vision. La libération vient quand vous arrêtez de collecter des données et commencez à vivre la sagesse — quand l\'expérience remplace la théorie.',
  /* Capricorn   */ 'Nœud Nord en Capricorne : votre voyage est de revendiquer votre vocation, construire une structure et laisser un héritage. Vous venez de schémas de dépendance émotionnelle, de victimisation familiale et de difficulté à prendre la responsabilité de votre propre chemin. La libération vient quand vous prenez la barre — quand vous cessez de blâmer les circonstances et construisez de vos propres mains.',
  /* Aquarius    */ 'Nœud Nord en Verseau : votre voyage est de servir le collectif, d\'embrasser l\'innovation et de penser au-delà de soi. Vous venez de schémas d\'ego gonflé, de besoin de reconnaissance personnelle et de difficulté à partager la lumière. La libération vient quand vous découvrez que votre brillance est la plus puissante quand elle illumine des causes plus grandes que vous.',
  /* Pisces      */ 'Nœud Nord en Poissons : votre voyage est l\'abandon spirituel — lâcher le contrôle, faire confiance à l\'intuition et dissoudre les frontières rigides de l\'ego. Vous venez de schémas d\'hyper-contrôle, de perfectionnisme et d\'anxiété de « bien faire ». La libération vient quand vous vous autorisez à couler — quand vous acceptez que tout n\'a pas besoin d\'être analysé pour être vrai.',
];

// ============================================================
// NOMS ET LABELS — Français

export const SIGN_NAMES = ['Bélier','Taureau','Gémeaux','Cancer','Lion','Vierge','Balance','Scorpion','Sagittaire','Capricorne','Verseau','Poissons'];
export const PLANET_NAMES: Record<string,string> = { sun:'Soleil', moon:'Lune', mercury:'Mercure', venus:'Vénus', mars:'Mars', jupiter:'Jupiter', saturn:'Saturne', uranus:'Uranus', neptune:'Neptune', pluto:'Pluton', northNode:'Nœud Nord', chiron:'Chiron', lilith:'Lilith' };
export const MONTHS = ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'];

export const SECTION_TITLES = {
  sun: (house: number, sign: string) => `☉ Soleil en Maison ${house} en ${sign}`,
  moon: (house: number, sign: string) => `☽ Lune en Maison ${house} en ${sign}`,
  mercury: (house: number, sign: string) => `☿ Mercure en Maison ${house} en ${sign}`,
  venus: (house: number, sign: string) => `♀ Vénus en Maison ${house} en ${sign}`,
  mars: (house: number, sign: string) => `♂ Mars en Maison ${house} en ${sign}`,
  jupiter: (house: number, sign: string) => `♃ Jupiter en Maison ${house} en ${sign}`,
  saturn: (house: number, sign: string) => `♄ Saturne en Maison ${house} en ${sign}`,
  uranus: (house: number, sign: string) => `♅ Uranus en Maison ${house} en ${sign}`,
  neptune: (house: number, sign: string) => `♆ Neptune en Maison ${house} en ${sign}`,
  pluto: (house: number, sign: string) => `♇ Pluton en Maison ${house} en ${sign}`,
  northNode: (house: number, sign: string) => `☊ Nœud Nord en Maison ${house} en ${sign}`,
  chiron: (house: number, sign: string) => `⚷ Chiron en Maison ${house} en ${sign}`,
  ascendant: (sign: string) => `Ascendant en ${sign}`,
};

export const PLANET_SUBTITLES: Record<string,string> = {
  sun:'Votre essence solaire — identité, but et énergie vitale', moon:'Votre monde émotionnel — besoins, instincts et sécurité intérieure', mercury:'Votre esprit et communication — comment vous pensez et apprenez', venus:'Votre langage amoureux — ce que vous attirez et désirez', mars:'Votre élan et action — comment vous poursuivez vos objectifs', jupiter:'Votre voie d\'expansion — où coulent abondance et croissance', saturn:'Votre zone de maîtrise — où la discipline forge des acquis durables', uranus:'Votre révolution intérieure — où vous brisez les schémas', neptune:'Votre portail spirituel — où vous dissolvez les frontières', pluto:'Votre pouvoir transformateur — mort et renaissance profondes', northNode:'Votre but évolutif — la direction de votre âme', chiron:'Votre blessure sacrée — la douleur qui devient don de guérison',
};

export const LABELS = {
  reportTitle:'Rapport Natal Complet', reportSubtitle:'Interprétation Profonde', positions:'Positions Planétaires', houses:'Cuspides des Maisons', overview:'Vue d\'Ensemble', potentials:'Vos 5 Plus Grands Potentiels', challenges:'Vos 5 Principaux Défis', conclusion:'Conclusion', advice:'Conseil Pratique', elements:'Éléments et Modalités', dignities:'Dignités Essentielles', aspects:'Aspects Majeurs', themes:'Synthèse Thématique', quote:'"Les astres inclinent, ils ne déterminent pas."', sampleNote:'Ceci était un aperçu gratuit !', sampleFull:'Le rapport complet contient 20-30 pages avec interprétation détaillée.', buyNow:'Version complète :', buyInstant:'Achetez maintenant et téléchargez instantanément — 100% dans votre navigateur.', natalChart:'Votre Carte Natale', retrograde:'(rétrograde)',
  annualTitle:'Prévision Annuelle', annualSubtitle:'Transits et tendances', profection:'Profection Annuelle — Thème de l\'Année', houseInFocus:'en Focus', rulerOfYear:'Maître de l\'Année', eclipses:'Éclipses de l\'Année', jupiterExpansion:'L\'Expansion de l\'Année', saturnLesson:'La Leçon de l\'Année', conclusionAnnual:'Conclusion — Votre Année en Perspective',
  relationshipTitle:'Rapport de Relation', compatibility:'Compatibilité', emotionalConnection:'Connexion Émotionnelle', attractionChemistry:'Attraction et Chimie', communication:'Communication', commitmentLimits:'Engagement et Limites — Saturne', growthPotential:'Potentiel de Croissance', challengesTension:'Points de Tension',
  psychTitle:'Analyse Psychologique Profonde', egoStructure:'Structure de l\'Ego — Soleil et Ascendant', emotionalWorld:'Monde Émotionnel — Lune', mentalProcesses:'Processus Mentaux — Mercure', lovePatterns:'Schémas Amoureux — Vénus', vitalForce:'Force Vitale — Mars', shadow:'Ombre — Pluton', wound:'Blessure Centrale — Chiron', unconscious:'Inconscient — Maison 12 et Neptune', familyPatterns:'Schémas Familiaux — Lune, Maison 4 et Saturne', defenseMechanisms:'Mécanismes de Défense — Saturne', integrationPath:'Chemin d\'Intégration — Nœud Nord',
  careerTitle:'Carrière et Vocation', midheaven:'Milieu du Ciel', house10:'Maison 10 — Vocation', house6:'Maison 6 — Routine et Travail', house2:'Maison 2 — Ressources et Talents',
  sinsTitle:'Les Sept Péchés', pride:'Orgueil — Soleil', lust:'Luxure — Vénus et Mars', greed:'Avarice — Saturne', gluttony:'Gourmandise — Jupiter', wrath:'Colère — Mars', envy:'Envie — Pluton', sloth:'Paresse — Neptune',
  repetitivePatterns:'Schémas Répétitifs — Carrés et Oppositions', unexploredPotentials:'Potentiels Inexplorés — Trigones et Talents', integrationPaths:'Chemins d\'Intégration', recommendedPractices:'Pratiques Recommandées', childhoodTemplate:'Enfance et Schéma Émotionnel', fromWoundToGift:'De la Blessure au Don', differentiation:'Différenciation — Être Vous, Pas Votre Famille', mainTensions:'Tensions Principales de la Carte', plutoAspects:'Aspects Tendus de Pluton',
};

export const TRANSITIONS = {
  afterOverview:'Cette base identitaire se manifeste concrètement en observant les planètes dans leurs maisons.',
  afterPersonalPlanets:'Les aspects entre planètes révèlent comment ces énergies dialoguent entre elles.',
  afterAspects:'De ces interactions émergent des schémas — thèmes centraux de votre expérience.',
  beforeConclusion:'En rassemblant tout ce que nous avons vu, votre carte raconte une histoire cohérente.',
};
