// INTERPRETATIONS — Italiano (it)
import { SUN_IN_HOUSE, MOON_IN_HOUSE, MERCURY_IN_HOUSE } from './pt';
import { VENUS_IN_HOUSE, MARS_IN_HOUSE, NORTH_NODE_HOUSE, NORTH_NODE_IN_SIGN } from '../interpret';
import { JUPITER_IN_HOUSE, SATURN_IN_HOUSE, URANUS_IN_HOUSE, NEPTUNE_IN_HOUSE, PLUTO_IN_HOUSE } from '../outer-planets';
import { CHIRON_IN_HOUSE, CHIRON_IN_SIGN } from '../chiron';
export { SUN_IN_HOUSE, MOON_IN_HOUSE, MERCURY_IN_HOUSE, VENUS_IN_HOUSE, MARS_IN_HOUSE };
export { JUPITER_IN_HOUSE, SATURN_IN_HOUSE, URANUS_IN_HOUSE, NEPTUNE_IN_HOUSE, PLUTO_IN_HOUSE };
export { CHIRON_IN_HOUSE, CHIRON_IN_SIGN, NORTH_NODE_HOUSE, NORTH_NODE_IN_SIGN };

export const SIGN_NAMES = ['Ariete','Toro','Gemelli','Cancro','Leone','Vergine','Bilancia','Scorpione','Sagittario','Capricorno','Acquario','Pesci'];
export const PLANET_NAMES: Record<string,string> = { sun:'Sole', moon:'Luna', mercury:'Mercurio', venus:'Venere', mars:'Marte', jupiter:'Giove', saturn:'Saturno', uranus:'Urano', neptune:'Nettuno', pluto:'Plutone', northNode:'Nodo Nord', chiron:'Chirone', lilith:'Lilith' };
export const MONTHS = ['Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre'];
export const SECTION_TITLES = { sun:(h:number,s:string)=>`☉ Sole in Casa ${h} in ${s}`, moon:(h:number,s:string)=>`☽ Luna in Casa ${h} in ${s}`, mercury:(h:number,s:string)=>`☿ Mercurio in Casa ${h} in ${s}`, venus:(h:number,s:string)=>`♀ Venere in Casa ${h} in ${s}`, mars:(h:number,s:string)=>`♂ Marte in Casa ${h} in ${s}`, jupiter:(h:number,s:string)=>`♃ Giove in Casa ${h} in ${s}`, saturn:(h:number,s:string)=>`♄ Saturno in Casa ${h} in ${s}`, uranus:(h:number,s:string)=>`♅ Urano in Casa ${h} in ${s}`, neptune:(h:number,s:string)=>`♆ Nettuno in Casa ${h} in ${s}`, pluto:(h:number,s:string)=>`♇ Plutone in Casa ${h} in ${s}`, northNode:(h:number,s:string)=>`☊ Nodo Nord in Casa ${h} in ${s}`, chiron:(h:number,s:string)=>`⚷ Chirone in Casa ${h} in ${s}`, ascendant:(s:string)=>`Ascendente in ${s}` };
export const PLANET_SUBTITLES: Record<string,string> = { sun:'La tua essenza solare — identità, scopo ed energia vitale', moon:'Il tuo mondo emotivo — bisogni, istinti e sicurezza interiore', mercury:'La tua mente e comunicazione — come pensi e impari', venus:'Il tuo linguaggio d\'amore — cosa attrai e desideri', mars:'Il tuo slancio e azione — come persegui gli obiettivi', jupiter:'Il tuo percorso di espansione — dove fluiscono abbondanza e crescita', saturn:'La tua zona di padronanza — dove la disciplina forgia risultati duraturi', uranus:'La tua rivoluzione interiore — dove rompi gli schemi', neptune:'Il tuo portale spirituale — dove dissolvi i confini', pluto:'Il tuo potere trasformativo — morte e rinascita profonde', northNode:'Il tuo scopo evolutivo — la direzione della tua anima', chiron:'La tua ferita sacra — il dolore che diventa dono di guarigione' };
export const LABELS = { reportTitle:'Report Natale Completo', reportSubtitle:'Interpretazione Profonda', positions:'Posizioni Planetarie', houses:'Cuspidi delle Case', overview:'Panoramica', potentials:'I Tuoi 5 Maggiori Potenziali', challenges:'Le Tue 5 Sfide Principali', conclusion:'Conclusione', advice:'Consiglio Pratico', elements:'Elementi e Modalità', dignities:'Dignità Essenziali', aspects:'Aspetti Principali', themes:'Sintesi Tematica', quote:'"Gli astri inclinano, non obbligano."', sampleNote:'Questa era un\'anteprima gratuita!', sampleFull:'Il report completo contiene 20-30 pagine con interpretazione dettagliata.', buyNow:'Versione completa:', buyInstant:'Acquista ora e scarica istantaneamente — 100% nel browser.', natalChart:'La Tua Carta Natale', retrograde:'(retrogrado)', annualTitle:'Previsione Annuale', annualSubtitle:'Transiti e tendenze', profection:'Profezione Annuale — Tema dell\'Anno', houseInFocus:'in Focus', rulerOfYear:'Reggente dell\'Anno', eclipses:'Eclissi dell\'Anno', jupiterExpansion:'L\'Espansione dell\'Anno', saturnLesson:'La Lezione dell\'Anno', conclusionAnnual:'Conclusione — Il Tuo Anno in Prospettiva', relationshipTitle:'Report di Relazione', compatibility:'Compatibilità', emotionalConnection:'Connessione Emotiva', attractionChemistry:'Attrazione e Chimica', communication:'Comunicazione', commitmentLimits:'Impegno e Limiti — Saturno', growthPotential:'Potenziale di Crescita', challengesTension:'Punti di Tensione', psychTitle:'Analisi Psicologica Profonda', egoStructure:'Struttura dell\'Ego — Sole e Ascendente', emotionalWorld:'Mondo Emotivo — Luna', mentalProcesses:'Processi Mentali — Mercurio', lovePatterns:'Schemi d\'Amore — Venere', vitalForce:'Forza Vitale — Marte', shadow:'Ombra — Plutone', wound:'Ferita Centrale — Chirone', unconscious:'Inconscio — Casa 12 e Nettuno', familyPatterns:'Schemi Familiari — Luna, Casa 4 e Saturno', defenseMechanisms:'Meccanismi di Difesa — Saturno', integrationPath:'Percorso di Integrazione — Nodo Nord', careerTitle:'Carriera e Vocazione', midheaven:'Medio Cielo', house10:'Casa 10 — Vocazione', house6:'Casa 6 — Routine e Lavoro', house2:'Casa 2 — Risorse e Talenti', sinsTitle:'I Sette Peccati', pride:'Orgoglio — Sole', lust:'Lussuria — Venere e Marte', greed:'Avarizia — Saturno', gluttony:'Gola — Giove', wrath:'Ira — Marte', envy:'Invidia — Plutone', sloth:'Accidia — Nettuno', repetitivePatterns:'Schemi Ripetitivi — Quadrature e Opposizioni', unexploredPotentials:'Potenziali Inesplorati — Trigoni e Talenti', integrationPaths:'Percorsi di Integrazione', recommendedPractices:'Pratiche Raccomandate', childhoodTemplate:'Infanzia e Schema Emotivo', fromWoundToGift:'Dalla Ferita al Dono', differentiation:'Differenziazione — Essere Te Stesso', mainTensions:'Tensioni Principali della Carta', plutoAspects:'Aspetti Tesi di Plutone' };
export const TRANSITIONS = { afterOverview:'Questa base identitaria si manifesta concretamente osservando i pianeti nelle loro case.', afterPersonalPlanets:'Gli aspetti tra pianeti rivelano come queste energie dialogano tra loro.', afterAspects:'Da queste interazioni emergono schemi — temi centrali della tua esperienza.', beforeConclusion:'Riunendo tutto, la tua carta racconta una storia coerente.' };
