// INTERPRETATIONS — 日本語 (ja)
import { SUN_IN_HOUSE, MOON_IN_HOUSE, MERCURY_IN_HOUSE } from './pt';
import { VENUS_IN_HOUSE, MARS_IN_HOUSE, NORTH_NODE_HOUSE, NORTH_NODE_IN_SIGN } from '../interpret';
import { JUPITER_IN_HOUSE, SATURN_IN_HOUSE, URANUS_IN_HOUSE, NEPTUNE_IN_HOUSE, PLUTO_IN_HOUSE } from '../outer-planets';
import { CHIRON_IN_HOUSE, CHIRON_IN_SIGN } from '../chiron';
export { SUN_IN_HOUSE, MOON_IN_HOUSE, MERCURY_IN_HOUSE, VENUS_IN_HOUSE, MARS_IN_HOUSE };
export { JUPITER_IN_HOUSE, SATURN_IN_HOUSE, URANUS_IN_HOUSE, NEPTUNE_IN_HOUSE, PLUTO_IN_HOUSE };
export { CHIRON_IN_HOUSE, CHIRON_IN_SIGN, NORTH_NODE_HOUSE, NORTH_NODE_IN_SIGN };
export const SIGN_NAMES = ['牡羊座','牡牛座','双子座','蟹座','獅子座','乙女座','天秤座','蠍座','射手座','山羊座','水瓶座','魚座'];
export const PLANET_NAMES: Record<string,string> = { sun:'太陽', moon:'月', mercury:'水星', venus:'金星', mars:'火星', jupiter:'木星', saturn:'土星', uranus:'天王星', neptune:'海王星', pluto:'冥王星', northNode:'ノースノード', chiron:'キロン', lilith:'リリス' };
export const MONTHS = ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'];
export const SECTION_TITLES = { sun:(h:number,s:string)=>`☉ 太陽 第${h}ハウス ${s}`, moon:(h:number,s:string)=>`☽ 月 第${h}ハウス ${s}`, mercury:(h:number,s:string)=>`☿ 水星 第${h}ハウス ${s}`, venus:(h:number,s:string)=>`♀ 金星 第${h}ハウス ${s}`, mars:(h:number,s:string)=>`♂ 火星 第${h}ハウス ${s}`, jupiter:(h:number,s:string)=>`♃ 木星 第${h}ハウス ${s}`, saturn:(h:number,s:string)=>`♄ 土星 第${h}ハウス ${s}`, uranus:(h:number,s:string)=>`♅ 天王星 第${h}ハウス ${s}`, neptune:(h:number,s:string)=>`♆ 海王星 第${h}ハウス ${s}`, pluto:(h:number,s:string)=>`♇ 冥王星 第${h}ハウス ${s}`, northNode:(h:number,s:string)=>`☊ ノースノード 第${h}ハウス ${s}`, chiron:(h:number,s:string)=>`⚷ キロン 第${h}ハウス ${s}`, ascendant:(s:string)=>`アセンダント ${s}` };
export const PLANET_SUBTITLES: Record<string,string> = { sun:'あなたの太陽の本質 — アイデンティティ、目的、生命エネルギー', moon:'あなたの感情の世界 — ニーズ、本能、内なる安心感', mercury:'あなたの知性とコミュニケーション — 思考と学びの方法', venus:'あなたの愛の言語 — 引き寄せるもの、大切にするもの', mars:'あなたの衝動と行動 — 目標の追求方法', jupiter:'あなたの拡大の道 — 豊かさと成長が流れる場所', saturn:'あなたの習熟の領域 — 規律が永続的な成果を生む場所', uranus:'あなたの内なる革命 — パターンを壊す場所', neptune:'あなたのスピリチュアルなポータル — 境界を溶かす場所', pluto:'あなたの変容の力 — 深い死と再生', northNode:'あなたの進化の目的 — 魂が向かう方向', chiron:'あなたの聖なる傷 — 癒しの贈り物となる痛み' };
export const LABELS = { reportTitle:'完全ネイタルレポート', reportSubtitle:'深層解釈', positions:'惑星位置', houses:'ハウスカスプ', overview:'概要', potentials:'あなたの5つの最大の可能性', challenges:'あなたの5つの主な課題', conclusion:'結論', advice:'実践的アドバイス', elements:'エレメントとモダリティ', dignities:'本質的品位', aspects:'主要アスペクト', themes:'テーマ別総合', quote:'"星は傾けるが、決定しない。"', sampleNote:'これは無料サンプルでした！', sampleFull:'完全版レポートは20-30ページの詳細な解釈を含みます。', buyNow:'完全版：', buyInstant:'今すぐ購入してダウンロード — 100%ブラウザで完結。', natalChart:'あなたのネイタルチャート', retrograde:'(逆行)', annualTitle:'年間予測', annualSubtitle:'トランジットと傾向', profection:'年間プロフェクション — 年のテーマ', houseInFocus:'フォーカス中', rulerOfYear:'年の支配星', eclipses:'年の食', jupiterExpansion:'年の拡大', saturnLesson:'年のレッスン', conclusionAnnual:'結論 — あなたの年を展望して', relationshipTitle:'関係性レポート', compatibility:'相性', emotionalConnection:'感情的つながり', attractionChemistry:'引力と化学反応', communication:'コミュニケーション', commitmentLimits:'コミットメントと限界 — 土星', growthPotential:'成長の可能性', challengesTension:'緊張点', psychTitle:'深層心理分析', egoStructure:'自我構造 — 太陽とアセンダント', emotionalWorld:'感情世界 — 月', mentalProcesses:'精神プロセス — 水星', lovePatterns:'愛のパターン — 金星', vitalForce:'生命力 — 火星', shadow:'影 — 冥王星', wound:'核心の傷 — キロン', unconscious:'無意識 — 第12ハウスと海王星', familyPatterns:'家族パターン — 月、第4ハウスと土星', defenseMechanisms:'防衛メカニズム — 土星', integrationPath:'統合の道 — ノースノード', careerTitle:'キャリアと天職', midheaven:'ミッドヘブン', house10:'第10ハウス — 天職', house6:'第6ハウス — 日常と仕事', house2:'第2ハウス — 資源と才能', sinsTitle:'七つの大罪', pride:'傲慢 — 太陽', lust:'色欲 — 金星と火星', greed:'強欲 — 土星', gluttony:'暴食 — 木星', wrath:'憤怒 — 火星', envy:'嫉妬 — 冥王星', sloth:'怠惰 — 海王星', repetitivePatterns:'繰り返しパターン — スクエアとオポジション', unexploredPotentials:'未開拓の可能性 — トラインと才能', integrationPaths:'統合の道筋', recommendedPractices:'推奨される実践', childhoodTemplate:'幼少期と感情的テンプレート', fromWoundToGift:'傷から贈り物へ', differentiation:'分化 — 自分自身であること', mainTensions:'チャートの主な緊張', plutoAspects:'冥王星の緊張アスペクト' };
export const TRANSITIONS = { afterOverview:'このアイデンティティの基盤は、各ハウスの惑星に具体的に現れます。', afterPersonalPlanets:'惑星間のアスペクトは、これらのエネルギーがどのように相互作用するかを示します。', afterAspects:'これらの相互作用からパターンが生まれます — あなたの経験の中心テーマです。', beforeConclusion:'すべてをまとめると、あなたのチャートは一貫した物語を語ります。' };
