// INTERPRETATIONS — Nederlands (nl)
import { SUN_IN_HOUSE, MOON_IN_HOUSE, MERCURY_IN_HOUSE } from './pt';
import { VENUS_IN_HOUSE, MARS_IN_HOUSE, NORTH_NODE_HOUSE, NORTH_NODE_IN_SIGN } from '../interpret';
import { JUPITER_IN_HOUSE, SATURN_IN_HOUSE, URANUS_IN_HOUSE, NEPTUNE_IN_HOUSE, PLUTO_IN_HOUSE } from '../outer-planets';
import { CHIRON_IN_HOUSE, CHIRON_IN_SIGN } from '../chiron';
export { SUN_IN_HOUSE, MOON_IN_HOUSE, MERCURY_IN_HOUSE, VENUS_IN_HOUSE, MARS_IN_HOUSE };
export { JUPITER_IN_HOUSE, SATURN_IN_HOUSE, URANUS_IN_HOUSE, NEPTUNE_IN_HOUSE, PLUTO_IN_HOUSE };
export { CHIRON_IN_HOUSE, CHIRON_IN_SIGN, NORTH_NODE_HOUSE, NORTH_NODE_IN_SIGN };
export const SIGN_NAMES = ['Ram','Stier','Tweelingen','Kreeft','Leeuw','Maagd','Weegschaal','Schorpioen','Boogschutter','Steenbok','Waterman','Vissen'];
export const PLANET_NAMES: Record<string,string> = { sun:'Zon', moon:'Maan', mercury:'Mercurius', venus:'Venus', mars:'Mars', jupiter:'Jupiter', saturn:'Saturnus', uranus:'Uranus', neptune:'Neptunus', pluto:'Pluto', northNode:'Noordknoop', chiron:'Chiron', lilith:'Lilith' };
export const MONTHS = ['Januari','Februari','Maart','April','Mei','Juni','Juli','Augustus','September','Oktober','November','December'];
export const SECTION_TITLES = { sun:(h:number,s:string)=>`☉ Zon in Huis ${h} in ${s}`, moon:(h:number,s:string)=>`☽ Maan in Huis ${h} in ${s}`, mercury:(h:number,s:string)=>`☿ Mercurius in Huis ${h} in ${s}`, venus:(h:number,s:string)=>`♀ Venus in Huis ${h} in ${s}`, mars:(h:number,s:string)=>`♂ Mars in Huis ${h} in ${s}`, jupiter:(h:number,s:string)=>`♃ Jupiter in Huis ${h} in ${s}`, saturn:(h:number,s:string)=>`♄ Saturnus in Huis ${h} in ${s}`, uranus:(h:number,s:string)=>`♅ Uranus in Huis ${h} in ${s}`, neptune:(h:number,s:string)=>`♆ Neptunus in Huis ${h} in ${s}`, pluto:(h:number,s:string)=>`♇ Pluto in Huis ${h} in ${s}`, northNode:(h:number,s:string)=>`☊ Noordknoop in Huis ${h} in ${s}`, chiron:(h:number,s:string)=>`⚷ Chiron in Huis ${h} in ${s}`, ascendant:(s:string)=>`Ascendant in ${s}` };
export const PLANET_SUBTITLES: Record<string,string> = { sun:'Uw zonne-essentie — identiteit, doel en levensenergie', moon:'Uw emotionele wereld — behoeften, instincten en innerlijke zekerheid', mercury:'Uw geest en communicatie — hoe u denkt en leert', venus:'Uw liefdestaal — wat u aantrekt en waardeert', mars:'Uw drijfveer en actie — hoe u doelen nastreeft', jupiter:'Uw expansiepad — waar overvloed en groei stromen', saturn:'Uw meesterschapszone — waar discipline duurzame prestaties smeedt', uranus:'Uw innerlijke revolutie — waar u patronen doorbreekt', neptune:'Uw spiritueel portaal — waar u grenzen oplost', pluto:'Uw transformatieve kracht — dood en wedergeboorte', northNode:'Uw evolutionaire doel — de richting van uw ziel', chiron:'Uw heilige wonde — pijn die een genezingsgeschenk wordt' };
export const LABELS = { reportTitle:'Volledig Geboorterapport', reportSubtitle:'Diepgaande Interpretatie', positions:'Planeetposities', houses:'Huistoppen', overview:'Overzicht', potentials:'Uw 5 Grootste Potenties', challenges:'Uw 5 Belangrijkste Uitdagingen', conclusion:'Conclusie', advice:'Praktisch Advies', elements:'Elementen en Modaliteiten', dignities:'Essentiële Waardigheden', aspects:'Hoofdaspecten', themes:'Thematische Synthese', quote:'"De sterren neigen, ze bepalen niet."', sampleNote:'Dit was een gratis voorbeeld!', sampleFull:'Het volledige rapport bevat 20-30 pagina\'s met gedetailleerde interpretatie.', buyNow:'Volledige versie:', buyInstant:'Koop nu en download direct — 100% in uw browser.', natalChart:'Uw Geboortekaart', retrograde:'(retrograde)', annualTitle:'Jaarvoorspelling', annualSubtitle:'Transits en tendensen', profection:'Jaarprofectie — Thema van het Jaar', houseInFocus:'in Focus', rulerOfYear:'Heerser van het Jaar', eclipses:'Eclipsen van het Jaar', jupiterExpansion:'De Expansie van het Jaar', saturnLesson:'De Les van het Jaar', conclusionAnnual:'Conclusie — Uw Jaar in Perspectief', relationshipTitle:'Relatierapport', compatibility:'Compatibiliteit', emotionalConnection:'Emotionele Verbinding', attractionChemistry:'Aantrekking en Chemie', communication:'Communicatie', commitmentLimits:'Betrokkenheid en Grenzen — Saturnus', growthPotential:'Groeipotentieel', challengesTension:'Spanningspunten', psychTitle:'Dieptepsychologische Analyse', egoStructure:'Ego-Structuur — Zon en Ascendant', emotionalWorld:'Emotionele Wereld — Maan', mentalProcesses:'Mentale Processen — Mercurius', lovePatterns:'Liefdespatronen — Venus', vitalForce:'Levenskracht — Mars', shadow:'Schaduw — Pluto', wound:'Kernwonde — Chiron', unconscious:'Onbewuste — 12e Huis en Neptunus', familyPatterns:'Familiepatronen — Maan, 4e Huis en Saturnus', defenseMechanisms:'Verdedigingsmechanismen — Saturnus', integrationPath:'Integratiepad — Noordknoop', careerTitle:'Carrière en Roeping', midheaven:'Medium Coeli', house10:'10e Huis — Roeping', house6:'6e Huis — Routine en Werk', house2:'2e Huis — Middelen en Talenten', sinsTitle:'De Zeven Zonden', pride:'Trots — Zon', lust:'Lust — Venus en Mars', greed:'Hebzucht — Saturnus', gluttony:'Gulzigheid — Jupiter', wrath:'Toorn — Mars', envy:'Jaloezie — Pluto', sloth:'Luiheid — Neptunus', repetitivePatterns:'Herhalingspatronen — Vierkanten en Opposities', unexploredPotentials:'Onontdekte Potenties — Driehoeken en Talenten', integrationPaths:'Integratiewegen', recommendedPractices:'Aanbevolen Praktijken', childhoodTemplate:'Jeugd en Emotioneel Patroon', fromWoundToGift:'Van Wonde naar Geschenk', differentiation:'Differentiatie — Uzelf Zijn', mainTensions:'Hoofdspanningen van de Kaart', plutoAspects:'Gespannen Pluto-Aspecten' };
export const TRANSITIONS = { afterOverview:'Deze identiteitsbasis manifesteert zich concreet in de planeten in hun huizen.', afterPersonalPlanets:'De aspecten tussen planeten onthullen hoe deze energieën met elkaar communiceren.', afterAspects:'Uit deze interacties ontstaan patronen — centrale thema\'s van uw ervaring.', beforeConclusion:'Alles samengenomen vertelt uw kaart een samenhangend verhaal.' };
