// Mercúrio nas casas — textos extensos separados para não poluir pt.ts principal
export const MERCURY_IN_HOUSE: string[] = [
  /* Casa 1  */ 'Sua mente é rápida e define a forma como o mundo te percebe. Você pensa em voz alta, processa em tempo real e as pessoas te identificam imediatamente como alguém inteligente e comunicativo. Seu temperamento nervoso e intuitivo te dá habilidade natural para o comércio de ideias. O desafio é desacelerar o suficiente para ouvir — sua mente avança tão rápido que pode atropelar as respostas que chegam devagar.',
  /* Casa 2  */ 'Sua inteligência é sua maior ferramenta de geração de riqueza. Você ganha dinheiro através da mente — escrita, jornalismo, comércio, administração, ensino ou qualquer forma de trabalho intelectual. Há um faro natural para negócios e para identificar onde está o valor. O desafio é não reduzir toda a inteligência à utilidade financeira — sua mente precisa de liberdade para explorar, não apenas para lucrar.',
  /* Casa 3  */ 'Posição natural de Mercúrio — sua mente está em casa aqui. Facilidade extraordinária para aprender, comunicar e se expressar. Você assimila informações rapidamente, transita entre assuntos com leveza e tem um espírito jovial que mantém o ambiente ao redor leve. Sucesso com escritos, ensino e qualquer forma de transmissão de conhecimento. O desafio é a profundidade: quando tudo vem fácil, pode faltar incentivo para mergulhar verdadeiramente fundo.',
  /* Casa 4  */ 'Sua mente está enraizada na família, nas memórias e na herança intelectual dos seus pais. Você pode ser a pessoa que guarda as histórias da família, que trabalha de casa, ou cuja profissão foi inspirada pelo ambiente doméstico. Há uma vivacidade intelectual que te acompanha até o fim da vida. Capacidade notável de se adaptar a mudanças — cada recomeço é uma oportunidade de reescrever sua narrativa.',
  /* Casa 5  */ 'Sua mente é criativa e lúdica — você expressa ideias de forma divertida e envolvente. Há talento natural para o ensino, especialmente com crianças ou jovens. Amor pelo jogo, por palavras cruzadas, enigmas e desafios mentais. Nos relacionamentos, racionaliza o amor — precisa entender intelectualmente antes de se entregar. Quando a mente se alinha com o coração, sua comunicação se torna irresistível.',
  /* Casa 6  */ 'Sua mente é uma máquina de resolver problemas — analítica, precisa e incansável. Grande capacidade de trabalho intelectual, especialmente em funções de secretariado, administração, saúde ou qualquer coisa que exija organização metódica. Você se destaca pela eficiência e pelo engenho. O desafio é a tensão nervosa: a mesma mente que resolve tudo pode se sobrecarregar se não encontrar válvulas de descanso.',
  /* Casa 7  */ 'Sua mente funciona melhor em diálogo — você precisa do outro para pensar, debater e processar ideias. Excelente para mediação, negociação e qualquer forma de parceria intelectual. Pode atrair cônjuges mercuriais (comunicativos, inquietos, versáteis). O sucesso literário ou profissional pode vir de colaborações. O desafio é não depender do espelho alheio para validar suas próprias ideias.',
  /* Casa 8  */ 'Sua mente é investigativa — você vai naturalmente além da superfície, atraído por mistérios, psicologia profunda, ocultismo e tudo que está oculto. Percebe o que não é dito, lê nas entrelinhas com facilidade perturbadora. Pode haver interesse por temas de morte, transformação, heranças ou sexualidade. O desafio é usar esse poder de penetração para curar, não para manipular.',
  /* Casa 9  */ 'Sua mente é filosófica e expansiva — orientada para o sentido da vida, não apenas para os fatos. Aptidão natural para línguas estrangeiras, estudos superiores, viagens que expandem a perspectiva. Há objetividade para aceitar críticas e ideias contrárias, desde que baseadas em seriedade intelectual. O desafio é não se perder em teorias abstratas sem aplicação — a sabedoria precisa ser vivida.',
  /* Casa 10 */ 'Comunicação é sua ferramenta de carreira — você se destaca profissionalmente pela inteligência e articulação. Posição por excelência do intermediário, do comunicador público, do intelectual que conquista posição. Múltiplas atividades profissionais são possíveis ao longo da vida. O desafio é manter foco: a versatilidade que te permite transitar entre campos pode dispersar a energia se não houver uma direção clara.',
  /* Casa 11 */ 'Sua mente é voltada para o futuro — projetos intelectuais, causas coletivas, difusão do pensamento. Você se comunica excepcionalmente bem em grupos e tem facilidade para fazer amizades baseadas em troca intelectual. Os amigos são variados e estimulantes. O desafio é não se perder na abstração dos ideais coletivos a ponto de negligenciar as conexões íntimas que também precisam de você.',
  /* Casa 12 */ 'Sua mente é contemplativa e intuitiva — insights chegam através de sonhos, meditação e momentos de solidão. Há aptidão natural para trabalhar com o inconsciente: psicologia, escrita introspectiva, pesquisa sobre o oculto. Pode haver dificuldade em verbalizar o que sente, porque o que você percebe é mais amplo do que as palavras alcançam. O desafio é confiar na sua percepção sutil sem se perder na indefinição.',
];
