// INTERPRETATIONS — Русский (ru)
import { SUN_IN_HOUSE, MOON_IN_HOUSE, MERCURY_IN_HOUSE } from './pt';
import { VENUS_IN_HOUSE, MARS_IN_HOUSE, NORTH_NODE_HOUSE, NORTH_NODE_IN_SIGN } from '../interpret';
import { JUPITER_IN_HOUSE, SATURN_IN_HOUSE, URANUS_IN_HOUSE, NEPTUNE_IN_HOUSE, PLUTO_IN_HOUSE } from '../outer-planets';
import { CHIRON_IN_HOUSE, CHIRON_IN_SIGN } from '../chiron';
export { SUN_IN_HOUSE, MOON_IN_HOUSE, MERCURY_IN_HOUSE, VENUS_IN_HOUSE, MARS_IN_HOUSE };
export { JUPITER_IN_HOUSE, SATURN_IN_HOUSE, URANUS_IN_HOUSE, NEPTUNE_IN_HOUSE, PLUTO_IN_HOUSE };
export { CHIRON_IN_HOUSE, CHIRON_IN_SIGN, NORTH_NODE_HOUSE, NORTH_NODE_IN_SIGN };
export const SIGN_NAMES = ['Овен','Телец','Близнецы','Рак','Лев','Дева','Весы','Скорпион','Стрелец','Козерог','Водолей','Рыбы'];
export const PLANET_NAMES: Record<string,string> = { sun:'Солнце', moon:'Луна', mercury:'Меркурий', venus:'Венера', mars:'Марс', jupiter:'Юпитер', saturn:'Сатурн', uranus:'Уран', neptune:'Нептун', pluto:'Плутон', northNode:'Северный Узел', chiron:'Хирон', lilith:'Лилит' };
export const MONTHS = ['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];
export const SECTION_TITLES = { sun:(h:number,s:string)=>`☉ Солнце в ${h}-м доме в ${s}`, moon:(h:number,s:string)=>`☽ Луна в ${h}-м доме в ${s}`, mercury:(h:number,s:string)=>`☿ Меркурий в ${h}-м доме в ${s}`, venus:(h:number,s:string)=>`♀ Венера в ${h}-м доме в ${s}`, mars:(h:number,s:string)=>`♂ Марс в ${h}-м доме в ${s}`, jupiter:(h:number,s:string)=>`♃ Юпитер в ${h}-м доме в ${s}`, saturn:(h:number,s:string)=>`♄ Сатурн в ${h}-м доме в ${s}`, uranus:(h:number,s:string)=>`♅ Уран в ${h}-м доме в ${s}`, neptune:(h:number,s:string)=>`♆ Нептун в ${h}-м доме в ${s}`, pluto:(h:number,s:string)=>`♇ Плутон в ${h}-м доме в ${s}`, northNode:(h:number,s:string)=>`☊ Северный Узел в ${h}-м доме в ${s}`, chiron:(h:number,s:string)=>`⚷ Хирон в ${h}-м доме в ${s}`, ascendant:(s:string)=>`Асцендент в ${s}` };
export const PLANET_SUBTITLES: Record<string,string> = { sun:'Ваша солнечная сущность — идентичность, цель и жизненная энергия', moon:'Ваш эмоциональный мир — потребности, инстинкты и внутренняя безопасность', mercury:'Ваш разум и общение — как вы думаете и учитесь', venus:'Ваш язык любви — что вы привлекаете и цените', mars:'Ваш импульс и действие — как вы преследуете цели', jupiter:'Ваш путь расширения — где текут изобилие и рост', saturn:'Ваша зона мастерства — где дисциплина кует прочные достижения', uranus:'Ваша внутренняя революция — где вы ломаете шаблоны', neptune:'Ваш духовный портал — где вы растворяете границы', pluto:'Ваша трансформирующая сила — глубокая смерть и возрождение', northNode:'Ваша эволюционная цель — направление вашей души', chiron:'Ваша священная рана — боль, которая становится даром исцеления' };
export const LABELS = { reportTitle:'Полный Натальный Отчёт', reportSubtitle:'Глубокая Интерпретация', positions:'Положения Планет', houses:'Куспиды Домов', overview:'Обзор', potentials:'Ваши 5 Величайших Потенциалов', challenges:'Ваши 5 Основных Вызовов', conclusion:'Заключение', advice:'Практический Совет', elements:'Элементы и Модальности', dignities:'Эссенциальные Достоинства', aspects:'Главные Аспекты', themes:'Тематический Синтез', quote:'"Звёзды склоняют, не определяют."', sampleNote:'Это был бесплатный образец!', sampleFull:'Полный отчёт содержит 20-30 страниц с детальной интерпретацией.', buyNow:'Полная версия:', buyInstant:'Купите сейчас и скачайте мгновенно — 100% в браузере.', natalChart:'Ваша Натальная Карта', retrograde:'(ретроградный)', annualTitle:'Годовой Прогноз', annualSubtitle:'Транзиты и тенденции', profection:'Годовая Профекция — Тема Года', houseInFocus:'в Фокусе', rulerOfYear:'Управитель Года', eclipses:'Затмения Года', jupiterExpansion:'Расширение Года', saturnLesson:'Урок Года', conclusionAnnual:'Заключение — Ваш Год в Перспективе', relationshipTitle:'Отчёт об Отношениях', compatibility:'Совместимость', emotionalConnection:'Эмоциональная Связь', attractionChemistry:'Притяжение и Химия', communication:'Общение', commitmentLimits:'Обязательства и Границы — Сатурн', growthPotential:'Потенциал Роста', challengesTension:'Точки Напряжения', psychTitle:'Глубокий Психологический Анализ', egoStructure:'Структура Эго — Солнце и Асцендент', emotionalWorld:'Эмоциональный Мир — Луна', mentalProcesses:'Ментальные Процессы — Меркурий', lovePatterns:'Паттерны Любви — Венера', vitalForce:'Жизненная Сила — Марс', shadow:'Тень — Плутон', wound:'Центральная Рана — Хирон', unconscious:'Бессознательное — 12-й Дом и Нептун', familyPatterns:'Семейные Паттерны — Луна, 4-й Дом и Сатурн', defenseMechanisms:'Механизмы Защиты — Сатурн', integrationPath:'Путь Интеграции — Северный Узел', careerTitle:'Карьера и Призвание', midheaven:'Середина Неба', house10:'10-й Дом — Призвание', house6:'6-й Дом — Рутина и Работа', house2:'2-й Дом — Ресурсы и Таланты', sinsTitle:'Семь Грехов', pride:'Гордыня — Солнце', lust:'Похоть — Венера и Марс', greed:'Алчность — Сатурн', gluttony:'Чревоугодие — Юпитер', wrath:'Гнев — Марс', envy:'Зависть — Плутон', sloth:'Лень — Нептун', repetitivePatterns:'Повторяющиеся Паттерны — Квадраты и Оппозиции', unexploredPotentials:'Неисследованные Потенциалы — Тригоны и Таланты', integrationPaths:'Пути Интеграции', recommendedPractices:'Рекомендуемые Практики', childhoodTemplate:'Детство и Эмоциональный Шаблон', fromWoundToGift:'От Раны к Дару', differentiation:'Дифференциация — Быть Собой', mainTensions:'Главные Напряжения Карты', plutoAspects:'Напряжённые Аспекты Плутона' };
export const TRANSITIONS = { afterOverview:'Эта идентичностная основа конкретно проявляется в планетах в их домах.', afterPersonalPlanets:'Аспекты между планетами показывают, как эти энергии взаимодействуют.', afterAspects:'Из этих взаимодействий возникают паттерны — центральные темы вашего опыта.', beforeConclusion:'Собирая всё воедино, ваша карта рассказывает связную историю.' };
