// ============================================================
// INTERPRETATIONS — Türkçe (tr)
// Tam Türkçe yorumlama metinleri — PT/EN ithalatı yok
// ============================================================

export const SUN_IN_HOUSE: string[] = [
  /* House 1 */ 'Güneş 1. evde doğduğunuzda, kimliğiniz ve yaşam enerjiniz doğrudan dünyaya yansır; güçlü bir varlık ve kendine özgü bir karizma taşırsınız. Kendinizi ifade etmek sizin için en doğal yoldur.',
  /* House 2 */ 'Güneş 2. evde, öz değerinizi maddi güvenlik ve kişisel kaynaklar üzerinden inşa edersiniz. Sahip olduklarınız aracılığıyla kim olduğunuzu keşfeder ve değer yaratma konusunda güçlü bir yetenek geliştirirsiniz.',
  /* House 3 */ 'Güneş 3. evde, zihniniz ve iletişiminiz kimliğinizin merkezindedir. Öğrenme, yazma ve fikir alışverişi yoluyla parlar; çevrenizle kurduğunuz bağlantılar sizi canlı tutar.',
  /* House 4 */ 'Güneş 4. evde, kökenleriniz ve aile mirasınız kimliğinizin temelini oluşturur. Ev ve aile yaşamı sizin için bir güç kaynağıdır; içsel dünyanızı inşa etmek en derin amacınızdır.',
  /* House 5 */ 'Güneş 5. evde, yaratıcılık ve öz ifade yoluyla parıldarsınız. Sevgi, oyun ve sanatsal ifade sizin için yaşamın özüdür; başkalarına ilham vermek doğanızın bir parçasıdır.',
  /* House 6 */ 'Güneş 6. evde, günlük hizmet ve ustalık yoluyla kendinizi ifade edersiniz. Çalışmaya ve başkalarına faydalı olmaya derin bir bağlılık taşırsınız; mükemmeliyetçilik kimliğinizin bir parçasıdır.',
  /* House 7 */ 'Güneş 7. evde, ilişkiler aracılığıyla kendinizi keşfedersiniz. Ortaklıklar ve yakın bağlar sizi tanımlar; başkalarında ayna bularak kendi ışığınızı görürsünüz.',
  /* House 8 */ 'Güneş 8. evde, dönüşüm ve derinlik sizi tanımlar. Varoluşun gizli katmanlarını araştırma yeteneğiniz güçlüdür; krizler ve yeniden doğuşlar aracılığıyla gerçek gücünüzü bulursunuz.',
  /* House 9 */ 'Güneş 9. evde, bilgelik arayışı ve anlam arayışı yaşamınızın odak noktasıdır. Felsefe, seyahat ve yüksek öğrenim aracılığıyla parlar; ufkunuzu genişletmek sizi besler.',
  /* House 10 */ 'Güneş 10. evde, kariyer ve toplumsal statü aracılığıyla kendinizi gerçekleştirirsiniz. Liderlik ve başarı doğanızın ayrılmaz bir parçasıdır; dünyada iz bırakmak en derin motivasyonunuzdur.',
  /* House 11 */ 'Güneş 11. evde, topluluk ve kolektif vizyonlar aracılığıyla parlar. Arkadaşlık ve ortak idealler sizi besler; geleceği şekillendirme arzusu kimliğinizin merkezindedir.',
  /* House 12 */ 'Güneş 12. evde, manevi derinlik ve yalnızlık aracılığıyla güç bulursunuz. Görünmez alemler size çekici gelir; ruhsal arayış ve iç dünyaya çekilme aracılığıyla gerçek benliğinizi keşfedersiniz.',
];

export const MOON_IN_HOUSE: string[] = [
  /* House 1 */ 'Ay 1. evde, duygularınız yüzünüze yansır ve ilk izleniminiz çok güçlüdür. Duygusal tepkileriniz anlık ve otantiktir; başkalarının ihtiyaçlarını sezgisel olarak hissedersiniz.',
  /* House 2 */ 'Ay 2. evde, duygusal güvenliğinizi maddi istikrara bağlarsınız. Konfor ve beslenme size güvenli hissettirir; değerleriniz ve kaynaklarınız duygusal dengenizin temelidir.',
  /* House 3 */ 'Ay 3. evde, düşünceleriniz duygularınızla iç içe geçmiştir. Sezgisel bir iletişim tarzınız vardır; yakın çevrenizle olan bağlar duygusal beslenmişliğinizi doğrudan etkiler.',
  /* House 4 */ 'Ay 4. evde, aile ve ev ortamı duygusal dünyanızın merkezindedir. Kökenlerinizle derin bir bağ taşırsınız; güvenli bir yuva yaratmak içsel bir ihtiyaçtır.',
  /* House 5 */ 'Ay 5. evde, duygusal ifade ve yaratıcılık aracılığıyla beslenirsiniz. Sevgi ilişkileri ve çocuklarla olan bağlar derin duygusal tatmin sağlar; oyun ve eğlence ruhunuzu canlı tutar.',
  /* House 6 */ 'Ay 6. evde, günlük rutinler ve hizmet duygusal dengenizi belirler. Başkalarına bakım sunmak içsel bir ihtiyaçtır; sağlık ve düzen size güvenli hissettirir.',
  /* House 7 */ 'Ay 7. evde, ilişkiler aracılığıyla duygusal besleniş bulursunuz. Yakın ortaklıklar güvenlik hissinizi doğrudan etkiler; başkalarının ihtiyaçlarına derin bir duyarlılık taşırsınız.',
  /* House 8 */ 'Ay 8. evde, derin duygusal dönüşümler yaşarsınız. Paylaşılan kaynaklar ve yakın bağların getirdiği savunmasızlık sizi dönüştürür; içgüdüsel ve psikolojik derinliğiniz güçlüdür.',
  /* House 9 */ 'Ay 9. evde, anlam arayışı ve özgürlük duygusal dengenizi besler. Farklı kültürler ve felsefi keşifler ruhunuzu canlı tutar; geniş ufuklar size güvenli hissettirr.',
  /* House 10 */ 'Ay 10. evde, toplumsal rolünüz ve kariyer duygusal kimliğinizle iç içe geçmiştir. Kamuoyunun tanıması size duygusal tatmin sağlar; annenizin ya da toplumun beklentileri derin izler bırakmıştır.',
  /* House 11 */ 'Ay 11. evde, topluluk ve arkadaşlık duygusal beslenmişliğinizin kaynağıdır. Kolektif idealler ve grup bağları size aidiyet hissi verir; insanlığa hizmet içsel bir ihtiyaçtır.',
  /* House 12 */ 'Ay 12. evde, duygularınız çoğunlukla gizli ya da bilinçdışı kalır. Yalnızlık ve manevi geri çekilme sizi besler; empati yeteneğiniz son derece derindir ancak sınırları korumak önemlidir.',
];

export const MERCURY_IN_HOUSE: string[] = [
  /* House 1 */ 'Merkür 1. evde, düşünceleriniz ve iletişiminiz kişiliğinizin ön planındadır. Zeki ve meraklı bir izlenim yaratırsınız; fikirlerinizi paylaşmak en doğal ifade biçiminizdir.',
  /* House 2 */ 'Merkür 2. evde, zihinsel yeteneklerinizi pratik kaynaklara ve maddi kazanca dönüştürürsünüz. Kelimeler ve fikirler sizin için değer yaratmanın araçlarıdır; para ve iletişim sıklıkla kesişir.',
  /* House 3 */ 'Merkür 3. evde, merak ve öğrenme yaşamınızın odak noktasıdır. Yazma, konuşma ve fikir alışverişi size zevk verir; yakın çevrenizle sürekli bir bilgi alışverişi içindesinizdir.',
  /* House 4 */ 'Merkür 4. evde, aile ve kökenlerinizle ilgili konularda derin bir düşünce yeteneğiniz vardır. Ev ortamı fikir alışverişinin merkezidir; geçmişi anlamlandırmak zihinsel bir ihtiyaçtır.',
  /* House 5 */ 'Merkür 5. evde, yaratıcı ifade ve oyun zihninizi besler. Hikaye anlatımı, yazarlık ve sanatsal iletişimde doğal bir yeteneğiniz vardır; fikirlerinizi eğlenceli biçimde sunarsınız.',
  /* House 6 */ 'Merkür 6. evde, analitik düşünce ve pratik problem çözme güçlüdür. Rutin işlerde verimlilik ararsınız; sağlık ve iş konularında ayrıntılara dikkat etmek doğanızın bir parçasıdır.',
  /* House 7 */ 'Merkür 7. evde, ilişkiler zihninizi uyarır. Ortaklarınızla fikir alışverişi sizi besler; iletişim açıklığı ilişkilerinizin temel taşıdır.',
  /* House 8 */ 'Merkür 8. evde, gizli gerçekleri araştırma ve derinlemesine analiz etme yeteneğiniz güçlüdür. Psikoloji, gizem ve dönüşüm konuları zihninizi meşgul eder; sırları çözme konusunda keskin bir zekanız vardır.',
  /* House 9 */ 'Merkür 9. evde, felsefi düşünce ve yüksek öğrenim zihinsel dünyanızı şekillendirir. Farklı kültürler ve inanç sistemleri sizi büyüler; öğretme ve yayın yapma konularında doğal bir yeteneğiniz vardır.',
  /* House 10 */ 'Merkür 10. evde, iletişim yetenekleriniz kariyerinizde belirleyici bir rol oynar. Yazarlık, konuşma veya medya aracılığıyla toplumsal etki yaratırsınız; sözel zekanız mesleki başarınızın anahtarıdır.',
  /* House 11 */ 'Merkür 11. evde, grup düşüncesi ve kolektif vizyonlar zihninizi besler. Arkadaş çevrenizdeki fikir alışverişi sizi canlandırır; sosyal ağlar ve topluluklar aracılığıyla bilgi yayarsınız.',
  /* House 12 */ 'Merkür 12. evde, düşünceleriniz sıklıkla bilinçdışından beslenir. Sezgisel anlayış ve mistik düşünce güçlüdür; yalnızlık ve sessizlik zihninizin en verimli ortamıdır.',
];

export const VENUS_IN_HOUSE: string[] = [
  /* House 1 */ 'Venüs 1. evde, cazibeniz ve estetik duyarlılığınız kişiliğinizin ayrılmaz bir parçasıdır. Çekici ve uyumlu bir izlenim yaratırsınız; güzellik ve incelik size doğal gelir.',
  /* House 2 */ 'Venüs 2. evde, maddi zevkler ve güzellik size derin tatmin sağlar. Kaliteli yaşam standartlarına değer verirsiniz; maddi bolluk ile duygusal güvenlik arasında güçlü bir bağ hissedersiniz.',
  /* House 3 */ 'Venüs 3. evde, iletişim ve fikir paylaşımı üzerinden bağlantı kurarsınız. Güzel konuşmak ve yazmak size zevk verir; kardeşler ve yakın çevreyle ilişkiler özellikle anlamlıdır.',
  /* House 4 */ 'Venüs 4. evde, güzel ve huzurlu bir ev ortamı yaratmak derin bir ihtiyaçtır. Aile bağları ve kökenler sevgi dilinizi şekillendirir; sıcak ve davetkar bir yuva kurmak en büyük zevklerinizden biridir.',
  /* House 5 */ 'Venüs 5. evde, aşk ve yaratıcılık iç içe geçmiştir. Romantizm, sanat ve oyun aracılığıyla sevgi ifade edersiniz; hayat dolu ve cömert bir kalp taşırsınız.',
  /* House 6 */ 'Venüs 6. evde, günlük hayatınıza güzellik ve uyum katmaktan zevk alırsınız. Çalışma ortamınızın estetik olması önemlidir; iş arkadaşlarıyla uyumlu ilişkiler kurmak için çaba gösterirsiniz.',
  /* House 7 */ 'Venüs 7. evde, ilişkiler ve ortaklıklar yaşamınızın merkezindedir. Derin bir bağ ve karşılıklı saygı arayışındasınızdır; estetik ve uyumu paylaşabileceğiniz bir partner arzularsınız.',
  /* House 8 */ 'Venüs 8. evde, derin ve dönüştürücü aşk deneyimleri yaşarsınız. Paylaşılan kaynaklara ve samimi bağlara çekilirsiniz; sevginin derin boyutlarını keşfetmek için samimiyet gerektirir.',
  /* House 9 */ 'Venüs 9. evde, farklı kültürler ve yabancı ülkeler aşk ve güzellik anlayışınızı genişletir. Felsefe ve macera romantikliğinizin bir parçasıdır; seyahat ederek ya da öğrenerek sevgiyi bulursunuz.',
  /* House 10 */ 'Venüs 10. evde, kariyer ve toplumsal statü aracılığıyla güzellik ve uyum yaratırsınız. Sanat veya diplomasiyle ilgili meslekler size çekici gelir; kamuoyunun beğenisini kazanma konusunda doğal bir yeteneğiniz vardır.',
  /* House 11 */ 'Venüs 11. evde, arkadaşlık ve topluluk aracılığıyla sevgi bulursunuz. Kolektif idealleri paylaşan insanlarla derin bağlar kurarsınız; sosyal çevrenizde uyum ve güzellik yaratmaktan keyif alırsınız.',
  /* House 12 */ 'Venüs 12. evde, aşk ve sevgi çoğunlukla gizli ya da manevi bir boyut taşır. Derin empati ve koşulsuz sevgi yeteneğiniz güçlüdür; romantik ilişkilerinizde sınırları net tutmak önem kazanır.',
];

export const MARS_IN_HOUSE: string[] = [
  /* House 1 */ 'Mars 1. evde, enerjiniz ve kararlılığınız doğrudan dışa vurur. Girişken ve cesur bir yapıya sahipsinizdir; hedeflere ulaşmak için doğrudan harekete geçersiniz.',
  /* House 2 */ 'Mars 2. evde, maddi güvenlik için enerjik ve kararlı biçimde çalışırsınız. Kaynaklarınızı elde etmek ve korumak için güçlü bir dürtü taşırsınız; değerleriniz uğruna savaşabilirsiniz.',
  /* House 3 */ 'Mars 3. evde, düşüncelerinizi ve fikirlerinizi güçlü bir şekilde savunursunuz. Tartışmacı ve keskin bir zihne sahipsinizdir; iletişimde doğrudan ve çarpıcı bir tarz sergilersiziniz.',
  /* House 4 */ 'Mars 4. evde, aile ve ev ortamında güçlü duygular ve çatışmalar yaşayabilirsiniz. Yuvanızı koruma içgüdünüz güçlüdür; kökenlerinizden gelen enerji ile yüzleşmek dönüştürücüdür.',
  /* House 5 */ 'Mars 5. evde, yaratıcı ifade ve aşk ilişkilerinde ateşli ve tutkulu bir enerji taşırsınız. Rekabet ve spor size zevk verir; hayatı tam anlamıyla yaşamak için güçlü bir dürtü hissedersiniz.',
  /* House 6 */ 'Mars 6. evde, çalışmaya ve görev yapmaya güçlü bir enerji ayırırsınız. Verimli ve disiplinli bir çalışma tarzınız vardır; sağlık ve rutinler konusunda kararlı adımlar atarsınız.',
  /* House 7 */ 'Mars 7. evde, ilişkilerde tutku ve bazen gerilim yaşarsınız. Güçlü ve iddialı ortaklar sizi çeker; ortak hedefler doğrultusunda birlikte harekete geçmek sizi canlandırır.',
  /* House 8 */ 'Mars 8. evde, derin dönüşümler için güçlü bir irade taşırsınız. Kriz anlarında güçlü ve kararlı kalırsınız; cinsellik ve güç dinamikleri yaşamınızda önemli temalar olabilir.',
  /* House 9 */ 'Mars 9. evde, inançlarınız ve idealler için tutkuyla savaşırsınız. Macera ve keşif arzusu güçlüdür; yüksek öğrenim ve felsefi arayış sizi harekete geçirir.',
  /* House 10 */ 'Mars 10. evde, kariyerinizde güçlü bir hırs ve liderlik arzusu taşırsınız. Başarı için enerjik biçimde çalışırsınız; rekabetçi ortamlarda öne çıkma yeteneğiniz güçlüdür.',
  /* House 11 */ 'Mars 11. evde, kolektif hedefler ve topluluk projeleri için enerjik biçimde çalışırsınız. Arkadaş çevrenizdeki güçlü kişiliklerle çatışabilir ya da ilham alabilirsiniz; sosyal değişim için savaşmaya hazırsınızdır.',
  /* House 12 */ 'Mars 12. evde, enerjiniz ve dürtüleriniz çoğunlukla bilinçdışında işler. Gizli güçler ve manevi savaşlar sizi meşgul edebilir; yalnız çalışma ortamlarında en yüksek verimliliğe ulaşırsınız.',
];

export const JUPITER_IN_HOUSE: string[] = [
  /* House 1 */ 'Jüpiter 1. evde, yaşama iyimser ve cömert bir enerjiyle yaklaşırsınız. Büyüme ve genişleme sizin için doğaldır; insanlar üzerinde olumlu ve ilham verici bir etki bırakırsınız.',
  /* House 2 */ 'Jüpiter 2. evde, maddi bolluğu çekme konusunda güçlü bir şansınız vardır. Kaynaklarınızı genişletme ve değer yaratma konusunda doğal bir yeteneğiniz vardır; cömertlik size geri döner.',
  /* House 3 */ 'Jüpiter 3. evde, öğrenme ve iletişim alanında büyük bir hevesle ilerlersiniz. Fikirleri genişletmek ve yaymak için doğal bir yeteneğiniz vardır; yazarlık ve eğitim alanlarında şansınız açıktır.',
  /* House 4 */ 'Jüpiter 4. evde, aile ve kökenlerinizden bolluk ve destek gelir. Büyük ve misafirperver bir yuva oluşturma arzusu taşırsınız; duygusal temeller hayatınızda genişleme için alan açar.',
  /* House 5 */ 'Jüpiter 5. evde, yaratıcılık, aşk ve zevk alanında bol fırsatlar bulursunuz. Oyun ve eğlence hayatınızı zenginleştirir; çocuklarla ve romantik ilişkilerle bol neşe yaşarsınız.',
  /* House 6 */ 'Jüpiter 6. evde, çalışma ve sağlık alanında büyüme fırsatları bulursunuz. Hizmet etmek size anlam katar; rutin ve düzene olumlu bir bakış açısıyla yaklaşırsınız.',
  /* House 7 */ 'Jüpiter 7. evde, ilişkiler aracılığıyla büyüme ve şans gelir. Cömert ve destekleyici ortaklar çekersiniz; evlilik ve ortaklıklar hayatınızı genişletir.',
  /* House 8 */ 'Jüpiter 8. evde, dönüşümler ve paylaşılan kaynaklar aracılığıyla bolluk gelir. Manevi ve psikolojik derinlikleri keşfetmek için büyük bir heves taşırsınız; miraslar ve ortaklıklardan kazanç sağlayabilirsiniz.',
  /* House 9 */ 'Jüpiter 9. evde, felsefe, seyahat ve yüksek öğrenimde doğal bir şansınız ve hevesniz vardır. Farklı kültürleri keşfetmek ruhunuzu besler; öğretme ve rehberlik rolünde parlarsınız.',
  /* House 10 */ 'Jüpiter 10. evde, kariyer ve toplumsal statü alanında büyüme ve tanınırlık gelir. Liderlik ve başarı yolculuğunuzda güçlü bir şans rüzgarı esir; toplumsal katkılarınız geniş yankı bulur.',
  /* House 11 */ 'Jüpiter 11. evde, topluluk ve kolektif idealler aracılığıyla büyüme yaşarsınız. Geniş ve çeşitli arkadaş çevreleri ve sosyal ağlar bolluk getirir; insanlığa katkı sizi besler.',
  /* House 12 */ 'Jüpiter 12. evde, manevi büyüme ve içsel keşif aracılığıyla bolluk bulursunuz. Sessizlik ve yalnızlık size rehberlik eder; görünmez destek ve korunma hissedersiniz.',
];

export const SATURN_IN_HOUSE: string[] = [
  /* House 1 */ 'Satürn 1. evde, kimliğinizi sabır ve çalışma aracılığıyla inşa edersiniz. Başlangıçta kısıtlamalar yaşayabilirsiniz ancak zamanla güçlü bir yapı ve olgunluk kazanırsınız.',
  /* House 2 */ 'Satürn 2. evde, maddi güvenliği güçlükle elde edersiniz ancak sabırla kalıcı bir temel atarsınız. Kaynaklar konusunda disiplinli ve tutumlú bir yaklaşım geliştirirsiniz.',
  /* House 3 */ 'Satürn 3. evde, düşünce ve iletişimde titizlik ve derinlik kazanırsınız. Öğrenmek zaman alabilir ancak sonunda sağlam bir bilgi birikimi oluşturursunuz; yazı ve söz konusunda ciddi bir yapınız vardır.',
  /* House 4 */ 'Satürn 4. evde, aile ve kökenlerden gelen yük ve sorumluluklar taşıyabilirsiniz. Güvenli bir yuva inşa etmek için çok çalışırsınız; zamanla kökenlerinizle barışma sürecini yaşarsınız.',
  /* House 5 */ 'Satürn 5. evde, yaratıcılık ve sevgi ifadesi ciddi ve disiplinli bir boyut kazanır. Eğlence konusunda kendinize izin vermek zaman alabilir; ancak sanatsal ustalık ve derin bağlar geliştirebilirsiniz.',
  /* House 6 */ 'Satürn 6. evde, çalışma ve sağlık konularında disiplin ve titizlik ön plana çıkar. Rutin ve görev duygusu güçlüdür; zamanla verimlilik ve ustalık kazanırsınız.',
  /* House 7 */ 'Satürn 7. evde, ilişkiler ve ortaklıklar ciddi dersler getirir. Kararlılık ve sorumluluk üzerine kurulu bağlar zamanla güçlenir; gerçek bir bağlılık inşa etmek için çalışırsınız.',
  /* House 8 */ 'Satürn 8. evde, dönüşüm ve paylaşılan kaynaklar konusunda derin bir sorumluluk taşırsınız. Korkularla yüzleşmek gücünüzün kaynağıdır; zamanla derin bir psikolojik ustalık geliştirir.',
  /* House 9 */ 'Satürn 9. evde, inanç ve felsefi sorular ciddi bir önem taşır. Yüksek öğrenim veya manevi arayış zorlu ancak derin bir yolculuktur; dogmalardan uzaklaşarak kendi gerçeğinizi inşa edersiniz.',
  /* House 10 */ 'Satürn 10. evde, kariyer ve toplumsal konum için büyük bir çaba ve sabır gerekir. Geç de olsa güçlü ve kalıcı bir başarı inşa edersiniz; liderlik ve sorumluluk omuzlarınızda ağır hissedebilir.',
  /* House 11 */ 'Satürn 11. evde, topluluk ve arkadaşlık ilişkilerinde seçici ve temkinlisinizdir. Kolektif hedefler için ciddi bir sorumluluk hissedersiniz; gerçek ve kalıcı bağlar inşa edersiniz.',
  /* House 12 */ 'Satürn 12. evde, bilinçdışı korkular ve gizli sınırlamalarla yüzleşme süreci yaşarsınız. Yalnızlık ve manevi disiplin gücünüzün kaynağıdır; içsel çalışma aracılığıyla derin bir özgürlük kazanırsınız.',
];

export const URANUS_IN_HOUSE: string[] = [
  /* House 1 */ 'Uranüs 1. evde, özgün ve alışılmadık bir kişiliğiniz vardır. Bireyselliğinizi ön plana çıkarmak için güçlü bir dürtü taşırsınız; beklenmedik değişimler yaşamınızı yeniler.',
  /* House 2 */ 'Uranüs 2. evde, maddi kaynaklara alışılmadık yollarla ulaşırsınız. Değerleriniz ve maddi anlayışınız zaman içinde köklü biçimde değişebilir; finansal özgürlük temel bir hedefimizdirdir.',
  /* House 3 */ 'Uranüs 3. evde, düşünceleriniz ve iletişiminiz çığır açıcı ve özgündür. Sıra dışı fikirler ve yenilikçi bakış açıları sizi tanımlar; öğrenme biçiminiz alışılmadık yolları izler.',
  /* House 4 */ 'Uranüs 4. evde, aile ve köken konularında beklenmedik değişimler ve özgürlük arayışı yaşarsınız. Geleneksel aile yapılarından farklı bir yol çizersiniz; ev ve yuva kavramını yeniden tanımlarsınız.',
  /* House 5 */ 'Uranüs 5. evde, yaratıcılık ve aşk ilişkilerinde özgünlük ve özgürlük belirleyicidir. Sıra dışı sanatsal ifade yolları keşfedersiniz; sevgide geleneksel kalıpların dışına çıkarsınız.',
  /* House 6 */ 'Uranüs 6. evde, çalışma yöntemleriniz yenilikçi ve alışılmadıktır. Sağlık ve rutin konularında özgün yaklaşımlar geliştirirsiniz; iş hayatında bağımsızlık ve esneklik ararsınız.',
  /* House 7 */ 'Uranüs 7. evde, ilişkilerde özgürlük ve bireyselliğe büyük önem verirsiniz. Alışılmadık ortaklıklar ve beklenmedik ilişki dinamikleri yaşarsınız; bağımsızlık ve bağlılık arasında denge ararsınız.',
  /* House 8 */ 'Uranüs 8. evde, dönüşüm ve kriz anlarında ani ve beklenmedik değişimler yaşarsınız. Paylaşılan kaynaklar ve güç dinamiklerinde özgürlük arayışı güçlüdür; ölüm ve yeniden doğuşu yeni biçimlerde deneyimlersiniz.',
  /* House 9 */ 'Uranüs 9. evde, inanç ve felsefede devrimci ve özgün bir bakış açısı geliştirirsiniz. Geleneksel öğretilerle aranız çoğunlukla gergindir; yeni bilgi sistemleri keşfetmek sizi besler.',
  /* House 10 */ 'Uranüs 10. evde, kariyer ve toplumsal rolünüz sıra dışı ve yenilikçidir. Geleneksel kariyer yollarının dışına çıkarsınız; beklenmedik kariyer değişimleri yaşayabilirsiniz ancak her biri sizi daha özgün kılar.',
  /* House 11 */ 'Uranüs 11. evde, topluluk ve kolektif değişim için devrimci bir enerji taşırsınız. Sıra dışı arkadaşlıklar ve sosyal ağlar sizi besler; geleceği yeniden şekillendirme arzusu güçlüdür.',
  /* House 12 */ 'Uranüs 12. evde, bilinçdışındaki özgürlük arayışı ve devrimci içgüdüler güçlüdür. Mistik ve sıra dışı ruhsal deneyimler yaşarsınız; eski kalıpları kırmak için güçlü bir iç dürtü taşırsınız.',
];

export const NEPTUNE_IN_HOUSE: string[] = [
  /* House 1 */ 'Neptün 1. evde, kişiliğiniz belirsiz ve değişken bir boyut taşır. Derin bir empati ve sezgi yeteneğiniz vardır; başkalarının ruh hallerini kolayca hissedersiniz.',
  /* House 2 */ 'Neptün 2. evde, maddi değerler ve kaynaklar konusunda idealist ya da yanılsamalı olabilirsiniz. Manevi zenginlik maddi güvenliğin önüne geçebilir; maddi konularda netlik sağlamak önemlidir.',
  /* House 3 */ 'Neptün 3. evde, düşünceleriniz sezgisel ve şiirsel bir boyut taşır. İletişimde imgeler ve metaforlar güçlüdür; gündelik iletişimde net olmak zaman zaman güçlük yaratabilir.',
  /* House 4 */ 'Neptün 4. evde, aile ve köken konusunda idealize etme ya da yanılsama yaşayabilirsiniz. Ruhsal bir yuva arayışı güçlüdür; duygusal sınırları netleştirmek dönüştürücü olabilir.',
  /* House 5 */ 'Neptün 5. evde, yaratıcılık ve aşk romantik ve idealist bir renk alır. Sanat ve hayal gücü yoluyla derin bir ifade bulursunuz; sevgide gerçekçilik ile romantizm arasında denge önemlidir.',
  /* House 6 */ 'Neptün 6. evde, sağlık ve çalışma konularında sezgisel bir yaklaşım benimsersiniz. Şifa ve hizmet alanında güçlü bir empati taşırsınız; sınırları netleştirmek enerjinizi korur.',
  /* House 7 */ 'Neptün 7. evde, ilişkilerde idealize etme ve yanılsama güçlüdür. Koşulsuz sevgi ve empati ortaklıklarınızı besler; sağlıklı sınırlar oluşturmak ilişkilerinizi güçlendirir.',
  /* House 8 */ 'Neptün 8. evde, derin dönüşümler ve bilinçdışı süreçler mistik bir boyut kazanır. Ölüm ve yeniden doğuş temaları manevi bir anlam taşır; paylaşılan kaynaklarda netlik önemlidir.',
  /* House 9 */ 'Neptün 9. evde, inanç ve felsefede derin bir mistisizm ve idealizm taşırsınız. Manevi arayış ve ruhsal öğretiler sizi besler; dogmatizmden uzak kalmak özgürlüğünüzü korur.',
  /* House 10 */ 'Neptün 10. evde, kariyerinizde sanatsal, manevi veya şifa verici alanlar öne çıkar. Kamuoyunda idealize edilme ya da yanılsama yaşanabilir; gerçekçilik ile vizyonu dengelemek başarı getirir.',
  /* House 11 */ 'Neptün 11. evde, kolektif idealler ve insanlığa hizmet güçlü bir motivasyon kaynağıdır. Topluluk bağlarında idealizm ve yanılsama yaşanabilir; gerçek ve sahte grupları ayırt etmek önem kazanır.',
  /* House 12 */ 'Neptün 12. evde, manevi derinlik ve bilinçdışı süreçler güçlüdür. Sezgi ve mistik deneyimler sizi besler; yalnızlık ve sessizlikte en derin ilhamı bulursunuz.',
];

export const PLUTO_IN_HOUSE: string[] = [
  /* House 1 */ 'Plüton 1. evde, kişiliğiniz derin bir dönüşüm gücü taşır. Başkalarını güçlü biçimde etkilersiniz; kendinizi sürekli yeniden yaratma ve dönüştürme kapasitesine sahipsinizdir.',
  /* House 2 */ 'Plüton 2. evde, maddi kaynaklar ve değerler köklü dönüşümler geçirir. Güç ve kontrol ile para arasındaki ilişki derin bir tema oluşturur; kayıplar aracılığıyla gerçek zenginliği keşfedersiniz.',
  /* House 3 */ 'Plüton 3. evde, düşünceleriniz ve iletişiminiz derin ve dönüştürücü bir güce sahiptir. Gerçeği araştırma ve gizlileri ortaya çıkarma konusunda güçlü bir dürtü taşırsınız.',
  /* House 4 */ 'Plüton 4. evde, aile ve köken konularında güçlü dönüşümler yaşarsınız. Geçmişin gizli örüntülerini yüzeye çıkarmak iyileştirici olabilir; duygusal temeller kökten yenilenir.',
  /* House 5 */ 'Plüton 5. evde, yaratıcılık ve aşk ilişkilerinde yoğun ve dönüştürücü deneyimler yaşarsınız. Yaratma gücünüz hem yıkıcı hem de inşa edicidir; tutkular derin izler bırakır.',
  /* House 6 */ 'Plüton 6. evde, çalışma ve sağlık alanında derin dönüşümler yaşarsınız. Rutin ve sistemleri köklü biçimde yenileme kapasitesi güçlüdür; hastalıklar önemli yaşam dönüşümlerinin habercisi olabilir.',
  /* House 7 */ 'Plüton 7. evde, ilişkiler ve ortaklıklar derin güç dinamiklerini barındırır. Dönüştürücü bağlar yaşarsınız; ilişkiler aracılığıyla kendinizin en derin yüzüyle yüzleşirsiniz.',
  /* House 8 */ 'Plüton 8. evde, ölüm ve yeniden doğuş temaları yaşamınızın merkezindedir. Derin psikolojik dönüşümler ve güç dinamiklerini keşfetme konusunda güçlü bir kapasite taşırsınız.',
  /* House 9 */ 'Plüton 9. evde, inanç ve felsefi anlayışınız köklü dönüşümler geçirir. Dogmaları yıkmak ve gerçeği araştırmak için güçlü bir dürtü taşırsınız; ruhsal yolculuğunuz dönüştürücüdür.',
  /* House 10 */ 'Plüton 10. evde, kariyer ve toplumsal güç alanında dönüştürücü bir etki taşırsınız. Güç mücadeleleri ve dönüşümler kariyerinizde belirleyici rol oynar; gerçek otoritenizi inşa etmek derin bir süreçtir.',
  /* House 11 */ 'Plüton 11. evde, topluluk ve kolektif yapılar aracılığıyla derin dönüşümler yaşarsınız. Grupların güç dinamiklerini görme yeteneğiniz güçlüdür; sosyal değişim için dönüştürücü bir enerji taşırsınız.',
  /* House 12 */ 'Plüton 12. evde, bilinçdışının en derin katmanlarıyla güçlü bir bağınız vardır. Gizli korkular ve kolektif gölgeyle yüzleşme dönüştürücüdür; manevi dönüşüm yaşamınızın merkezindedir.',
];

export const CHIRON_IN_HOUSE: string[] = [
  /* House 1 */ 'Kiron 1. evde, kimlik ve var oluşunuzla ilgili derin bir yara taşırsınız; kendinizi olduğunuz gibi kabul etmek uzun bir yolculuk gerektirebilir. Bu yara aynı zamanda başkalarına kendiniz olma cesareti konusunda ilham verme yeteneğine dönüşür. Kendi özgünlüğünüzü kucaklamak en büyük şifa kaynağınızdır.',
  /* House 2 */ 'Kiron 2. evde, öz değer ve maddi güvenlik konusunda derin bir yara bulunur; yeterli olmadığınız hissi köklü bir iz bırakmış olabilir. Ancak bu yara, başkalarına gerçek değerlerini keşfetmelerinde rehberlik etme gücüne dönüşür. Kendi değerinizle barışmak iyileşmenizin temeli olacaktır.',
  /* House 3 */ 'Kiron 3. evde, iletişim ve öğrenme alanında yara bulunur; erken dönemde fikir ve sözleriniz küçümsenmiş ya da yanlış anlaşılmış olabilir. Bu deneyim zamanla güçlü bir öğretme ve anlatma yeteneğine dönüşür. Kelimelerinizin gücüne güvenmek iyileşme yolunuzdur.',
  /* House 4 */ 'Kiron 4. evde, aile ve köken konusundaki yara derindir; ev ve aitlik duygusu zedelenmiş olabilir. Bu yara, başkalarına güvenli bir alan yaratma konusunda derin bir empati ve yetenek kazandırır. Kendi kökenlerinizle barışmak ve yeni bir aile kavramı oluşturmak dönüştürücüdür.',
  /* House 5 */ 'Kiron 5. evde, yaratıcılık ve ifade özgürlüğü konusunda yara bulunur; görülmek ya da takdir görmek zor gelmiş olabilir. Bu yara, başkalarının yaratıcı potansiyelini açığa çıkarma konusunda güçlü bir yeteneğe dönüşür. Kendi yaratıcılığınıza yatırım yapmak şifanın kapısını açar.',
  /* House 6 */ 'Kiron 6. evde, sağlık ve günlük işleyiş konusundaki yara güçlüdür; bedensel ya da pratik hayat alanında kronik zorluklar yaşanmış olabilir. Bu deneyim, başkalarının sağlık ve iyilik yolculuğunda derin bir anlayış ve şifa getirme yeteneğine dönüşür. Rutini şifalandırıcı bir pratik olarak görmek önemlidir.',
  /* House 7 */ 'Kiron 7. evde, ilişkiler ve ortaklıklar aracılığıyla derin bir yara taşırsınız; yakın bağlarda reddedilme ya da hayal kırıklığı yaşanmış olabilir. Bu yara zamanla ilişki iyileşmesi ve uzlaşma konusunda güçlü bir arabuluculuk yeteneğine dönüşür. Gerçek bağlantı ararken kendinizle barışmak şifanın temelidir.',
  /* House 8 */ 'Kiron 8. evde, kayıp, dönüşüm ve savunmasızlık konularında derin bir yara bulunur; ölüm, cinsellik ya da güç dinamikleri erken yaşta sarsıcı deneyimler yaratmış olabilir. Bu deneyim zamanla derin bir psikolojik şifa ve dönüşüm rehberliği yeteneğine dönüşür. Karanlıkla yüzleşmek sizin en büyük gücünüzü açığa çıkarır.',
  /* House 9 */ 'Kiron 9. evde, inanç ve anlam arayışı konusundaki yara derin olabilir; dogmatik ya da kısıtlayıcı bir inanç sistemiyle büyümüş olabilirsiniz. Bu yara zamanla gerçek anlamı arayan başkalarına rehberlik etme yeteneğine dönüşür. Kendi gerçeğinizi cesurca inşa etmek şifanın yoludur.',
  /* House 10 */ 'Kiron 10. evde, kariyer ve toplumsal başarı konusunda yara bulunur; tanınma ya da başarının zorla kazanılması gerektiği hissi güçlü olabilir. Bu yara başkalarının mesleki yolculuklarında rehberlik ve mentorluk yeteneğine dönüşür. Gerçek başarıyı içeriden tanımlamak iyileşmenizin kaynağıdır.',
  /* House 11 */ 'Kiron 11. evde, aitlik ve topluluk konusunda derin bir yara taşırsınız; dışlanma ya da farklı hissetme deneyimleri güçlü izler bırakmış olabilir. Bu yara, marjinalleşmiş ya da dışlanmış bireylere topluluk ve aitlik duygusu sağlama konusunda güçlü bir yeteneğe dönüşür. Kendi özgünlüğünüzü güç olarak görmek şifanızın temelidir.',
  /* House 12 */ 'Kiron 12. evde, bilinçdışı ve manevi yara derindir; görünmez acılar ve kollektif bir üzüntü taşıyor olabilirsiniz. Bu yara zamanla manevi şifa ve başkalarının bilinçdışı süreçlerini anlamalarında güçlü bir rehberlik yeteneğine dönüşür. Sessizlik ve içsel çalışma sizin en derin şifa kaynağınızdır.',
];

export const CHIRON_IN_SIGN: string[] = [
  /* Aries */ 'Koç burcu Kironu, kimlik ve inisiyatif konusunda yara işaret eder; kendinize ait bir yer açma ve var olma hakkını kazanma süreci iyileştirici bir yolculuktur.',
  /* Taurus */ 'Boğa burcu Kironu, öz değer ve maddi güvenlik konusundaki yarayı gösterir; bedeniyle ve somut dünyayla barışmak derin bir şifa sunar.',
  /* Gemini */ 'İkizler burcu Kironu, iletişim ve öğrenme alanındaki yarayı simgeler; kelimelerini ve düşüncelerini güvenle paylaşabilmek iyileşmenin yoludur.',
  /* Cancer */ 'Yengeç burcu Kironu, beslenme ve ev duygusuyla ilgili yarayı taşır; güvenli bir iç dünya yaratmak ve duygusal sınırları sağlamlaştırmak şifayı getirir.',
  /* Leo */ 'Aslan burcu Kironu, tanınma ve yaratıcı ifade konusundaki yarayı simgeler; kendini olduğu gibi gösterme cesareti en büyük şifa kaynağıdır.',
  /* Virgo */ 'Başak burcu Kironu, mükemmeliyetçilik ve yetersizlik hissiyle ilgili yarayı taşır; yeterince iyi olduğunu kabul etmek ve hizmet etmenin anlamını yeniden keşfetmek şifayı sunar.',
  /* Libra */ 'Terazi burcu Kironu, ilişkiler ve adaletsizlik konusundaki yarayı gösterir; gerçek uyum ve dengeyi kendinizden başlayarak aramak iyileştiricidir.',
  /* Scorpio */ 'Akrep burcu Kironu, güç, kontrol ve derin kayıp konularındaki yarayı simgeler; savunmasızlığı kabullenme ve dönüşüm aracılığıyla güç bulmak şifayı getirir.',
  /* Sagittarius */ 'Yay burcu Kironu, inanç ve anlam arayışındaki yarayı taşır; kendi gerçeğini özgürce aramak ve dogmalardan bağımsızlaşmak iyileşmenin yoludur.',
  /* Capricorn */ 'Oğlak burcu Kironu, otorite ve başarıyla ilgili yarayı gösterir; başarının korkudan değil özgün değerlerden gelmesine izin vermek şifayı açar.',
  /* Aquarius */ 'Kova burcu Kironu, aitlik ve dışlanmayla ilgili yarayı simgeler; özgünlüğünü toplulukla bir arada var edebilmek derin bir iyileşme sağlar.',
  /* Pisces */ 'Balık burcu Kironu, sınır belirsizliği ve savunmasızlıkla ilgili derin bir yara taşır; sezgisel şifa kapasitesini geliştirmek ve sınırları öğrenmek iyileşmenin yoludur.',
];

export const NORTH_NODE_HOUSE: string[] = [
  /* House 1 */ 'Kuzey Düğümü 1. evde, evrimsel amacınız kendinizi özgürce var etmek ve özgün kimliğinizi geliştirmektir. Başkalarına bağımlılıktan vazgeçerek kendi liderliğinizi üstlenmek ruhunuzun yönüdür.',
  /* House 2 */ 'Kuzey Düğümü 2. evde, evrimsel büyümeniz öz değeri içselleştirmek ve maddi gerçekliğe sağlam biçimde tutunmak aracılığıyla gelir. Kendi kaynaklarınızı ve yeteneklerinizi güvene almak ruhsal yolculuğunuzun özüdür.',
  /* House 3 */ 'Kuzey Düğümü 3. evde, evrimsel amaç iletişim ve öğrenimdeki merakı geliştirmektir. Gündelik çevre ve fikir alışverişi aracılığıyla büyümek ruhunuzun çağrısıdır.',
  /* House 4 */ 'Kuzey Düğümü 4. evde, evrimsel yolculuk içsel güvenlik ve duygusal köklere dönme aracılığıyla ilerler. Güvenli bir iç dünya inşa etmek ve aileyle barışmak ruhunuzun amacıdır.',
  /* House 5 */ 'Kuzey Düğümü 5. evde, evrimsel büyüme yaratıcı ifade, zevk ve özgün sevgi aracılığıyla gerçekleşir. Kalbinizin sesini dinleyerek hayatı kutlamak ruhsal yolunuzdur.',
  /* House 6 */ 'Kuzey Düğümü 6. evde, evrimsel amaç günlük hizmete ve pratik ustalığa odaklanmaktır. Rutin ve disiplin aracılığıyla büyümek, bedeninize ve çalışmanıza saygı göstermek ruhunuzun yönüdür.',
  /* House 7 */ 'Kuzey Düğümü 7. evde, evrimsel yolculuk gerçek ortaklıklar ve ilişkiler aracılığıyla ilerler. Başkasıyla derin bir bağ kurmak ve işbirliğini öğrenmek ruhunuzun amacıdır.',
  /* House 8 */ 'Kuzey Düğümü 8. evde, evrimsel büyüme dönüşüm ve savunmasızlığı kucaklamak aracılığıyla gelir. Derin paylaşım ve pskolojik iyileşme ruhunuzun yönüdür.',
  /* House 9 */ 'Kuzey Düğümü 9. evde, evrimsel amaç bilgelik, anlam ve özgürlük arayışında yatmaktadır. Farklı kültür ve inançları keşfederek ufkunu genişletmek ruhsal yolculuğunuzdur.',
  /* House 10 */ 'Kuzey Düğümü 10. evde, evrimsel büyüme toplumsal katkı ve mesleki amaç aracılığıyla gelir. Dünyada görünür ve anlamlı bir rol üstlenmek ruhunuzun çağrısıdır.',
  /* House 11 */ 'Kuzey Düğümü 11. evde, evrimsel yolculuk topluluk, kolektif vizyon ve insanlığa katkıyla ilerler. Bireysel çıkarların ötesine geçerek ortak bir geleceği inşa etmek ruhunuzun amacıdır.',
  /* House 12 */ 'Kuzey Düğümü 12. evde, evrimsel amaç manevi derinlik, yalnızlık ve sezgiyi geliştirmektir. Bilinçdışıyla bağ kurmak ve sessizlikte bilgelik bulmak ruhsal yolculuğunuzun özüdür.',
];

export const NORTH_NODE_IN_SIGN: string[] = [
  /* Aries */ 'Kuzey Düğümü Koç\'ta, ruhsal yolculuğunuz bağımsızlığı ve özgün inisiyatifi kucaklamaya yöneliktir. Başkalarının onayını beklemeden harekete geçmeyi öğrenmek büyümenizin merkezindedir. Cesaret ve öz güven ruhunuzun çağrısını yanıtlar.',
  /* Taurus */ 'Kuzey Düğümü Boğa\'da, evrimsel yolculuğunuz somut değerler ve güvenli bir hayat inşa etmeye odaklanır. Sabır, bedensel farkındalık ve gerçek konforu deneyimlemek ruhunuzun büyümesidir. Süreklilik ve istikrar en büyük hedefinizdir.',
  /* Gemini */ 'Kuzey Düğümü İkizler\'de, evrimsel büyüme merak, iletişim ve çeşitlilik aracılığıyla gerçekleşir. Tek bir doğruda ısrar etmek yerine bilginin farklı boyutlarını keşfetmek ruhunuzu besler. Esneklik ve açık zihin yolculuğunuzun anahtarıdır.',
  /* Cancer */ 'Kuzey Düğümü Yengeç\'te, ruhsal yolculuğunuz duygusal kökler ve içsel güvenliği geliştirmeyi hedefler. Sertlik ve başarı odaklılıktan duygusal besleniş ve bakım sunmaya evrilmek büyümenizin özüdür. Yumuşaklık ve kırılganlık güç kaynağınızdır.',
  /* Leo */ 'Kuzey Düğümü Aslan\'da, evrimsel büyüme özgün yaratıcılığı ve kalbinizin sevincini ifade etmeyle gelir. Gruba ya da kolektif beklentilere sığınmak yerine bireysel ışığınızı öne çıkarmak ruhunuzun amacıdır. Oyun, sevgi ve cömertlik yolunuzu aydınlatır.',
  /* Virgo */ 'Kuzey Düğümü Başak\'ta, evrimsel yol pratik hizmet, analiz ve iyileştirme sanatına odaklanır. Büyük hayaller ve sezgilerden somut ve disiplinli bir çalışma anlayışına geçmek büyümenizi simgeler. Mütevazılık ve dikkat ruhunuzun çağrısıdır.',
  /* Libra */ 'Kuzey Düğümü Terazi\'de, ruhsal büyüme ilişkilerde uyum, adalet ve işbirliğini öğrenmekle gelir. Tek başına hareket etmek yerine birlikte inşa etmeyi benimsemek evrimsel amacınızdır. Denge ve şefkat yolculuğunuzun rehberidir.',
  /* Scorpio */ 'Kuzey Düğümü Akrep\'te, evrimsel yolculuk dönüşüm, derinlik ve savunmasızlığı kucaklamayı içerir. Yüzeysel güvenlikten vazgeçerek yaşamın derin gerçekleriyle yüzleşmek ruhunuzu büyütür. Güç, iyileşme ve yeniden doğuş yolunuzun özüdür.',
  /* Sagittarius */ 'Kuzey Düğümü Yay\'da, evrimsel büyüme anlam arayışı, özgürlük ve yüksek bilgelik aracılığıyla gelir. Gündelik ayrıntılara odaklanmaktan büyük resmi görmek ve ufku genişletmek ruhunuzun çağrısıdır. Macera ve öğrenme yolunuzun anahtarıdır.',
  /* Capricorn */ 'Kuzey Düğümü Oğlak\'ta, evrimsel yolculuğunuz sorumluluk, disiplin ve kalıcı bir miras inşa etmeyle ilerler. Duygusal güvenlikten çıkarak dünyadaki rolünüzü üstlenmek büyümenizin özüdür. Sabır ve kararlılık ruhsal amacınızı şekillendirir.',
  /* Aquarius */ 'Kuzey Düğümü Kova\'da, evrimsel büyüme topluluk, insanlık ve yenilikçi vizyonla gerçekleşir. Bireysel çıkarların ötesine geçerek kolektif geleceğe katkıda bulunmak ruhunuzun amacıdır. Özgünlük ve dayanışma yolunuzu aydınlatır.',
  /* Pisces */ 'Kuzey Düğümü Balık\'ta, ruhsal yolculuğunuz şefkat, sezgi ve evrensel bağlılığı geliştirmeyi hedefler. Sert gerçekçilikten manevi duyarlılığa ve şefkate açılmak büyümenizin özüdür. Empati ve teslimiyet ruhunuzu besler.',
];

export const SIGN_NAMES = ['Koç','Boğa','İkizler','Yengeç','Aslan','Başak','Terazi','Akrep','Yay','Oğlak','Kova','Balık'];

export const PLANET_NAMES: Record<string,string> = {
  sun: 'Güneş',
  moon: 'Ay',
  mercury: 'Merkür',
  venus: 'Venüs',
  mars: 'Mars',
  jupiter: 'Jüpiter',
  saturn: 'Satürn',
  uranus: 'Uranüs',
  neptune: 'Neptün',
  pluto: 'Plüton',
  northNode: 'Kuzey Düğümü',
  chiron: 'Kiron',
  lilith: 'Lilit',
};

export const MONTHS = ['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'];

export const SECTION_TITLES = {
  sun: (house: number, sign: string) => `☉ Güneş ${house}. Evde ${sign}`,
  moon: (house: number, sign: string) => `☽ Ay ${house}. Evde ${sign}`,
  mercury: (house: number, sign: string) => `☿ Merkür ${house}. Evde ${sign}`,
  venus: (house: number, sign: string) => `♀ Venüs ${house}. Evde ${sign}`,
  mars: (house: number, sign: string) => `♂ Mars ${house}. Evde ${sign}`,
  jupiter: (house: number, sign: string) => `♃ Jüpiter ${house}. Evde ${sign}`,
  saturn: (house: number, sign: string) => `♄ Satürn ${house}. Evde ${sign}`,
  uranus: (house: number, sign: string) => `♅ Uranüs ${house}. Evde ${sign}`,
  neptune: (house: number, sign: string) => `♆ Neptün ${house}. Evde ${sign}`,
  pluto: (house: number, sign: string) => `♇ Plüton ${house}. Evde ${sign}`,
  northNode: (house: number, sign: string) => `☊ Kuzey Düğümü ${house}. Evde ${sign}`,
  chiron: (house: number, sign: string) => `⚷ Kiron ${house}. Evde ${sign}`,
  ascendant: (sign: string) => `Yükselen ${sign}`,
};

export const PLANET_SUBTITLES: Record<string,string> = {
  sun: 'Güneş özünüz — kimlik, amaç ve yaşam enerjisi',
  moon: 'Duygusal dünyanız — ihtiyaçlar, içgüdüler ve iç güvenlik',
  mercury: 'Zihniniz ve iletişiminiz — nasıl düşünür ve öğrenirsiniz',
  venus: 'Aşk diliniz — neyi çekersiniz ve neye değer verirsiniz',
  mars: 'Dürtünüz ve eyleminiz — hedefleri nasıl takip edersiniz',
  jupiter: 'Genişleme yolunuz — bolluk ve büyümenin aktığı yer',
  saturn: 'Ustalık alanınız — disiplinin kalıcı başarıları dövdüğü yer',
  uranus: 'İç devriminiz — kalıpları kırdığınız yer',
  neptune: 'Ruhsal portalınız — sınırları çözdüğünüz yer',
  pluto: 'Dönüştürücü gücünüz — derin ölüm ve yeniden doğuş',
  northNode: 'Evrimsel amacınız — ruhunuzun yönü',
  chiron: 'Kutsal yaranız — şifa armağanına dönüşen acı',
};

export const LABELS = {
  reportTitle: 'Tam Doğum Raporu',
  reportSubtitle: 'Derin Yorum',
  positions: 'Gezegen Konumları',
  houses: 'Ev Başlangıçları',
  overview: 'Genel Bakış',
  potentials: '5 En Büyük Potansiyeliniz',
  challenges: '5 Ana Zorluğunuz',
  conclusion: 'Sonuç',
  advice: 'Pratik Tavsiye',
  elements: 'Elementler ve Modaliteler',
  dignities: 'Temel Onurlar',
  aspects: 'Ana Açılar',
  themes: 'Tematik Sentez',
  quote: '"Yıldızlar eğilim verir, belirlemez."',
  sampleNote: 'Bu ücretsiz bir örnekti!',
  sampleFull: 'Tam rapor 20-30 sayfa detaylı yorum içerir.',
  buyNow: 'Tam sürüm:',
  buyInstant: 'Şimdi satın alın ve anında indirin — %100 tarayıcınızda.',
  natalChart: 'Doğum Haritanız',
  retrograde: '(geri giden)',
  annualTitle: 'Yıllık Tahmin',
  annualSubtitle: 'Geçişler ve eğilimler',
  profection: 'Yıllık Profeksiyon — Yılın Teması',
  houseInFocus: 'Odakta',
  rulerOfYear: 'Yılın Yöneticisi',
  eclipses: 'Yılın Tutulmaları',
  jupiterExpansion: 'Yılın Genişlemesi',
  saturnLesson: 'Yılın Dersi',
  conclusionAnnual: 'Sonuç — Yılınız Perspektifte',
  relationshipTitle: 'İlişki Raporu',
  compatibility: 'Uyumluluk',
  emotionalConnection: 'Duygusal Bağlantı',
  attractionChemistry: 'Çekim ve Kimya',
  communication: 'İletişim',
  commitmentLimits: 'Bağlılık ve Sınırlar — Satürn',
  growthPotential: 'Büyüme Potansiyeli',
  challengesTension: 'Gerilim Noktaları',
  psychTitle: 'Derin Psikolojik Analiz',
  egoStructure: 'Ego Yapısı — Güneş ve Yükselen',
  emotionalWorld: 'Duygusal Dünya — Ay',
  mentalProcesses: 'Zihinsel Süreçler — Merkür',
  lovePatterns: 'Aşk Kalıpları — Venüs',
  vitalForce: 'Yaşam Gücü — Mars',
  shadow: 'Gölge — Plüton',
  wound: 'Çekirdek Yara — Kiron',
  unconscious: 'Bilinçdışı — 12. Ev ve Neptün',
  familyPatterns: 'Aile Kalıpları — Ay, 4. Ev ve Satürn',
  defenseMechanisms: 'Savunma Mekanizmaları — Satürn',
  integrationPath: 'Entegrasyon Yolu — Kuzey Düğümü',
  careerTitle: 'Kariyer ve Meslek',
  midheaven: 'Gökyüzü Ortası',
  house10: '10. Ev — Meslek',
  house6: '6. Ev — Rutin ve İş',
  house2: '2. Ev — Kaynaklar ve Yetenekler',
  sinsTitle: 'Yedi Ölümcül Günah',
  pride: 'Gurur — Güneş',
  lust: 'Şehvet — Venüs ve Mars',
  greed: 'Açgözlülk — Satürn',
  gluttony: 'Oburluk — Jüpiter',
  wrath: 'Gazap — Mars',
  envy: 'Kıskançlık — Plüton',
  sloth: 'Tembellik — Neptün',
  repetitivePatterns: 'Tekrarlayan Kalıplar — Kareler ve Karşıtlıklar',
  unexploredPotentials: 'Keşfedilmemiş Potansiyeller — Üçgenler ve Yetenekler',
  integrationPaths: 'Entegrasyon Yolları',
  recommendedPractices: 'Önerilen Uygulamalar',
  childhoodTemplate: 'Çocukluk ve Duygusal Şablon',
  fromWoundToGift: 'Yaradan Armağana',
  differentiation: 'Farklılaşma — Kendiniz Olmak',
  mainTensions: 'Haritanın Ana Gerilimleri',
  plutoAspects: 'Gergin Plüton Açıları',
};

export const TRANSITIONS = {
  afterOverview: 'Bu kimlik temeli, gezegenlerin evlerinde somut olarak tezahür eder.',
  afterPersonalPlanets: 'Gezegenler arasındaki açılar, bu enerjilerin nasıl etkileştiğini ortaya koyar.',
  afterAspects: 'Bu etkileşimlerden kalıplar doğar — deneyiminizin merkezi temaları.',
  beforeConclusion: 'Her şeyi bir araya getirdiğimizde, haritanız tutarlı bir hikaye anlatır.',
};
