// INTERPRETATIONS — Türkçe (tr)
import { SUN_IN_HOUSE, MOON_IN_HOUSE, MERCURY_IN_HOUSE } from './pt';
import { VENUS_IN_HOUSE, MARS_IN_HOUSE, NORTH_NODE_HOUSE, NORTH_NODE_IN_SIGN } from '../interpret';
import { JUPITER_IN_HOUSE, SATURN_IN_HOUSE, URANUS_IN_HOUSE, NEPTUNE_IN_HOUSE, PLUTO_IN_HOUSE } from '../outer-planets';
import { CHIRON_IN_HOUSE, CHIRON_IN_SIGN } from '../chiron';
export { SUN_IN_HOUSE, MOON_IN_HOUSE, MERCURY_IN_HOUSE, VENUS_IN_HOUSE, MARS_IN_HOUSE };
export { JUPITER_IN_HOUSE, SATURN_IN_HOUSE, URANUS_IN_HOUSE, NEPTUNE_IN_HOUSE, PLUTO_IN_HOUSE };
export { CHIRON_IN_HOUSE, CHIRON_IN_SIGN, NORTH_NODE_HOUSE, NORTH_NODE_IN_SIGN };
export const SIGN_NAMES = ['Koç','Boğa','İkizler','Yengeç','Aslan','Başak','Terazi','Akrep','Yay','Oğlak','Kova','Balık'];
export const PLANET_NAMES: Record<string,string> = { sun:'Güneş', moon:'Ay', mercury:'Merkür', venus:'Venüs', mars:'Mars', jupiter:'Jüpiter', saturn:'Satürn', uranus:'Uranüs', neptune:'Neptün', pluto:'Plüton', northNode:'Kuzey Düğümü', chiron:'Chiron', lilith:'Lilith' };
export const MONTHS = ['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'];
export const SECTION_TITLES = { sun:(h:number,s:string)=>`☉ Güneş ${h}. Evde ${s} burcunda`, moon:(h:number,s:string)=>`☽ Ay ${h}. Evde ${s} burcunda`, mercury:(h:number,s:string)=>`☿ Merkür ${h}. Evde ${s} burcunda`, venus:(h:number,s:string)=>`♀ Venüs ${h}. Evde ${s} burcunda`, mars:(h:number,s:string)=>`♂ Mars ${h}. Evde ${s} burcunda`, jupiter:(h:number,s:string)=>`♃ Jüpiter ${h}. Evde ${s} burcunda`, saturn:(h:number,s:string)=>`♄ Satürn ${h}. Evde ${s} burcunda`, uranus:(h:number,s:string)=>`♅ Uranüs ${h}. Evde ${s} burcunda`, neptune:(h:number,s:string)=>`♆ Neptün ${h}. Evde ${s} burcunda`, pluto:(h:number,s:string)=>`♇ Plüton ${h}. Evde ${s} burcunda`, northNode:(h:number,s:string)=>`☊ Kuzey Düğümü ${h}. Evde ${s} burcunda`, chiron:(h:number,s:string)=>`⚷ Chiron ${h}. Evde ${s} burcunda`, ascendant:(s:string)=>`Yükselen ${s}` };
export const PLANET_SUBTITLES: Record<string,string> = { sun:'Güneş özünüz — kimlik, amaç ve yaşam enerjisi', moon:'Duygusal dünyanız — ihtiyaçlar, içgüdüler ve iç güvenlik', mercury:'Zihniniz ve iletişiminiz — nasıl düşünür ve öğrenirsiniz', venus:'Aşk diliniz — neyi çekersiniz ve değer verirsiniz', mars:'Dürtü ve eyleminiz — hedefleri nasıl takip edersiniz', jupiter:'Genişleme yolunuz — bolluk ve büyümenin aktığı yer', saturn:'Ustalık alanınız — disiplinin kalıcı başarılar ürettiği yer', uranus:'İç devriminiz — kalıpları kırdığınız yer', neptune:'Ruhani portalınız — sınırları çözdüğünüz yer', pluto:'Dönüştürücü gücünüz — derin ölüm ve yeniden doğuş', northNode:'Evrimsel amacınız — ruhunuzun yöneldiği yön', chiron:'Kutsal yaranız — şifa armağanına dönüşen acı' };
export const LABELS = { reportTitle:'Tam Doğum Raporu', reportSubtitle:'Derin Yorumlama', positions:'Gezegen Konumları', houses:'Ev Başlangıçları', overview:'Genel Bakış', potentials:'En Büyük 5 Potansiyeliniz', challenges:'5 Ana Zorluğunuz', conclusion:'Sonuç', advice:'Pratik Tavsiye', elements:'Elementler ve Modaliteler', dignities:'Temel İtibarlar', aspects:'Ana Açılar', themes:'Tematik Sentez', quote:'"Yıldızlar eğilim verir, belirlemez."', sampleNote:'Bu ücretsiz bir önizlemeydi!', sampleFull:'Tam rapor 20-30 sayfa detaylı yorum içerir.', buyNow:'Tam versiyon:', buyInstant:'Şimdi satın alın ve anında indirin — 100% tarayıcıda.', natalChart:'Doğum Haritanız', retrograde:'(retrograd)', annualTitle:'Yıllık Öngörü', annualSubtitle:'Transitler ve eğilimler', profection:'Yıllık Profeksiyon — Yılın Teması', houseInFocus:'Odakta', rulerOfYear:'Yılın Yöneticisi', eclipses:'Yılın Tutulmaları', jupiterExpansion:'Yılın Genişlemesi', saturnLesson:'Yılın Dersi', conclusionAnnual:'Sonuç — Yılınız Perspektifte', relationshipTitle:'İlişki Raporu', compatibility:'Uyumluluk', emotionalConnection:'Duygusal Bağ', attractionChemistry:'Çekim ve Kimya', communication:'İletişim', commitmentLimits:'Bağlılık ve Sınırlar — Satürn', growthPotential:'Büyüme Potansiyeli', challengesTension:'Gerilim Noktaları', psychTitle:'Derin Psikolojik Analiz', egoStructure:'Ego Yapısı — Güneş ve Yükselen', emotionalWorld:'Duygusal Dünya — Ay', mentalProcesses:'Zihinsel Süreçler — Merkür', lovePatterns:'Aşk Kalıpları — Venüs', vitalForce:'Yaşam Gücü — Mars', shadow:'Gölge — Plüton', wound:'Çekirdek Yara — Chiron', unconscious:'Bilinçdışı — 12. Ev ve Neptün', familyPatterns:'Aile Kalıpları — Ay, 4. Ev ve Satürn', defenseMechanisms:'Savunma Mekanizmaları — Satürn', integrationPath:'Entegrasyon Yolu — Kuzey Düğümü', careerTitle:'Kariyer ve Meslek', midheaven:'Gökyüzü Ortası', house10:'10. Ev — Meslek', house6:'6. Ev — Rutin ve İş', house2:'2. Ev — Kaynaklar ve Yetenekler', sinsTitle:'Yedi Günah', pride:'Kibir — Güneş', lust:'Şehvet — Venüs ve Mars', greed:'Açgözlülük — Satürn', gluttony:'Oburluk — Jüpiter', wrath:'Gazap — Mars', envy:'Kıskançlık — Plüton', sloth:'Tembellik — Neptün', repetitivePatterns:'Tekrarlayan Kalıplar — Kareler ve Karşıtlıklar', unexploredPotentials:'Keşfedilmemiş Potansiyeller — Üçgenler ve Yetenekler', integrationPaths:'Entegrasyon Yolları', recommendedPractices:'Önerilen Uygulamalar', childhoodTemplate:'Çocukluk ve Duygusal Kalıp', fromWoundToGift:'Yaradan Armağana', differentiation:'Farklılaşma — Kendiniz Olmak', mainTensions:'Haritanın Ana Gerilimleri', plutoAspects:'Gergin Plüton Açıları' };
export const TRANSITIONS = { afterOverview:'Bu kimlik temeli, gezegenlerin evlerindeki konumlarında somutlaşır.', afterPersonalPlanets:'Gezegenler arası açılar, bu enerjilerin nasıl iletişim kurduğunu ortaya koyar.', afterAspects:'Bu etkileşimlerden kalıplar doğar — deneyiminizin merkezi temaları.', beforeConclusion:'Her şeyi bir araya getirdiğimizde, haritanız tutarlı bir hikaye anlatır.' };
