// INTERPRETATIONS — 中文 (zh)
import { SUN_IN_HOUSE, MOON_IN_HOUSE, MERCURY_IN_HOUSE } from './pt';
import { VENUS_IN_HOUSE, MARS_IN_HOUSE, NORTH_NODE_HOUSE, NORTH_NODE_IN_SIGN } from '../interpret';
import { JUPITER_IN_HOUSE, SATURN_IN_HOUSE, URANUS_IN_HOUSE, NEPTUNE_IN_HOUSE, PLUTO_IN_HOUSE } from '../outer-planets';
import { CHIRON_IN_HOUSE, CHIRON_IN_SIGN } from '../chiron';
export { SUN_IN_HOUSE, MOON_IN_HOUSE, MERCURY_IN_HOUSE, VENUS_IN_HOUSE, MARS_IN_HOUSE };
export { JUPITER_IN_HOUSE, SATURN_IN_HOUSE, URANUS_IN_HOUSE, NEPTUNE_IN_HOUSE, PLUTO_IN_HOUSE };
export { CHIRON_IN_HOUSE, CHIRON_IN_SIGN, NORTH_NODE_HOUSE, NORTH_NODE_IN_SIGN };
export const SIGN_NAMES = ['白羊座','金牛座','双子座','巨蟹座','狮子座','处女座','天秤座','天蝎座','射手座','摩羯座','水瓶座','双鱼座'];
export const PLANET_NAMES: Record<string,string> = { sun:'太阳', moon:'月亮', mercury:'水星', venus:'金星', mars:'火星', jupiter:'木星', saturn:'土星', uranus:'天王星', neptune:'海王星', pluto:'冥王星', northNode:'北交点', chiron:'凯龙', lilith:'莉莉丝' };
export const MONTHS = ['一月','二月','三月','四月','五月','六月','七月','八月','九月','十月','十一月','十二月'];
export const SECTION_TITLES = { sun:(h:number,s:string)=>`☉ 太阳在第${h}宫 ${s}`, moon:(h:number,s:string)=>`☽ 月亮在第${h}宫 ${s}`, mercury:(h:number,s:string)=>`☿ 水星在第${h}宫 ${s}`, venus:(h:number,s:string)=>`♀ 金星在第${h}宫 ${s}`, mars:(h:number,s:string)=>`♂ 火星在第${h}宫 ${s}`, jupiter:(h:number,s:string)=>`♃ 木星在第${h}宫 ${s}`, saturn:(h:number,s:string)=>`♄ 土星在第${h}宫 ${s}`, uranus:(h:number,s:string)=>`♅ 天王星在第${h}宫 ${s}`, neptune:(h:number,s:string)=>`♆ 海王星在第${h}宫 ${s}`, pluto:(h:number,s:string)=>`♇ 冥王星在第${h}宫 ${s}`, northNode:(h:number,s:string)=>`☊ 北交点在第${h}宫 ${s}`, chiron:(h:number,s:string)=>`⚷ 凯龙在第${h}宫 ${s}`, ascendant:(s:string)=>`上升星座 ${s}` };
export const PLANET_SUBTITLES: Record<string,string> = { sun:'你的太阳本质 — 身份、目的与生命能量', moon:'你的情感世界 — 需求、本能与内在安全感', mercury:'你的思维与沟通 — 你如何思考与学习', venus:'你的爱情语言 — 你吸引什么、珍视什么', mars:'你的驱动力与行动 — 你如何追求目标', jupiter:'你的扩展之路 — 丰盛与成长流向何方', saturn:'你的精通领域 — 纪律锻造持久成就之处', uranus:'你的内在革命 — 你打破模式之处', neptune:'你的灵性门户 — 你消融界限之处', pluto:'你的转化力量 — 深层的死亡与重生', northNode:'你的进化目的 — 灵魂前进的方向', chiron:'你的神圣伤口 — 转化为疗愈之礼的痛苦' };
export const LABELS = { reportTitle:'完整本命报告', reportSubtitle:'深度解读', positions:'行星位置', houses:'宫头', overview:'概述', potentials:'你的5大潜力', challenges:'你的5大挑战', conclusion:'结论', advice:'实用建议', elements:'元素与模式', dignities:'本质尊贵', aspects:'主要相位', themes:'主题综合', quote:'"星辰倾向，而非决定。"', sampleNote:'这是一份免费样本！', sampleFull:'完整报告包含20-30页详细解读。', buyNow:'完整版：', buyInstant:'立即购买并下载 — 100%在浏览器中完成。', natalChart:'你的本命盘', retrograde:'(逆行)', annualTitle:'年度预测', annualSubtitle:'行运与趋势', profection:'年度小限 — 年度主题', houseInFocus:'聚焦', rulerOfYear:'年度主星', eclipses:'年度食相', jupiterExpansion:'年度扩展', saturnLesson:'年度课题', conclusionAnnual:'结论 — 年度展望', relationshipTitle:'关系报告', compatibility:'兼容性', emotionalConnection:'情感连接', attractionChemistry:'吸引力与化学反应', communication:'沟通', commitmentLimits:'承诺与界限 — 土星', growthPotential:'成长潜力', challengesTension:'紧张点', psychTitle:'深度心理分析', egoStructure:'自我结构 — 太阳与上升', emotionalWorld:'情感世界 — 月亮', mentalProcesses:'心智过程 — 水星', lovePatterns:'爱情模式 — 金星', vitalForce:'生命力 — 火星', shadow:'阴影 — 冥王星', wound:'核心伤口 — 凯龙', unconscious:'潜意识 — 第12宫与海王星', familyPatterns:'家庭模式 — 月亮、第4宫与土星', defenseMechanisms:'防御机制 — 土星', integrationPath:'整合之路 — 北交点', careerTitle:'事业与天职', midheaven:'天顶', house10:'第10宫 — 天职', house6:'第6宫 — 日常与工作', house2:'第2宫 — 资源与才能', sinsTitle:'七宗罪', pride:'傲慢 — 太阳', lust:'色欲 — 金星与火星', greed:'贪婪 — 土星', gluttony:'暴食 — 木星', wrath:'暴怒 — 火星', envy:'嫉妒 — 冥王星', sloth:'懒惰 — 海王星', repetitivePatterns:'重复模式 — 四分与对冲', unexploredPotentials:'未开发潜力 — 三分与才能', integrationPaths:'整合路径', recommendedPractices:'推荐练习', childhoodTemplate:'童年与情感模板', fromWoundToGift:'从伤口到礼物', differentiation:'分化 — 做你自己', mainTensions:'星盘主要紧张', plutoAspects:'冥王星紧张相位' };
export const TRANSITIONS = { afterOverview:'这个身份基础在行星所在宫位中具体体现。', afterPersonalPlanets:'行星之间的相位揭示了这些能量如何相互作用。', afterAspects:'从这些互动中浮现出模式 — 你体验的核心主题。', beforeConclusion:'将一切汇集起来，你的星盘讲述了一个连贯的故事。' };
