export const horoscope = {
  daily: {
    title: '個人デイリーホロスコープ',
    subtitle: '詳細な解釈付きのあなたの今日のパーソナルトランジット',
    selectProfile: '個人化されたホロスコープを見るにはプロフィールを選択してください',
    noProfile: 'まず出生図を計算してください。',
    moonToday: '今日の月',
    activeTransits: 'アクティブトランジット',
    intensity: { high: '強い', medium: '中程度', low: '軽い' },
    categories: { love: '恋愛', career: 'キャリア', health: '健康' },
    today: '今日',
    tomorrow: '明日',
  },
  love: {
    title: '恋愛ホロスコープ',
    subtitle: 'あなたの恋愛生活に影響する金星、火星、今日のアスペクト',
  },
  weekly: {
    title: '週間ホロスコープ',
    subtitle: '今後7日間のトランジットとエネルギーの概要',
    thisWeek: '今週',
    prevWeek: '← 前週',
    nextWeek: '翌週 →',
    selectProfile: '週間ホロスコープを見るにはプロフィールを選択してください',
  },
  events: {
    title: '天体イベント',
    subtitle: '惑星インギュリス、正確なアスペクト、月相、逆行ステーション',
    noEvents: 'この日に重要な天体イベントはありません。',
    types: { ingress: 'インギュリス', aspect: '正確なアスペクト', 'moon-phase': '月相', retrograde: 'ステーション' },
  },
  interpretation: {
    title: '基本解釈',
    premiumCta: '完全なパーソナライズ分析が必要ですか？',
    premiumDesc: '完全ネイタルレポートにはすべての惑星、アスペクト、品位と予測がプロフェッショナルPDFで含まれます。',
    premiumButton: 'プレミアムレポートを見る',
    freeNotice: '無料の概要解釈。完全分析（20ページ以上）はプレミアムレポートをご覧ください。',
  },
  transitTexts: {
    noTransits: '重要なトランジットのない穏やかな日。休息と内省の時間を取りましょう。',
    intenseDay: '複数の強力なトランジットを持つ激しい日。意識的で柔軟に。',
    normalWork: '通常の仕事日。日常業務に集中を保ちましょう。',
    energyHigh: 'エネルギーが高いが過剰傾向。運動するが過度に疲れないよう注意。',
    vitalityGood: '活力が高い。身体活動やスポーツに最適。',
    energyStable: '安定したエネルギー。健康的な習慣を維持し、自分のリズムを尊重して。',
  },
  moonLove: [
    'ロマンティックな衝動と素早い情熱。',
    '官能性と一緒に快適さを求める気持ち。',
    '知的なフリートとセダクティブな会話。',
    '愛における愛情と安心の必要性。',
    'ドラマティックなロマンスと寛大な表現。',
    '実際の行動で示される愛。',
    '調和と友情の探求。',
    '激しく独占的な欲望。',
    '新しさと冒険への引力。',
    '成熟した愛とコミットメント。',
    '愛における自由と珍しいつながり。',
    'ロマンティシズムと理想化。',
  ],
};
