export const chiron = {
  title: 'Chiron — Der Verwundete Heiler',
  intro: 'Chiron ist ein 1977 entdeckter Himmelskörper, klassifiziert als Planetoid oder Zentaur, in einer Umlaufbahn zwischen Saturn und Uranus. In der humanistischen Astrologie repräsentiert er die urwüchsige Wunde, die wir tragen — einen Schmerz, den wir in uns selbst nicht heilen können, der uns paradoxerweise jedoch befähigt, anderen zu helfen. Es ist der Archetyp des Therapeuten, Mentors und Weisen, der durch Leid lernte.',
  mythology: {
    title: 'Die Mythologie des Chiron',
    text: 'Chiron war ein Zentaur, der sich von anderen unterschied: weise, zivilisiert, Meister der Medizin, Musik, Prophezeiung und Kampfkünste. Er war Tutor für Helden wie Achilles, Asklepios und Jason. Als Sohn von Kronos und Philyra wurde er bei der Geburt von seiner Mutter verlassen, weil er halb Mensch, halb Pferd war — seine erste Wunde: die Ablehnung durch seine eigene Herkunft.',
    wound: 'Seine tragische Ironie: Als größter Heiler des antiken Griechenlands erhielt er einen vergifteten Pfeil von Herakles — ein Unfall, keine Bosheit — und konnte als Unsterblicher weder sterben noch sich selbst heilen. Er lebte in ewigem Schmerz, bis er seine Unsterblichkeit aufgab und in ein Sternbild verwandelt wurde.',
    meaning: 'Chirons Wunde wird nicht gelöst. Sie wird integriert. Das ist der grundlegende Unterschied zwischen Saturn (der durch Disziplin überwindet) und Chiron (der lernt, mit der Wunde zu leben, bis sie zur Weisheit wird).',
  },
  signsTitle: 'Chiron Durch die Zeichen',
  signsIntro: 'Das Zeichen von Chiron offenbart die Natur der Wunde — das "wo es wehtut" auf der Ebene der Identität. Da Chiron zwischen 4 und 9 Jahren in jedem Zeichen verbringt, ist es eine Generationenwunde, die von Millionen geteilt wird.',
  signs: [
    { sign: 'Widder ♈', years: '(1968–77 / 2018–27)', wound: 'Wunde in der Existenz und Initiative', healing: 'Heilung durch das Recht zu handeln, zu führen und vollständig zu existieren' },
    { sign: 'Stier ♉', years: '(1977–83)', wound: 'Wunde im Selbstwert und Körper', healing: 'Heilung durch eine gesunde Beziehung zum Selbstwert und Ressourcen' },
    { sign: 'Zwillinge ♊', years: '(1983–88)', wound: 'Wunde in Kommunikation und Intellekt', healing: 'Heilung durch die Fähigkeit, gehört und verstanden zu werden' },
    { sign: 'Krebs ♋', years: '(1988–91)', wound: 'Wunde in Zugehörigkeit und Familie', healing: 'Heilung durch das Erschaffen eines inneren Zuhauses, unabhängig vom äußeren' },
    { sign: 'Löwe ♌', years: '(1991–93)', wound: 'Wunde in Selbstausdruck und Anerkennung', healing: 'Heilung durch das Recht zu glänzen, ohne Zustimmung zu brauchen' },
    { sign: 'Jungfrau ♍', years: '(1993–96)', wound: 'Wunde in Perfektion und Angemessenheit', healing: 'Heilung durch das Akzeptieren von Unvollkommenheit als Teil des Menschseins' },
    { sign: 'Waage ♎', years: '(1996–99)', wound: 'Wunde in Beziehungen und Balance', healing: 'Heilung durch das Erlernen, sich zu verbinden ohne sich zu verlieren' },
    { sign: 'Skorpion ♏', years: '(1999–01)', wound: 'Wunde in Macht und Intimität', healing: 'Heilung durch das Konfrontieren von Schatten ohne Zerstörung' },
    { sign: 'Schütze ♐', years: '(2001–05)', wound: 'Wunde in Glauben, Sinn und philosophischer Zugehörigkeit', healing: 'Heilung durch das Finden einer eigenen Wahrheit, nicht einer geerbten' },
    { sign: 'Steinbock ♑', years: '(2005–10)', wound: 'Wunde in Autorität und Erfolg', healing: 'Heilung durch das Neudefinieren von Erfolg nach eigenen Maßstäben' },
    { sign: 'Wassermann ♒', years: '(2010–11)', wound: 'Wunde in Originalität und Gruppenzugehörigkeit', healing: 'Heilung durch das Recht, anders zu sein und trotzdem geliebt zu werden' },
    { sign: 'Fische ♓', years: '(2011–18)', wound: 'Wunde in Spiritualität und Ego-Grenzen', healing: 'Heilung durch Integration des Transzendenten ohne sich darin aufzulösen' },
  ],
  housesTitle: 'Chiron Durch die Häuser',
  housesIntro: 'Das Haus von Chiron zeigt den Lebensbereich an, wo die Wunde sich manifestiert — wo Sie sich wie der "ewige Verwundete, der andere heilt" fühlen. Es ist auch der Ort, wo Ihre größte Weisheit nach der Integration entsteht.',
  houses: [
    { num: '1.', name: 'Haus der Identität', wound: 'Wunde in der eigenen Existenz und Präsenz', gift: 'Kraft, andere zu lehren, wie man vollständig existiert' },
    { num: '2.', name: 'Haus der Ressourcen', wound: 'Wunde im Selbstwert und materiellen Unterhalt', gift: 'Gabe, anderen zu helfen, ihre Talente zu entdecken' },
    { num: '3.', name: 'Haus der Kommunikation', wound: 'Wunde im verbalen Ausdruck und Lernen', gift: 'Gabe als Lehrer, Schriftsteller oder Kommunikator' },
    { num: '4.', name: 'Haus des Zuhauses', wound: 'Wunde in Wurzeln, Familie und emotionaler Sicherheit', gift: 'Fähigkeit, für andere Zuhause und Geborgenheit zu schaffen' },
    { num: '5.', name: 'Haus der Kreativität', wound: 'Wunde im kreativen Selbstausdruck und der Freude', gift: 'Gabe, Kreativität in anderen zu inspirieren' },
    { num: '6.', name: 'Haus der Gesundheit', wound: 'Wunde in Körper, Gesundheit und Routinen', gift: 'Gabe für körperliche und ganzheitliche Heilung' },
    { num: '7.', name: 'Haus der Beziehungen', wound: 'Wunde in intimem Partnerschaft und Verpflichtung', gift: 'Gabe für Mediation und Beratung in Beziehungen' },
    { num: '8.', name: 'Haus der Transformation', wound: 'Wunde in Verlusten, Sexualität und gemeinsamer Macht', gift: 'Gabe, andere durch Tod/Wiedergeburtsprozesse zu führen' },
    { num: '9.', name: 'Haus der Philosophie', wound: 'Wunde in Überzeugung, Glaube und Sinnsuche', gift: 'Gabe als spiritueller Lehrer und Philosoph' },
    { num: '10.', name: 'Haus der Karriere', wound: 'Wunde in öffentlicher Anerkennung und Autorität', gift: 'Gabe für Führung mit echter Bescheidenheit' },
    { num: '11.', name: 'Haus der Gruppen', wound: 'Wunde in Zugehörigkeit und Freundschaften', gift: 'Gabe für das Heilen von Gemeinschaften und Gruppen' },
    { num: '12.', name: 'Haus des Unbewussten', wound: 'Tief unbewusste Wunde, schwer zu artikulieren', gift: 'Spirituelle Gabe und Kapazität für transzendente Heilung' },
  ],
  healingTitle: 'Wie Man Chirons Wunde Heilt',
  healingIntro: 'Chirons Wunde verschwindet nicht — sie wird integriert. Der Prozess geht nicht ums Überwinden, sondern um Alchemie: Schmerz in Weisheit zu verwandeln.',
  healingSteps: [
    { step: '1. Die Wunde anerkennen', text: 'Der erste Schritt ist, sie zu benennen: "hier tut es auf eine Weise weh, die keine einfache Heilung hat". Nicht minimieren, nicht dramatisieren. Einfach mitfühlend anerkennen.' },
    { step: '2. Die Rolle des "verneinenden Heilers" aufgeben', text: 'Der verwundete Chiron verbringt häufig sein Leben damit, alle außer sich selbst zu heilen. Anderen zu helfen ist real und wertvoll — kann aber keine Flucht vor dem Innenblick sein.' },
    { step: '3. Verletzlichkeit als Stärke akzeptieren', text: 'Die Tendenz ist, Chirons Wunde zu verbergen. Aber genau wenn wir sie — mit Bedacht — offenbaren, gewinnt sie Heilungskraft. Authentische Verletzlichkeit erzeugt Verbindung.' },
    { step: '4. Therapie, Mentoring oder Unterstützung suchen', text: 'Ironisch aber wahr: Menschen mit einem prominenten Chiron suchen selten Hilfe. Heilung beginnt, wenn Sie akzeptieren, dass Sie auch der "Verwundete" sein können, nicht nur der "Heiler".' },
    { step: '5. Sie in Berufung verwandeln', text: 'Die Frage ist nicht "wie werde ich diese Wunde los?" sondern "wie kann diese Wunde mich der Welt nützlich machen?" Ein gut integrierter Chiron ist einer der mächtigsten Punkte im Horoskop.' },
  ],
  cta: 'Entdecken Sie die Position von Chiron in Ihrem Geburtshoroskop',
  ctaButton: 'Mein Horoskop Berechnen →',
};
