export const horoscope = {
  daily: {
    title: 'Persönliches Tageshoroskop',
    subtitle: 'Ihre persönlichen Transite des Tages mit detaillierter Interpretation',
    selectProfile: 'Wählen Sie ein Profil aus, um Ihr personalisiertes Horoskop zu sehen',
    noProfile: 'Berechnen Sie zunächst Ihr Geburtshoroskop.',
    moonToday: 'Mond heute',
    activeTransits: 'Aktive Transite',
    intensity: { high: 'stark', medium: 'mittel', low: 'leicht' },
    categories: { love: 'Liebe', career: 'Karriere', health: 'Gesundheit' },
    today: 'Heute',
    tomorrow: 'Morgen',
  },
  love: {
    title: 'Liebeshoroskop',
    subtitle: 'Venus, Mars und die heutigen Aspekte, die Ihr Liebesleben beeinflussen',
  },
  weekly: {
    title: 'Wochenhoroskop',
    subtitle: 'Überblick über Transite und Energien für die nächsten 7 Tage',
    thisWeek: 'Diese Woche',
    prevWeek: '← Woche',
    nextWeek: 'Woche →',
    selectProfile: 'Wählen Sie ein Profil aus, um das Wochenhoroskop zu sehen',
  },
  events: {
    title: 'Himmelsereignisse',
    subtitle: 'Planetarische Eintritte, exakte Aspekte, Mondphasen und rückläufige Stationen',
    noEvents: 'Keine bedeutenden Himmelsereignisse an diesem Tag.',
    types: { ingress: 'Einzug', aspect: 'Exakter Aspekt', 'moon-phase': 'Mondphase', retrograde: 'Station' },
  },
  interpretation: {
    title: 'Grundinterpretation',
    premiumCta: 'Möchten Sie eine vollständige personalisierte Analyse?',
    premiumDesc: 'Unser Vollständiger Natalreport enthält alle Planeten, Aspekte, Würden und Prognosen in professionellem PDF.',
    premiumButton: 'Premium-Berichte ansehen',
    freeNotice: 'Kostenlose Zusammenfassungsinterpretation. Für vollständige Analyse (mehr als 20 Seiten) sehen Sie unsere Premium-Berichte.',
  },
  transitTexts: {
    noTransits: 'Ruhiger Tag ohne bedeutende Transite. Nehmen Sie sich Zeit zum Ausruhen und Nachdenken.',
    intenseDay: 'Intensiver Tag mit mehreren kraftvollen Transiten. Bleiben Sie bewusst und flexibel.',
    normalWork: 'Normaler Arbeitstag. Halten Sie den Fokus auf alltäglichen Aufgaben.',
    energyHigh: 'Hohe Energie, aber Tendenz zu Übertreibungen. Trainieren Sie, aber vermeiden Sie Überanstrengung.',
    vitalityGood: 'Vitalität ist hoch. Ausgezeichnet für körperliche Aktivitäten und Sport.',
    energyStable: 'Stabile Energie. Behalten Sie gesunde Gewohnheiten bei und respektieren Sie Ihren Rhythmus.',
  },
  moonLove: [
    'Romantischer Impuls und schnelle Leidenschaft.',
    'Sinnlichkeit und Wunsch nach Geborgenheit.',
    'Intellektuelles Flirten und verführerische Gespräche.',
    'Bedürfnis nach Zuneigung und Sicherheit in der Liebe.',
    'Dramatische Romanze und großzügiger Ausdruck.',
    'Liebe durch praktische Handlungen gezeigt.',
    'Suche nach Harmonie und Gesellschaft.',
    'Intensives und besitzergreifendes Verlangen.',
    'Anziehung durch Neuheit und Abenteuer.',
    'Reife Liebe und Verpflichtung.',
    'Freiheit in der Liebe und ungewöhnliche Verbindungen.',
    'Romantik und Idealisierung.',
  ],
};
