export const planetaryCycles = {
  title: 'Planetarische Zyklen',
  intro: 'Astrologie hat eine zeitliche Dimension, die über das Geburtshoroskop hinausgeht. Planeten bewegen sich nach der Geburt weiter und kehren periodisch zu dem Punkt zurück, wo sie sich zum Zeitpunkt Ihrer Geburt befanden — oder bilden bedeutende Winkel mit diesem Punkt. Diese Zyklen funktionieren als biologisch-symbolische Uhr der Psyche und markieren natürliche Phasen von Wachstum, Krise, Integration und Erneuerung.',
  whatAreCycles: {
    title: 'Was Sind Planetarische Zyklen?',
    text: 'Jeder Planet hat eine Umlaufzeit — die Zeit, die er benötigt, um eine vollständige Umlaufbahn um die Sonne zu vollenden. Wenn ein Transitplanet zu dem genauen Punkt zurückkehrt, den er im Moment Ihrer Geburt einnahm, nennen wir es eine "Wiederkehr". Wenn er einen 180°-Winkel zur Natalposition bildet, nennen wir es eine "Opposition".',
    note: 'Wiederkehren und Oppositionen sind keine externen Ereignisse, die "Ihnen passieren" — sie sind innere Einladungen, eine spezifische Dimension Ihres Lebens zu überprüfen, zu integrieren oder zu transformieren.',
  },
  cycles: [
    {
      planet: 'Jupiter ♃',
      icon: '✦',
      cycle: 'Wiederkehr alle ~12 Jahre',
      ages: '12, 24, 36, 48, 60, 72...',
      title: 'Der Expansionszyklus',
      description: 'Jupiter vollendet eine Umlaufbahn in etwa 12 Jahren. Seine Wiederkehren fallen mit Jahren der Gelegenheit, Expansion und offenen Türen zusammen. Die Jupiter-Wiederkehr liefert keine Gelegenheiten — sie schärft Ihre Wahrnehmung jener, die bereits vorhanden sind.',
      phases: [
        { age: '~12 Jahre', title: 'Erste Wiederkehr', text: 'Übergang von der Kindheit zur Vorpubertät. Erweiterung des Weltbilds, erste philosophische Fragen.' },
        { age: '~24 Jahre', title: 'Zweite Wiederkehr', text: 'Expansion ins unabhängige Erwachsenenleben. Jahr beruflicher oder bildungsbezogener Möglichkeiten.' },
        { age: '~36 Jahre', title: 'Dritte Wiederkehr', text: 'Konsolidierung und Erweiterung der erwachsenen Identität. Öffnung für neue Lebensprojekte.' },
        { age: '~48 Jahre', title: 'Vierte Wiederkehr', text: 'Erneuerung von Zweck und Sinn. Fällt oft mit Karriere- oder Lebensphilosophieveränderungen zusammen.' },
      ],
    },
    {
      planet: 'Saturn ♄',
      icon: '⧖',
      cycle: 'Wiederkehr bei ~29-30 Jahren und ~58-60 Jahren',
      ages: '~14-15 (Quadrat), ~29-30 (Wiederkehr), ~36-37 (Opposition), ~58-60 (Wiederkehr)',
      title: 'Der Große Lehrer — Saturn-Wiederkehr',
      description: 'Saturn ist der am meisten gefürchtete und wichtigste Planet der Lebenszyklen. Seine erste Wiederkehr um das 29.-30. Lebensjahr ist ein universeller Übergangsritus — der Moment, wenn die Jugend endet und das echte Erwachsenenleben beginnt. Sie werden aufgefordert, volle Verantwortung dafür zu übernehmen, wer Sie sind.',
      phases: [
        { age: '~14-15 Jahre', title: 'Erstes Quadrat', text: 'Erste Konfrontation mit Autorität und Grenzen. Jugendliche Identität in Bildung.' },
        { age: '~21-22 Jahre', title: 'Wachsendes erstes Quadrat', text: 'Spannung zwischen gewünschter Freiheit und wachsenden Verantwortlichkeiten.' },
        { age: '~29-30 Jahre', title: 'Saturn-Wiederkehr', text: 'Der große Wendepunkt. Saturn "fordert die Schuld ein" — Beziehungen, Karrieren und ohne Authentizität aufgebaute Identitäten neigen sich aufzulösen. Was echt ist, wird stärker. Häufige Existenzkrise, aber notwendig.' },
        { age: '~36-37 Jahre', title: 'Saturn-Opposition', text: 'Halbzyklus-Überprüfung. Bewertung dessen, was seit dem 29. Lebensjahr aufgebaut wurde. Moment der Kurskorrektur.' },
        { age: '~44 Jahre', title: 'Zweites abnehmendes Quadrat', text: 'Vorbereitung auf die zweite Wiederkehr. Konfrontation mit dem Aufgeschobenen oder Verneinen.' },
        { age: '~58-60 Jahre', title: 'Zweite Saturn-Wiederkehr', text: 'Übergang zur vollen Reife. Tiefe Überprüfung von Vermächtnis und Lebenszweck.' },
      ],
    },
    {
      planet: 'Uranus ♅',
      icon: '⚡',
      cycle: 'Opposition bei ~38-44 Jahren',
      ages: '~38-44 (Opposition), ~84 (Wiederkehr)',
      title: 'Die Midlife-Crisis — Uranus-Opposition',
      description: 'Uranus braucht 84 Jahre für seinen Zyklus. Die Opposition — wenn Uranus in Transit 180° mit dem natalen Uranus bildet — tritt zwischen 38 und 44 Jahren auf. Das ist die berühmte "Midlife-Crisis". Uranus, der Planet der Freiheit und des Umbruchs, hinterfragt radikal etablierte Muster.',
      phases: [
        { age: '~38-44 Jahre', title: 'Uranus-Opposition', text: 'Plötzliche Dringlichkeit nach Freiheit. Infragestellung von allem, was aufgebaut wurde. "Für wen lebe ich dieses Leben?" Kann sich als abrupte Karriere-, Beziehungs- oder Lebensstilveränderungen manifestieren. Das ist keine Krise zu vermeiden — es ist ein Ruf zur Authentizität.' },
        { age: '~21 Jahre', title: 'Uranus-Quadrat', text: 'Erster Impuls, sich von elterlichen und gesellschaftlichen Mustern zu befreien. "Ich will nicht das Leben, das man mir beibrachte zu wollen."' },
        { age: '~63 Jahre', title: 'Zweites Quadrat', text: 'Konsolidierung der authentischen Identität nach der Midlife-Crisis. Wer bin ich wirklich, frei von Erwartungen?' },
      ],
    },
    {
      planet: 'Chiron ⚷',
      icon: '⚷',
      cycle: 'Wiederkehr bei ~49-51 Jahren',
      ages: '~49-51 (Wiederkehr)',
      title: 'Die Chiron-Wiederkehr',
      description: 'Chiron, der Verwundete Heiler, kehrt um das 49. bis 51. Lebensjahr zum Natalort zurück — fällt oft mit Menopause/Andropause zusammen und was Jung "Individuation" nannte. Es ist eine Einladung zur abschließenden Integration der urwüchsigen Wunde.',
      phases: [
        { age: '~49-51 Jahre', title: 'Chiron-Wiederkehr', text: 'Die zentrale Frage: "Wie viel von diesem Schmerz, den ich trage, ist noch nötig?" Es ist der Moment zu akzeptieren, dass die Wunde nicht mehr versteckt werden muss. Verletzlichkeit wird Weisheit. Viele Menschen beginnen oder vertiefen therapeutische oder spirituelle Arbeit in dieser Zeit.' },
        { age: '~22-25 Jahre', title: 'Chiron-Quadrat', text: 'Erste Krise mit der Wunde. Kann eine Zeit der Isolation, Scham oder Schwierigkeit der Zugehörigkeit sein.' },
        { age: '~37-40 Jahre', title: 'Chiron-Opposition', text: 'Direkte Konfrontation mit der Wunde. Fällt oft mit der Midlife-Crisis zusammen und erfordert, dem Vermiedenen zu begegnen.' },
      ],
    },
    {
      planet: 'Neptun ♆',
      icon: '🌊',
      cycle: 'Quadrat bei ~40-42 Jahren und ~82-84 Jahren',
      ages: '~40-42 (erstes Quadrat), ~82-84 (Wiederkehr)',
      title: 'Auflösung und Transzendenz',
      description: 'Neptun braucht 165 Jahre für seinen Zyklus. Neptuns Quadrat (bei ~40-42 Jahren) fällt oft mit der Midlife-Crisis zusammen und fügt eine Dimension der Illusionsauflösung hinzu — besonders Illusionen darüber, wer wir sind und was wir wollen.',
      phases: [
        { age: '~40-42 Jahre', title: 'Neptun-Quadrat', text: 'Auflösung der in der Jugend aufgebauten Illusionen. "Das Leben, das ich mir vorstellte, ist nicht genau dieses." Periode kreativer Desorientierung — das alte Selbst löst sich auf, bevor sich das neue bildet.' },
      ],
    },
    {
      planet: 'Pluto ♇',
      icon: '🔥',
      cycle: 'Quadrat bei ~36-44 Jahren',
      ages: '~36-44 (erstes Quadrat)',
      title: 'Tod und Wiedergeburt',
      description: 'Pluto braucht 248 Jahre, kehrt also nie zurück. Aber das Plutonische Quadrat (bei ~36-44 Jahren) ist einer der intensivsten Übergänge — fällt mit der Midlife-Crisis zusammen und verlangt den symbolischen Tod von Ego-Teilen, die zu Hindernissen geworden sind.',
      phases: [
        { age: '~36-44 Jahre', title: 'Pluto-Quadrat', text: 'Psychologischer Tod-Wiedergeburt-Prozess. Macht, Kontrolle, Schatten und Verletzlichkeit kommen an die Oberfläche. Was man mit Kraft festgehalten hat, beginnt sich aufzulösen. Tiefgreifend transformierend und möglicherweise erschreckend — und notwendig.' },
      ],
    },
  ],
  integration: {
    title: 'Wie Man Bewusst mit Zyklen Arbeitet',
    text: 'Die eigenen Zyklen zu kennen dient nicht der Vorhersage der Zukunft — es geht darum, den inneren Boden vorzubereiten. Wenn man weiß, dass man in eine Saturnianische Zeit eintritt, kann man Raum für Überprüfung schaffen, anstatt mitgerissen zu werden. Zyklen sind nicht deterministisch: Sie offenbaren die Qualität der Zeit, nicht ihren Inhalt.',
    tips: [
      'Identifizieren Sie, in welchem Zyklus Sie sich gerade befinden',
      'Fragen Sie: Welche Art von Wachstum lädt dieser Zyklus ein?',
      'Widerstehen Sie dem Impuls, die Krisen der größeren Zyklen zu "fliehen"',
      'Nutzen Sie Therapie, Meditation oder Tagebuchschreiben als Integrationswerkzeuge',
      'Schwierige Zyklen produzieren die größten Bewusstseinssprünge, wenn sie bewusst durchlebt werden',
    ],
  },
  cta: 'Entdecken Sie, in welchen Zyklen Sie sich gerade befinden',
  ctaButton: 'Meine Transite ansehen →',
};
