export const signs = {
  title: 'Die 12 Tierkreiszeichen',
  intro: 'Zeichen sind 12 energetische Archetypen. Jeder Planet in Ihrem Horoskop befindet sich in einem Zeichen und färbt seinen Ausdruck mit spezifischen Qualitäten.',
  list: [
    { symbol: '♈', name: 'Widder', dates: '21. Mär – 19. Apr', element: 'Feuer', mode: 'Kardinal', ruler: '♂ Mars', color: '#cc0000', description: 'Erstes Zeichen — der Funken des Beginns. Mut, Impuls, Wettbewerb und Individualität. Widder durchbricht Trägheit und öffnet neue Wege. Schatten: Impulsivität, Egoismus, Aggression.' },
    { symbol: '♉', name: 'Stier', dates: '20. Apr – 20. Mai', element: 'Erde', mode: 'Fix', ruler: '♀ Venus', color: '#006600', description: 'Konsolidierung dessen, was Widder begann. Stabilität, Sinnesgenuss, Loyalität und Beharrlichkeit. Stier baut solide Fundamente mit Geduld. Schatten: Besitzdenken, Sturheit, Materialismus.' },
    { symbol: '♊', name: 'Zwillinge', dates: '21. Mai – 20. Jun', element: 'Luft', mode: 'Veränderlich', ruler: '☿ Merkur', color: '#0000cc', description: 'Die Brücke zwischen den Welten. Unersättliche Neugier, Kommunikation, Vielseitigkeit und Leichtigkeit. Zwillinge verbinden Informationen und Menschen. Schatten: Oberflächlichkeit, Unbeständigkeit, Dualität.' },
    { symbol: '♋', name: 'Krebs', dates: '21. Jun – 22. Jul', element: 'Wasser', mode: 'Kardinal', ruler: '☽ Mond', color: '#cc6600', description: 'Das emotionale Nest. Schutz, Erinnerung, Zugehörigkeit und Fürsorge. Krebs schlägt Wurzeln und sorgt tief. Schatten: Abhängigkeit, emotionale Manipulation, Festhalten an der Vergangenheit.' },
    { symbol: '♌', name: 'Löwe', dates: '23. Jul – 22. Aug', element: 'Feuer', mode: 'Fix', ruler: '☉ Sonne', color: '#cc0000', description: 'Die Bühne des Lebens. Kreativer Ausdruck, persönlicher Glanz, Großzügigkeit und Führung. Löwe strahlt aus und inspiriert. Schatten: Arroganz, Applausbedürfnis, Drama.' },
    { symbol: '♍', name: 'Jungfrau', dates: '23. Aug – 22. Sep', element: 'Erde', mode: 'Veränderlich', ruler: '☿ Merkur', color: '#006600', description: 'Verfeinerung der Erfahrung. Analyse, Kompetenz, Dienst und Verbesserung. Jungfrau trennt das Wesentliche vom Überflüssigen. Schatten: übermäßige Kritik, Perfektionismus, Angst.' },
    { symbol: '♎', name: 'Waage', dates: '23. Sep – 22. Okt', element: 'Luft', mode: 'Kardinal', ruler: '♀ Venus', color: '#0000cc', description: 'Die Begegnung mit dem anderen. Balance, Gerechtigkeit, Diplomatie und Partnerschaft. Waage sucht Harmonie in Beziehungen und Ästhetik. Schatten: Unentschlossenheit, Abhängigkeit von anderen.' },
    { symbol: '♏', name: 'Skorpion', dates: '23. Okt – 21. Nov', element: 'Wasser', mode: 'Fix', ruler: '♇ Pluto', color: '#cc6600', description: 'Der Abstieg in die Tiefen. Intensität, Transformation, Wahrheit und Macht. Skorpion scheut das Verborgene nicht. Schatten: Obsession, Eifersucht, Manipulation, Rache.' },
    { symbol: '♐', name: 'Schütze', dates: '22. Nov – 21. Dez', element: 'Feuer', mode: 'Veränderlich', ruler: '♃ Jupiter', color: '#cc0000', description: 'Der Pfeil des Sinns. Expansion, Philosophie, Abenteuer und Glaube. Schütze sucht Bedeutung jenseits des Horizonts. Schatten: Übertreibung, Fanatismus, Verantwortungslosigkeit.' },
    { symbol: '♑', name: 'Steinbock', dates: '22. Dez – 19. Jan', element: 'Erde', mode: 'Kardinal', ruler: '♄ Saturn', color: '#006600', description: 'Der Berg zum Erklimmen. Ehrgeiz, Disziplin, Reife und Vermächtnis. Steinbock baut mit Zeit und Beharrlichkeit. Schatten: Kälte, Starrheit, Pessimismus.' },
    { symbol: '♒', name: 'Wassermann', dates: '20. Jan – 18. Feb', element: 'Luft', mode: 'Fix', ruler: '♅ Uranus', color: '#0000cc', description: 'Die stille Revolution. Originalität, Unabhängigkeit, Zukunftsvision und Humanitarismus. Wassermann hinterfragt den Status quo. Schatten: emotionale Distanzierung, leere Rebellion.' },
    { symbol: '♓', name: 'Fische', dates: '19. Feb – 20. Mär', element: 'Wasser', mode: 'Veränderlich', ruler: '♆ Neptun', color: '#cc6600', description: 'Der letzte Ozean. Universelles Mitgefühl, Spiritualität, Kunst und Ego-Auflösung. Fische spüren alles und verbinden sich mit dem Ganzen. Schatten: Eskapismus, Opferrolle, Verwirrung.' },
  ],
};
