export const chiron = {
  title: 'Quíron — O Curador Ferido',
  intro: 'Quíron é um corpo celeste descoberto em 1977, classificado como planetoide ou centauro, orbitando entre Saturno e Urano. Na astrologia humanística, representa a ferida primordial que carregamos — a dor que não conseguimos curar em nós mesmos, mas que paradoxalmente nos torna capazes de ajudar outros. É o arquétipo do terapeuta, do mentor e do sábio que aprendeu através do sofrimento.',
  mythology: {
    title: 'A Mitologia de Quíron',
    text: 'Quíron era um centauro diferente dos outros: sábio, civilizado, mestre da medicina, música, profecia e artes marciais. Foi tutor de heróis como Aquiles, Asclépio e Jasão. Filho de Cronos e Fílira, foi abandonado por sua mãe ao nascer por ser meio homem, meio cavalo — sua primeira ferida: a rejeição pela própria origem.',
    wound: 'Sua ironia trágica: sendo o maior curador da Grécia Antiga, recebeu uma flecha envenenada de Hércules — um acidente, não uma maldade — e, sendo imortal, não podia morrer, mas tampouco podia se curar. Viveu em dor eterna, até abrir mão de sua imortalidade e ser transformado em constelação.',
    meaning: 'A ferida de Quíron não é resolvida. É integrada. Essa é a diferença fundamental entre Saturno (que supera através de disciplina) e Quíron (que aprende a viver com a ferida até que ela vire sabedoria).',
  },
  signsTitle: 'Quíron nos Signos',
  signsIntro: 'O signo de Quíron revela a natureza da ferida — o "onde dói" no nível da identidade. Como Quíron fica entre 4 e 9 anos em cada signo, é uma ferida geracional compartilhada por milhões.',
  signs: [
    { sign: 'Áries ♈', years: '(1968–77 / 2018–27)', wound: 'Ferida na existência e iniciativa', healing: 'Curar pelo direito de agir, liderar e existir plenamente' },
    { sign: 'Touro ♉', years: '(1977–83)', wound: 'Ferida na autoestima e no corpo', healing: 'Curar pela relação saudável com o valor próprio e os recursos' },
    { sign: 'Gêmeos ♊', years: '(1983–88)', wound: 'Ferida na comunicação e inteligência', healing: 'Curar pela capacidade de ser ouvido e compreendido' },
    { sign: 'Câncer ♋', years: '(1988–91)', wound: 'Ferida no pertencimento e na família', healing: 'Curar criando um lar interno que independe do externo' },
    { sign: 'Leão ♌', years: '(1991–93)', wound: 'Ferida na autoexpressão e reconhecimento', healing: 'Curar pelo direito de brilhar sem precisar de aprovação' },
    { sign: 'Virgem ♍', years: '(1993–96)', wound: 'Ferida na perfeição e adequação', healing: 'Curar pela aceitação da imperfeição como parte do humano' },
    { sign: 'Libra ♎', years: '(1996–99)', wound: 'Ferida nos relacionamentos e equilíbrio', healing: 'Curar aprendendo a se relacionar sem se perder' },
    { sign: 'Escorpião ♏', years: '(1999–01)', wound: 'Ferida no poder e na intimidade', healing: 'Curar pelo enfrentamento das sombras sem destruição' },
    { sign: 'Sagitário ♐', years: '(2001–05)', wound: 'Ferida na fé, sentido e pertencimento filosófico', healing: 'Curar encontrando uma verdade própria, não herdada' },
    { sign: 'Capricórnio ♑', years: '(2005–10)', wound: 'Ferida na autoridade e sucesso', healing: 'Curar redefinindo conquista em termos próprios' },
    { sign: 'Aquário ♒', years: '(2010–11)', wound: 'Ferida na originalidade e pertença ao grupo', healing: 'Curar pelo direito de ser diferente e ainda amado' },
    { sign: 'Peixes ♓', years: '(2011–18)', wound: 'Ferida na espiritualidade e limites do ego', healing: 'Curar integrando o transcendente sem se dissolver nele' },
  ],
  housesTitle: 'Quíron nas Casas',
  housesIntro: 'A casa de Quíron indica a área da vida onde a ferida se manifesta — onde você sente que é "o eterno ferido que cura os outros". É também onde sua maior sabedoria emerge depois da integração.',
  houses: [
    { num: '1ª', name: 'Casa da Identidade', wound: 'Ferida na própria existência e presença', gift: 'Poder ensinar outros a existirem plenamente' },
    { num: '2ª', name: 'Casa dos Recursos', wound: 'Ferida no valor próprio e sustento material', gift: 'Dom para ajudar outros a descobrirem seus talentos' },
    { num: '3ª', name: 'Casa da Comunicação', wound: 'Ferida na expressão verbal e aprendizado', gift: 'Dom como professor, escritor ou comunicador' },
    { num: '4ª', name: 'Casa do Lar', wound: 'Ferida nas raízes, família e segurança emocional', gift: 'Capacidade de criar lar e acolhimento para outros' },
    { num: '5ª', name: 'Casa da Criação', wound: 'Ferida na autoexpressão criativa e alegria', gift: 'Dom para inspirar a criatividade nos outros' },
    { num: '6ª', name: 'Casa da Saúde', wound: 'Ferida no corpo, saúde e rotinas', gift: 'Dom para curas físicas e holísticas' },
    { num: '7ª', name: 'Casa dos Relacionamentos', wound: 'Ferida na parceria íntima e comprometimento', gift: 'Dom para mediar e aconselhar relacionamentos' },
    { num: '8ª', name: 'Casa das Transformações', wound: 'Ferida nas perdas, sexualidade e poder compartilhado', gift: 'Dom para guiar outros em processos de morte/renascimento' },
    { num: '9ª', name: 'Casa da Filosofia', wound: 'Ferida na crença, fé e busca de sentido', gift: 'Dom como mestre espiritual e filósofo' },
    { num: '10ª', name: 'Casa da Carreira', wound: 'Ferida no reconhecimento público e autoridade', gift: 'Dom para liderar com humildade genuína' },
    { num: '11ª', name: 'Casa dos Grupos', wound: 'Ferida no pertencimento e amizades', gift: 'Dom para curar comunidades e grupos' },
    { num: '12ª', name: 'Casa do Inconsciente', wound: 'Ferida profundamente inconsciente, difícil de articular', gift: 'Dom espiritual e capacidade de cura transcendente' },
  ],
  healingTitle: 'Como Curar a Ferida de Quíron',
  healingIntro: 'A ferida de Quíron não desaparece — ela é integrada. O processo não é de superação, mas de alquimia: transformar a dor em sabedoria.',
  healingSteps: [
    { step: '1. Reconheça a ferida', text: 'O primeiro passo é nomear: "aqui é onde dói de um jeito que não tem cura simples". Não minimizar, não dramatizar. Apenas reconhecer com compaixão.' },
    { step: '2. Abandone o papel de "curador negador"', text: 'Quíron ferido frequentemente passa a vida curando todos menos a si mesmo. Ajudar os outros é real e valioso — mas não pode ser uma fuga de se olhar.' },
    { step: '3. Aceite a vulnerabilidade como força', text: 'A tendência é esconder a ferida de Quíron. Mas é exatamente quando a revelamos — com discernimento — que ela ganha poder de cura. Vulnerabilidade autêntica gera conexão.' },
    { step: '4. Busque terapia, mentoria ou apoio', text: 'Irônico mas verdadeiro: quem tem Quíron proeminente raramente busca ajuda. A cura começa quando aceita que também pode ser o "ferido" e não apenas o "curador".' },
    { step: '5. Transforme em vocação', text: 'A pergunta não é "como me livro desta ferida?" mas "como esta ferida pode me tornar útil para o mundo?" Quíron bem integrado é um dos pontos mais poderosos do mapa.' },
  ],
  cta: 'Descubra a posição de Quíron no seu mapa natal',
  ctaButton: 'Calcular Meu Mapa →',
};
