export const horoscope = {
  daily: {
    title: 'Horóscopo Diário Pessoal',
    subtitle: 'Seus trânsitos pessoais do dia com interpretação detalhada',
    selectProfile: 'Selecione um perfil para ver seu horóscopo personalizado',
    noProfile: 'Calcule primeiro seu mapa natal.',
    moonToday: 'Lua hoje',
    activeTransits: 'Trânsitos Ativos',
    intensity: { high: 'forte', medium: 'médio', low: 'leve' },
    categories: { love: 'Amor', career: 'Carreira', health: 'Saúde' },
    today: 'Hoje',
    tomorrow: 'Amanhã',
  },
  love: {
    title: 'Horóscopo do Amor',
    subtitle: 'Vênus, Marte e os aspectos do dia que influenciam sua vida afetiva',
  },
  weekly: {
    title: 'Horóscopo Semanal',
    subtitle: 'Visão geral dos trânsitos e energias dos próximos 7 dias',
    thisWeek: 'Esta semana',
    prevWeek: '← Semana',
    nextWeek: 'Semana →',
    selectProfile: 'Selecione um perfil para ver o horóscopo semanal',
  },
  events: {
    title: 'Eventos Celestes',
    subtitle: 'Ingressos planetários, aspectos exatos, fases da Lua e estações de retrógrado',
    noEvents: 'Nenhum evento celeste significativo neste dia.',
    types: { ingress: 'Ingresso', aspect: 'Aspecto exato', 'moon-phase': 'Fase lunar', retrograde: 'Estação' },
  },
  interpretation: {
    title: 'Interpretação Básica',
    premiumCta: 'Quer uma análise completa e personalizada?',
    premiumDesc: 'Nosso Relatório Natal Completo inclui todos os planetas, aspectos, dignidades e previsões em PDF profissional.',
    premiumButton: 'Ver Relatórios Premium',
    freeNotice: 'Interpretação gratuita resumida. Para análise completa (20+ páginas), veja nossos relatórios premium.',
  },
  // Transit interpretation texts for daily horoscope
  transitTexts: {
    noTransits: 'Dia tranquilo sem trânsitos significativos. Aproveite para descansar e refletir.',
    intenseDay: 'Dia intenso com múltiplos trânsitos poderosos. Mantenha consciência e flexibilidade.',
    normalWork: 'Dia normal no trabalho. Mantenha o foco nas tarefas cotidianas.',
    energyHigh: 'Energia alta mas tendência a excesso. Exercite-se mas evite esforço exagerado.',
    vitalityGood: 'Vitalidade em alta. Excelente para atividades físicas e desporto.',
    energyStable: 'Energia estável. Mantenha hábitos saudáveis e respeite seu ritmo.',
  },
  moonLove: [
    'Impulso romântico e paixão rápida.',
    'Sensualidade e desejo de conforto a dois.',
    'Flerte intelectual e conversas sedutoras.',
    'Necessidade de afeto e segurança no amor.',
    'Romance dramático e expressão generosa.',
    'Amor demonstrado em atos práticos.',
    'Busca de harmonia e companhia.',
    'Desejo intenso e possessivo.',
    'Atração por novidade e aventura.',
    'Amor maduro e compromisso.',
    'Liberdade no amor e conexões inusitadas.',
    'Romantismo e idealização.',
  ],
};
