export const planets = {
  title: 'Os Planetas na Astrologia',
  intro: 'Na astrologia, cada planeta representa uma função psicológica ou área da experiência humana. Os planetas pessoais (Sol a Marte) definem a personalidade individual; os sociais (Júpiter e Saturno) mostram como interagimos com a sociedade; e os transpessoais (Urano, Netuno, Plutão) representam forças coletivas que transformam gerações.',
  cta: 'Quer saber onde cada planeta está no SEU mapa?',
  ctaButton: 'Calcular Meu Mapa Natal →',
  list: [
    { symbol: '☉', name: 'Sol', keywords: 'Identidade, ego, vitalidade, propósito', ruler: 'Leão', cycle: '1 ano', description: 'O Sol representa sua essência — quem você é no centro. É a vontade consciente, o ego saudável, a vitalidade e o propósito de vida. No mapa, mostra como você busca brilhar, ser reconhecido e expressar sua individualidade. O signo solar indica sua identidade básica; a casa mostra onde você precisa se destacar.' },
    { symbol: '☽', name: 'Lua', keywords: 'Emoções, instinto, mãe, conforto', ruler: 'Câncer', cycle: '28 dias', description: 'A Lua é seu mundo emocional inconsciente — reações automáticas, necessidades de segurança, memória e hábitos. Representa o que você precisa para se sentir nutrido e protegido. O signo lunar mostra como você processa emoções; a casa revela onde busca conforto e pertencimento.' },
    { symbol: '☿', name: 'Mercúrio', keywords: 'Mente, comunicação, raciocínio, aprendizado', ruler: 'Gêmeos / Virgem', cycle: '88 dias', description: 'Mercúrio governa como sua mente funciona — estilo de pensamento, comunicação, aprendizado e processamento de informações. O signo indica seu estilo mental; a casa mostra a área de vida onde a comunicação é central.' },
    { symbol: '♀', name: 'Vênus', keywords: 'Amor, beleza, prazer, valores, atração', ruler: 'Touro / Libra', cycle: '225 dias', description: 'Vênus representa o que você valoriza e deseja atrair — como ama, o que considera belo, como busca prazer e harmonia. É o princípio do magnetismo e da receptividade.' },
    { symbol: '♂', name: 'Marte', keywords: 'Ação, energia, coragem, desejo, raiva', ruler: 'Áries', cycle: '687 dias', description: 'Marte é sua energia vital em ação — como luta, toma iniciativa, expressa raiva e canaliza desejo. É o princípio da assertividade e da conquista.' },
    { symbol: '♃', name: 'Júpiter', keywords: 'Expansão, fé, sabedoria, abundância, sorte', ruler: 'Sagitário', cycle: '12 anos', description: 'Júpiter é o Grande Benéfico — onde encontra sentido, crescimento e oportunidade. Governa a filosofia de vida, a fé, o ensino superior e as viagens.' },
    { symbol: '♄', name: 'Saturno', keywords: 'Disciplina, limite, responsabilidade, maturidade', ruler: 'Capricórnio', cycle: '29 anos', description: 'Saturno é o Mestre Severo — representa seus maiores medos, deveres e onde precisa amadurecer com paciência. Inicialmente vivido como limitação, torna-se a base de conquistas sólidas.' },
    { symbol: '♅', name: 'Urano', keywords: 'Liberdade, originalidade, ruptura, inovação', ruler: 'Aquário', cycle: '84 anos', description: 'Urano é o Despertar Súbito — onde precisa de liberdade radical e rompe com padrões. Governa a originalidade, a genialidade e as revoluções.' },
    { symbol: '♆', name: 'Netuno', keywords: 'Espiritualidade, intuição, sonho, ilusão', ruler: 'Peixes', cycle: '165 anos', description: 'Netuno é o Véu entre mundos — porta para transcendência, arte sublime e compaixão universal, mas também para ilusão, confusão e fuga.' },
    { symbol: '♇', name: 'Plutão', keywords: 'Transformação, poder, regeneração, morte/renascimento', ruler: 'Escorpião', cycle: '248 anos', description: 'Plutão é o Fênix — o poder de transformação absoluta. Morte simbólica e renascimento, intensidade, regeneração.' },
  ],
};
