export const planetaryCycles = {
  title: 'Ciclos Planetários',
  intro: 'A astrologia tem uma dimensão temporal que vai além do mapa natal. Os planetas continuam se movendo após o nascimento e, periodicamente, retornam ao mesmo ponto do céu onde estavam quando você nasceu — ou formam ângulos significativos com esse ponto. Esses ciclos funcionam como relógio biológico-simbólico da psique, marcando fases naturais de crescimento, crise, integração e renovação.',
  whatAreCycles: {
    title: 'O que são Ciclos Planetários?',
    text: 'Cada planeta tem um período orbital — o tempo que leva para dar uma volta completa ao redor do Sol. Quando um planeta em trânsito retorna ao ponto exato que ocupava no momento do seu nascimento, chamamos de "retorno". Quando forma um ângulo de 180° com a posição natal, chamamos de "oposição".',
    note: 'Retornos e oposições não são eventos externos que "acontecem com você" — são convites internos para revisar, integrar ou transformar uma dimensão específica da sua vida.',
  },
  cycles: [
    {
      planet: 'Júpiter ♃',
      icon: '✦',
      cycle: 'Retorno a cada ~12 anos',
      ages: '12, 24, 36, 48, 60, 72...',
      title: 'O Ciclo de Expansão',
      description: 'Júpiter completa uma volta em aproximadamente 12 anos. Seus retornos coincidem com anos de oportunidade, expansão e abertura de portas. O retorno de Júpiter não entrega oportunidades — ele afina sua percepção para as que já estão presentes.',
      phases: [
        { age: '~12 anos', title: 'Primeiro retorno', text: 'Transição da infância para a pré-adolescência. Expansão da visão de mundo, primeiros questionamentos filosóficos.' },
        { age: '~24 anos', title: 'Segundo retorno', text: 'Expansão para a vida adulta independente. Ano de oportunidades profissionais ou educacionais.' },
        { age: '~36 anos', title: 'Terceiro retorno', text: 'Consolidação e expansão da identidade adulta. Abertura para novos projetos de vida.' },
        { age: '~48 anos', title: 'Quarto retorno', text: 'Renovação de propósito e significado. Frequentemente coincide com mudanças de carreira ou filosofia de vida.' },
      ],
    },
    {
      planet: 'Saturno ♄',
      icon: '⧖',
      cycle: 'Retorno aos ~29-30 anos e ~58-60 anos',
      ages: '~14-15 (quadratura), ~29-30 (retorno), ~36-37 (oposição), ~58-60 (retorno)',
      title: 'O Grande Mestre — Retorno de Saturno',
      description: 'Saturno é o planeta mais temido e mais importante dos ciclos de vida. Seu primeiro retorno, por volta dos 29-30 anos, é um rito de passagem universal — o momento em que a juventude termina e a vida adulta real começa. Você é convocado a assumir responsabilidade plena por quem você é.',
      phases: [
        { age: '~14-15 anos', title: 'Primeira quadratura', text: 'Primeiro confronto com autoridade e limites. Identidade adolescente em formação.' },
        { age: '~21-22 anos', title: 'Primeira quadratura waxing', text: 'Tensão entre liberdade desejada e responsabilidades crescentes.' },
        { age: '~29-30 anos', title: 'Retorno de Saturno', text: 'A grande virada. Saturno "cobra a conta" — relacionamentos, carreiras e identidades construídas sem autenticidade tendem a se desfazer. O que é genuíno se fortalece. Crise existencial frequente, mas necessária.' },
        { age: '~36-37 anos', title: 'Oposição de Saturno', text: 'Revisão de meio-ciclo. Avaliação do que foi construído desde os 29. Momento de correção de curso.' },
        { age: '~44 anos', title: 'Segunda quadratura waning', text: 'Preparação para o segundo retorno. Confronto com o que foi adiado ou negado.' },
        { age: '~58-60 anos', title: 'Segundo retorno', text: 'Transição para a maturidade plena. Revisão profunda do legado e propósito de vida.' },
      ],
    },
    {
      planet: 'Urano ♅',
      icon: '⚡',
      cycle: 'Oposição aos ~38-44 anos',
      ages: '~38-44 (oposição), ~84 (retorno)',
      title: 'A Crise dos 40 — Oposição de Urano',
      description: 'Urano leva 84 anos para completar seu ciclo. A oposição — quando Urano em trânsito forma 180° com o Urano natal — ocorre entre os 38 e 44 anos. Esta é a famosa "crise da meia-vida". Urano, o planeta da liberdade e ruptura, questiona radicalmente os padrões estabelecidos.',
      phases: [
        { age: '~38-44 anos', title: 'Oposição de Urano', text: 'Urgência repentina de liberdade. Questionamento de tudo que foi construído. "Para quem estou vivendo esta vida?" Pode manifestar como mudanças abruptas de carreira, relacionamentos ou estilo de vida. Não é uma crise a ser evitada — é um chamado para autenticidade.' },
        { age: '~21 anos', title: 'Quadratura de Urano', text: 'Primeiro impulso de romper com padrões dos pais e da sociedade. "Não quero a vida que me ensinaram a querer."' },
        { age: '~63 anos', title: 'Segunda quadratura', text: 'Consolidação da identidade autêntica após a crise dos 40. Quem sou de verdade, livre das expectativas?' },
      ],
    },
    {
      planet: 'Quíron ⚷',
      icon: '⚷',
      cycle: 'Retorno aos ~49-51 anos',
      ages: '~49-51 (retorno)',
      title: 'O Retorno de Quíron',
      description: 'Quíron, o Curador Ferido, retorna ao ponto natal por volta dos 49 a 51 anos — coincidindo frequentemente com o período da menopausa/andropausa e o que Jung chamou de "individuação". É um convite para a integração final da ferida primordial.',
      phases: [
        { age: '~49-51 anos', title: 'Retorno de Quíron', text: 'A pergunta central: "Quanto desta dor que carrego ainda é necessária?" É o momento de aceitar que a ferida não precisa mais ser escondida. A vulnerabilidade se torna sabedoria. Muitas pessoas iniciam ou aprofundam trabalhos terapêuticos ou espirituais neste período.' },
        { age: '~22-25 anos', title: 'Quadratura de Quíron', text: 'Primeira crise com a ferida. Pode ser período de isolamento, vergonha ou dificuldade em pertencer.' },
        { age: '~37-40 anos', title: 'Oposição de Quíron', text: 'Confronto direto com a ferida. Frequentemente coincide com a crise dos 40 e exige encarar o que foi evitado.' },
      ],
    },
    {
      planet: 'Netuno ♆',
      icon: '🌊',
      cycle: 'Quadratura aos ~40-42 anos e ~82-84 anos',
      ages: '~40-42 (primeira quadratura), ~82-84 (retorno)',
      title: 'Dissolução e Transcendência',
      description: 'Netuno leva 165 anos para completar seu ciclo. A quadratura de Netuno (aos ~40-42 anos) coincide frequentemente com a crise de meia-vida e adiciona uma dimensão de dissolução de ilusões — especialmente ilusões sobre quem somos e o que queremos.',
      phases: [
        { age: '~40-42 anos', title: 'Quadratura de Netuno', text: 'Dissolução das ilusões construídas na juventude. "A vida que imaginei não é exatamente isso." Período de desorientação criativa — o velho eu se dissolve antes do novo se formar.' },
      ],
    },
    {
      planet: 'Plutão ♇',
      icon: '🔥',
      cycle: 'Quadratura aos ~36-44 anos',
      ages: '~36-44 (primeira quadratura)',
      title: 'Morte e Renascimento',
      description: 'Plutão leva 248 anos, então nunca retorna. Mas a quadratura plutoniana (aos ~36-44 anos) é uma das transições mais intensas — coincide com a crise de meia-vida e exige morte simbólica de partes do ego que se tornaram obstáculos.',
      phases: [
        { age: '~36-44 anos', title: 'Quadratura de Plutão', text: 'Processo de morte-renascimento psicológico. Poder, controle, sombra e vulnerabilidade vêm à tona. O que você segurou com força começa a se desfazer. É profundamente transformador e pode ser assustador — e necessário.' },
      ],
    },
  ],
  integration: {
    title: 'Como Usar os Ciclos Conscientemente',
    text: 'Conhecer seus ciclos não é prever o futuro — é preparar o terreno interno. Quando você sabe que está entrando em um período Saturnino, por exemplo, pode criar espaço para a revisão em vez de ser varrido por ela. Os ciclos não são deterministas: eles revelam a qualidade do tempo, não o conteúdo.',
    tips: [
      'Identifique em qual ciclo você está atualmente',
      'Pergunte: que tipo de crescimento este ciclo convida?',
      'Resista ao impulso de "escapar" das crises dos ciclos maiores',
      'Use terapia, meditação ou diário como ferramentas de integração',
      'Ciclos difíceis produzem os maiores saltos de consciência quando atravessados conscientemente',
    ],
  },
  cta: 'Descubra em que ciclos você está agora',
  ctaButton: 'Ver Meus Trânsitos →',
};
