export const signs = {
  title: 'Os 12 Signos do Zodíaco',
  intro: 'Os signos são 12 arquétipos de energia. Cada planeta no seu mapa está em um signo, colorindo sua expressão com qualidades específicas.',
  list: [
    { symbol: '♈', name: 'Áries', dates: '21 Mar – 19 Abr', element: 'Fogo', mode: 'Cardinal', ruler: '♂ Marte', color: '#cc0000', description: 'Primeiro signo — a faísca do início. Coragem, impulso, competitividade e individualidade. Áries é a energia que rompe a inércia e abre novos caminhos. Sombra: impulsividade, egoísmo, agressividade.' },
    { symbol: '♉', name: 'Touro', dates: '20 Abr – 20 Mai', element: 'Terra', mode: 'Fixo', ruler: '♀ Vênus', color: '#006600', description: 'A consolidação do que Áries iniciou. Estabilidade, prazer sensorial, lealdade e persistência. Touro constrói bases sólidas com paciência. Sombra: possessividade, teimosia, materialismo.' },
    { symbol: '♊', name: 'Gêmeos', dates: '21 Mai – 20 Jun', element: 'Ar', mode: 'Mutável', ruler: '☿ Mercúrio', color: '#0000cc', description: 'A ponte entre mundos. Curiosidade insaciável, comunicação, versatilidade e leveza. Gêmeos conecta informações e pessoas. Sombra: superficialidade, inconstância, dualidade.' },
    { symbol: '♋', name: 'Câncer', dates: '21 Jun – 22 Jul', element: 'Água', mode: 'Cardinal', ruler: '☽ Lua', color: '#cc6600', description: 'O ninho emocional. Proteção, memória, pertencimento e nutrição. Câncer cria raízes e cuida do que ama. Sombra: dependência, manipulação emocional, apego ao passado.' },
    { symbol: '♌', name: 'Leão', dates: '23 Jul – 22 Ago', element: 'Fogo', mode: 'Fixo', ruler: '☉ Sol', color: '#cc0000', description: 'O palco da vida. Expressão criativa, brilho pessoal, generosidade e liderança. Leão irradia e inspira. Sombra: arrogância, necessidade de aplausos, drama.' },
    { symbol: '♍', name: 'Virgem', dates: '23 Ago – 22 Set', element: 'Terra', mode: 'Mutável', ruler: '☿ Mercúrio', color: '#006600', description: 'O refinamento da experiência. Análise, competência, serviço e aperfeiçoamento. Virgem separa o essencial do supérfluo. Sombra: crítica excessiva, perfeccionismo, ansiedade.' },
    { symbol: '♎', name: 'Libra', dates: '23 Set – 22 Out', element: 'Ar', mode: 'Cardinal', ruler: '♀ Vênus', color: '#0000cc', description: 'O encontro com o outro. Equilíbrio, justiça, diplomacia e parceria. Libra busca harmonia nas relações e na estética. Sombra: indecisão, dependência do outro.' },
    { symbol: '♏', name: 'Escorpião', dates: '23 Out – 21 Nov', element: 'Água', mode: 'Fixo', ruler: '♇ Plutão', color: '#cc6600', description: 'A descida ao fundo. Intensidade, transformação, verdade e poder. Escorpião não teme o que está oculto. Sombra: obsessão, ciúme, manipulação, vingança.' },
    { symbol: '♐', name: 'Sagitário', dates: '22 Nov – 21 Dez', element: 'Fogo', mode: 'Mutável', ruler: '♃ Júpiter', color: '#cc0000', description: 'A flecha do sentido. Expansão, filosofia, aventura e fé. Sagitário busca significado além do horizonte. Sombra: exagero, fanatismo, irresponsabilidade.' },
    { symbol: '♑', name: 'Capricórnio', dates: '22 Dez – 19 Jan', element: 'Terra', mode: 'Cardinal', ruler: '♄ Saturno', color: '#006600', description: 'A montanha a escalar. Ambição, disciplina, maturidade e legado. Capricórnio constrói com tempo e persistência. Sombra: frieza, rigidez, pessimismo.' },
    { symbol: '♒', name: 'Aquário', dates: '20 Jan – 18 Fev', element: 'Ar', mode: 'Fixo', ruler: '♅ Urano', color: '#0000cc', description: 'A revolução silenciosa. Originalidade, independência, visão de futuro e humanitarismo. Aquário questiona o status quo. Sombra: distanciamento emocional, rebeldia vazia.' },
    { symbol: '♓', name: 'Peixes', dates: '19 Fev – 20 Mar', element: 'Água', mode: 'Mutável', ruler: '♆ Netuno', color: '#cc6600', description: 'O oceano final. Compaixão universal, espiritualidade, arte e dissolução do ego. Peixes sente tudo e conecta-se ao todo. Sombra: fuga da realidade, vitimismo, confusão.' },
  ],
};
