export const horoscope = {
  daily: {
    title: '个人每日星座运势',
    subtitle: '您当天的个人行星过境及详细解读',
    selectProfile: '选择档案以查看您的个性化运势',
    noProfile: '请先计算您的本命星盘。',
    moonToday: '今日月亮',
    activeTransits: '活跃过境',
    intensity: { high: '强', medium: '中', low: '轻' },
    categories: { love: '爱情', career: '事业', health: '健康' },
    today: '今天',
    tomorrow: '明天',
  },
  love: {
    title: '爱情运势',
    subtitle: '金星、火星以及今日影响您爱情生活的相位',
  },
  weekly: {
    title: '每周运势',
    subtitle: '未来7天过境和能量概览',
    thisWeek: '本周',
    prevWeek: '← 上周',
    nextWeek: '下周 →',
    selectProfile: '选择档案以查看每周运势',
  },
  events: {
    title: '天象事件',
    subtitle: '行星入境、精准相位、月相及逆行停滞',
    noEvents: '本日无重要天象事件。',
    types: { ingress: '入境', aspect: '精准相位', 'moon-phase': '月相', retrograde: '停滞' },
  },
  interpretation: {
    title: '基本解读',
    premiumCta: '想要完整的个性化分析？',
    premiumDesc: '我们的完整本命报告包含所有行星、相位、尊贵及预测的专业PDF。',
    premiumButton: '查看高级报告',
    freeNotice: '免费简要解读。完整分析（20+页）请查看我们的高级报告。',
  },
  transitTexts: {
    noTransits: '平静的一天，没有重要过境。花时间休息和思考。',
    intenseDay: '多个强力过境的紧张一天。保持清醒和灵活。',
    normalWork: '工作日常日。专注于日常任务。',
    energyHigh: '能量高但有过度倾向。运动但避免过度用力。',
    vitalityGood: '活力充沛。非常适合体育活动和运动。',
    energyStable: '能量稳定。保持健康习惯并尊重您的节奏。',
  },
  moonLove: [
    '浪漫冲动和快速激情。',
    '感性和对舒适的渴望共存。',
    '智识调情和诱人的对话。',
    '在爱情中需要温情和安全感。',
    '戏剧性的浪漫和慷慨的表达。',
    '通过实际行动表达的爱。',
    '寻求和谐与陪伴。',
    '强烈而占有欲强的渴望。',
    '对新奇和冒险的吸引。',
    '成熟的爱情和承诺。',
    '爱情中的自由和不寻常的联系。',
    '浪漫主义和理想化。',
  ],
};
